Bank Marketing（bank-full）数据集 BTTWD 实验

本 notebook 按步骤运行：环境准备 → 加载配置 → 读取数据 → 预处理 → 桶树划分 → 基线与 BTTWD 实验 → 桶级分析。

In [1]:
# 步骤0：环境与路径设置
import os, sys
import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams['font.sans-serif'] = ['Microsoft YaHei']
plt.rcParams['axes.unicode_minus'] = False

# 将项目根目录加入路径，便于导入 bttwdlib
root_path = os.path.abspath(os.path.join(os.getcwd(), '..'))
if root_path not in sys.path:
    sys.path.append(root_path)

from bttwdlib import (
    load_yaml_cfg,
    show_cfg,
    load_dataset,
    prepare_features_and_labels,
    BucketTree,
    run_holdout_experiment,
    run_kfold_experiments,
    log_info,
    set_global_seed,
)

cfg_path = os.path.join(root_path, 'configs', 'bank_bttwd.yaml')
cfg = load_yaml_cfg(cfg_path)
set_global_seed(cfg.get('SEED', {}).get('global_seed', 42))
log_info('【步骤0摘要】环境准备完毕，路径与随机种子已设置。')

【INFO】【2026-03-26 18:42:08】【配置加载】已读取 e:\yan\组\三支决策\机器学习\BT_TWD\configs\bank_bttwd.yaml
【INFO】【2026-03-26 18:42:18】【步骤0摘要】环境准备完毕，路径与随机种子已设置。

In [2]:
# 步骤1：加载配置
show_cfg(cfg)
log_info('【步骤1摘要】配置文件加载完成，关键参数检查通过。')

【INFO】【2026-03-26 18:42:20】【配置-数据】数据集=bank_full, k折=5, 目标列=y, 正类="yes"
【INFO】【2026-03-26 18:42:20】【配置-BTTWD】阈值模式=None, 全局模型=xgb, 桶内模型=none, 后验估计器(兼容字段)=logreg
【INFO】【2026-03-26 18:42:20】【配置-基线】LogReg启用=True, RandomForest启用=True, KNN启用=True, XGBoost启用=True
【INFO】【2026-03-26 18:42:20】【步骤1摘要】配置文件加载完成，关键参数检查通过。

In [3]:
# 步骤2：加载原始数据
df_raw, target_col_model = load_dataset(cfg)  # 返回用于建模的标签列，例如 "y"

display(df_raw.head())
print('用于建模的标签列:', target_col_model)

# 1）画 0/1 标签比例
class_counts = df_raw[target_col_model].value_counts(normalize=True).sort_index()
ax = class_counts.plot(kind='bar', title='订购 vs 未订购比例')
plt.ylabel('比例')

fig_path = os.path.join(root_path, cfg['OUTPUT']['figs_dir'], 'bank_class_distribution.png')
os.makedirs(os.path.dirname(fig_path), exist_ok=True)
plt.savefig(fig_path, bbox_inches='tight')
plt.close()

log_info('【步骤2摘要】Bank Marketing 数据加载与标签分布完成。')

【INFO】【2026-03-26 18:42:24】【数据加载】文本表格 E:\yan\组\三支决策\机器学习\BT_TWD\data\bank\bank-full.csv 已读取，样本数=45211，列数=17
【INFO】【2026-03-26 18:42:24】【数据加载】标签列 y 已处理完成：dropna_target=False, 丢弃样本=0, 最终样本数=45211, 正类比例=11.70%
【INFO】【2026-03-26 18:42:24】【数据加载】银行营销数据集已读取，标签已映射为0/1，样本数=45211，正类比例=11.70%
【INFO】【2026-03-26 18:42:24】【数据集信息】名称=bank_full，样本数=45211，目标列=y，正类比例=11.70%

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,0
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,0
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,0
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,0
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,0

用于建模的标签列: y
【INFO】【2026-03-26 18:42:24】【步骤2摘要】Bank Marketing 数据加载与标签分布完成。

In [4]:
# 步骤3：预处理与特征工程
X, y, meta = prepare_features_and_labels(df_raw, cfg)
log_info(f'【预处理】编码特征维度={X.shape[1]}，样本数={X.shape[0]}')
log_info(f"【步骤3摘要】特征预处理完成：连续={len(meta['continuous_cols'])}，类别={len(meta['categorical_cols'])}，编码维度={X.shape[1]}。")

【INFO】【2026-03-26 18:42:31】【预处理】连续特征=7个，类别特征=9个
【INFO】【2026-03-26 18:42:31】【预处理】编码后维度=42
【INFO】【2026-03-26 18:42:31】【预处理】编码特征维度=42，样本数=45211
【INFO】【2026-03-26 18:42:31】【步骤3摘要】特征预处理完成：连续=7，类别=9，编码维度=42。

In [5]:
# 步骤4：构建桶树并检查划分
feature_df_for_bucket = df_raw.drop(columns=[target_col_model])
bucket_tree = BucketTree(cfg['BTTWD']['bucket_levels'], feature_names=feature_df_for_bucket.columns.tolist())
bucket_ids_full = bucket_tree.assign_buckets(feature_df_for_bucket)
group_df = df_raw.groupby(bucket_ids_full)[target_col_model].agg(['size', 'mean']).reset_index()
group_df.columns = ['bucket_id', 'count', 'pos_rate']
bucket_df = group_df.sort_values('count', ascending=False).reset_index(drop=True)

display(bucket_df.head())
bucket_df.set_index('bucket_id')['count'].plot(kind='bar', figsize=(12,4), title='桶样本数分布')
fig_bucket = os.path.join(root_path, cfg['OUTPUT']['figs_dir'], 'bucket_metrics_bar.png')
plt.savefig(fig_bucket, bbox_inches='tight')
plt.close()
log_info(f'【步骤4摘要】桶树划分完成，共有 {bucket_ids_full.nunique()} 个叶子桶。')

【INFO】【2026-03-26 18:42:35】【桶树】已为样本生成桶ID，共 87 个组合

                                           bucket_id  count  pos_rate
0  L1_age=30-40|L2_job=white_collar|L3_contact=ce...   7237  0.141219
1  L1_age=40-50|L2_job=white_collar|L3_contact=ce...   3747  0.133974
2  L1_age=30-40|L2_job=blue_collar|L3_contact=cel...   3380  0.099704
3  L1_age=<=30|L2_job=white_collar|L3_contact=cel...   2434  0.199671
4  L1_age=30-40|L2_job=blue_collar|L3_contact=unk...   2399  0.036682

【INFO】【2026-03-26 18:42:36】【步骤4摘要】桶树划分完成，共有 87 个叶子桶。

In [6]:
# 步骤5：运行基线模型实验占位
# 基线部分在 run_kfold_experiments 内统一调度（仅在 use_kfold=True 时执行）
log_info('【步骤5】基线模型（LogReg / XGBoost）将在交叉验证模式中一并运行。')
log_info('【步骤5摘要】基线模型性能将作为后续对比基准。')

【INFO】【2026-03-26 18:42:40】【步骤5】基线模型（LogReg / XGBoost）将在交叉验证模式中一并运行。
【INFO】【2026-03-26 18:42:40】【步骤5摘要】基线模型性能将作为后续对比基准。

In [7]:
# 步骤6：运行 BTTWD 实验（k 折或单次留出）
use_kfold_raw = cfg.get('DATA', {}).get('use_kfold', False)
if isinstance(use_kfold_raw, str):
    use_kfold = use_kfold_raw.strip().lower() in ['true', '1', 'yes']
else:
    use_kfold = bool(use_kfold_raw)

if use_kfold:
    log_info('【步骤6】检测到 use_kfold=True，进入 k 折实验。')
    results = run_kfold_experiments(X, y, feature_df_for_bucket, cfg)
    summary_df = pd.read_csv(os.path.join(root_path, cfg['OUTPUT']['results_dir'], 'metrics_kfold_summary.csv'))
    display(summary_df)
    summary_df.plot(x='model', kind='bar', figsize=(8,4), title='模型指标对比')
    fig_compare = os.path.join(root_path, cfg['OUTPUT']['figs_dir'], 'metrics_compare.png')
    plt.savefig(fig_compare, bbox_inches='tight')
    plt.close()
    log_info('【步骤6摘要】BTTWD 与基线的 k 折结果已生成并保存。')
else:
    log_info('【步骤6】use_kfold=False，执行单次留出验证流程。')
    holdout_metrics = run_holdout_experiment(X, y, feature_df_for_bucket, cfg)
    display(pd.DataFrame(holdout_metrics))
    log_info('【步骤6摘要】单次留出验证完成，指标已列出。')

【INFO】【2026-03-26 18:42:44】【步骤6】检测到 use_kfold=True，进入 k 折实验。
【INFO】【2026-03-26 18:42:44】【基线-LogReg】使用模型自定义阈值=0.400（per_model 模式）

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\baselines.py:109: RuntimeWarning: Mean of empty slice
  summary[f"{col}_mean"] = float(np.nanmean(arr))
d:\Anaconda3\Lib\site-packages\numpy\lib\nanfunctions.py:1879: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

【INFO】【2026-03-26 18:42:44】【基线-LogReg】整体指标：AUC_mean=0.907, AUC_std=0.005, BAC_mean=0.701, BAC_std=0.006, BND_ratio_mean=0.000, BND_ratio_std=0.000, F1_mean=0.513, F1_std=0.008, Kappa_mean=0.461, Kappa_std=0.008, MCC_mean=0.471, MCC_std=0.008, POS_Coverage_mean=nan, POS_Coverage_std=nan, Precision_mean=0.624, Precision_std=0.018, Recall_mean=0.437, Recall_std=0.015, Regret_mean=0.155, Regret_std=0.002
【INFO】【2026-03-26 18:42:44】【基线-RF】使用通用阈值=0.400（per_model 模式）

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\baselines.py:109: RuntimeWarning: Mean of empty slice
  summary[f"{col}_mean"] = float(np.nanmean(arr))
d:\Anaconda3\Lib\site-packages\numpy\lib\nanfunctions.py:1879: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

【INFO】【2026-03-26 18:42:51】【基线-RF】整体指标：AUC_mean=0.931, AUC_std=0.003, BAC_mean=0.766, BAC_std=0.009, BND_ratio_mean=0.000, BND_ratio_std=0.000, F1_mean=0.592, F1_std=0.015, Kappa_mean=0.539, Kappa_std=0.017, MCC_mean=0.539, MCC_std=0.017, POS_Coverage_mean=nan, POS_Coverage_std=nan, Precision_mean=0.601, Precision_std=0.015, Recall_mean=0.583, Recall_std=0.016, Regret_mean=0.132, Regret_std=0.005
【INFO】【2026-03-26 18:42:51】【基线-KNN】使用通用阈值=0.400（per_model 模式）

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\baselines.py:109: RuntimeWarning: Mean of empty slice
  summary[f"{col}_mean"] = float(np.nanmean(arr))
d:\Anaconda3\Lib\site-packages\numpy\lib\nanfunctions.py:1879: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [18:42:55] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 18:42:55】【基线-KNN】整体指标：AUC_mean=0.877, AUC_std=0.005, BAC_mean=0.728, BAC_std=0.003, BND_ratio_mean=0.000, BND_ratio_std=0.000, F1_mean=0.533, F1_std=0.007, Kappa_mean=0.474, Kappa_std=0.009, MCC_mean=0.475, MCC_std=0.009, POS_Coverage_mean=nan, POS_Coverage_std=nan, Precision_mean=0.560, Precision_std=0.013, Recall_mean=0.508, Recall_std=0.006, Regret_mean=0.150, Regret_std=0.002
【INFO】【2026-03-26 18:42:55】【基线-XGB】使用模型自定义阈值=0.400（per_model 模式）

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [18:42:55] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [18:42:56] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [18:42:57] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [18:42:58] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\baselines.py:109: RuntimeWarning: Mean of empty slice
  summary[f"{col}_mean"] = float(np.nanmean(arr))
d:\Anaconda3\Lib\site-packages\numpy\lib\nanfunctions.py:1879: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [18:42:58] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 18:42:58】【基线-XGB】整体指标：AUC_mean=0.935, AUC_std=0.003, BAC_mean=0.776, BAC_std=0.007, BND_ratio_mean=0.000, BND_ratio_std=0.000, F1_mean=0.605, F1_std=0.010, Kappa_mean=0.553, Kappa_std=0.011, MCC_mean=0.553, MCC_std=0.011, POS_Coverage_mean=nan, POS_Coverage_std=nan, Precision_mean=0.606, Precision_std=0.011, Recall_mean=0.604, Recall_std=0.013, Regret_mean=0.127, Regret_std=0.003
【INFO】【2026-03-26 18:42:58】【K折实验】正在执行第 1/5 折...
【INFO】【2026-03-26 18:42:58】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=1.0
【INFO】【2026-03-26 18:42:59】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=36168
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="30-40"，n_samples=14173
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=40-50，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="40-50"，n_samples=8943
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="50-60"，n_samples=6407
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=<=30，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="<=30"，n_samples=5675
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=>60，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule=">60"，n_samples=970
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=4830
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=499
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=932
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=7845
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40|L2_job=others，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=67
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=3357
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=288
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=677
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=4449
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=40-50|L2_job=others，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=172
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=1939
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=216
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=retired，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="retired"，n_samples=988
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=475
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=2715
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=others，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=74
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=1860
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=786
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=305
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=2707
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=<=30|L2_job=others，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=17
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=>60|L2_job=retired，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="retired"，n_samples=712
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=132
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=>60|L2_job=others，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=126
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=2708
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=215
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1907
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=335
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=131
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=33
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=652
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=247
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=33
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=5859
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=239
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1747
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1821
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=264
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1272
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=188
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=40-50|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=100
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=425
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=200
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=52
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=3005
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=242
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1202
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1048
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=237
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=654
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=146
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=70
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=578
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=323
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=87
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=281
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=146
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=48
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1732
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=274
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=709
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1068
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=714
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=78
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=595
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=114
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=77
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=224
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=81
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1996
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=633
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=78
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=cellular，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=480
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=telephone，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=224
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=others，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=8
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=>60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=108
[INFO][BT][2026-03-26 18:42:59] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar|L3_contact=others，level=3，parent_id=L1_age=>60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=24
[INFO][BT][2026-03-26 18:43:02] 桶树构建完成：总桶数=83，最大层数=3，叶子桶数=58
【INFO】【2026-03-26 18:43:02】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 18:43:03】【阈值】桶 ROOT（n_val=3252，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:43:03] 桶 bucket_id=ROOT level=0：
    n_train=7594, n_val=3252,
    BAC=0.820, F1=0.636, AUC=0.937,
    Regret=0.113, BND_ratio=0.069, POS_coverage=0.179,
    Score(f1_regret_bnd )=0.454，threshold_source=val
【INFO】【2026-03-26 18:43:03】【阈值】桶 L1_age=30-40 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:43:03] 桶 bucket_id=L1_age=30-40 level=1：
    n_train=3001, n_val=1295,
    BAC=0.820, F1=0.637, AUC=0.937,
    Regret=0.111, BND_ratio=0.079, POS_coverage=0.177,
    Score(f1_regret_bnd )=0.447，threshold_source=val
[INFO][BT][2026-03-26 18:43:03] 桶 bucket_id=L1_age=30-40：
    parent_id=ROOT，parent_Score=0.454, bucket_Score=0.447,
    Gain=-0.007, is_weak=True
【INFO】【2026-03-26 18:43:03】【阈值】桶 L1_age=40-50（n_val=923，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:43:03] 桶 bucket_id=L1_age=40-50 level=1：
    n_train=1859, n_val=923,
    BAC=0.751, F1=0.608, AUC=0.947,
    Regret=0.087, BND_ratio=0.051, POS_coverage=0.079,
    Score(f1_regret_bnd )=0.469，threshold_source=val
[INFO][BT][2026-03-26 18:43:03] 桶 bucket_id=L1_age=40-50：
    parent_id=ROOT，parent_Score=0.454, bucket_Score=0.469,
    Gain=+0.015, is_weak=False
【INFO】【2026-03-26 18:43:04】【阈值】桶 L1_age=50-60（n_val=605，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:43:04] 桶 bucket_id=L1_age=50-60 level=1：
    n_train=1408, n_val=605,
    BAC=0.777, F1=0.647, AUC=0.952,
    Regret=0.098, BND_ratio=0.091, POS_coverage=0.121,
    Score(f1_regret_bnd )=0.459，threshold_source=val
[INFO][BT][2026-03-26 18:43:04] 桶 bucket_id=L1_age=50-60：
    parent_id=ROOT，parent_Score=0.454, bucket_Score=0.459,
    Gain=+0.005, is_weak=False
【INFO】【2026-03-26 18:43:04】【阈值】桶 L1_age=<=30 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:43:04] 桶 bucket_id=L1_age=<=30 level=1：
    n_train=1198, n_val=580,
    BAC=0.805, F1=0.667, AUC=0.939,
    Regret=0.134, BND_ratio=0.091, POS_coverage=0.240,
    Score(f1_regret_bnd )=0.441，threshold_source=val
[INFO][BT][2026-03-26 18:43:04] 桶 bucket_id=L1_age=<=30：
    parent_id=ROOT，parent_Score=0.454, bucket_Score=0.441,
    Gain=-0.013, is_weak=True
【INFO】【2026-03-26 18:43:04】【阈值】桶 L1_age=>60 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:43:04] 桶 bucket_id=L1_age=>60 level=1：
    n_train=336, n_val=135,
    BAC=0.583, F1=0.762, AUC=0.826,
    Regret=0.252, BND_ratio=0.230, POS_coverage=0.622,
    Score(f1_regret_bnd )=0.280，threshold_source=val
[INFO][BT][2026-03-26 18:43:04] 桶 bucket_id=L1_age=>60：
    parent_id=ROOT，parent_Score=0.454, bucket_Score=0.280,
    Gain=-0.174, is_weak=True
【INFO】【2026-03-26 18:43:04】【阈值】桶 L1_age=30-40|L2_job=blue_collar（n_val=496，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:43:04] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar level=2：
    n_train=998, n_val=496,
    BAC=0.813, F1=0.652, AUC=0.960,
    Regret=0.075, BND_ratio=0.081, POS_coverage=0.101,
    Score(f1_regret_bnd )=0.496，threshold_source=val
[INFO][BT][2026-03-26 18:43:04] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar：
    parent_id=L1_age=30-40，parent_Score=0.447, bucket_Score=0.496,
    Gain=+0.049, is_weak=False
【INFO】【2026-03-26 18:43:05】【阈值】桶 L1_age=30-40|L2_job=no_income（n_val=140，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:43:05] 桶 bucket_id=L1_age=30-40|L2_job=no_income level=2：
    n_train=194, n_val=140,
    BAC=0.799, F1=0.688, AUC=0.953,
    Regret=0.089, BND_ratio=0.036, POS_coverage=0.107,
    Score(f1_regret_bnd )=0.562，threshold_source=val
[INFO][BT][2026-03-26 18:43:05] 桶 bucket_id=L1_age=30-40|L2_job=no_income：
    parent_id=L1_age=30-40，parent_Score=0.447, bucket_Score=0.562,
    Gain=+0.115, is_weak=False
【INFO】【2026-03-26 18:43:05】【阈值】桶 L1_age=30-40|L2_job=self_emp 标记为弱桶，阈值将回退使用 L1_age=30-40 的阈值
[INFO][BT][2026-03-26 18:43:05] 桶 bucket_id=L1_age=30-40|L2_job=self_emp level=2：
    n_train=214, n_val=137,
    BAC=0.807, F1=0.476, AUC=0.946,
    Regret=0.071, BND_ratio=0.044, POS_coverage=0.102,
    Score(f1_regret_bnd )=0.361，threshold_source=val
[INFO][BT][2026-03-26 18:43:05] 桶 bucket_id=L1_age=30-40|L2_job=self_emp：
    parent_id=L1_age=30-40，parent_Score=0.447, bucket_Score=0.361,
    Gain=-0.086, is_weak=True
【INFO】【2026-03-26 18:43:05】【阈值】桶 L1_age=30-40|L2_job=white_collar（n_val=756，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:43:05] 桶 bucket_id=L1_age=30-40|L2_job=white_collar level=2：
    n_train=1648, n_val=756,
    BAC=0.768, F1=0.643, AUC=0.941,
    Regret=0.102, BND_ratio=0.065, POS_coverage=0.110,
    Score(f1_regret_bnd )=0.477，threshold_source=val
[INFO][BT][2026-03-26 18:43:05] 桶 bucket_id=L1_age=30-40|L2_job=white_collar：
    parent_id=L1_age=30-40，parent_Score=0.447, bucket_Score=0.477,
    Gain=+0.030, is_weak=False
【INFO】【2026-03-26 18:43:05】【阈值】桶 L1_age=30-40|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=30-40 的阈值
[INFO][BT][2026-03-26 18:43:05] 桶 bucket_id=L1_age=30-40|L2_job=others level=2：
    n_train=47, n_val=20,
    BAC=0.867, F1=0.857, AUC=0.972,
    Regret=0.034, BND_ratio=0.015, POS_coverage=0.045,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:43:05] 桶 bucket_id=L1_age=30-40|L2_job=others：
    parent_id=L1_age=30-40，parent_Score=0.447, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:43:06】【阈值】桶 L1_age=40-50|L2_job=blue_collar（n_val=353，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:43:06] 桶 bucket_id=L1_age=40-50|L2_job=blue_collar level=2：
    n_train=698, n_val=353,
    BAC=0.832, F1=0.723, AUC=0.960,
    Regret=0.053, BND_ratio=0.059, POS_coverage=0.068,
    Score(f1_regret_bnd )=0.611，threshold_source=val
[INFO][BT][2026-03-26 18:43:06] 桶 bucket_id=L1_age=40-50|L2_job=blue_collar：
    parent_id=L1_age=40-50，parent_Score=0.469, bucket_Score=0.611,
    Gain=+0.142, is_weak=False
【INFO】【2026-03-26 18:43:06】【阈值】桶 L1_age=40-50|L2_job=no_income（n_val=83，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:43:06] 桶 bucket_id=L1_age=40-50|L2_job=no_income level=2：
    n_train=110, n_val=83,
    BAC=0.895, F1=0.880, AUC=0.989,
    Regret=0.042, BND_ratio=0.060, POS_coverage=0.145,
    Score(f1_regret_bnd )=0.778，threshold_source=val
[INFO][BT][2026-03-26 18:43:06] 桶 bucket_id=L1_age=40-50|L2_job=no_income：
    parent_id=L1_age=40-50，parent_Score=0.469, bucket_Score=0.778,
    Gain=+0.308, is_weak=False
【INFO】【2026-03-26 18:43:06】【阈值】桶 L1_age=40-50|L2_job=self_emp（n_val=109，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:43:06] 桶 bucket_id=L1_age=40-50|L2_job=self_emp level=2：
    n_train=171, n_val=109,
    BAC=0.902, F1=0.769, AUC=0.972,
    Regret=0.034, BND_ratio=0.009, POS_coverage=0.064,
    Score(f1_regret_bnd )=0.726，threshold_source=val
[INFO][BT][2026-03-26 18:43:06] 桶 bucket_id=L1_age=40-50|L2_job=self_emp：
    parent_id=L1_age=40-50，parent_Score=0.469, bucket_Score=0.726,
    Gain=+0.256, is_weak=False
【INFO】【2026-03-26 18:43:06】【阈值】桶 L1_age=40-50|L2_job=white_collar 标记为弱桶，阈值将回退使用 L1_age=40-50 的阈值
[INFO][BT][2026-03-26 18:43:06] 桶 bucket_id=L1_age=40-50|L2_job=white_collar level=2：
    n_train=923, n_val=459,
    BAC=0.782, F1=0.612, AUC=0.921,
    Regret=0.129, BND_ratio=0.089, POS_coverage=0.172,
    Score(f1_regret_bnd )=0.394，threshold_source=val
[INFO][BT][2026-03-26 18:43:06] 桶 bucket_id=L1_age=40-50|L2_job=white_collar：
    parent_id=L1_age=40-50，parent_Score=0.469, bucket_Score=0.394,
    Gain=-0.076, is_weak=True
【INFO】【2026-03-26 18:43:07】【阈值】桶 L1_age=40-50|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=40-50 的阈值
[INFO][BT][2026-03-26 18:43:07] 桶 bucket_id=L1_age=40-50|L2_job=others level=2：
    n_train=108, n_val=64,
    BAC=0.889, F1=0.714, AUC=0.970,
    Regret=0.054, BND_ratio=0.017, POS_coverage=0.093,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:43:07] 桶 bucket_id=L1_age=40-50|L2_job=others：
    parent_id=L1_age=40-50，parent_Score=0.469, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:43:07】【阈值】桶 L1_age=50-60|L2_job=blue_collar 标记为弱桶，阈值将回退使用 L1_age=50-60 的阈值
[INFO][BT][2026-03-26 18:43:07] 桶 bucket_id=L1_age=50-60|L2_job=blue_collar level=2：
    n_train=410, n_val=211,
    BAC=0.660, F1=0.400, AUC=0.932,
    Regret=0.071, BND_ratio=0.066, POS_coverage=0.047,
    Score(f1_regret_bnd )=0.263，threshold_source=val
[INFO][BT][2026-03-26 18:43:07] 桶 bucket_id=L1_age=50-60|L2_job=blue_collar：
    parent_id=L1_age=50-60，parent_Score=0.459, bucket_Score=0.263,
    Gain=-0.196, is_weak=True
【INFO】【2026-03-26 18:43:07】【阈值】桶 L1_age=50-60|L2_job=no_income（n_val=60，source=val) 使用本地阈值 α=0.6000, β=0.3000
[INFO][BT][2026-03-26 18:43:07] 桶 bucket_id=L1_age=50-60|L2_job=no_income level=2：
    n_train=84, n_val=60,
    BAC=0.774, F1=0.769, AUC=0.962,
    Regret=0.083, BND_ratio=0.100, POS_coverage=0.083,
    Score(f1_regret_bnd )=0.586，threshold_source=val
[INFO][BT][2026-03-26 18:43:07] 桶 bucket_id=L1_age=50-60|L2_job=no_income：
    parent_id=L1_age=50-60，parent_Score=0.459, bucket_Score=0.586,
    Gain=+0.127, is_weak=False
【INFO】【2026-03-26 18:43:07】【阈值】桶 L1_age=50-60|L2_job=retired（n_val=172，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:43:07] 桶 bucket_id=L1_age=50-60|L2_job=retired level=2：
    n_train=252, n_val=172,
    BAC=0.757, F1=0.600, AUC=0.970,
    Regret=0.061, BND_ratio=0.076, POS_coverage=0.058,
    Score(f1_regret_bnd )=0.463，threshold_source=val
[INFO][BT][2026-03-26 18:43:07] 桶 bucket_id=L1_age=50-60|L2_job=retired：
    parent_id=L1_age=50-60，parent_Score=0.459, bucket_Score=0.463,
    Gain=+0.005, is_weak=False
【INFO】【2026-03-26 18:43:08】【阈值】桶 L1_age=50-60|L2_job=self_emp（n_val=138，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:43:08] 桶 bucket_id=L1_age=50-60|L2_job=self_emp level=2：
    n_train=192, n_val=138,
    BAC=0.772, F1=0.667, AUC=0.957,
    Regret=0.103, BND_ratio=0.087, POS_coverage=0.109,
    Score(f1_regret_bnd )=0.476，threshold_source=val
[INFO][BT][2026-03-26 18:43:08] 桶 bucket_id=L1_age=50-60|L2_job=self_emp：
    parent_id=L1_age=50-60，parent_Score=0.459, bucket_Score=0.476,
    Gain=+0.018, is_weak=False
【INFO】【2026-03-26 18:43:08】【阈值】桶 L1_age=50-60|L2_job=white_collar（n_val=288，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:43:08] 桶 bucket_id=L1_age=50-60|L2_job=white_collar level=2：
    n_train=581, n_val=288,
    BAC=0.765, F1=0.615, AUC=0.931,
    Regret=0.119, BND_ratio=0.024, POS_coverage=0.108,
    Score(f1_regret_bnd )=0.472，threshold_source=val
[INFO][BT][2026-03-26 18:43:08] 桶 bucket_id=L1_age=50-60|L2_job=white_collar：
    parent_id=L1_age=50-60，parent_Score=0.459, bucket_Score=0.472,
    Gain=+0.014, is_weak=False
【INFO】【2026-03-26 18:43:08】【阈值】桶 L1_age=50-60|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=50-60 的阈值
[INFO][BT][2026-03-26 18:43:08] 桶 bucket_id=L1_age=50-60|L2_job=others level=2：
    n_train=56, n_val=18,
    BAC=0.814, F1=0.800, AUC=0.985,
    Regret=0.061, BND_ratio=0.122, POS_coverage=0.095,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:43:08] 桶 bucket_id=L1_age=50-60|L2_job=others：
    parent_id=L1_age=50-60，parent_Score=0.459, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:43:08】【阈值】桶 L1_age=<=30|L2_job=blue_collar（n_val=182，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:43:08] 桶 bucket_id=L1_age=<=30|L2_job=blue_collar level=2：
    n_train=429, n_val=182,
    BAC=0.801, F1=0.700, AUC=0.950,
    Regret=0.093, BND_ratio=0.093, POS_coverage=0.115,
    Score(f1_regret_bnd )=0.513，threshold_source=val
[INFO][BT][2026-03-26 18:43:08] 桶 bucket_id=L1_age=<=30|L2_job=blue_collar：
    parent_id=L1_age=<=30，parent_Score=0.441, bucket_Score=0.513,
    Gain=+0.072, is_weak=False
【INFO】【2026-03-26 18:43:09】【阈值】桶 L1_age=<=30|L2_job=no_income 标记为弱桶，阈值将回退使用 L1_age=<=30 的阈值
[INFO][BT][2026-03-26 18:43:09] 桶 bucket_id=L1_age=<=30|L2_job=no_income level=2：
    n_train=265, n_val=103,
    BAC=0.635, F1=0.524, AUC=0.850,
    Regret=0.201, BND_ratio=0.223, POS_coverage=0.233,
    Score(f1_regret_bnd )=0.099，threshold_source=val
[INFO][BT][2026-03-26 18:43:09] 桶 bucket_id=L1_age=<=30|L2_job=no_income：
    parent_id=L1_age=<=30，parent_Score=0.441, bucket_Score=0.099,
    Gain=-0.342, is_weak=True
【INFO】【2026-03-26 18:43:09】【阈值】桶 L1_age=<=30|L2_job=self_emp 标记为弱桶，阈值将回退使用 L1_age=<=30 的阈值
[INFO][BT][2026-03-26 18:43:09] 桶 bucket_id=L1_age=<=30|L2_job=self_emp level=2：
    n_train=99, n_val=96,
    BAC=0.554, F1=0.476, AUC=0.891,
    Regret=0.159, BND_ratio=0.292, POS_coverage=0.083,
    Score(f1_regret_bnd )=0.026，threshold_source=val
[INFO][BT][2026-03-26 18:43:09] 桶 bucket_id=L1_age=<=30|L2_job=self_emp：
    parent_id=L1_age=<=30，parent_Score=0.441, bucket_Score=0.026,
    Gain=-0.415, is_weak=True
【INFO】【2026-03-26 18:43:09】【阈值】桶 L1_age=<=30|L2_job=white_collar 标记为弱桶，阈值将回退使用 L1_age=<=30 的阈值
[INFO][BT][2026-03-26 18:43:09] 桶 bucket_id=L1_age=<=30|L2_job=white_collar level=2：
    n_train=597, n_val=268,
    BAC=0.745, F1=0.678, AUC=0.915,
    Regret=0.162, BND_ratio=0.131, POS_coverage=0.224,
    Score(f1_regret_bnd )=0.385，threshold_source=val
[INFO][BT][2026-03-26 18:43:09] 桶 bucket_id=L1_age=<=30|L2_job=white_collar：
    parent_id=L1_age=<=30，parent_Score=0.441, bucket_Score=0.385,
    Gain=-0.056, is_weak=True
【INFO】【2026-03-26 18:43:10】【阈值】桶 L1_age=<=30|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=<=30 的阈值
[INFO][BT][2026-03-26 18:43:10] 桶 bucket_id=L1_age=<=30|L2_job=others level=2：
    n_train=13, n_val=4,
    BAC=0.964, F1=1.000, AUC=1.000,
    Regret=0.015, BND_ratio=0.059, POS_coverage=0.176,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:43:10] 桶 bucket_id=L1_age=<=30|L2_job=others：
    parent_id=L1_age=<=30，parent_Score=0.441, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:43:10】【阈值】桶 L1_age=>60|L2_job=retired 标记为弱桶，阈值将回退使用 L1_age=>60 的阈值
[INFO][BT][2026-03-26 18:43:10] 桶 bucket_id=L1_age=>60|L2_job=retired level=2：
    n_train=149, n_val=107,
    BAC=0.610, F1=0.685, AUC=0.786,
    Regret=0.283, BND_ratio=0.178, POS_coverage=0.607,
    Score(f1_regret_bnd )=0.225，threshold_source=val
[INFO][BT][2026-03-26 18:43:10] 桶 bucket_id=L1_age=>60|L2_job=retired：
    parent_id=L1_age=>60，parent_Score=0.280, bucket_Score=0.225,
    Gain=-0.056, is_weak=True
【INFO】【2026-03-26 18:43:10】【阈值】桶 L1_age=>60|L2_job=white_collar 标记为弱桶，阈值将回退使用 L1_age=>60 的阈值
[INFO][BT][2026-03-26 18:43:10] 桶 bucket_id=L1_age=>60|L2_job=white_collar level=2：
    n_train=99, n_val=33,
    BAC=0.537, F1=0.800, AUC=0.849,
    Regret=0.242, BND_ratio=0.333, POS_coverage=0.545,
    Score(f1_regret_bnd )=0.224，threshold_source=val
[INFO][BT][2026-03-26 18:43:10] 桶 bucket_id=L1_age=>60|L2_job=white_collar：
    parent_id=L1_age=>60，parent_Score=0.280, bucket_Score=0.224,
    Gain=-0.056, is_weak=True
【INFO】【2026-03-26 18:43:11】【阈值】桶 L1_age=>60|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=>60 的阈值
[INFO][BT][2026-03-26 18:43:11] 桶 bucket_id=L1_age=>60|L2_job=others level=2：
    n_train=91, n_val=35,
    BAC=0.737, F1=0.809, AUC=0.919,
    Regret=0.183, BND_ratio=0.206, POS_coverage=0.317,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:43:11] 桶 bucket_id=L1_age=>60|L2_job=others：
    parent_id=L1_age=>60，parent_Score=0.280, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:43:11】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=cellular 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=blue_collar 的阈值
[INFO][BT][2026-03-26 18:43:11] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular level=3：
    n_train=1859, n_val=849,
    BAC=0.735, F1=0.538, AUC=0.907,
    Regret=0.111, BND_ratio=0.035, POS_coverage=0.095,
    Score(f1_regret_bnd )=0.391，threshold_source=val
[INFO][BT][2026-03-26 18:43:11] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.496, bucket_Score=0.391,
    Gain=-0.105, is_weak=True
【INFO】【2026-03-26 18:43:11】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=telephone（n_val=69，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:43:11] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone level=3：
    n_train=146, n_val=69,
    BAC=1.000, F1=1.000, AUC=1.000,
    Regret=0.000, BND_ratio=0.000, POS_coverage=0.058,
    Score(f1_regret_bnd )=1.000，threshold_source=val
[INFO][BT][2026-03-26 18:43:11] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.496, bucket_Score=1.000,
    Gain=+0.504, is_weak=False
【INFO】【2026-03-26 18:43:12】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=unknown 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=blue_collar 的阈值
[INFO][BT][2026-03-26 18:43:12] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown level=3：
    n_train=1329, n_val=578,
    BAC=0.706, F1=0.471, AUC=0.953,
    Regret=0.063, BND_ratio=0.033, POS_coverage=0.043,
    Score(f1_regret_bnd )=0.375，threshold_source=val
[INFO][BT][2026-03-26 18:43:12] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.496, bucket_Score=0.375,
    Gain=-0.121, is_weak=True
【INFO】【2026-03-26 18:43:12】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=cellular（n_val=100，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:43:12] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular level=3：
    n_train=235, n_val=100,
    BAC=0.804, F1=0.714, AUC=0.944,
    Regret=0.107, BND_ratio=0.040, POS_coverage=0.130,
    Score(f1_regret_bnd )=0.567，threshold_source=val
[INFO][BT][2026-03-26 18:43:12] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.562, bucket_Score=0.567,
    Gain=+0.004, is_weak=False
【INFO】【2026-03-26 18:43:12】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=unknown（n_val=33，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:43:12] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown level=3：
    n_train=98, n_val=33,
    BAC=0.750, F1=0.667, AUC=1.000,
    Regret=0.030, BND_ratio=0.030, POS_coverage=0.030,
    Score(f1_regret_bnd )=0.606，threshold_source=val
[INFO][BT][2026-03-26 18:43:12] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.562, bucket_Score=0.606,
    Gain=+0.044, is_weak=False
【INFO】【2026-03-26 18:43:13】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=others 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=no_income 的阈值
[INFO][BT][2026-03-26 18:43:13] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others level=3：
    n_train=26, n_val=7,
    BAC=0.889, F1=0.857, AUC=0.975,
    Regret=0.076, BND_ratio=0.121, POS_coverage=0.242,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:43:13] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.562, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:43:13】【阈值】桶 L1_age=30-40|L2_job=self_emp|L3_contact=cellular 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=self_emp 的阈值
[INFO][BT][2026-03-26 18:43:13] 桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular level=3：
    n_train=456, n_val=196,
    BAC=0.738, F1=0.560, AUC=0.923,
    Regret=0.114, BND_ratio=0.092, POS_coverage=0.138,
    Score(f1_regret_bnd )=0.355，threshold_source=val
[INFO][BT][2026-03-26 18:43:13] 桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=self_emp，parent_Score=0.361, bucket_Score=0.355,
    Gain=-0.007, is_weak=True
【INFO】【2026-03-26 18:43:13】【阈值】桶 L1_age=30-40|L2_job=self_emp|L3_contact=unknown 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=self_emp 的阈值
[INFO][BT][2026-03-26 18:43:13] 桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=unknown level=3：
    n_train=175, n_val=72,
    BAC=0.486, F1=0.000, AUC=0.972,
    Regret=0.021, BND_ratio=0.042, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.062，threshold_source=val

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [18:43:32] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 18:43:33】[BASELINE] 全局 XGB 模型训练完成
【INFO】【2026-03-26 18:43:33】[BASELINE] 阈值搜索开始
【INFO】【2026-03-26 18:43:34】[BASELINE] 最佳阈值找到: alpha=0.3000, beta=0.1000, regret=0.1134
【INFO】【2026-03-26 18:43:34】【桶树】已为样本生成桶ID，共 82 个组合
【INFO】【2026-03-26 18:43:34】[BASELINE] 测试集桶映射完成，共 82 个桶

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar|L3_contact=unknown: BAC=0.8518, Regret=0.0423, Precision=0.5333, Recall=0.7273
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar|L3_contact=unknown: BAC=0.9368, Regret=0.0419, Precision=0.6923, Recall=0.9000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=retired|L3_contact=unknown: BAC=0.4868, Regret=0.0641, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar|L3_contact=unknown: BAC=0.7311, Regret=0.0412, Precision=0.6667, Recall=0.4706
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar|L3_contact=unknown: BAC=0.8119, Regret=0.0676, Precision=0.7778, Recall=0.6364
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar|L3_contact=unknown: BAC=0.7562, Regret=0.0709, Precision=0.3846, Recall=0.5556
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar|L3_contact=unknown: BAC=0.8604, Regret=0.0277, Precision=0.8000, Recall=0.7273
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp|L3_contact=unknown: BAC=0.9273, Regret=0.0636, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp|L3_contact=unknown: BAC=0.9487, Regret=0.0577, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar|L3_contact=unknown: BAC=0.8185, Regret=0.0576, Precision=0.5185, Recall=0.6667
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp|L3_contact=unknown: BAC=0.9750, Regret=0.0516, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=no_income|L3_contact=unknown: BAC=0.9667, Regret=0.0250, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=retired|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=no_income|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar|L3_contact=unknown: BAC=0.7707, Regret=0.0704, Precision=0.6154, Recall=0.5714
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=no_income|L3_contact=unknown: BAC=1.0000, Regret=0.0417, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=no_income|L3_contact=unknown: BAC=0.9677, Regret=0.0625, Precision=0.3333, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=unknown|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp|L3_contact=unknown: BAC=0.6500, Regret=0.2647, Precision=0.2500, Recall=0.5000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=retired|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=unknown|L3_contact=unknown: BAC=1.0000, Regret=0.0357, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=unknown|L3_contact=unknown: BAC=0.5000, Regret=0.2222, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=unknown|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=retired|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar|L3_contact=cellular: BAC=0.7894, Regret=0.1035, Precision=0.5938, Recall=0.6333
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar|L3_contact=telephone: BAC=0.8133, Regret=0.0714, Precision=0.6667, Recall=0.6667
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar|L3_contact=cellular: BAC=0.8018, Regret=0.1379, Precision=0.5781, Recall=0.6884
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar|L3_contact=cellular: BAC=0.8287, Regret=0.1316, Precision=0.6506, Recall=0.7297
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp|L3_contact=cellular: BAC=0.7258, Regret=0.0898, Precision=0.2500, Recall=0.5000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar|L3_contact=cellular: BAC=0.7479, Regret=0.1039, Precision=0.5854, Recall=0.5333
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=retired|L3_contact=cellular: BAC=0.8734, Regret=0.1476, Precision=0.4865, Recall=0.9000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar|L3_contact=cellular: BAC=0.8403, Regret=0.1166, Precision=0.5902, Recall=0.7579
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp|L3_contact=cellular: BAC=0.7716, Regret=0.1475, Precision=0.4828, Recall=0.6364
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar|L3_contact=cellular: BAC=0.7356, Regret=0.2266, Precision=0.5283, Recall=0.6154
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=no_income|L3_contact=cellular: BAC=0.8035, Regret=0.1900, Precision=0.6250, Recall=0.7692
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar|L3_contact=cellular: BAC=0.8102, Regret=0.1057, Precision=0.6024, Recall=0.6757
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar|L3_contact=telephone: BAC=0.6848, Regret=0.1092, Precision=0.5000, Recall=0.4000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar|L3_contact=cellular: BAC=0.8202, Regret=0.1287, Precision=0.5778, Recall=0.7222
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar|L3_contact=telephone: BAC=0.9688, Regret=0.0417, Precision=0.6667, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=no_income|L3_contact=cellular: BAC=0.7743, Regret=0.2482, Precision=0.5965, Recall=0.7907
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar|L3_contact=telephone: BAC=0.9706, Regret=0.0625, Precision=0.2500, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar|L3_contact=telephone: BAC=0.8335, Regret=0.1404, Precision=0.6111, Recall=0.7857
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp|L3_contact=cellular: BAC=0.8491, Regret=0.0950, Precision=0.7333, Recall=0.7333
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar|L3_contact=telephone: BAC=0.8517, Regret=0.0638, Precision=0.6000, Recall=0.7500
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=unknown|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=unknown|L3_contact=cellular: BAC=0.7500, Regret=0.2500, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp|L3_contact=cellular: BAC=0.9630, Regret=0.0847, Precision=0.5556, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=no_income|L3_contact=cellular: BAC=0.8479, Regret=0.1649, Precision=0.5556, Recall=0.9091
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=retired|L3_contact=telephone: BAC=0.8773, Regret=0.0741, Precision=0.8000, Recall=0.8000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar|L3_contact=telephone: BAC=0.8750, Regret=0.0550, Precision=1.0000, Recall=0.7500
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=unknown|L3_contact=cellular: BAC=0.8750, Regret=0.2222, Precision=0.3333, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=unknown|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp|L3_contact=telephone: BAC=1.0000, Regret=0.0625, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=retired|L3_contact=cellular: BAC=0.6405, Regret=0.3617, Precision=0.4800, Recall=0.9000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp|L3_contact=telephone: BAC=0.9375, Regret=0.0750, Precision=0.6667, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=retired|L3_contact=cellular: BAC=1.0000, Regret=0.0556, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=no_income|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=no_income|L3_contact=cellular: BAC=0.8848, Regret=0.1212, Precision=0.7500, Recall=0.9000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=no_income|L3_contact=telephone: BAC=0.6500, Regret=0.2500, Precision=0.5000, Recall=0.5000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=retired|L3_contact=cellular: BAC=1.0000, Regret=0.0357, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar|L3_contact=telephone: BAC=0.7643, Regret=0.2895, Precision=0.7500, Recall=0.6000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=no_income|L3_contact=telephone: BAC=1.0000, Regret=0.1071, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=unknown|L3_contact=cellular: BAC=0.9286, Regret=0.1111, Precision=0.6667, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=unknown|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=unknown|L3_contact=cellular: BAC=0.8333, Regret=0.2500, Precision=1.0000, Recall=0.6667
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=no_income|L3_contact=telephone: BAC=0.8750, Regret=0.2083, Precision=0.3333, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=white_collar|L3_contact=cellular: BAC=0.6865, Regret=0.2283, Precision=0.7222, Recall=0.9286
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=no_income|L3_contact=telephone: BAC=1.0000, Regret=0.2500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=retired|L3_contact=telephone: BAC=0.6432, Regret=0.3640, Precision=0.4571, Recall=0.8000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=white_collar|L3_contact=telephone: BAC=0.8750, Regret=0.2000, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar|L3_contact=cellular: BAC=1.0000, Regret=0.0312, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar|L3_contact=telephone: BAC=0.4286, Regret=0.2812, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=retired|L3_contact=telephone: BAC=0.0000, Regret=1.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=retired|L3_contact=cellular: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=no_income|L3_contact=cellular: BAC=0.0000, Regret=0.7500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=self_emp|L3_contact=telephone: BAC=0.5000, Regret=0.1875, Precision=0.7500, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=self_emp|L3_contact=cellular: BAC=1.0000, Regret=0.2500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=unknown|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=unknown|L3_contact=telephone: BAC=0.0000, Regret=1.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar: BAC=0.8472, Regret=0.0978, Precision=0.5871, Recall=0.7583
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50: BAC=0.8265, Regret=0.0898, Precision=0.6000, Recall=0.7009
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar: BAC=0.7670, Regret=0.1804, Precision=0.5528, Recall=0.6415
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30: BAC=0.7983, Regret=0.1539, Precision=0.5606, Recall=0.6981
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=retired: BAC=0.8579, Regret=0.1135, Precision=0.5000, Recall=0.8148
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60: BAC=0.8292, Regret=0.1020, Precision=0.5841, Recall=0.7184
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar: BAC=0.8036, Regret=0.0778, Precision=0.6100, Recall=0.6421
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40: BAC=0.8143, Regret=0.1039, Precision=0.5749, Recall=0.6890
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar: BAC=0.8236, Regret=0.1142, Precision=0.6562, Recall=0.7000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar: BAC=0.7872, Regret=0.0871, Precision=0.5102, Recall=0.6250
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar: BAC=0.7799, Regret=0.0732, Precision=0.6481, Recall=0.5833
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp: BAC=0.8528, Regret=0.0842, Precision=0.6000, Recall=0.7500
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp: BAC=0.8475, Regret=0.0774, Precision=0.3333, Recall=0.7500
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar: BAC=0.8084, Regret=0.1164, Precision=0.5741, Recall=0.6858
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp: BAC=0.8065, Regret=0.1196, Precision=0.5000, Recall=0.6923
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=no_income: BAC=0.8007, Regret=0.2083, Precision=0.5625, Recall=0.8000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=retired: BAC=1.0000, Regret=0.0208, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=no_income: BAC=0.8042, Regret=0.1585, Precision=0.6111, Recall=0.7333
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar: BAC=0.8160, Regret=0.1028, Precision=0.5902, Recall=0.6923
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=no_income: BAC=0.9115, Regret=0.0918, Precision=0.7500, Recall=0.9000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=no_income: BAC=0.8769, Regret=0.1379, Precision=0.5385, Recall=0.9130
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=unknown: BAC=0.8750, Regret=0.1500, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar: BAC=0.8750, Regret=0.1389, Precision=0.8333, Recall=0.8333
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60: BAC=0.6834, Regret=0.3211, Precision=0.5248, Recall=0.8706
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp: BAC=0.8875, Regret=0.1218, Precision=0.5000, Recall=0.8750
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=retired: BAC=0.5000, Regret=0.0714, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=50-60|L2_job=unknown: BAC=0.9688, Regret=0.0658, Precision=0.7500, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=40-50|L2_job=unknown: BAC=0.7000, Regret=0.1818, Precision=0.3333, Recall=0.5000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=30-40|L2_job=unknown: BAC=0.8333, Regret=0.1250, Precision=1.0000, Recall=0.6667
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=retired: BAC=0.6518, Regret=0.3558, Precision=0.4727, Recall=0.8667
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=white_collar: BAC=0.7359, Regret=0.2232, Precision=0.7000, Recall=0.9333
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=no_income: BAC=0.6667, Regret=0.4167, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=<=30|L2_job=retired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=self_emp: BAC=0.7500, Regret=0.2000, Precision=0.7500, Recall=1.0000
【INFO】【2026-03-26 18:43:36】[BASELINE] 桶 L1_age=>60|L2_job=unknown: BAC=0.0000, Regret=1.0000, Precision=0.0000, Recall=0.0000

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [18:43:37] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 18:43:37】【K折实验】正在执行第 2/5 折...
【INFO】【2026-03-26 18:43:37】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=1.0
【INFO】【2026-03-26 18:43:37】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=36169
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="30-40"，n_samples=14083
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=40-50，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="40-50"，n_samples=9058
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="50-60"，n_samples=6487
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=<=30，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="<=30"，n_samples=5587
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=>60，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule=">60"，n_samples=954
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=4832
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=523
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=945
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=7723
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40|L2_job=others，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=60
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=3428
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=280
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=691
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=4484
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=40-50|L2_job=others，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=175
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=1981
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=210
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=retired，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="retired"，n_samples=999
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=469
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=2750
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=others，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=78
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=1875
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=790
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=282
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=2622
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=<=30|L2_job=others，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=18
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=>60|L2_job=retired，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="retired"，n_samples=707
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=129
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=>60|L2_job=others，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=118
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=2728
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=213
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1891
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=357
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=131
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=35
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=660
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=251
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=34
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=5743
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=232
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1748
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1883
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=253
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1292
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=193
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=40-50|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=87
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=443
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=197
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=51
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=3018
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=248
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1218
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1051
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=235
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=695
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=145
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=65
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=586
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=319
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=94
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=275
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=148
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=46
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1771
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=274
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=705
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1078
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=723
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=74
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=598
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=113
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=79
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=206
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=76
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1895
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=650
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=77
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=cellular，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=469
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=telephone，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=227
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=others，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=11
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=>60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=106
[INFO][BT][2026-03-26 18:43:38] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar|L3_contact=others，level=3，parent_id=L1_age=>60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=23
[INFO][BT][2026-03-26 18:43:42] 桶树构建完成：总桶数=83，最大层数=3，叶子桶数=58
【INFO】【2026-03-26 18:43:42】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 18:43:42】【阈值】桶 ROOT（n_val=3253，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:43:42] 桶 bucket_id=ROOT level=0：
    n_train=7593, n_val=3253,
    BAC=0.831, F1=0.641, AUC=0.935,
    Regret=0.107, BND_ratio=0.069, POS_coverage=0.172,
    Score(f1_regret_bnd )=0.466，threshold_source=val
【INFO】【2026-03-26 18:43:42】【阈值】桶 L1_age=30-40 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:43:42] 桶 bucket_id=L1_age=30-40 level=1：
    n_train=2969, n_val=1295,
    BAC=0.775, F1=0.609, AUC=0.936,
    Regret=0.099, BND_ratio=0.057, POS_coverage=0.113,
    Score(f1_regret_bnd )=0.453，threshold_source=val
[INFO][BT][2026-03-26 18:43:42] 桶 bucket_id=L1_age=30-40：
    parent_id=ROOT，parent_Score=0.466, bucket_Score=0.453,
    Gain=-0.013, is_weak=True
【INFO】【2026-03-26 18:43:43】【阈值】桶 L1_age=40-50 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:43:43] 桶 bucket_id=L1_age=40-50 level=1：
    n_train=1922, n_val=883,
    BAC=0.735, F1=0.583, AUC=0.937,
    Regret=0.104, BND_ratio=0.108, POS_coverage=0.104,
    Score(f1_regret_bnd )=0.371，threshold_source=val
[INFO][BT][2026-03-26 18:43:43] 桶 bucket_id=L1_age=40-50：
    parent_id=ROOT，parent_Score=0.466, bucket_Score=0.371,
    Gain=-0.095, is_weak=True
【INFO】【2026-03-26 18:43:43】【阈值】桶 L1_age=50-60（n_val=648，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:43:43] 桶 bucket_id=L1_age=50-60 level=1：
    n_train=1393, n_val=648,
    BAC=0.876, F1=0.709, AUC=0.965,
    Regret=0.077, BND_ratio=0.062, POS_coverage=0.159,
    Score(f1_regret_bnd )=0.570，threshold_source=val
[INFO][BT][2026-03-26 18:43:43] 桶 bucket_id=L1_age=50-60：
    parent_id=ROOT，parent_Score=0.466, bucket_Score=0.570,
    Gain=+0.105, is_weak=False
【INFO】【2026-03-26 18:43:43】【阈值】桶 L1_age=<=30 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:43:43] 桶 bucket_id=L1_age=<=30 level=1：
    n_train=1171, n_val=574,
    BAC=0.692, F1=0.589, AUC=0.901,
    Regret=0.149, BND_ratio=0.132, POS_coverage=0.127,
    Score(f1_regret_bnd )=0.308，threshold_source=val
[INFO][BT][2026-03-26 18:43:43] 桶 bucket_id=L1_age=<=30：
    parent_id=ROOT，parent_Score=0.466, bucket_Score=0.308,
    Gain=-0.158, is_weak=True
【INFO】【2026-03-26 18:43:44】【阈值】桶 L1_age=>60 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:43:44] 桶 bucket_id=L1_age=>60 level=1：
    n_train=335, n_val=123,
    BAC=0.627, F1=0.750, AUC=0.795,
    Regret=0.250, BND_ratio=0.236, POS_coverage=0.496,
    Score(f1_regret_bnd )=0.264，threshold_source=val
[INFO][BT][2026-03-26 18:43:44] 桶 bucket_id=L1_age=>60：
    parent_id=ROOT，parent_Score=0.466, bucket_Score=0.264,
    Gain=-0.201, is_weak=True
【INFO】【2026-03-26 18:43:44】【阈值】桶 L1_age=30-40|L2_job=blue_collar 标记为弱桶，阈值将回退使用 L1_age=30-40 的阈值
[INFO][BT][2026-03-26 18:43:44] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar level=2：
    n_train=1005, n_val=484,
    BAC=0.785, F1=0.609, AUC=0.948,
    Regret=0.087, BND_ratio=0.072, POS_coverage=0.105,
    Score(f1_regret_bnd )=0.450，threshold_source=val
[INFO][BT][2026-03-26 18:43:44] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar：
    parent_id=L1_age=30-40，parent_Score=0.453, bucket_Score=0.450,
    Gain=-0.003, is_weak=True
【INFO】【2026-03-26 18:43:44】【阈值】桶 L1_age=30-40|L2_job=no_income（n_val=81，source=val) 使用本地阈值 α=0.5000, β=0.3000
[INFO][BT][2026-03-26 18:43:44] 桶 bucket_id=L1_age=30-40|L2_job=no_income level=2：
    n_train=191, n_val=81,
    BAC=0.854, F1=0.737, AUC=0.969,
    Regret=0.059, BND_ratio=0.049, POS_coverage=0.123,
    Score(f1_regret_bnd )=0.629，threshold_source=val
[INFO][BT][2026-03-26 18:43:44] 桶 bucket_id=L1_age=30-40|L2_job=no_income：
    parent_id=L1_age=30-40，parent_Score=0.453, bucket_Score=0.629,
    Gain=+0.176, is_weak=False
【INFO】【2026-03-26 18:43:45】【阈值】桶 L1_age=30-40|L2_job=self_emp（n_val=147，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:43:45] 桶 bucket_id=L1_age=30-40|L2_job=self_emp level=2：
    n_train=216, n_val=147,
    BAC=0.830, F1=0.828, AUC=0.973,
    Regret=0.065, BND_ratio=0.054, POS_coverage=0.082,
    Score(f1_regret_bnd )=0.709，threshold_source=val
[INFO][BT][2026-03-26 18:43:45] 桶 bucket_id=L1_age=30-40|L2_job=self_emp：
    parent_id=L1_age=30-40，parent_Score=0.453, bucket_Score=0.709,
    Gain=+0.256, is_weak=False
【INFO】【2026-03-26 18:43:45】【阈值】桶 L1_age=30-40|L2_job=white_collar 标记为弱桶，阈值将回退使用 L1_age=30-40 的阈值
[INFO][BT][2026-03-26 18:43:45] 桶 bucket_id=L1_age=30-40|L2_job=white_collar level=2：
    n_train=1617, n_val=747,
    BAC=0.772, F1=0.590, AUC=0.945,
    Regret=0.098, BND_ratio=0.066, POS_coverage=0.122,
    Score(f1_regret_bnd )=0.427，threshold_source=val
[INFO][BT][2026-03-26 18:43:45] 桶 bucket_id=L1_age=30-40|L2_job=white_collar：
    parent_id=L1_age=30-40，parent_Score=0.453, bucket_Score=0.427,
    Gain=-0.026, is_weak=True
【INFO】【2026-03-26 18:43:45】【阈值】桶 L1_age=30-40|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=30-40 的阈值
[INFO][BT][2026-03-26 18:43:45] 桶 bucket_id=L1_age=30-40|L2_job=others level=2：
    n_train=40, n_val=20,
    BAC=0.839, F1=0.750, AUC=0.982,
    Regret=0.042, BND_ratio=0.067, POS_coverage=0.067,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:43:45] 桶 bucket_id=L1_age=30-40|L2_job=others：
    parent_id=L1_age=30-40，parent_Score=0.453, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:43:46】【阈值】桶 L1_age=40-50|L2_job=blue_collar（n_val=339，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:43:46] 桶 bucket_id=L1_age=40-50|L2_job=blue_collar level=2：
    n_train=733, n_val=339,
    BAC=0.775, F1=0.595, AUC=0.958,
    Regret=0.063, BND_ratio=0.074, POS_coverage=0.059,
    Score(f1_regret_bnd )=0.458，threshold_source=val
[INFO][BT][2026-03-26 18:43:46] 桶 bucket_id=L1_age=40-50|L2_job=blue_collar：
    parent_id=L1_age=40-50，parent_Score=0.371, bucket_Score=0.458,
    Gain=+0.087, is_weak=False
【INFO】【2026-03-26 18:43:46】【阈值】桶 L1_age=40-50|L2_job=no_income（n_val=75，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:43:46] 桶 bucket_id=L1_age=40-50|L2_job=no_income level=2：
    n_train=107, n_val=75,
    BAC=0.800, F1=0.727, AUC=0.932,
    Regret=0.110, BND_ratio=0.133, POS_coverage=0.160,
    Score(f1_regret_bnd )=0.484，threshold_source=val
[INFO][BT][2026-03-26 18:43:46] 桶 bucket_id=L1_age=40-50|L2_job=no_income：
    parent_id=L1_age=40-50，parent_Score=0.371, bucket_Score=0.484,
    Gain=+0.113, is_weak=False
【INFO】【2026-03-26 18:43:46】【阈值】桶 L1_age=40-50|L2_job=self_emp 标记为弱桶，阈值将回退使用 L1_age=40-50 的阈值
[INFO][BT][2026-03-26 18:43:46] 桶 bucket_id=L1_age=40-50|L2_job=self_emp level=2：
    n_train=164, n_val=126,
    BAC=0.650, F1=0.500, AUC=0.952,
    Regret=0.087, BND_ratio=0.048, POS_coverage=0.024,
    Score(f1_regret_bnd )=0.365，threshold_source=val
[INFO][BT][2026-03-26 18:43:46] 桶 bucket_id=L1_age=40-50|L2_job=self_emp：
    parent_id=L1_age=40-50，parent_Score=0.371, bucket_Score=0.365,
    Gain=-0.006, is_weak=True
【INFO】【2026-03-26 18:43:46】【阈值】桶 L1_age=40-50|L2_job=white_collar（n_val=443，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:43:46] 桶 bucket_id=L1_age=40-50|L2_job=white_collar level=2：
    n_train=950, n_val=443,
    BAC=0.806, F1=0.699, AUC=0.951,
    Regret=0.097, BND_ratio=0.104, POS_coverage=0.151,
    Score(f1_regret_bnd )=0.498，threshold_source=val
[INFO][BT][2026-03-26 18:43:46] 桶 bucket_id=L1_age=40-50|L2_job=white_collar：
    parent_id=L1_age=40-50，parent_Score=0.371, bucket_Score=0.498,
    Gain=+0.127, is_weak=False
【INFO】【2026-03-26 18:43:47】【阈值】桶 L1_age=40-50|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=40-50 的阈值
[INFO][BT][2026-03-26 18:43:47] 桶 bucket_id=L1_age=40-50|L2_job=others level=2：
    n_train=120, n_val=55,
    BAC=0.803, F1=0.667, AUC=0.968,
    Regret=0.056, BND_ratio=0.017, POS_coverage=0.057,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:43:47] 桶 bucket_id=L1_age=40-50|L2_job=others：
    parent_id=L1_age=40-50，parent_Score=0.371, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:43:47】【阈值】桶 L1_age=50-60|L2_job=blue_collar（n_val=225，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:43:47] 桶 bucket_id=L1_age=50-60|L2_job=blue_collar level=2：
    n_train=413, n_val=225,
    BAC=0.873, F1=0.683, AUC=0.961,
    Regret=0.058, BND_ratio=0.036, POS_coverage=0.107,
    Score(f1_regret_bnd )=0.590，threshold_source=val
[INFO][BT][2026-03-26 18:43:47] 桶 bucket_id=L1_age=50-60|L2_job=blue_collar：
    parent_id=L1_age=50-60，parent_Score=0.570, bucket_Score=0.590,
    Gain=+0.019, is_weak=False
【INFO】【2026-03-26 18:43:47】【阈值】桶 L1_age=50-60|L2_job=no_income（n_val=64，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:43:47] 桶 bucket_id=L1_age=50-60|L2_job=no_income level=2：
    n_train=146, n_val=64,
    BAC=0.843, F1=0.750, AUC=0.952,
    Regret=0.090, BND_ratio=0.078, POS_coverage=0.203,
    Score(f1_regret_bnd )=0.582，threshold_source=val
[INFO][BT][2026-03-26 18:43:47] 桶 bucket_id=L1_age=50-60|L2_job=no_income：
    parent_id=L1_age=50-60，parent_Score=0.570, bucket_Score=0.582,
    Gain=+0.012, is_weak=False
【INFO】【2026-03-26 18:43:48】【阈值】桶 L1_age=50-60|L2_job=retired（n_val=116，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:43:48] 桶 bucket_id=L1_age=50-60|L2_job=retired level=2：
    n_train=248, n_val=116,
    BAC=0.908, F1=0.692, AUC=0.954,
    Regret=0.067, BND_ratio=0.017, POS_coverage=0.138,
    Score(f1_regret_bnd )=0.608，threshold_source=val
[INFO][BT][2026-03-26 18:43:48] 桶 bucket_id=L1_age=50-60|L2_job=retired：
    parent_id=L1_age=50-60，parent_Score=0.570, bucket_Score=0.608,
    Gain=+0.038, is_weak=False
【INFO】【2026-03-26 18:43:48】【阈值】桶 L1_age=50-60|L2_job=self_emp（n_val=151，source=val) 使用本地阈值 α=0.5000, β=0.3000
[INFO][BT][2026-03-26 18:43:48] 桶 bucket_id=L1_age=50-60|L2_job=self_emp level=2：
    n_train=183, n_val=151,
    BAC=0.879, F1=0.667, AUC=0.978,
    Regret=0.026, BND_ratio=0.026, POS_coverage=0.046,
    Score(f1_regret_bnd )=0.614，threshold_source=val
[INFO][BT][2026-03-26 18:43:48] 桶 bucket_id=L1_age=50-60|L2_job=self_emp：
    parent_id=L1_age=50-60，parent_Score=0.570, bucket_Score=0.614,
    Gain=+0.043, is_weak=False
【INFO】【2026-03-26 18:43:48】【阈值】桶 L1_age=50-60|L2_job=white_collar 标记为弱桶，阈值将回退使用 L1_age=50-60 的阈值
[INFO][BT][2026-03-26 18:43:48] 桶 bucket_id=L1_age=50-60|L2_job=white_collar level=2：
    n_train=585, n_val=297,
    BAC=0.824, F1=0.673, AUC=0.934,
    Regret=0.121, BND_ratio=0.071, POS_coverage=0.219,
    Score(f1_regret_bnd )=0.481，threshold_source=val
[INFO][BT][2026-03-26 18:43:48] 桶 bucket_id=L1_age=50-60|L2_job=white_collar：
    parent_id=L1_age=50-60，parent_Score=0.570, bucket_Score=0.481,
    Gain=-0.090, is_weak=True
【INFO】【2026-03-26 18:43:49】【阈值】桶 L1_age=50-60|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=50-60 的阈值
[INFO][BT][2026-03-26 18:43:49] 桶 bucket_id=L1_age=50-60|L2_job=others level=2：
    n_train=49, n_val=29,
    BAC=0.846, F1=0.857, AUC=0.970,
    Regret=0.051, BND_ratio=0.064, POS_coverage=0.077,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:43:49] 桶 bucket_id=L1_age=50-60|L2_job=others：
    parent_id=L1_age=50-60，parent_Score=0.570, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:43:49】【阈值】桶 L1_age=<=30|L2_job=blue_collar（n_val=185，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:43:49] 桶 bucket_id=L1_age=<=30|L2_job=blue_collar level=2：
    n_train=427, n_val=185,
    BAC=0.867, F1=0.742, AUC=0.946,
    Regret=0.089, BND_ratio=0.070, POS_coverage=0.195,
    Score(f1_regret_bnd )=0.582，threshold_source=val
[INFO][BT][2026-03-26 18:43:49] 桶 bucket_id=L1_age=<=30|L2_job=blue_collar：
    parent_id=L1_age=<=30，parent_Score=0.308, bucket_Score=0.582,
    Gain=+0.275, is_weak=False
【INFO】【2026-03-26 18:43:49】【阈值】桶 L1_age=<=30|L2_job=no_income 标记为弱桶，阈值将回退使用 L1_age=<=30 的阈值
[INFO][BT][2026-03-26 18:43:49] 桶 bucket_id=L1_age=<=30|L2_job=no_income level=2：
    n_train=259, n_val=111,
    BAC=0.712, F1=0.638, AUC=0.832,
    Regret=0.259, BND_ratio=0.090, POS_coverage=0.351,
    Score(f1_regret_bnd )=0.289，threshold_source=val
[INFO][BT][2026-03-26 18:43:49] 桶 bucket_id=L1_age=<=30|L2_job=no_income：
    parent_id=L1_age=<=30，parent_Score=0.308, bucket_Score=0.289,
    Gain=-0.019, is_weak=True
【INFO】【2026-03-26 18:43:49】【阈值】桶 L1_age=<=30|L2_job=self_emp（n_val=84，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:43:49] 桶 bucket_id=L1_age=<=30|L2_job=self_emp level=2：
    n_train=95, n_val=84,
    BAC=0.873, F1=0.833, AUC=0.962,
    Regret=0.080, BND_ratio=0.107, POS_coverage=0.238,
    Score(f1_regret_bnd )=0.646，threshold_source=val
[INFO][BT][2026-03-26 18:43:49] 桶 bucket_id=L1_age=<=30|L2_job=self_emp：
    parent_id=L1_age=<=30，parent_Score=0.308, bucket_Score=0.646,
    Gain=+0.338, is_weak=False
【INFO】【2026-03-26 18:43:50】【阈值】桶 L1_age=<=30|L2_job=white_collar（n_val=258，source=val) 使用本地阈值 α=0.5000, β=0.2000
[INFO][BT][2026-03-26 18:43:50] 桶 bucket_id=L1_age=<=30|L2_job=white_collar level=2：
    n_train=580, n_val=258,
    BAC=0.736, F1=0.641, AUC=0.931,
    Regret=0.131, BND_ratio=0.140, POS_coverage=0.155,
    Score(f1_regret_bnd )=0.371，threshold_source=val
[INFO][BT][2026-03-26 18:43:50] 桶 bucket_id=L1_age=<=30|L2_job=white_collar：
    parent_id=L1_age=<=30，parent_Score=0.308, bucket_Score=0.371,
    Gain=+0.063, is_weak=False
【INFO】【2026-03-26 18:43:50】【阈值】桶 L1_age=<=30|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=<=30 的阈值
[INFO][BT][2026-03-26 18:43:50] 桶 bucket_id=L1_age=<=30|L2_job=others level=2：
    n_train=13, n_val=5,
    BAC=1.000, F1=1.000, AUC=1.000,
    Regret=0.000, BND_ratio=0.000, POS_coverage=0.222,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:43:50] 桶 bucket_id=L1_age=<=30|L2_job=others：
    parent_id=L1_age=<=30，parent_Score=0.308, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:43:50】【阈值】桶 L1_age=>60|L2_job=retired（n_val=115，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:43:50] 桶 bucket_id=L1_age=>60|L2_job=retired level=2：
    n_train=151, n_val=115,
    BAC=0.645, F1=0.682, AUC=0.755,
    Regret=0.287, BND_ratio=0.078, POS_coverage=0.713,
    Score(f1_regret_bnd )=0.317，threshold_source=val
[INFO][BT][2026-03-26 18:43:50] 桶 bucket_id=L1_age=>60|L2_job=retired：
    parent_id=L1_age=>60，parent_Score=0.264, bucket_Score=0.317,
    Gain=+0.053, is_weak=False
【INFO】【2026-03-26 18:43:51】【阈值】桶 L1_age=>60|L2_job=white_collar 标记为弱桶，阈值将回退使用 L1_age=>60 的阈值
[INFO][BT][2026-03-26 18:43:51] 桶 bucket_id=L1_age=>60|L2_job=white_collar level=2：
    n_train=100, n_val=29,
    BAC=0.564, F1=0.609, AUC=0.667,
    Regret=0.336, BND_ratio=0.241, POS_coverage=0.483,
    Score(f1_regret_bnd )=0.031，threshold_source=val
[INFO][BT][2026-03-26 18:43:51] 桶 bucket_id=L1_age=>60|L2_job=white_collar：
    parent_id=L1_age=>60，parent_Score=0.264, bucket_Score=0.031,
    Gain=-0.233, is_weak=True
【INFO】【2026-03-26 18:43:51】【阈值】桶 L1_age=>60|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=>60 的阈值
[INFO][BT][2026-03-26 18:43:51] 桶 bucket_id=L1_age=>60|L2_job=others level=2：
    n_train=89, n_val=29,
    BAC=0.848, F1=0.857, AUC=0.946,
    Regret=0.127, BND_ratio=0.068, POS_coverage=0.432,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:43:51] 桶 bucket_id=L1_age=>60|L2_job=others：
    parent_id=L1_age=>60，parent_Score=0.264, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:43:51】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=cellular 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=blue_collar 的阈值
[INFO][BT][2026-03-26 18:43:51] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular level=3：
    n_train=1860, n_val=868,
    BAC=0.754, F1=0.576, AUC=0.929,
    Regret=0.111, BND_ratio=0.029, POS_coverage=0.101,
    Score(f1_regret_bnd )=0.437，threshold_source=val
[INFO][BT][2026-03-26 18:43:51] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.450, bucket_Score=0.437,
    Gain=-0.013, is_weak=True
【INFO】【2026-03-26 18:43:52】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=telephone（n_val=60，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:43:52] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone level=3：
    n_train=153, n_val=60,
    BAC=0.773, F1=0.667, AUC=0.964,
    Regret=0.071, BND_ratio=0.050, POS_coverage=0.067,
    Score(f1_regret_bnd )=0.546，threshold_source=val
[INFO][BT][2026-03-26 18:43:52] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.450, bucket_Score=0.546,
    Gain=+0.096, is_weak=False
【INFO】【2026-03-26 18:43:53】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=unknown 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=blue_collar 的阈值
[INFO][BT][2026-03-26 18:43:53] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown level=3：
    n_train=1342, n_val=549,
    BAC=0.674, F1=0.485, AUC=0.963,
    Regret=0.045, BND_ratio=0.058, POS_coverage=0.024,
    Score(f1_regret_bnd )=0.382，threshold_source=val
[INFO][BT][2026-03-26 18:43:53] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.450, bucket_Score=0.382,
    Gain=-0.068, is_weak=True
【INFO】【2026-03-26 18:43:53】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=cellular 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=no_income 的阈值
[INFO][BT][2026-03-26 18:43:53] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular level=3：
    n_train=235, n_val=122,
    BAC=0.713, F1=0.636, AUC=0.900,
    Regret=0.158, BND_ratio=0.156, POS_coverage=0.180,
    Score(f1_regret_bnd )=0.323，threshold_source=val
[INFO][BT][2026-03-26 18:43:53] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.629, bucket_Score=0.323,
    Gain=-0.306, is_weak=True
【INFO】【2026-03-26 18:43:53】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=unknown（n_val=37，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:43:53] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown level=3：
    n_train=94, n_val=37,
    BAC=0.986, F1=0.667, AUC=0.972,
    Regret=0.020, BND_ratio=0.000, POS_coverage=0.054,
    Score(f1_regret_bnd )=0.646，threshold_source=val
[INFO][BT][2026-03-26 18:43:53] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.629, bucket_Score=0.646,
    Gain=+0.018, is_weak=False
【INFO】【2026-03-26 18:43:54】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=others 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=no_income 的阈值
[INFO][BT][2026-03-26 18:43:54] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others level=3：
    n_train=27, n_val=8,
    BAC=0.750, F1=0.667, AUC=0.973,
    Regret=0.093, BND_ratio=0.114, POS_coverage=0.114,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:43:54] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.629, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:43:54】【阈值】桶 L1_age=30-40|L2_job=self_emp|L3_contact=cellular 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=self_emp 的阈值
[INFO][BT][2026-03-26 18:43:54] 桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular level=3：
    n_train=471, n_val=189,
    BAC=0.762, F1=0.642, AUC=0.924,
    Regret=0.120, BND_ratio=0.074, POS_coverage=0.138,
    Score(f1_regret_bnd )=0.447，threshold_source=val
[INFO][BT][2026-03-26 18:43:54] 桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=self_emp，parent_Score=0.709, bucket_Score=0.447,
    Gain=-0.261, is_weak=True
【INFO】【2026-03-26 18:43:54】【阈值】桶 L1_age=30-40|L2_job=self_emp|L3_contact=unknown（n_val=81，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:43:54] 桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=unknown level=3：
    n_train=170, n_val=81,
    BAC=0.830, F1=0.833, AUC=0.990,
    Regret=0.037, BND_ratio=0.074, POS_coverage=0.062,
    Score(f1_regret_bnd )=0.722，threshold_source=val

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [18:44:12] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 18:44:12】[BASELINE] 全局 XGB 模型训练完成
【INFO】【2026-03-26 18:44:12】[BASELINE] 阈值搜索开始
【INFO】【2026-03-26 18:44:13】[BASELINE] 最佳阈值找到: alpha=0.4000, beta=0.2000, regret=0.1148
【INFO】【2026-03-26 18:44:13】【桶树】已为样本生成桶ID，共 80 个组合
【INFO】【2026-03-26 18:44:13】[BASELINE] 测试集桶映射完成，共 80 个桶

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp|L3_contact=unknown: BAC=0.5000, Regret=0.0424, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar|L3_contact=unknown: BAC=0.7003, Regret=0.0648, Precision=0.5882, Recall=0.4167
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar|L3_contact=unknown: BAC=0.6486, Regret=0.0747, Precision=0.2857, Recall=0.3333
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=retired|L3_contact=unknown: BAC=0.9937, Regret=0.0122, Precision=0.7500, Recall=1.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar|L3_contact=unknown: BAC=0.6771, Regret=0.0531, Precision=0.5000, Recall=0.3684
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar|L3_contact=unknown: BAC=0.5802, Regret=0.0872, Precision=0.6667, Recall=0.1667
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar|L3_contact=unknown: BAC=0.6250, Regret=0.0273, Precision=1.0000, Recall=0.2500
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar|L3_contact=unknown: BAC=0.7429, Regret=0.0301, Precision=0.5000, Recall=0.5000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar|L3_contact=unknown: BAC=0.7056, Regret=0.0372, Precision=0.3750, Recall=0.4286
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp|L3_contact=unknown: BAC=0.5000, Regret=0.0811, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar|L3_contact=unknown: BAC=0.6000, Regret=0.0507, Precision=1.0000, Recall=0.2000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=retired|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=no_income|L3_contact=unknown: BAC=0.5000, Regret=0.0703, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp|L3_contact=unknown: BAC=0.5000, Regret=0.0388, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=unknown|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=no_income|L3_contact=unknown: BAC=1.0000, Regret=0.0081, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=no_income|L3_contact=unknown: BAC=0.8750, Regret=0.0385, Precision=1.0000, Recall=0.7500
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=no_income|L3_contact=unknown: BAC=1.0000, Regret=0.0156, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=unknown|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp|L3_contact=unknown: BAC=0.8333, Regret=0.1125, Precision=1.0000, Recall=0.6667
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=retired|L3_contact=unknown: BAC=1.0000, Regret=0.0357, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=unknown|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=retired|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=unknown|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar|L3_contact=cellular: BAC=0.7649, Regret=0.1981, Precision=0.6017, Recall=0.6396
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar|L3_contact=cellular: BAC=0.7616, Regret=0.1049, Precision=0.5581, Recall=0.5714
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar|L3_contact=telephone: BAC=0.6250, Regret=0.2386, Precision=1.0000, Recall=0.2500
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar|L3_contact=cellular: BAC=0.8014, Regret=0.0813, Precision=0.5439, Recall=0.6458
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=no_income|L3_contact=telephone: BAC=0.5000, Regret=0.2000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar|L3_contact=cellular: BAC=0.6728, Regret=0.1657, Precision=0.3939, Recall=0.4333
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar|L3_contact=cellular: BAC=0.7744, Regret=0.1514, Precision=0.6418, Recall=0.6143
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar|L3_contact=cellular: BAC=0.7479, Regret=0.1426, Precision=0.6042, Recall=0.5550
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp|L3_contact=cellular: BAC=0.8853, Regret=0.0729, Precision=0.7391, Recall=0.8095
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar|L3_contact=cellular: BAC=0.8060, Regret=0.1235, Precision=0.6636, Recall=0.6698
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar|L3_contact=telephone: BAC=0.6000, Regret=0.1230, Precision=1.0000, Recall=0.2000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=unknown|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=retired|L3_contact=cellular: BAC=0.7318, Regret=0.1710, Precision=0.7647, Recall=0.5000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar|L3_contact=cellular: BAC=0.7681, Regret=0.0925, Precision=0.6500, Recall=0.5652
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp|L3_contact=cellular: BAC=0.6149, Regret=0.1509, Precision=0.6000, Recall=0.2500
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp|L3_contact=cellular: BAC=0.7441, Regret=0.2013, Precision=0.6250, Recall=0.5882
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar|L3_contact=telephone: BAC=0.6589, Regret=0.0634, Precision=0.5000, Recall=0.3333
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=no_income|L3_contact=cellular: BAC=0.7350, Regret=0.3204, Precision=0.7027, Recall=0.5909
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar|L3_contact=telephone: BAC=0.9906, Regret=0.0278, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=no_income|L3_contact=cellular: BAC=0.8500, Regret=0.1167, Precision=0.5000, Recall=0.8000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=retired|L3_contact=telephone: BAC=0.7473, Regret=0.2000, Precision=0.8000, Recall=0.5714
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar|L3_contact=telephone: BAC=0.6263, Regret=0.1655, Precision=0.3750, Recall=0.3333
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar|L3_contact=telephone: BAC=0.8225, Regret=0.0663, Precision=0.6667, Recall=0.6667
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp|L3_contact=cellular: BAC=0.5947, Regret=0.2179, Precision=0.5000, Recall=0.2222
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp|L3_contact=telephone: BAC=0.4545, Regret=0.2500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=retired|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar|L3_contact=telephone: BAC=0.8393, Regret=0.0992, Precision=0.7143, Recall=0.7143
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=no_income|L3_contact=telephone: BAC=0.7564, Regret=0.1562, Precision=0.5000, Recall=0.6667
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar|L3_contact=telephone: BAC=0.7188, Regret=0.1625, Precision=0.6667, Recall=0.5000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=no_income|L3_contact=cellular: BAC=0.6978, Regret=0.3015, Precision=0.5556, Recall=0.5556
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=retired|L3_contact=cellular: BAC=0.7500, Regret=0.2500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=no_income|L3_contact=cellular: BAC=0.6844, Regret=0.2200, Precision=0.4667, Recall=0.5000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=white_collar|L3_contact=cellular: BAC=0.7500, Regret=0.3400, Precision=0.7000, Recall=0.7000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=unknown|L3_contact=cellular: BAC=0.6282, Regret=0.2500, Precision=0.5000, Recall=0.3333
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=unknown|L3_contact=cellular: BAC=0.8333, Regret=0.3214, Precision=1.0000, Recall=0.6667
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=retired|L3_contact=cellular: BAC=0.8571, Regret=0.1071, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=no_income|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=retired|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=unknown|L3_contact=cellular: BAC=1.0000, Regret=0.0500, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar|L3_contact=cellular: BAC=0.5000, Regret=0.4375, Precision=0.3333, Recall=0.5000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp|L3_contact=telephone: BAC=0.8333, Regret=0.2500, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp|L3_contact=telephone: BAC=0.4000, Regret=0.2917, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=unknown|L3_contact=cellular: BAC=1.0000, Regret=0.1250, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=no_income|L3_contact=telephone: BAC=0.5000, Regret=0.1250, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar|L3_contact=telephone: BAC=0.5000, Regret=0.2500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=retired|L3_contact=cellular: BAC=0.6542, Regret=0.3750, Precision=0.5968, Recall=0.7115
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=retired|L3_contact=telephone: BAC=0.7965, Regret=0.2500, Precision=0.7895, Recall=0.7143
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=self_emp|L3_contact=cellular: BAC=0.5000, Regret=0.4167, Precision=0.5000, Recall=0.6667
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=white_collar|L3_contact=telephone: BAC=0.8333, Regret=0.2917, Precision=1.0000, Recall=0.6667
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=self_emp|L3_contact=telephone: BAC=0.2500, Regret=0.5833, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=unknown|L3_contact=telephone: BAC=0.7500, Regret=0.3333, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=retired|L3_contact=cellular: BAC=0.0000, Regret=0.7500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=no_income|L3_contact=cellular: BAC=0.5000, Regret=1.1250, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=unknown|L3_contact=cellular: BAC=0.0000, Regret=0.7500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=no_income|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp: BAC=0.8380, Regret=0.0708, Precision=0.7083, Recall=0.7083
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40: BAC=0.7597, Regret=0.1028, Precision=0.5946, Recall=0.5609
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar: BAC=0.7490, Regret=0.1235, Precision=0.6065, Recall=0.5458
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar: BAC=0.7644, Regret=0.1718, Precision=0.5859, Recall=0.6198
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30: BAC=0.7415, Regret=0.1729, Precision=0.5815, Recall=0.5617
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=retired: BAC=0.7629, Regret=0.1187, Precision=0.7692, Recall=0.5556
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60: BAC=0.7468, Regret=0.1130, Precision=0.6454, Recall=0.5291
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar: BAC=0.7708, Regret=0.0689, Precision=0.5405, Recall=0.5714
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar: BAC=0.6481, Regret=0.1394, Precision=0.4324, Recall=0.3478
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar: BAC=0.7589, Regret=0.1211, Precision=0.6184, Recall=0.5663
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar: BAC=0.8037, Regret=0.0948, Precision=0.6496, Recall=0.6496
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50: BAC=0.7730, Regret=0.0910, Precision=0.6138, Recall=0.5829
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar: BAC=0.7430, Regret=0.0810, Precision=0.5385, Recall=0.5185
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp: BAC=0.5693, Regret=0.1786, Precision=0.4000, Recall=0.1667
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar: BAC=0.7496, Regret=0.0715, Precision=0.6522, Recall=0.5172
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=retired: BAC=0.9500, Regret=0.0909, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=no_income: BAC=0.6771, Regret=0.1763, Precision=0.4667, Recall=0.4375
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp: BAC=0.6012, Regret=0.1044, Precision=0.6000, Recall=0.2143
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=unknown: BAC=0.8333, Regret=0.1500, Precision=1.0000, Recall=0.6667
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=no_income: BAC=0.7497, Regret=0.2527, Precision=0.6829, Recall=0.5957
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=no_income: BAC=0.8210, Regret=0.0918, Precision=0.6364, Recall=0.7000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=50-60|L2_job=no_income: BAC=0.7343, Regret=0.1909, Precision=0.5556, Recall=0.5556
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=30-40|L2_job=unknown: BAC=1.0000, Regret=0.0312, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp: BAC=0.7658, Regret=0.1856, Precision=0.6500, Recall=0.6190
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=retired: BAC=0.9688, Regret=0.0588, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=unknown: BAC=1.0000, Regret=0.0833, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=<=30|L2_job=retired: BAC=0.5000, Regret=0.3750, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=40-50|L2_job=unknown: BAC=0.6417, Regret=0.1739, Precision=0.5000, Recall=0.3333
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=white_collar: BAC=0.7628, Regret=0.3306, Precision=0.7500, Recall=0.6923
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60: BAC=0.6911, Regret=0.3494, Precision=0.6204, Recall=0.6837
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar: BAC=0.5571, Regret=0.3684, Precision=0.3333, Recall=0.4000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=retired: BAC=0.7035, Regret=0.3348, Precision=0.6420, Recall=0.7123
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=self_emp: BAC=0.4500, Regret=0.4722, Precision=0.4000, Recall=0.5000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=unknown: BAC=0.6667, Regret=0.4375, Precision=0.3333, Recall=1.0000
【INFO】【2026-03-26 18:44:16】[BASELINE] 桶 L1_age=>60|L2_job=no_income: BAC=0.7500, Regret=0.7500, Precision=1.0000, Recall=0.5000

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

【INFO】【2026-03-26 18:44:17】【K折实验】正在执行第 3/5 折...
【INFO】【2026-03-26 18:44:17】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=1.0

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [18:44:17] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 18:44:17】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=36169
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="30-40"，n_samples=14168
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=40-50，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="40-50"，n_samples=8935
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="50-60"，n_samples=6450
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=<=30，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="<=30"，n_samples=5673
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=>60，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule=">60"，n_samples=943
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=4833
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=502
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=959
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=7800
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40|L2_job=others，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=74
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=3345
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=284
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=700
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=4436
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=40-50|L2_job=others，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=170
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=1988
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=218
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=retired，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="retired"，n_samples=982
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=458
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=2735
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=others，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=69
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=1880
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=777
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=328
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=2670
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=<=30|L2_job=others，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=18
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=>60|L2_job=retired，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="retired"，n_samples=689
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=134
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=>60|L2_job=others，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=120
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=2697
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=209
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1927
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=340
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=131
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=31
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=673
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=252
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=34
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=5780
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=243
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1777
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1859
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=239
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1247
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=188
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=40-50|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=96
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=433
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=212
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=55
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=2978
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=257
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1201
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1056
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=230
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=702
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=146
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=72
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=558
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=336
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=88
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=264
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=148
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=46
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1762
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=285
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=688
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1078
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=729
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=73
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=588
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=116
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=73
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=244
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=84
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1952
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=634
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=84
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=cellular，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=453
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=telephone，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=231
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=others，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=5
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=>60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=108
[INFO][BT][2026-03-26 18:44:18] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar|L3_contact=others，level=3，parent_id=L1_age=>60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=26
[INFO][BT][2026-03-26 18:44:22] 桶树构建完成：总桶数=83，最大层数=3，叶子桶数=58
【INFO】【2026-03-26 18:44:22】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 18:44:22】【阈值】桶 ROOT（n_val=3253，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:44:22] 桶 bucket_id=ROOT level=0：
    n_train=7593, n_val=3253,
    BAC=0.757, F1=0.620, AUC=0.933,
    Regret=0.108, BND_ratio=0.075, POS_coverage=0.115,
    Score(f1_regret_bnd )=0.437，threshold_source=val
【INFO】【2026-03-26 18:44:23】【阈值】桶 L1_age=30-40（n_val=1289，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:44:23] 桶 bucket_id=L1_age=30-40 level=1：
    n_train=3010, n_val=1289,
    BAC=0.878, F1=0.676, AUC=0.948,
    Regret=0.090, BND_ratio=0.051, POS_coverage=0.178,
    Score(f1_regret_bnd )=0.535，threshold_source=val
[INFO][BT][2026-03-26 18:44:23] 桶 bucket_id=L1_age=30-40：
    parent_id=ROOT，parent_Score=0.437, bucket_Score=0.535,
    Gain=+0.098, is_weak=False
【INFO】【2026-03-26 18:44:23】【阈值】桶 L1_age=40-50（n_val=885，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:44:23] 桶 bucket_id=L1_age=40-50 level=1：
    n_train=1883, n_val=885,
    BAC=0.777, F1=0.632, AUC=0.955,
    Regret=0.091, BND_ratio=0.058, POS_coverage=0.099,
    Score(f1_regret_bnd )=0.483，threshold_source=val
[INFO][BT][2026-03-26 18:44:23] 桶 bucket_id=L1_age=40-50：
    parent_id=ROOT，parent_Score=0.437, bucket_Score=0.483,
    Gain=+0.046, is_weak=False
【INFO】【2026-03-26 18:44:23】【阈值】桶 L1_age=50-60 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:44:23] 桶 bucket_id=L1_age=50-60 level=1：
    n_train=1383, n_val=641,
    BAC=0.734, F1=0.564, AUC=0.934,
    Regret=0.114, BND_ratio=0.098, POS_coverage=0.125,
    Score(f1_regret_bnd )=0.351，threshold_source=val
[INFO][BT][2026-03-26 18:44:23] 桶 bucket_id=L1_age=50-60：
    parent_id=ROOT，parent_Score=0.437, bucket_Score=0.351,
    Gain=-0.086, is_weak=True
【INFO】【2026-03-26 18:44:24】【阈值】桶 L1_age=<=30 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:44:24] 桶 bucket_id=L1_age=<=30 level=1：
    n_train=1192, n_val=519,
    BAC=0.757, F1=0.650, AUC=0.910,
    Regret=0.155, BND_ratio=0.135, POS_coverage=0.227,
    Score(f1_regret_bnd )=0.361，threshold_source=val
[INFO][BT][2026-03-26 18:44:24] 桶 bucket_id=L1_age=<=30：
    parent_id=ROOT，parent_Score=0.437, bucket_Score=0.361,
    Gain=-0.076, is_weak=True
【INFO】【2026-03-26 18:44:24】【阈值】桶 L1_age=>60 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:44:24] 桶 bucket_id=L1_age=>60 level=1：
    n_train=334, n_val=126,
    BAC=0.614, F1=0.676, AUC=0.734,
    Regret=0.343, BND_ratio=0.056, POS_coverage=0.714,
    Score(f1_regret_bnd )=0.277，threshold_source=val
[INFO][BT][2026-03-26 18:44:24] 桶 bucket_id=L1_age=>60：
    parent_id=ROOT，parent_Score=0.437, bucket_Score=0.277,
    Gain=-0.160, is_weak=True
【INFO】【2026-03-26 18:44:24】【阈值】桶 L1_age=30-40|L2_job=blue_collar 标记为弱桶，阈值将回退使用 L1_age=30-40 的阈值
[INFO][BT][2026-03-26 18:44:24] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar level=2：
    n_train=998, n_val=503,
    BAC=0.765, F1=0.586, AUC=0.947,
    Regret=0.063, BND_ratio=0.040, POS_coverage=0.058,
    Score(f1_regret_bnd )=0.483，threshold_source=val
[INFO][BT][2026-03-26 18:44:24] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar：
    parent_id=L1_age=30-40，parent_Score=0.535, bucket_Score=0.483,
    Gain=-0.051, is_weak=True
【INFO】【2026-03-26 18:44:25】【阈值】桶 L1_age=30-40|L2_job=no_income 标记为弱桶，阈值将回退使用 L1_age=30-40 的阈值
[INFO][BT][2026-03-26 18:44:25] 桶 bucket_id=L1_age=30-40|L2_job=no_income level=2：
    n_train=176, n_val=154,
    BAC=0.661, F1=0.538, AUC=0.932,
    Regret=0.114, BND_ratio=0.123, POS_coverage=0.065,
    Score(f1_regret_bnd )=0.301，threshold_source=val
[INFO][BT][2026-03-26 18:44:25] 桶 bucket_id=L1_age=30-40|L2_job=no_income：
    parent_id=L1_age=30-40，parent_Score=0.535, bucket_Score=0.301,
    Gain=-0.233, is_weak=True
【INFO】【2026-03-26 18:44:25】【阈值】桶 L1_age=30-40|L2_job=self_emp（n_val=137，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:44:25] 桶 bucket_id=L1_age=30-40|L2_job=self_emp level=2：
    n_train=223, n_val=137,
    BAC=0.930, F1=0.667, AUC=0.969,
    Regret=0.066, BND_ratio=0.066, POS_coverage=0.131,
    Score(f1_regret_bnd )=0.535，threshold_source=val
[INFO][BT][2026-03-26 18:44:25] 桶 bucket_id=L1_age=30-40|L2_job=self_emp：
    parent_id=L1_age=30-40，parent_Score=0.535, bucket_Score=0.535,
    Gain=+0.001, is_weak=False
【INFO】【2026-03-26 18:44:25】【阈值】桶 L1_age=30-40|L2_job=white_collar 标记为弱桶，阈值将回退使用 L1_age=30-40 的阈值
[INFO][BT][2026-03-26 18:44:25] 桶 bucket_id=L1_age=30-40|L2_job=white_collar level=2：
    n_train=1647, n_val=735,
    BAC=0.829, F1=0.689, AUC=0.948,
    Regret=0.095, BND_ratio=0.091, POS_coverage=0.162,
    Score(f1_regret_bnd )=0.503，threshold_source=val
[INFO][BT][2026-03-26 18:44:25] 桶 bucket_id=L1_age=30-40|L2_job=white_collar：
    parent_id=L1_age=30-40，parent_Score=0.535, bucket_Score=0.503,
    Gain=-0.031, is_weak=True
【INFO】【2026-03-26 18:44:26】【阈值】桶 L1_age=30-40|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=30-40 的阈值
[INFO][BT][2026-03-26 18:44:26] 桶 bucket_id=L1_age=30-40|L2_job=others level=2：
    n_train=52, n_val=22,
    BAC=0.899, F1=0.857, AUC=0.989,
    Regret=0.034, BND_ratio=0.054, POS_coverage=0.095,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:44:26] 桶 bucket_id=L1_age=30-40|L2_job=others：
    parent_id=L1_age=30-40，parent_Score=0.535, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:44:26】【阈值】桶 L1_age=40-50|L2_job=blue_collar 标记为弱桶，阈值将回退使用 L1_age=40-50 的阈值
[INFO][BT][2026-03-26 18:44:26] 桶 bucket_id=L1_age=40-50|L2_job=blue_collar level=2：
    n_train=699, n_val=363,
    BAC=0.714, F1=0.514, AUC=0.965,
    Regret=0.059, BND_ratio=0.066, POS_coverage=0.047,
    Score(f1_regret_bnd )=0.390，threshold_source=val
[INFO][BT][2026-03-26 18:44:26] 桶 bucket_id=L1_age=40-50|L2_job=blue_collar：
    parent_id=L1_age=40-50，parent_Score=0.483, bucket_Score=0.390,
    Gain=-0.094, is_weak=True
【INFO】【2026-03-26 18:44:26】【阈值】桶 L1_age=40-50|L2_job=no_income（n_val=83，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:44:26] 桶 bucket_id=L1_age=40-50|L2_job=no_income level=2：
    n_train=107, n_val=83,
    BAC=0.911, F1=0.762, AUC=0.955,
    Regret=0.063, BND_ratio=0.012, POS_coverage=0.145,
    Score(f1_regret_bnd )=0.687，threshold_source=val
[INFO][BT][2026-03-26 18:44:26] 桶 bucket_id=L1_age=40-50|L2_job=no_income：
    parent_id=L1_age=40-50，parent_Score=0.483, bucket_Score=0.687,
    Gain=+0.203, is_weak=False
【INFO】【2026-03-26 18:44:27】【阈值】桶 L1_age=40-50|L2_job=self_emp 标记为弱桶，阈值将回退使用 L1_age=40-50 的阈值
[INFO][BT][2026-03-26 18:44:27] 桶 bucket_id=L1_age=40-50|L2_job=self_emp level=2：
    n_train=175, n_val=111,
    BAC=0.657, F1=0.500, AUC=0.943,
    Regret=0.059, BND_ratio=0.036, POS_coverage=0.018,
    Score(f1_regret_bnd )=0.405，threshold_source=val
[INFO][BT][2026-03-26 18:44:27] 桶 bucket_id=L1_age=40-50|L2_job=self_emp：
    parent_id=L1_age=40-50，parent_Score=0.483, bucket_Score=0.405,
    Gain=-0.078, is_weak=True
【INFO】【2026-03-26 18:44:27】【阈值】桶 L1_age=40-50|L2_job=white_collar（n_val=445，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:44:27] 桶 bucket_id=L1_age=40-50|L2_job=white_collar level=2：
    n_train=936, n_val=445,
    BAC=0.803, F1=0.673, AUC=0.948,
    Regret=0.092, BND_ratio=0.088, POS_coverage=0.124,
    Score(f1_regret_bnd )=0.494，threshold_source=val
[INFO][BT][2026-03-26 18:44:27] 桶 bucket_id=L1_age=40-50|L2_job=white_collar：
    parent_id=L1_age=40-50，parent_Score=0.483, bucket_Score=0.494,
    Gain=+0.011, is_weak=False
【INFO】【2026-03-26 18:44:27】【阈值】桶 L1_age=40-50|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=40-50 的阈值
[INFO][BT][2026-03-26 18:44:27] 桶 bucket_id=L1_age=40-50|L2_job=others level=2：
    n_train=123, n_val=47,
    BAC=0.751, F1=0.600, AUC=0.958,
    Regret=0.066, BND_ratio=0.035, POS_coverage=0.053,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:44:27] 桶 bucket_id=L1_age=40-50|L2_job=others：
    parent_id=L1_age=40-50，parent_Score=0.483, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:44:27】【阈值】桶 L1_age=50-60|L2_job=blue_collar（n_val=239，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:44:27] 桶 bucket_id=L1_age=50-60|L2_job=blue_collar level=2：
    n_train=407, n_val=239,
    BAC=0.868, F1=0.720, AUC=0.959,
    Regret=0.065, BND_ratio=0.042, POS_coverage=0.117,
    Score(f1_regret_bnd )=0.613，threshold_source=val
[INFO][BT][2026-03-26 18:44:27] 桶 bucket_id=L1_age=50-60|L2_job=blue_collar：
    parent_id=L1_age=50-60，parent_Score=0.351, bucket_Score=0.613,
    Gain=+0.262, is_weak=False
【INFO】【2026-03-26 18:44:28】【阈值】桶 L1_age=50-60|L2_job=no_income（n_val=65，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:44:28] 桶 bucket_id=L1_age=50-60|L2_job=no_income level=2：
    n_train=76, n_val=65,
    BAC=0.795, F1=0.609, AUC=0.922,
    Regret=0.146, BND_ratio=0.015, POS_coverage=0.200,
    Score(f1_regret_bnd )=0.447，threshold_source=val
[INFO][BT][2026-03-26 18:44:28] 桶 bucket_id=L1_age=50-60|L2_job=no_income：
    parent_id=L1_age=50-60，parent_Score=0.351, bucket_Score=0.447,
    Gain=+0.096, is_weak=False
【INFO】【2026-03-26 18:44:28】【阈值】桶 L1_age=50-60|L2_job=retired（n_val=166，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:44:28] 桶 bucket_id=L1_age=50-60|L2_job=retired level=2：
    n_train=252, n_val=166,
    BAC=0.847, F1=0.759, AUC=0.965,
    Regret=0.057, BND_ratio=0.072, POS_coverage=0.090,
    Score(f1_regret_bnd )=0.629，threshold_source=val
[INFO][BT][2026-03-26 18:44:28] 桶 bucket_id=L1_age=50-60|L2_job=retired：
    parent_id=L1_age=50-60，parent_Score=0.351, bucket_Score=0.629,
    Gain=+0.278, is_weak=False
【INFO】【2026-03-26 18:44:28】【阈值】桶 L1_age=50-60|L2_job=self_emp（n_val=154，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:44:28] 桶 bucket_id=L1_age=50-60|L2_job=self_emp level=2：
    n_train=114, n_val=154,
    BAC=0.811, F1=0.720, AUC=0.971,
    Regret=0.065, BND_ratio=0.058, POS_coverage=0.078,
    Score(f1_regret_bnd )=0.597，threshold_source=val
[INFO][BT][2026-03-26 18:44:28] 桶 bucket_id=L1_age=50-60|L2_job=self_emp：
    parent_id=L1_age=50-60，parent_Score=0.351, bucket_Score=0.597,
    Gain=+0.245, is_weak=False
【INFO】【2026-03-26 18:44:29】【阈值】桶 L1_age=50-60|L2_job=white_collar 标记为弱桶，阈值将回退使用 L1_age=50-60 的阈值
[INFO][BT][2026-03-26 18:44:29] 桶 bucket_id=L1_age=50-60|L2_job=white_collar level=2：
    n_train=575, n_val=301,
    BAC=0.701, F1=0.538, AUC=0.921,
    Regret=0.135, BND_ratio=0.130, POS_coverage=0.140,
    Score(f1_regret_bnd )=0.274，threshold_source=val
[INFO][BT][2026-03-26 18:44:29] 桶 bucket_id=L1_age=50-60|L2_job=white_collar：
    parent_id=L1_age=50-60，parent_Score=0.351, bucket_Score=0.274,
    Gain=-0.077, is_weak=True
【INFO】【2026-03-26 18:44:29】【阈值】桶 L1_age=50-60|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=50-60 的阈值
[INFO][BT][2026-03-26 18:44:29] 桶 bucket_id=L1_age=50-60|L2_job=others level=2：
    n_train=52, n_val=17,
    BAC=0.856, F1=0.778, AUC=0.974,
    Regret=0.072, BND_ratio=0.043, POS_coverage=0.130,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:44:29] 桶 bucket_id=L1_age=50-60|L2_job=others：
    parent_id=L1_age=50-60，parent_Score=0.351, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:44:29】【阈值】桶 L1_age=<=30|L2_job=blue_collar（n_val=191，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:44:29] 桶 bucket_id=L1_age=<=30|L2_job=blue_collar level=2：
    n_train=422, n_val=191,
    BAC=0.789, F1=0.667, AUC=0.946,
    Regret=0.101, BND_ratio=0.110, POS_coverage=0.147,
    Score(f1_regret_bnd )=0.456，threshold_source=val
[INFO][BT][2026-03-26 18:44:29] 桶 bucket_id=L1_age=<=30|L2_job=blue_collar：
    parent_id=L1_age=<=30，parent_Score=0.361, bucket_Score=0.456,
    Gain=+0.095, is_weak=False
【INFO】【2026-03-26 18:44:30】【阈值】桶 L1_age=<=30|L2_job=no_income 标记为弱桶，阈值将回退使用 L1_age=<=30 的阈值
[INFO][BT][2026-03-26 18:44:30] 桶 bucket_id=L1_age=<=30|L2_job=no_income level=2：
    n_train=254, n_val=111,
    BAC=0.672, F1=0.583, AUC=0.861,
    Regret=0.212, BND_ratio=0.171, POS_coverage=0.234,
    Score(f1_regret_bnd )=0.200，threshold_source=val
[INFO][BT][2026-03-26 18:44:30] 桶 bucket_id=L1_age=<=30|L2_job=no_income：
    parent_id=L1_age=<=30，parent_Score=0.361, bucket_Score=0.200,
    Gain=-0.161, is_weak=True
【INFO】【2026-03-26 18:44:30】【阈值】桶 L1_age=<=30|L2_job=self_emp（n_val=101，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:44:30] 桶 bucket_id=L1_age=<=30|L2_job=self_emp level=2：
    n_train=104, n_val=101,
    BAC=0.844, F1=0.694, AUC=0.933,
    Regret=0.126, BND_ratio=0.059, POS_coverage=0.297,
    Score(f1_regret_bnd )=0.508，threshold_source=val
[INFO][BT][2026-03-26 18:44:30] 桶 bucket_id=L1_age=<=30|L2_job=self_emp：
    parent_id=L1_age=<=30，parent_Score=0.361, bucket_Score=0.508,
    Gain=+0.147, is_weak=False
【INFO】【2026-03-26 18:44:31】【阈值】桶 L1_age=<=30|L2_job=white_collar 标记为弱桶，阈值将回退使用 L1_age=<=30 的阈值
[INFO][BT][2026-03-26 18:44:31] 桶 bucket_id=L1_age=<=30|L2_job=white_collar level=2：
    n_train=610, n_val=248,
    BAC=0.779, F1=0.618, AUC=0.883,
    Regret=0.169, BND_ratio=0.089, POS_coverage=0.274,
    Score(f1_regret_bnd )=0.360，threshold_source=val
[INFO][BT][2026-03-26 18:44:31] 桶 bucket_id=L1_age=<=30|L2_job=white_collar：
    parent_id=L1_age=<=30，parent_Score=0.361, bucket_Score=0.360,
    Gain=-0.001, is_weak=True
【INFO】【2026-03-26 18:44:31】【阈值】桶 L1_age=<=30|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=<=30 的阈值
[INFO][BT][2026-03-26 18:44:31] 桶 bucket_id=L1_age=<=30|L2_job=others level=2：
    n_train=15, n_val=3,
    BAC=1.000, F1=1.000, AUC=1.000,
    Regret=0.000, BND_ratio=0.000, POS_coverage=0.167,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:44:31] 桶 bucket_id=L1_age=<=30|L2_job=others：
    parent_id=L1_age=<=30，parent_Score=0.361, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:44:32】【阈值】桶 L1_age=>60|L2_job=retired 标记为弱桶，阈值将回退使用 L1_age=>60 的阈值
[INFO][BT][2026-03-26 18:44:32] 桶 bucket_id=L1_age=>60|L2_job=retired level=2：
    n_train=148, n_val=106,
    BAC=0.480, F1=0.705, AUC=0.734,
    Regret=0.333, BND_ratio=0.170, POS_coverage=0.830,
    Score(f1_regret_bnd )=0.203，threshold_source=val
[INFO][BT][2026-03-26 18:44:32] 桶 bucket_id=L1_age=>60|L2_job=retired：
    parent_id=L1_age=>60，parent_Score=0.277, bucket_Score=0.203,
    Gain=-0.074, is_weak=True
【INFO】【2026-03-26 18:44:32】【阈值】桶 L1_age=>60|L2_job=white_collar 标记为弱桶，阈值将回退使用 L1_age=>60 的阈值
[INFO][BT][2026-03-26 18:44:32] 桶 bucket_id=L1_age=>60|L2_job=white_collar level=2：
    n_train=97, n_val=37,
    BAC=0.452, F1=0.776, AUC=0.685,
    Regret=0.284, BND_ratio=0.243, POS_coverage=0.757,
    Score(f1_regret_bnd )=0.248，threshold_source=val
[INFO][BT][2026-03-26 18:44:32] 桶 bucket_id=L1_age=>60|L2_job=white_collar：
    parent_id=L1_age=>60，parent_Score=0.277, bucket_Score=0.248,
    Gain=-0.029, is_weak=True
【INFO】【2026-03-26 18:44:32】【阈值】桶 L1_age=>60|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=>60 的阈值
[INFO][BT][2026-03-26 18:44:32] 桶 bucket_id=L1_age=>60|L2_job=others level=2：
    n_train=91, n_val=29,
    BAC=0.665, F1=0.776, AUC=0.885,
    Regret=0.227, BND_ratio=0.233, POS_coverage=0.425,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:44:32] 桶 bucket_id=L1_age=>60|L2_job=others：
    parent_id=L1_age=>60，parent_Score=0.277, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:44:33】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=cellular 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=blue_collar 的阈值
[INFO][BT][2026-03-26 18:44:33] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular level=3：
    n_train=1879, n_val=818,
    BAC=0.761, F1=0.586, AUC=0.937,
    Regret=0.088, BND_ratio=0.059, POS_coverage=0.089,
    Score(f1_regret_bnd )=0.439，threshold_source=val
[INFO][BT][2026-03-26 18:44:33] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.483, bucket_Score=0.439,
    Gain=-0.044, is_weak=True
【INFO】【2026-03-26 18:44:33】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=telephone（n_val=77，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:44:33] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone level=3：
    n_train=132, n_val=77,
    BAC=0.861, F1=0.667, AUC=0.966,
    Regret=0.045, BND_ratio=0.000, POS_coverage=0.065,
    Score(f1_regret_bnd )=0.621，threshold_source=val
[INFO][BT][2026-03-26 18:44:33] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.483, bucket_Score=0.621,
    Gain=+0.138, is_weak=False
【INFO】【2026-03-26 18:44:34】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=unknown 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=blue_collar 的阈值
[INFO][BT][2026-03-26 18:44:34] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown level=3：
    n_train=1323, n_val=604,
    BAC=0.796, F1=0.582, AUC=0.963,
    Regret=0.050, BND_ratio=0.053, POS_coverage=0.051,
    Score(f1_regret_bnd )=0.479，threshold_source=val
[INFO][BT][2026-03-26 18:44:34] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.483, bucket_Score=0.479,
    Gain=-0.005, is_weak=True
【INFO】【2026-03-26 18:44:34】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=cellular（n_val=95，source=val) 使用本地阈值 α=0.5000, β=0.3000
[INFO][BT][2026-03-26 18:44:34] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular level=3：
    n_train=245, n_val=95,
    BAC=0.765, F1=0.606, AUC=0.908,
    Regret=0.150, BND_ratio=0.084, POS_coverage=0.200,
    Score(f1_regret_bnd )=0.372，threshold_source=val
[INFO][BT][2026-03-26 18:44:34] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.301, bucket_Score=0.372,
    Gain=+0.070, is_weak=False
【INFO】【2026-03-26 18:44:35】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=unknown 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=no_income 的阈值
[INFO][BT][2026-03-26 18:44:35] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown level=3：
    n_train=89, n_val=42,
    BAC=0.476, F1=0.000, AUC=0.976,
    Regret=0.036, BND_ratio=0.071, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.107，threshold_source=val
[INFO][BT][2026-03-26 18:44:35] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.301, bucket_Score=-0.107,
    Gain=-0.409, is_weak=True
【INFO】【2026-03-26 18:44:35】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=others 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=no_income 的阈值
[INFO][BT][2026-03-26 18:44:35] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others level=3：
    n_train=14, n_val=17,
    BAC=0.762, F1=0.750, AUC=1.000,
    Regret=0.081, BND_ratio=0.129, POS_coverage=0.097,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:44:35] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.301, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:44:36】【阈值】桶 L1_age=30-40|L2_job=self_emp|L3_contact=cellular 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=self_emp 的阈值
[INFO][BT][2026-03-26 18:44:36] 桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular level=3：
    n_train=481, n_val=192,
    BAC=0.811, F1=0.622, AUC=0.956,
    Regret=0.083, BND_ratio=0.068, POS_coverage=0.135,
    Score(f1_regret_bnd )=0.471，threshold_source=val
[INFO][BT][2026-03-26 18:44:36] 桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=self_emp，parent_Score=0.535, bucket_Score=0.471,
    Gain=-0.064, is_weak=True
【INFO】【2026-03-26 18:44:36】【阈值】桶 L1_age=30-40|L2_job=self_emp|L3_contact=unknown 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=self_emp 的阈值
[INFO][BT][2026-03-26 18:44:36] 桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=unknown level=3：
    n_train=181, n_val=71,
    BAC=0.471, F1=0.000, AUC=0.957,
    Regret=0.042, BND_ratio=0.085, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.127，threshold_source=val

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [18:45:02] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 18:45:04】[BASELINE] 全局 XGB 模型训练完成
【INFO】【2026-03-26 18:45:04】[BASELINE] 阈值搜索开始
【INFO】【2026-03-26 18:45:06】[BASELINE] 最佳阈值找到: alpha=0.3000, beta=0.1000, regret=0.1142
【INFO】【2026-03-26 18:45:06】【桶树】已为样本生成桶ID，共 82 个组合
【INFO】【2026-03-26 18:45:06】[BASELINE] 测试集桶映射完成，共 82 个桶

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)

【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar|L3_contact=unknown: BAC=0.8141, Regret=0.0681, Precision=0.4615, Recall=0.6667
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar|L3_contact=unknown: BAC=0.7155, Regret=0.0519, Precision=0.4167, Recall=0.4545
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar|L3_contact=unknown: BAC=0.7934, Regret=0.0494, Precision=0.5238, Recall=0.6111
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar|L3_contact=unknown: BAC=0.9128, Regret=0.0452, Precision=0.5455, Recall=0.8571
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar|L3_contact=unknown: BAC=0.7903, Regret=0.1031, Precision=0.3158, Recall=0.6667
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp|L3_contact=unknown: BAC=0.9907, Regret=0.0172, Precision=0.8000, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar|L3_contact=unknown: BAC=0.6868, Regret=0.0773, Precision=0.3600, Recall=0.4091
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar|L3_contact=unknown: BAC=0.7575, Regret=0.0572, Precision=0.5714, Recall=0.5333
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar|L3_contact=unknown: BAC=0.6562, Regret=0.0497, Precision=0.2500, Recall=0.3333
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=retired|L3_contact=unknown: BAC=0.7500, Regret=0.0577, Precision=1.0000, Recall=0.5000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=no_income|L3_contact=unknown: BAC=0.7500, Regret=0.1250, Precision=1.0000, Recall=0.5000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=no_income|L3_contact=unknown: BAC=0.9643, Regret=0.0714, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=no_income|L3_contact=unknown: BAC=0.6000, Regret=0.1719, Precision=1.0000, Recall=0.2000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp|L3_contact=unknown: BAC=0.5994, Regret=0.1395, Precision=0.3333, Recall=0.2500
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp|L3_contact=unknown: BAC=0.9722, Regret=0.0405, Precision=0.3333, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=retired|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=unknown|L3_contact=unknown: BAC=0.8571, Regret=0.1071, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=no_income|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=retired|L3_contact=unknown: BAC=1.0000, Regret=0.0833, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=retired|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=unknown|L3_contact=unknown: BAC=1.0000, Regret=0.0192, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp|L3_contact=unknown: BAC=0.7917, Regret=0.1333, Precision=0.6667, Recall=0.6667
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=unknown|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=unknown|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=unknown|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar|L3_contact=telephone: BAC=0.9932, Regret=0.0200, Precision=0.6667, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar|L3_contact=cellular: BAC=0.8357, Regret=0.0848, Precision=0.6346, Recall=0.7174
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar|L3_contact=cellular: BAC=0.8193, Regret=0.1120, Precision=0.5714, Recall=0.7027
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar|L3_contact=cellular: BAC=0.8032, Regret=0.1412, Precision=0.5444, Recall=0.6959
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar|L3_contact=telephone: BAC=0.9643, Regret=0.0593, Precision=0.4286, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar|L3_contact=cellular: BAC=0.8134, Regret=0.1521, Precision=0.6250, Recall=0.6944
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar|L3_contact=cellular: BAC=0.8227, Regret=0.1331, Precision=0.6076, Recall=0.7273
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar|L3_contact=cellular: BAC=0.7950, Regret=0.1310, Precision=0.5410, Recall=0.6735
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp|L3_contact=cellular: BAC=0.8363, Regret=0.1034, Precision=0.5769, Recall=0.7500
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=unknown|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=retired|L3_contact=telephone: BAC=0.7500, Regret=0.0962, Precision=1.0000, Recall=0.5000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar|L3_contact=cellular: BAC=0.8081, Regret=0.1048, Precision=0.5312, Recall=0.6800
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar|L3_contact=cellular: BAC=0.7662, Regret=0.2064, Precision=0.5169, Recall=0.6778
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar|L3_contact=telephone: BAC=0.9904, Regret=0.0236, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=retired|L3_contact=cellular: BAC=0.7452, Regret=0.1875, Precision=0.5185, Recall=0.5833
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp|L3_contact=cellular: BAC=0.7737, Regret=0.0833, Precision=0.4286, Recall=0.6000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp|L3_contact=cellular: BAC=0.8318, Regret=0.0888, Precision=0.5333, Recall=0.7273
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=no_income|L3_contact=cellular: BAC=0.8939, Regret=0.1200, Precision=0.7143, Recall=0.8333
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar|L3_contact=telephone: BAC=0.7500, Regret=0.2042, Precision=0.4118, Recall=0.7000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=no_income|L3_contact=cellular: BAC=0.7790, Regret=0.2414, Precision=0.6575, Recall=0.8421
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=no_income|L3_contact=cellular: BAC=0.8107, Regret=0.1515, Precision=0.4444, Recall=0.8000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar|L3_contact=telephone: BAC=0.9130, Regret=0.1087, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp|L3_contact=cellular: BAC=0.7722, Regret=0.2564, Precision=0.5000, Recall=0.7778
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar|L3_contact=telephone: BAC=0.8462, Regret=0.1346, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp|L3_contact=telephone: BAC=0.3636, Regret=0.2917, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar|L3_contact=telephone: BAC=0.7983, Regret=0.1422, Precision=0.4545, Recall=0.7143
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp|L3_contact=telephone: BAC=1.0000, Regret=0.0278, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=retired|L3_contact=cellular: BAC=1.0000, Regret=0.0577, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=no_income|L3_contact=telephone: BAC=0.7396, Regret=0.2614, Precision=0.5714, Recall=0.6667
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar|L3_contact=telephone: BAC=0.8574, Regret=0.1106, Precision=0.5000, Recall=0.8000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=retired|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=no_income|L3_contact=cellular: BAC=0.8010, Regret=0.1467, Precision=0.6842, Recall=0.6842
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=no_income|L3_contact=telephone: BAC=0.8125, Regret=0.2778, Precision=0.2500, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp|L3_contact=telephone: BAC=1.0000, Regret=0.0833, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=no_income|L3_contact=telephone: BAC=0.4167, Regret=0.4286, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=no_income|L3_contact=telephone: BAC=0.8750, Regret=0.1667, Precision=0.3333, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=unknown|L3_contact=cellular: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=unknown|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=unknown|L3_contact=cellular: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar|L3_contact=cellular: BAC=0.8000, Regret=0.3125, Precision=0.3333, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=unknown|L3_contact=cellular: BAC=0.7500, Regret=0.2500, Precision=1.0000, Recall=0.5000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=white_collar|L3_contact=cellular: BAC=0.7659, Regret=0.2609, Precision=0.6154, Recall=0.8889
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=unknown|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=retired|L3_contact=cellular: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=retired|L3_contact=telephone: BAC=0.6396, Regret=0.3550, Precision=0.5333, Recall=0.7619
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=retired|L3_contact=cellular: BAC=0.6655, Regret=0.3327, Precision=0.6173, Recall=0.7937
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=self_emp|L3_contact=cellular: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=white_collar|L3_contact=telephone: BAC=1.0000, Regret=0.0833, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=retired|L3_contact=cellular: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=unknown|L3_contact=telephone: BAC=0.1667, Regret=0.6071, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp|L3_contact=telephone: BAC=0.0000, Regret=0.7500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=unknown|L3_contact=cellular: BAC=1.0000, Regret=0.2500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=self_emp|L3_contact=telephone: BAC=0.5000, Regret=0.3750, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=unknown|L3_contact=cellular: BAC=1.0000, Regret=0.1250, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=no_income|L3_contact=cellular: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar: BAC=0.8195, Regret=0.1214, Precision=0.5596, Recall=0.7176
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60: BAC=0.8017, Regret=0.1118, Precision=0.5243, Recall=0.6708
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar: BAC=0.7937, Regret=0.1101, Precision=0.5241, Recall=0.6552
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50: BAC=0.8103, Regret=0.0929, Precision=0.5600, Recall=0.6731
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar: BAC=0.8087, Regret=0.1200, Precision=0.5415, Recall=0.6912
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40: BAC=0.8075, Regret=0.1097, Precision=0.5499, Recall=0.6795
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar: BAC=0.8332, Regret=0.1102, Precision=0.5849, Recall=0.7209
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30: BAC=0.8090, Regret=0.1641, Precision=0.5479, Recall=0.7339
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar: BAC=0.7736, Regret=0.1798, Precision=0.4820, Recall=0.6768
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp: BAC=0.8738, Regret=0.0808, Precision=0.6364, Recall=0.8077
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar: BAC=0.7944, Regret=0.0946, Precision=0.5254, Recall=0.6392
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar: BAC=0.8253, Regret=0.0685, Precision=0.6232, Recall=0.6825
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar: BAC=0.8134, Regret=0.0817, Precision=0.4884, Recall=0.6774
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=retired: BAC=0.7544, Regret=0.1451, Precision=0.5667, Recall=0.5667
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=no_income: BAC=0.8510, Regret=0.1400, Precision=0.5833, Recall=0.7778
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=no_income: BAC=0.8028, Regret=0.2192, Precision=0.6420, Recall=0.8254
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar: BAC=0.8333, Regret=0.2500, Precision=0.4286, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60: BAC=0.6934, Regret=0.3112, Precision=0.5931, Recall=0.8113
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=no_income: BAC=0.7630, Regret=0.1541, Precision=0.6522, Recall=0.6000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp: BAC=0.7838, Regret=0.0983, Precision=0.5263, Recall=0.6250
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp: BAC=0.7491, Regret=0.0904, Precision=0.3077, Recall=0.5714
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=retired: BAC=1.0000, Regret=0.0250, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=40-50|L2_job=unknown: BAC=0.9583, Regret=0.0500, Precision=0.7500, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=no_income: BAC=0.7602, Regret=0.1702, Precision=0.4000, Recall=0.6667
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=retired: BAC=1.0000, Regret=0.0500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=retired: BAC=0.6723, Regret=0.3280, Precision=0.5946, Recall=0.7857
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=50-60|L2_job=unknown: BAC=0.7500, Regret=0.0625, Precision=1.0000, Recall=0.5000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp: BAC=0.7703, Regret=0.2318, Precision=0.5000, Recall=0.7500
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=30-40|L2_job=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=unknown: BAC=1.0000, Regret=0.0625, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=unknown: BAC=0.2500, Regret=0.5000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=white_collar: BAC=0.7937, Regret=0.2404, Precision=0.6429, Recall=0.9000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=self_emp: BAC=0.5000, Regret=0.0938, Precision=0.8750, Recall=1.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=<=30|L2_job=retired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:45:11】[BASELINE] 桶 L1_age=>60|L2_job=no_income: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)

【INFO】【2026-03-26 18:45:12】【K折实验】正在执行第 4/5 折...
【INFO】【2026-03-26 18:45:12】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=1.0

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [18:45:12] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 18:45:22】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=36169
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="30-40"，n_samples=14179
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=40-50，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="40-50"，n_samples=8981
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="50-60"，n_samples=6436
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=<=30，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="<=30"，n_samples=5614
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=>60，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule=">60"，n_samples=959
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=4843
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=509
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=942
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=7810
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40|L2_job=others，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=75
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=3375
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=297
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=697
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=4440
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=40-50|L2_job=others，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=172
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=1926
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=207
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=retired，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="retired"，n_samples=987
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=468
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=2767
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=others，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=81
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=1866
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=778
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=307
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=2643
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=<=30|L2_job=others，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=20
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=>60|L2_job=retired，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="retired"，n_samples=708
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=121
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=>60|L2_job=others，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=130
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=2693
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=209
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1941
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=349
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=129
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=31
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=672
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=240
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=30
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=5806
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=229
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1775
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1855
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=258
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1262
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=198
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=40-50|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=99
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=443
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=205
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=49
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=2983
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=252
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1205
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1050
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=224
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=652
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=138
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=69
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=580
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=313
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=94
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=274
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=145
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=49
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1781
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=275
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=711
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1074
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=711
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=81
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=580
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=121
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=77
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=229
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=78
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1936
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=637
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=70
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=cellular，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=471
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=telephone，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=227
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=others，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=10
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=>60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=101
[INFO][BT][2026-03-26 18:45:24] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar|L3_contact=others，level=3，parent_id=L1_age=>60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=20
[INFO][BT][2026-03-26 18:45:30] 桶树构建完成：总桶数=83，最大层数=3，叶子桶数=58
【INFO】【2026-03-26 18:45:30】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 18:45:31】【阈值】桶 ROOT（n_val=3253，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:45:31] 桶 bucket_id=ROOT level=0：
    n_train=7594, n_val=3253,
    BAC=0.780, F1=0.643, AUC=0.949,
    Regret=0.101, BND_ratio=0.065, POS_coverage=0.120,
    Score(f1_regret_bnd )=0.478，threshold_source=val
【INFO】【2026-03-26 18:45:32】【阈值】桶 L1_age=30-40 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:45:32] 桶 bucket_id=L1_age=30-40 level=1：
    n_train=3026, n_val=1276,
    BAC=0.766, F1=0.632, AUC=0.947,
    Regret=0.102, BND_ratio=0.117, POS_coverage=0.131,
    Score(f1_regret_bnd )=0.413，threshold_source=val
[INFO][BT][2026-03-26 18:45:32] 桶 bucket_id=L1_age=30-40：
    parent_id=ROOT，parent_Score=0.478, bucket_Score=0.413,
    Gain=-0.065, is_weak=True
【INFO】【2026-03-26 18:45:33】【阈值】桶 L1_age=40-50（n_val=928，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:45:33] 桶 bucket_id=L1_age=40-50 level=1：
    n_train=1863, n_val=928,
    BAC=0.781, F1=0.653, AUC=0.945,
    Regret=0.091, BND_ratio=0.065, POS_coverage=0.106,
    Score(f1_regret_bnd )=0.497，threshold_source=val
[INFO][BT][2026-03-26 18:45:33] 桶 bucket_id=L1_age=40-50：
    parent_id=ROOT，parent_Score=0.478, bucket_Score=0.497,
    Gain=+0.019, is_weak=False
【INFO】【2026-03-26 18:45:34】【阈值】桶 L1_age=50-60（n_val=645，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:45:34] 桶 bucket_id=L1_age=50-60 level=1：
    n_train=1374, n_val=645,
    BAC=0.773, F1=0.638, AUC=0.960,
    Regret=0.082, BND_ratio=0.064, POS_coverage=0.088,
    Score(f1_regret_bnd )=0.492，threshold_source=val
[INFO][BT][2026-03-26 18:45:34] 桶 bucket_id=L1_age=50-60：
    parent_id=ROOT，parent_Score=0.478, bucket_Score=0.492,
    Gain=+0.015, is_weak=False
【INFO】【2026-03-26 18:45:34】【阈值】桶 L1_age=<=30 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:45:34] 桶 bucket_id=L1_age=<=30 level=1：
    n_train=1206, n_val=541,
    BAC=0.672, F1=0.547, AUC=0.907,
    Regret=0.159, BND_ratio=0.140, POS_coverage=0.131,
    Score(f1_regret_bnd )=0.247，threshold_source=val
[INFO][BT][2026-03-26 18:45:34] 桶 bucket_id=L1_age=<=30：
    parent_id=ROOT，parent_Score=0.478, bucket_Score=0.247,
    Gain=-0.231, is_weak=True
【INFO】【2026-03-26 18:45:35】【阈值】桶 L1_age=>60 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:45:35] 桶 bucket_id=L1_age=>60 level=1：
    n_train=329, n_val=134,
    BAC=0.592, F1=0.733, AUC=0.761,
    Regret=0.297, BND_ratio=0.082, POS_coverage=0.776,
    Score(f1_regret_bnd )=0.354，threshold_source=val
[INFO][BT][2026-03-26 18:45:35] 桶 bucket_id=L1_age=>60：
    parent_id=ROOT，parent_Score=0.478, bucket_Score=0.354,
    Gain=-0.124, is_weak=True
【INFO】【2026-03-26 18:45:35】【阈值】桶 L1_age=30-40|L2_job=blue_collar（n_val=481，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:45:35] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar level=2：
    n_train=1012, n_val=481,
    BAC=0.830, F1=0.653, AUC=0.949,
    Regret=0.077, BND_ratio=0.050, POS_coverage=0.112,
    Score(f1_regret_bnd )=0.526，threshold_source=val
[INFO][BT][2026-03-26 18:45:35] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar：
    parent_id=L1_age=30-40，parent_Score=0.413, bucket_Score=0.526,
    Gain=+0.113, is_weak=False
【INFO】【2026-03-26 18:45:36】【阈值】桶 L1_age=30-40|L2_job=no_income 标记为弱桶，阈值将回退使用 L1_age=30-40 的阈值
[INFO][BT][2026-03-26 18:45:36] 桶 bucket_id=L1_age=30-40|L2_job=no_income level=2：
    n_train=170, n_val=94,
    BAC=0.735, F1=0.703, AUC=0.928,
    Regret=0.133, BND_ratio=0.181, POS_coverage=0.191,
    Score(f1_regret_bnd )=0.389，threshold_source=val
[INFO][BT][2026-03-26 18:45:36] 桶 bucket_id=L1_age=30-40|L2_job=no_income：
    parent_id=L1_age=30-40，parent_Score=0.413, bucket_Score=0.389,
    Gain=-0.024, is_weak=True
【INFO】【2026-03-26 18:45:36】【阈值】桶 L1_age=30-40|L2_job=self_emp（n_val=125，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:45:36] 桶 bucket_id=L1_age=30-40|L2_job=self_emp level=2：
    n_train=223, n_val=125,
    BAC=0.919, F1=0.800, AUC=0.988,
    Regret=0.032, BND_ratio=0.032, POS_coverage=0.088,
    Score(f1_regret_bnd )=0.736，threshold_source=val
[INFO][BT][2026-03-26 18:45:36] 桶 bucket_id=L1_age=30-40|L2_job=self_emp：
    parent_id=L1_age=30-40，parent_Score=0.413, bucket_Score=0.736,
    Gain=+0.323, is_weak=False
【INFO】【2026-03-26 18:45:37】【阈值】桶 L1_age=30-40|L2_job=white_collar 标记为弱桶，阈值将回退使用 L1_age=30-40 的阈值
[INFO][BT][2026-03-26 18:45:37] 桶 bucket_id=L1_age=30-40|L2_job=white_collar level=2：
    n_train=1655, n_val=737,
    BAC=0.726, F1=0.577, AUC=0.909,
    Regret=0.123, BND_ratio=0.075, POS_coverage=0.107,
    Score(f1_regret_bnd )=0.379，threshold_source=val
[INFO][BT][2026-03-26 18:45:37] 桶 bucket_id=L1_age=30-40|L2_job=white_collar：
    parent_id=L1_age=30-40，parent_Score=0.413, bucket_Score=0.379,
    Gain=-0.033, is_weak=True
【INFO】【2026-03-26 18:45:38】【阈值】桶 L1_age=30-40|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=30-40 的阈值
[INFO][BT][2026-03-26 18:45:38] 桶 bucket_id=L1_age=30-40|L2_job=others level=2：
    n_train=53, n_val=22,
    BAC=0.742, F1=0.727, AUC=0.989,
    Regret=0.060, BND_ratio=0.120, POS_coverage=0.053,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:45:38] 桶 bucket_id=L1_age=30-40|L2_job=others：
    parent_id=L1_age=30-40，parent_Score=0.413, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:45:39】【阈值】桶 L1_age=40-50|L2_job=blue_collar 标记为弱桶，阈值将回退使用 L1_age=40-50 的阈值
[INFO][BT][2026-03-26 18:45:39] 桶 bucket_id=L1_age=40-50|L2_job=blue_collar level=2：
    n_train=699, n_val=363,
    BAC=0.765, F1=0.528, AUC=0.910,
    Regret=0.079, BND_ratio=0.066, POS_coverage=0.085,
    Score(f1_regret_bnd )=0.384，threshold_source=val
[INFO][BT][2026-03-26 18:45:39] 桶 bucket_id=L1_age=40-50|L2_job=blue_collar：
    parent_id=L1_age=40-50，parent_Score=0.497, bucket_Score=0.384,
    Gain=-0.113, is_weak=True
【INFO】【2026-03-26 18:45:40】【阈值】桶 L1_age=40-50|L2_job=no_income 标记为弱桶，阈值将回退使用 L1_age=40-50 的阈值
[INFO][BT][2026-03-26 18:45:40] 桶 bucket_id=L1_age=40-50|L2_job=no_income level=2：
    n_train=117, n_val=84,
    BAC=0.785, F1=0.667, AUC=0.921,
    Regret=0.116, BND_ratio=0.060, POS_coverage=0.143,
    Score(f1_regret_bnd )=0.491，threshold_source=val
[INFO][BT][2026-03-26 18:45:40] 桶 bucket_id=L1_age=40-50|L2_job=no_income：
    parent_id=L1_age=40-50，parent_Score=0.497, bucket_Score=0.491,
    Gain=-0.006, is_weak=True
【INFO】【2026-03-26 18:45:40】【阈值】桶 L1_age=40-50|L2_job=self_emp（n_val=113，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:45:40] 桶 bucket_id=L1_age=40-50|L2_job=self_emp level=2：
    n_train=170, n_val=113,
    BAC=0.836, F1=0.778, AUC=0.988,
    Regret=0.051, BND_ratio=0.097, POS_coverage=0.080,
    Score(f1_regret_bnd )=0.630，threshold_source=val
[INFO][BT][2026-03-26 18:45:40] 桶 bucket_id=L1_age=40-50|L2_job=self_emp：
    parent_id=L1_age=40-50，parent_Score=0.497, bucket_Score=0.630,
    Gain=+0.132, is_weak=False
【INFO】【2026-03-26 18:45:41】【阈值】桶 L1_age=40-50|L2_job=white_collar 标记为弱桶，阈值将回退使用 L1_age=40-50 的阈值
[INFO][BT][2026-03-26 18:45:41] 桶 bucket_id=L1_age=40-50|L2_job=white_collar level=2：
    n_train=919, n_val=464,
    BAC=0.789, F1=0.645, AUC=0.940,
    Regret=0.114, BND_ratio=0.116, POS_coverage=0.155,
    Score(f1_regret_bnd )=0.415，threshold_source=val
[INFO][BT][2026-03-26 18:45:41] 桶 bucket_id=L1_age=40-50|L2_job=white_collar：
    parent_id=L1_age=40-50，parent_Score=0.497, bucket_Score=0.415,
    Gain=-0.082, is_weak=True
【INFO】【2026-03-26 18:45:42】【阈值】桶 L1_age=40-50|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=40-50 的阈值
[INFO][BT][2026-03-26 18:45:42] 桶 bucket_id=L1_age=40-50|L2_job=others level=2：
    n_train=112, n_val=60,
    BAC=0.747, F1=0.636, AUC=0.963,
    Regret=0.074, BND_ratio=0.041, POS_coverage=0.052,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:45:42] 桶 bucket_id=L1_age=40-50|L2_job=others：
    parent_id=L1_age=40-50，parent_Score=0.497, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:45:43】【阈值】桶 L1_age=50-60|L2_job=blue_collar 标记为弱桶，阈值将回退使用 L1_age=50-60 的阈值
[INFO][BT][2026-03-26 18:45:43] 桶 bucket_id=L1_age=50-60|L2_job=blue_collar level=2：
    n_train=389, n_val=241,
    BAC=0.735, F1=0.485, AUC=0.950,
    Regret=0.076, BND_ratio=0.071, POS_coverage=0.079,
    Score(f1_regret_bnd )=0.339，threshold_source=val
[INFO][BT][2026-03-26 18:45:43] 桶 bucket_id=L1_age=50-60|L2_job=blue_collar：
    parent_id=L1_age=50-60，parent_Score=0.492, bucket_Score=0.339,
    Gain=-0.154, is_weak=True
【INFO】【2026-03-26 18:45:44】【阈值】桶 L1_age=50-60|L2_job=no_income 标记为弱桶，阈值将回退使用 L1_age=50-60 的阈值
[INFO][BT][2026-03-26 18:45:44] 桶 bucket_id=L1_age=50-60|L2_job=no_income level=2：
    n_train=84, n_val=50,
    BAC=0.776, F1=0.625, AUC=0.944,
    Regret=0.115, BND_ratio=0.100, POS_coverage=0.180,
    Score(f1_regret_bnd )=0.410，threshold_source=val
[INFO][BT][2026-03-26 18:45:44] 桶 bucket_id=L1_age=50-60|L2_job=no_income：
    parent_id=L1_age=50-60，parent_Score=0.492, bucket_Score=0.410,
    Gain=-0.082, is_weak=True
【INFO】【2026-03-26 18:45:45】【阈值】桶 L1_age=50-60|L2_job=retired（n_val=113，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:45:45] 桶 bucket_id=L1_age=50-60|L2_job=retired level=2：
    n_train=247, n_val=113,
    BAC=0.867, F1=0.791, AUC=0.963,
    Regret=0.088, BND_ratio=0.115, POS_coverage=0.221,
    Score(f1_regret_bnd )=0.587，threshold_source=val
[INFO][BT][2026-03-26 18:45:45] 桶 bucket_id=L1_age=50-60|L2_job=retired：
    parent_id=L1_age=50-60，parent_Score=0.492, bucket_Score=0.587,
    Gain=+0.095, is_weak=False
【INFO】【2026-03-26 18:45:45】【阈值】桶 L1_age=50-60|L2_job=self_emp 标记为弱桶，阈值将回退使用 L1_age=50-60 的阈值
[INFO][BT][2026-03-26 18:45:45] 桶 bucket_id=L1_age=50-60|L2_job=self_emp level=2：
    n_train=115, n_val=150,
    BAC=0.780, F1=0.643, AUC=0.961,
    Regret=0.077, BND_ratio=0.107, POS_coverage=0.100,
    Score(f1_regret_bnd )=0.460，threshold_source=val
[INFO][BT][2026-03-26 18:45:45] 桶 bucket_id=L1_age=50-60|L2_job=self_emp：
    parent_id=L1_age=50-60，parent_Score=0.492, bucket_Score=0.460,
    Gain=-0.033, is_weak=True
【INFO】【2026-03-26 18:45:46】【阈值】桶 L1_age=50-60|L2_job=white_collar（n_val=296，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:45:46] 桶 bucket_id=L1_age=50-60|L2_job=white_collar level=2：
    n_train=587, n_val=296,
    BAC=0.851, F1=0.700, AUC=0.934,
    Regret=0.073, BND_ratio=0.010, POS_coverage=0.108,
    Score(f1_regret_bnd )=0.616，threshold_source=val
[INFO][BT][2026-03-26 18:45:46] 桶 bucket_id=L1_age=50-60|L2_job=white_collar：
    parent_id=L1_age=50-60，parent_Score=0.492, bucket_Score=0.616,
    Gain=+0.124, is_weak=False
【INFO】【2026-03-26 18:45:47】【阈值】桶 L1_age=50-60|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=50-60 的阈值
[INFO][BT][2026-03-26 18:45:47] 桶 bucket_id=L1_age=50-60|L2_job=others level=2：
    n_train=54, n_val=27,
    BAC=0.826, F1=0.778, AUC=0.971,
    Regret=0.065, BND_ratio=0.111, POS_coverage=0.111,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:45:47] 桶 bucket_id=L1_age=50-60|L2_job=others：
    parent_id=L1_age=50-60，parent_Score=0.492, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:45:48】【阈值】桶 L1_age=<=30|L2_job=blue_collar（n_val=179，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:45:48] 桶 bucket_id=L1_age=<=30|L2_job=blue_collar level=2：
    n_train=435, n_val=179,
    BAC=0.790, F1=0.694, AUC=0.958,
    Regret=0.095, BND_ratio=0.101, POS_coverage=0.140,
    Score(f1_regret_bnd )=0.498，threshold_source=val
[INFO][BT][2026-03-26 18:45:48] 桶 bucket_id=L1_age=<=30|L2_job=blue_collar：
    parent_id=L1_age=<=30，parent_Score=0.247, bucket_Score=0.498,
    Gain=+0.252, is_weak=False
【INFO】【2026-03-26 18:45:49】【阈值】桶 L1_age=<=30|L2_job=no_income（n_val=102，source=val) 使用本地阈值 α=0.6000, β=0.2000
[INFO][BT][2026-03-26 18:45:49] 桶 bucket_id=L1_age=<=30|L2_job=no_income level=2：
    n_train=269, n_val=102,
    BAC=0.675, F1=0.611, AUC=0.911,
    Regret=0.174, BND_ratio=0.186, POS_coverage=0.167,
    Score(f1_regret_bnd )=0.251，threshold_source=val
[INFO][BT][2026-03-26 18:45:49] 桶 bucket_id=L1_age=<=30|L2_job=no_income：
    parent_id=L1_age=<=30，parent_Score=0.247, bucket_Score=0.251,
    Gain=+0.004, is_weak=False
【INFO】【2026-03-26 18:45:49】【阈值】桶 L1_age=<=30|L2_job=self_emp（n_val=75，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:45:49] 桶 bucket_id=L1_age=<=30|L2_job=self_emp level=2：
    n_train=114, n_val=75,
    BAC=0.754, F1=0.593, AUC=0.905,
    Regret=0.147, BND_ratio=0.080, POS_coverage=0.200,
    Score(f1_regret_bnd )=0.366，threshold_source=val
[INFO][BT][2026-03-26 18:45:49] 桶 bucket_id=L1_age=<=30|L2_job=self_emp：
    parent_id=L1_age=<=30，parent_Score=0.247, bucket_Score=0.366,
    Gain=+0.119, is_weak=False
【INFO】【2026-03-26 18:45:50】【阈值】桶 L1_age=<=30|L2_job=white_collar（n_val=242，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:45:50] 桶 bucket_id=L1_age=<=30|L2_job=white_collar level=2：
    n_train=598, n_val=242,
    BAC=0.739, F1=0.635, AUC=0.919,
    Regret=0.145, BND_ratio=0.174, POS_coverage=0.202,
    Score(f1_regret_bnd )=0.317，threshold_source=val
[INFO][BT][2026-03-26 18:45:50] 桶 bucket_id=L1_age=<=30|L2_job=white_collar：
    parent_id=L1_age=<=30，parent_Score=0.247, bucket_Score=0.317,
    Gain=+0.070, is_weak=False
【INFO】【2026-03-26 18:45:51】【阈值】桶 L1_age=<=30|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=<=30 的阈值
[INFO][BT][2026-03-26 18:45:51] 桶 bucket_id=L1_age=<=30|L2_job=others level=2：
    n_train=13, n_val=7,
    BAC=1.000, F1=1.000, AUC=1.000,
    Regret=0.000, BND_ratio=0.000, POS_coverage=0.150,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:45:51] 桶 bucket_id=L1_age=<=30|L2_job=others：
    parent_id=L1_age=<=30，parent_Score=0.247, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:45:52】【阈值】桶 L1_age=>60|L2_job=retired 标记为弱桶，阈值将回退使用 L1_age=>60 的阈值
[INFO][BT][2026-03-26 18:45:52] 桶 bucket_id=L1_age=>60|L2_job=retired level=2：
    n_train=151, n_val=117,
    BAC=0.621, F1=0.687, AUC=0.772,
    Regret=0.299, BND_ratio=0.103, POS_coverage=0.709,
    Score(f1_regret_bnd )=0.285，threshold_source=val
[INFO][BT][2026-03-26 18:45:52] 桶 bucket_id=L1_age=>60|L2_job=retired：
    parent_id=L1_age=>60，parent_Score=0.354, bucket_Score=0.285,
    Gain=-0.069, is_weak=True
【INFO】【2026-03-26 18:45:52】【阈值】桶 L1_age=>60|L2_job=white_collar（n_val=32，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 18:45:52] 桶 bucket_id=L1_age=>60|L2_job=white_collar level=2：
    n_train=89, n_val=32,
    BAC=0.688, F1=0.848, AUC=0.898,
    Regret=0.172, BND_ratio=0.219, POS_coverage=0.531,
    Score(f1_regret_bnd )=0.458，threshold_source=val
[INFO][BT][2026-03-26 18:45:52] 桶 bucket_id=L1_age=>60|L2_job=white_collar：
    parent_id=L1_age=>60，parent_Score=0.354, bucket_Score=0.458,
    Gain=+0.104, is_weak=False
【INFO】【2026-03-26 18:45:53】【阈值】桶 L1_age=>60|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=>60 的阈值
[INFO][BT][2026-03-26 18:45:53] 桶 bucket_id=L1_age=>60|L2_job=others level=2：
    n_train=95, n_val=35,
    BAC=0.776, F1=0.782, AUC=0.896,
    Regret=0.206, BND_ratio=0.077, POS_coverage=0.454,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:45:53] 桶 bucket_id=L1_age=>60|L2_job=others：
    parent_id=L1_age=>60，parent_Score=0.354, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:45:54】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=cellular 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=blue_collar 的阈值
[INFO][BT][2026-03-26 18:45:54] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular level=3：
    n_train=1879, n_val=814,
    BAC=0.730, F1=0.573, AUC=0.933,
    Regret=0.107, BND_ratio=0.070, POS_coverage=0.093,
    Score(f1_regret_bnd )=0.396，threshold_source=val
[INFO][BT][2026-03-26 18:45:54] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.526, bucket_Score=0.396,
    Gain=-0.129, is_weak=True
【INFO】【2026-03-26 18:45:55】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=telephone（n_val=60，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:45:55] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone level=3：
    n_train=149, n_val=60,
    BAC=0.891, F1=0.800, AUC=0.967,
    Regret=0.046, BND_ratio=0.000, POS_coverage=0.083,
    Score(f1_regret_bnd )=0.754，threshold_source=val
[INFO][BT][2026-03-26 18:45:55] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.526, bucket_Score=0.754,
    Gain=+0.228, is_weak=False
【INFO】【2026-03-26 18:45:56】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=unknown 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=blue_collar 的阈值
[INFO][BT][2026-03-26 18:45:56] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown level=3：
    n_train=1350, n_val=591,
    BAC=0.757, F1=0.591, AUC=0.975,
    Regret=0.041, BND_ratio=0.047, POS_coverage=0.036,
    Score(f1_regret_bnd )=0.502，threshold_source=val
[INFO][BT][2026-03-26 18:45:56] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.526, bucket_Score=0.502,
    Gain=-0.023, is_weak=True
【INFO】【2026-03-26 18:45:57】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=cellular（n_val=130，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 18:45:57] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular level=3：
    n_train=219, n_val=130,
    BAC=0.753, F1=0.724, AUC=0.915,
    Regret=0.146, BND_ratio=0.177, POS_coverage=0.238,
    Score(f1_regret_bnd )=0.401，threshold_source=val
[INFO][BT][2026-03-26 18:45:57] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.389, bucket_Score=0.401,
    Gain=+0.012, is_weak=False
【INFO】【2026-03-26 18:45:58】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=unknown 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=no_income 的阈值
[INFO][BT][2026-03-26 18:45:58] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown level=3：
    n_train=87, n_val=42,
    BAC=0.659, F1=0.571, AUC=0.962,
    Regret=0.089, BND_ratio=0.143, POS_coverage=0.048,
    Score(f1_regret_bnd )=0.339，threshold_source=val
[INFO][BT][2026-03-26 18:45:58] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.389, bucket_Score=0.339,
    Gain=-0.050, is_weak=True
【INFO】【2026-03-26 18:45:59】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=others 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=no_income 的阈值
[INFO][BT][2026-03-26 18:45:59] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others level=3：
    n_train=18, n_val=13,
    BAC=0.964, F1=0.750, AUC=0.940,
    Regret=0.048, BND_ratio=0.000, POS_coverage=0.161,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:45:59] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.389, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:46:00】【阈值】桶 L1_age=30-40|L2_job=self_emp|L3_contact=cellular 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=self_emp 的阈值
[INFO][BT][2026-03-26 18:46:00] 桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular level=3：
    n_train=496, n_val=176,
    BAC=0.780, F1=0.634, AUC=0.912,
    Regret=0.101, BND_ratio=0.034, POS_coverage=0.114,
    Score(f1_regret_bnd )=0.499，threshold_source=val
[INFO][BT][2026-03-26 18:46:00] 桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=self_emp，parent_Score=0.736, bucket_Score=0.499,
    Gain=-0.237, is_weak=True
【INFO】【2026-03-26 18:46:01】【阈值】桶 L1_age=30-40|L2_job=self_emp|L3_contact=unknown 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=self_emp 的阈值
[INFO][BT][2026-03-26 18:46:01] 桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=unknown level=3：
    n_train=173, n_val=67,
    BAC=0.843, F1=0.667, AUC=0.980,
    Regret=0.045, BND_ratio=0.045, POS_coverage=0.075,
    Score(f1_regret_bnd )=0.577，threshold_source=val

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [18:46:39] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 18:46:54】[BASELINE] 全局 XGB 模型训练完成
【INFO】【2026-03-26 18:46:54】[BASELINE] 阈值搜索开始
【INFO】【2026-03-26 18:46:55】[BASELINE] 最佳阈值找到: alpha=0.4000, beta=0.2000, regret=0.1120
【INFO】【2026-03-26 18:46:55】【桶树】已为样本生成桶ID，共 79 个组合
【INFO】【2026-03-26 18:46:55】[BASELINE] 测试集桶映射完成，共 79 个桶

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar|L3_contact=unknown: BAC=0.7500, Regret=0.0283, Precision=1.0000, Recall=0.5000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar|L3_contact=unknown: BAC=0.7680, Regret=0.0429, Precision=0.6667, Recall=0.5455
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp|L3_contact=unknown: BAC=0.5000, Regret=0.0200, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar|L3_contact=unknown: BAC=0.5661, Regret=0.0663, Precision=0.3333, Recall=0.1429
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar|L3_contact=unknown: BAC=0.6948, Regret=0.0584, Precision=0.6667, Recall=0.4000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar|L3_contact=unknown: BAC=0.6735, Regret=0.0463, Precision=0.3636, Recall=0.3636
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=retired|L3_contact=unknown: BAC=0.8333, Regret=0.0455, Precision=1.0000, Recall=0.6667
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar|L3_contact=unknown: BAC=0.7664, Regret=0.0529, Precision=0.5000, Recall=0.5556
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar|L3_contact=unknown: BAC=0.5976, Regret=0.0876, Precision=0.3333, Recall=0.2222
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar|L3_contact=unknown: BAC=0.7829, Regret=0.0489, Precision=0.8000, Recall=0.5714
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=no_income|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp|L3_contact=unknown: BAC=1.0000, Regret=0.0063, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp|L3_contact=unknown: BAC=0.7348, Regret=0.0643, Precision=0.5000, Recall=0.5000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp|L3_contact=unknown: BAC=0.7500, Regret=0.0909, Precision=1.0000, Recall=0.5000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=retired|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=no_income|L3_contact=unknown: BAC=0.5000, Regret=0.1250, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=no_income|L3_contact=unknown: BAC=0.5000, Regret=0.0870, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=no_income|L3_contact=unknown: BAC=1.0000, Regret=0.0294, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=retired|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=unknown|L3_contact=unknown: BAC=0.9167, Regret=0.0833, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=retired|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=unknown|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=self_emp|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=unknown|L3_contact=unknown: BAC=0.5000, Regret=0.4167, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar|L3_contact=cellular: BAC=0.7315, Regret=0.1727, Precision=0.6389, Recall=0.5227
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar|L3_contact=cellular: BAC=0.7609, Regret=0.1391, Precision=0.6230, Recall=0.5805
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar|L3_contact=cellular: BAC=0.8146, Regret=0.1207, Precision=0.7167, Recall=0.6825
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar|L3_contact=cellular: BAC=0.7461, Regret=0.1056, Precision=0.5610, Recall=0.5349
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar|L3_contact=cellular: BAC=0.6897, Regret=0.0996, Precision=0.5263, Recall=0.4167
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar|L3_contact=cellular: BAC=0.7513, Regret=0.1479, Precision=0.5902, Recall=0.5714
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp|L3_contact=cellular: BAC=0.8333, Regret=0.0704, Precision=1.0000, Recall=0.6667
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp|L3_contact=cellular: BAC=0.7505, Regret=0.1242, Precision=0.5455, Recall=0.5714
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar|L3_contact=cellular: BAC=0.7654, Regret=0.1797, Precision=0.5842, Recall=0.6344
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=retired|L3_contact=cellular: BAC=0.6803, Regret=0.1127, Precision=0.5455, Recall=0.4000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar|L3_contact=cellular: BAC=0.7794, Regret=0.0972, Precision=0.6667, Recall=0.5946
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar|L3_contact=telephone: BAC=0.5583, Regret=0.2075, Precision=0.2000, Recall=0.2000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=unknown|L3_contact=cellular: BAC=1.0000, Regret=0.0500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar|L3_contact=telephone: BAC=0.7212, Regret=0.1027, Precision=0.4000, Recall=0.5000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=no_income|L3_contact=cellular: BAC=0.8136, Regret=0.1463, Precision=0.7273, Recall=0.7273
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=no_income|L3_contact=telephone: BAC=0.8615, Regret=0.1250, Precision=0.8000, Recall=0.8000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp|L3_contact=cellular: BAC=0.6902, Regret=0.0901, Precision=0.3750, Recall=0.4286
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar|L3_contact=telephone: BAC=0.6111, Regret=0.1464, Precision=0.3333, Recall=0.2857
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar|L3_contact=telephone: BAC=0.7593, Regret=0.1190, Precision=0.7143, Recall=0.5556
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=no_income|L3_contact=cellular: BAC=0.8779, Regret=0.1114, Precision=0.8000, Recall=0.8000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp|L3_contact=cellular: BAC=0.8359, Regret=0.1019, Precision=0.7143, Recall=0.7143
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=retired|L3_contact=cellular: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp|L3_contact=telephone: BAC=0.9000, Regret=0.0750, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=retired|L3_contact=telephone: BAC=1.0000, Regret=0.0125, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=unknown|L3_contact=cellular: BAC=0.8889, Regret=0.0833, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar|L3_contact=telephone: BAC=0.8918, Regret=0.0341, Precision=0.8000, Recall=0.8000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=no_income|L3_contact=cellular: BAC=0.7520, Regret=0.2549, Precision=0.6000, Recall=0.7347
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar|L3_contact=telephone: BAC=0.5000, Regret=0.0667, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar|L3_contact=telephone: BAC=0.7917, Regret=0.0538, Precision=0.7500, Recall=0.6000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp|L3_contact=telephone: BAC=0.8889, Regret=0.0833, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar|L3_contact=telephone: BAC=0.7100, Regret=0.1667, Precision=0.3333, Recall=0.5000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=retired|L3_contact=cellular: BAC=0.9444, Regret=0.0750, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=no_income|L3_contact=telephone: BAC=0.8333, Regret=0.2500, Precision=1.0000, Recall=0.6667
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=no_income|L3_contact=cellular: BAC=0.9394, Regret=0.0813, Precision=0.6364, Recall=1.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=retired|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=unknown|L3_contact=cellular: BAC=0.4375, Regret=0.1944, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=no_income|L3_contact=telephone: BAC=0.4000, Regret=0.2917, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=no_income|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=retired|L3_contact=cellular: BAC=0.6771, Regret=0.3482, Precision=0.5862, Recall=0.7234
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar|L3_contact=cellular: BAC=0.8333, Regret=0.1250, Precision=0.7500, Recall=1.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=unknown|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=unknown|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=unknown|L3_contact=cellular: BAC=0.5000, Regret=0.6250, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=retired|L3_contact=telephone: BAC=0.6059, Regret=0.3611, Precision=0.5161, Recall=0.6957
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=white_collar|L3_contact=cellular: BAC=0.7411, Regret=0.2833, Precision=0.6667, Recall=0.8571
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=white_collar|L3_contact=telephone: BAC=0.6500, Regret=0.4444, Precision=0.6667, Recall=0.5000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=unknown|L3_contact=telephone: BAC=1.0000, Regret=0.2500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar|L3_contact=telephone: BAC=0.8750, Regret=0.2083, Precision=0.6667, Recall=1.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=self_emp|L3_contact=cellular: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=unknown|L3_contact=cellular: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=unknown|L3_contact=telephone: BAC=0.0000, Regret=0.7500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=self_emp|L3_contact=telephone: BAC=0.5000, Regret=0.5000, Precision=1.0000, Recall=0.5000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=no_income|L3_contact=cellular: BAC=0.0000, Regret=0.7500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar: BAC=0.7457, Regret=0.1175, Precision=0.5797, Recall=0.5405
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60: BAC=0.7357, Regret=0.0969, Precision=0.5969, Recall=0.5066
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar: BAC=0.7520, Regret=0.0813, Precision=0.5636, Recall=0.5345
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50: BAC=0.7921, Regret=0.0908, Precision=0.6528, Recall=0.6211
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp: BAC=0.7073, Regret=0.0625, Precision=0.4444, Recall=0.4444
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar: BAC=0.6822, Regret=0.0816, Precision=0.5385, Recall=0.3889
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar: BAC=0.8035, Regret=0.1039, Precision=0.7132, Recall=0.6467
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar: BAC=0.7639, Regret=0.1147, Precision=0.6135, Recall=0.5747
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40: BAC=0.7705, Regret=0.1031, Precision=0.6152, Recall=0.5829
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=retired: BAC=0.7272, Regret=0.0810, Precision=0.6667, Recall=0.4762
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar: BAC=0.7672, Regret=0.0851, Precision=0.6044, Recall=0.5670
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar: BAC=0.7566, Regret=0.1580, Precision=0.5636, Recall=0.5962
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30: BAC=0.7682, Regret=0.1520, Precision=0.6027, Recall=0.6109
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar: BAC=0.7425, Regret=0.1198, Precision=0.6585, Recall=0.5192
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=no_income: BAC=0.7899, Regret=0.1336, Precision=0.6667, Recall=0.6667
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp: BAC=0.8527, Regret=0.0500, Precision=0.8333, Recall=0.7143
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp: BAC=0.7502, Regret=0.1049, Precision=0.5185, Recall=0.5600
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp: BAC=0.8184, Regret=0.0987, Precision=0.7500, Recall=0.6667
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=retired: BAC=0.6561, Regret=0.3503, Precision=0.5618, Recall=0.7143
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60: BAC=0.6818, Regret=0.3297, Precision=0.5868, Recall=0.7396
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=no_income: BAC=0.9005, Regret=0.0847, Precision=0.6364, Recall=0.8750
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=no_income: BAC=0.7737, Regret=0.2229, Precision=0.6154, Recall=0.7273
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=no_income: BAC=0.8807, Regret=0.0992, Precision=0.8333, Recall=0.7895
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=retired: BAC=0.9737, Regret=0.0357, Precision=0.6667, Recall=1.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=40-50|L2_job=unknown: BAC=0.9091, Regret=0.0795, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar: BAC=0.8750, Regret=0.1538, Precision=0.7143, Recall=1.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=retired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=30-40|L2_job=unknown: BAC=1.0000, Regret=0.0312, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=self_emp: BAC=0.8333, Regret=0.2000, Precision=1.0000, Recall=0.6667
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=50-60|L2_job=unknown: BAC=0.4500, Regret=0.2500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=<=30|L2_job=unknown: BAC=0.5000, Regret=0.5000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=white_collar: BAC=0.7222, Regret=0.3205, Precision=0.6667, Recall=0.7778
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=unknown: BAC=0.7500, Regret=0.1875, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:46:59】[BASELINE] 桶 L1_age=>60|L2_job=no_income: BAC=0.0000, Regret=0.7500, Precision=0.0000, Recall=0.0000

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)

【INFO】【2026-03-26 18:47:00】【K折实验】正在执行第 5/5 折...
【INFO】【2026-03-26 18:47:00】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=1.0

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [18:47:00] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 18:47:04】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=36169
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="30-40"，n_samples=14145
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=40-50，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="40-50"，n_samples=9039
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="50-60"，n_samples=6488
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=<=30，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="<=30"，n_samples=5571
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=>60，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule=">60"，n_samples=926
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=4826
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=507
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=962
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=7778
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40|L2_job=others，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=72
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=3379
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=287
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=727
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=4475
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=40-50|L2_job=others，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=171
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=1978
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=209
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=retired，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="retired"，n_samples=992
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=482
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=2757
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=others，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=70
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=1827
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=757
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=310
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=2658
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=<=30|L2_job=others，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=19
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=>60|L2_job=retired，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="retired"，n_samples=684
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=124
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=>60|L2_job=others，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=118
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=2694
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=202
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1930
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=347
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=130
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=30
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=683
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=250
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=29
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=5760
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=237
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1781
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1858
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=242
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1279
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=185
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=40-50|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=102
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=472
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=206
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=49
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=3004
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=261
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1210
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1059
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=230
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=689
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=141
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=68
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=586
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=313
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=93
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=286
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=153
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=43
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1782
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=272
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=703
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1046
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=703
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=78
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=571
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=112
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=74
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=229
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=81
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1957
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=622
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=79
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=cellular，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=459
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=telephone，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=215
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=others，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=10
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=>60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=101
[INFO][BT][2026-03-26 18:47:06] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar|L3_contact=others，level=3，parent_id=L1_age=>60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=23
[INFO][BT][2026-03-26 18:47:10] 桶树构建完成：总桶数=83，最大层数=3，叶子桶数=58
【INFO】【2026-03-26 18:47:10】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 18:47:11】【阈值】桶 ROOT（n_val=3254，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:47:11] 桶 bucket_id=ROOT level=0：
    n_train=7593, n_val=3254,
    BAC=0.795, F1=0.661, AUC=0.946,
    Regret=0.103, BND_ratio=0.097, POS_coverage=0.149,
    Score(f1_regret_bnd )=0.461，threshold_source=val
【INFO】【2026-03-26 18:47:11】【阈值】桶 L1_age=30-40 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:47:11] 桶 bucket_id=L1_age=30-40 level=1：
    n_train=2970, n_val=1320,
    BAC=0.759, F1=0.607, AUC=0.933,
    Regret=0.102, BND_ratio=0.055, POS_coverage=0.097,
    Score(f1_regret_bnd )=0.450，threshold_source=val
[INFO][BT][2026-03-26 18:47:11] 桶 bucket_id=L1_age=30-40：
    parent_id=ROOT，parent_Score=0.461, bucket_Score=0.450,
    Gain=-0.011, is_weak=True
【INFO】【2026-03-26 18:47:12】【阈值】桶 L1_age=40-50（n_val=904，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:47:12] 桶 bucket_id=L1_age=40-50 level=1：
    n_train=1896, n_val=904,
    BAC=0.819, F1=0.663, AUC=0.953,
    Regret=0.076, BND_ratio=0.075, POS_coverage=0.108,
    Score(f1_regret_bnd )=0.512，threshold_source=val
[INFO][BT][2026-03-26 18:47:12] 桶 bucket_id=L1_age=40-50：
    parent_id=ROOT，parent_Score=0.461, bucket_Score=0.512,
    Gain=+0.050, is_weak=False
【INFO】【2026-03-26 18:47:12】【阈值】桶 L1_age=50-60 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:47:12] 桶 bucket_id=L1_age=50-60 level=1：
    n_train=1409, n_val=622,
    BAC=0.721, F1=0.603, AUC=0.947,
    Regret=0.104, BND_ratio=0.117, POS_coverage=0.096,
    Score(f1_regret_bnd )=0.382，threshold_source=val
[INFO][BT][2026-03-26 18:47:12] 桶 bucket_id=L1_age=50-60：
    parent_id=ROOT，parent_Score=0.461, bucket_Score=0.382,
    Gain=-0.079, is_weak=True
【INFO】【2026-03-26 18:47:13】【阈值】桶 L1_age=<=30 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:47:13] 桶 bucket_id=L1_age=<=30 level=1：
    n_train=1183, n_val=558,
    BAC=0.750, F1=0.667, AUC=0.901,
    Regret=0.150, BND_ratio=0.147, POS_coverage=0.210,
    Score(f1_regret_bnd )=0.370，threshold_source=val
[INFO][BT][2026-03-26 18:47:13] 桶 bucket_id=L1_age=<=30：
    parent_id=ROOT，parent_Score=0.461, bucket_Score=0.370,
    Gain=-0.092, is_weak=True
【INFO】【2026-03-26 18:47:13】【阈值】桶 L1_age=>60 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:47:13] 桶 bucket_id=L1_age=>60 level=1：
    n_train=324, n_val=122,
    BAC=0.668, F1=0.702, AUC=0.797,
    Regret=0.279, BND_ratio=0.074, POS_coverage=0.672,
    Score(f1_regret_bnd )=0.350，threshold_source=val
[INFO][BT][2026-03-26 18:47:13] 桶 bucket_id=L1_age=>60：
    parent_id=ROOT，parent_Score=0.461, bucket_Score=0.350,
    Gain=-0.112, is_weak=True
【INFO】【2026-03-26 18:47:13】【阈值】桶 L1_age=30-40|L2_job=blue_collar（n_val=478，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:47:13] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar level=2：
    n_train=1007, n_val=478,
    BAC=0.809, F1=0.607, AUC=0.945,
    Regret=0.081, BND_ratio=0.031, POS_coverage=0.105,
    Score(f1_regret_bnd )=0.494，threshold_source=val
[INFO][BT][2026-03-26 18:47:13] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar：
    parent_id=L1_age=30-40，parent_Score=0.450, bucket_Score=0.494,
    Gain=+0.044, is_weak=False
【INFO】【2026-03-26 18:47:14】【阈值】桶 L1_age=30-40|L2_job=no_income 标记为弱桶，阈值将回退使用 L1_age=30-40 的阈值
[INFO][BT][2026-03-26 18:47:14] 桶 bucket_id=L1_age=30-40|L2_job=no_income level=2：
    n_train=185, n_val=79,
    BAC=0.622, F1=0.471, AUC=0.883,
    Regret=0.158, BND_ratio=0.165, POS_coverage=0.101,
    Score(f1_regret_bnd )=0.148，threshold_source=val
[INFO][BT][2026-03-26 18:47:14] 桶 bucket_id=L1_age=30-40|L2_job=no_income：
    parent_id=L1_age=30-40，parent_Score=0.450, bucket_Score=0.148,
    Gain=-0.302, is_weak=True
【INFO】【2026-03-26 18:47:14】【阈值】桶 L1_age=30-40|L2_job=self_emp（n_val=148，source=val) 使用本地阈值 α=0.5000, β=0.2000
[INFO][BT][2026-03-26 18:47:14] 桶 bucket_id=L1_age=30-40|L2_job=self_emp level=2：
    n_train=215, n_val=148,
    BAC=0.764, F1=0.600, AUC=0.973,
    Regret=0.057, BND_ratio=0.068, POS_coverage=0.068,
    Score(f1_regret_bnd )=0.475，threshold_source=val
[INFO][BT][2026-03-26 18:47:14] 桶 bucket_id=L1_age=30-40|L2_job=self_emp：
    parent_id=L1_age=30-40，parent_Score=0.450, bucket_Score=0.475,
    Gain=+0.025, is_weak=False
【INFO】【2026-03-26 18:47:14】【阈值】桶 L1_age=30-40|L2_job=white_collar 标记为弱桶，阈值将回退使用 L1_age=30-40 的阈值
[INFO][BT][2026-03-26 18:47:14] 桶 bucket_id=L1_age=30-40|L2_job=white_collar level=2：
    n_train=1620, n_val=769,
    BAC=0.810, F1=0.622, AUC=0.920,
    Regret=0.118, BND_ratio=0.085, POS_coverage=0.177,
    Score(f1_regret_bnd )=0.419，threshold_source=val
[INFO][BT][2026-03-26 18:47:14] 桶 bucket_id=L1_age=30-40|L2_job=white_collar：
    parent_id=L1_age=30-40，parent_Score=0.450, bucket_Score=0.419,
    Gain=-0.031, is_weak=True
【INFO】【2026-03-26 18:47:15】【阈值】桶 L1_age=30-40|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=30-40 的阈值
[INFO][BT][2026-03-26 18:47:15] 桶 bucket_id=L1_age=30-40|L2_job=others level=2：
    n_train=39, n_val=33,
    BAC=0.795, F1=0.800, AUC=0.990,
    Regret=0.045, BND_ratio=0.097, POS_coverage=0.056,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:47:15] 桶 bucket_id=L1_age=30-40|L2_job=others：
    parent_id=L1_age=30-40，parent_Score=0.450, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:47:15】【阈值】桶 L1_age=40-50|L2_job=blue_collar（n_val=356，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:47:15] 桶 bucket_id=L1_age=40-50|L2_job=blue_collar level=2：
    n_train=709, n_val=356,
    BAC=0.895, F1=0.700, AUC=0.977,
    Regret=0.049, BND_ratio=0.045, POS_coverage=0.101,
    Score(f1_regret_bnd )=0.606，threshold_source=val
[INFO][BT][2026-03-26 18:47:15] 桶 bucket_id=L1_age=40-50|L2_job=blue_collar：
    parent_id=L1_age=40-50，parent_Score=0.512, bucket_Score=0.606,
    Gain=+0.094, is_weak=False
【INFO】【2026-03-26 18:47:15】【阈值】桶 L1_age=40-50|L2_job=no_income 标记为弱桶，阈值将回退使用 L1_age=40-50 的阈值
[INFO][BT][2026-03-26 18:47:15] 桶 bucket_id=L1_age=40-50|L2_job=no_income level=2：
    n_train=113, n_val=79,
    BAC=0.805, F1=0.640, AUC=0.921,
    Regret=0.114, BND_ratio=0.051, POS_coverage=0.177,
    Score(f1_regret_bnd )=0.475，threshold_source=val
[INFO][BT][2026-03-26 18:47:15] 桶 bucket_id=L1_age=40-50|L2_job=no_income：
    parent_id=L1_age=40-50，parent_Score=0.512, bucket_Score=0.475,
    Gain=-0.036, is_weak=True
【INFO】【2026-03-26 18:47:16】【阈值】桶 L1_age=40-50|L2_job=self_emp（n_val=130，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:47:16] 桶 bucket_id=L1_age=40-50|L2_job=self_emp level=2：
    n_train=170, n_val=130,
    BAC=0.825, F1=0.667, AUC=0.991,
    Regret=0.027, BND_ratio=0.015, POS_coverage=0.046,
    Score(f1_regret_bnd )=0.624，threshold_source=val
[INFO][BT][2026-03-26 18:47:16] 桶 bucket_id=L1_age=40-50|L2_job=self_emp：
    parent_id=L1_age=40-50，parent_Score=0.512, bucket_Score=0.624,
    Gain=+0.113, is_weak=False
【INFO】【2026-03-26 18:47:16】【阈值】桶 L1_age=40-50|L2_job=white_collar（n_val=449，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:47:16] 桶 bucket_id=L1_age=40-50|L2_job=white_collar level=2：
    n_train=942, n_val=449,
    BAC=0.862, F1=0.699, AUC=0.954,
    Regret=0.091, BND_ratio=0.058, POS_coverage=0.194,
    Score(f1_regret_bnd )=0.550，threshold_source=val
[INFO][BT][2026-03-26 18:47:16] 桶 bucket_id=L1_age=40-50|L2_job=white_collar：
    parent_id=L1_age=40-50，parent_Score=0.512, bucket_Score=0.550,
    Gain=+0.038, is_weak=False
【INFO】【2026-03-26 18:47:17】【阈值】桶 L1_age=40-50|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=40-50 的阈值
[INFO][BT][2026-03-26 18:47:17] 桶 bucket_id=L1_age=40-50|L2_job=others level=2：
    n_train=118, n_val=53,
    BAC=0.824, F1=0.692, AUC=0.963,
    Regret=0.057, BND_ratio=0.029, POS_coverage=0.076,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:47:17] 桶 bucket_id=L1_age=40-50|L2_job=others：
    parent_id=L1_age=40-50，parent_Score=0.512, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:47:17】【阈值】桶 L1_age=50-60|L2_job=blue_collar（n_val=222，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:47:17] 桶 bucket_id=L1_age=50-60|L2_job=blue_collar level=2：
    n_train=417, n_val=222,
    BAC=0.829, F1=0.619, AUC=0.941,
    Regret=0.079, BND_ratio=0.054, POS_coverage=0.113,
    Score(f1_regret_bnd )=0.486，threshold_source=val
[INFO][BT][2026-03-26 18:47:17] 桶 bucket_id=L1_age=50-60|L2_job=blue_collar：
    parent_id=L1_age=50-60，parent_Score=0.382, bucket_Score=0.486,
    Gain=+0.104, is_weak=False
【INFO】【2026-03-26 18:47:17】【阈值】桶 L1_age=50-60|L2_job=no_income（n_val=56，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:47:17] 桶 bucket_id=L1_age=50-60|L2_job=no_income level=2：
    n_train=80, n_val=56,
    BAC=0.761, F1=0.667, AUC=0.886,
    Regret=0.188, BND_ratio=0.089, POS_coverage=0.268,
    Score(f1_regret_bnd )=0.390，threshold_source=val
[INFO][BT][2026-03-26 18:47:17] 桶 bucket_id=L1_age=50-60|L2_job=no_income：
    parent_id=L1_age=50-60，parent_Score=0.382, bucket_Score=0.390,
    Gain=+0.008, is_weak=False
【INFO】【2026-03-26 18:47:18】【阈值】桶 L1_age=50-60|L2_job=retired（n_val=168，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:47:18] 桶 bucket_id=L1_age=50-60|L2_job=retired level=2：
    n_train=254, n_val=168,
    BAC=0.769, F1=0.609, AUC=0.960,
    Regret=0.076, BND_ratio=0.024, POS_coverage=0.065,
    Score(f1_regret_bnd )=0.509，threshold_source=val
[INFO][BT][2026-03-26 18:47:18] 桶 bucket_id=L1_age=50-60|L2_job=retired：
    parent_id=L1_age=50-60，parent_Score=0.382, bucket_Score=0.509,
    Gain=+0.127, is_weak=False
【INFO】【2026-03-26 18:47:18】【阈值】桶 L1_age=50-60|L2_job=self_emp 标记为弱桶，阈值将回退使用 L1_age=50-60 的阈值
[INFO][BT][2026-03-26 18:47:18] 桶 bucket_id=L1_age=50-60|L2_job=self_emp level=2：
    n_train=129, n_val=130,
    BAC=0.625, F1=0.375, AUC=0.888,
    Regret=0.123, BND_ratio=0.031, POS_coverage=0.046,
    Score(f1_regret_bnd )=0.221，threshold_source=val
[INFO][BT][2026-03-26 18:47:18] 桶 bucket_id=L1_age=50-60|L2_job=self_emp：
    parent_id=L1_age=50-60，parent_Score=0.382, bucket_Score=0.221,
    Gain=-0.161, is_weak=True
【INFO】【2026-03-26 18:47:19】【阈值】桶 L1_age=50-60|L2_job=white_collar（n_val=300，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:47:19] 桶 bucket_id=L1_age=50-60|L2_job=white_collar level=2：
    n_train=579, n_val=300,
    BAC=0.770, F1=0.641, AUC=0.928,
    Regret=0.109, BND_ratio=0.107, POS_coverage=0.140,
    Score(f1_regret_bnd )=0.425，threshold_source=val
[INFO][BT][2026-03-26 18:47:19] 桶 bucket_id=L1_age=50-60|L2_job=white_collar：
    parent_id=L1_age=50-60，parent_Score=0.382, bucket_Score=0.425,
    Gain=+0.043, is_weak=False
【INFO】【2026-03-26 18:47:19】【阈值】桶 L1_age=50-60|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=50-60 的阈值
[INFO][BT][2026-03-26 18:47:19] 桶 bucket_id=L1_age=50-60|L2_job=others level=2：
    n_train=50, n_val=20,
    BAC=0.725, F1=0.706, AUC=0.957,
    Regret=0.096, BND_ratio=0.171, POS_coverage=0.100,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:47:19] 桶 bucket_id=L1_age=50-60|L2_job=others：
    parent_id=L1_age=50-60，parent_Score=0.382, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:47:20】【阈值】桶 L1_age=<=30|L2_job=blue_collar（n_val=182，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:47:20] 桶 bucket_id=L1_age=<=30|L2_job=blue_collar level=2：
    n_train=419, n_val=182,
    BAC=0.803, F1=0.558, AUC=0.916,
    Regret=0.107, BND_ratio=0.060, POS_coverage=0.148,
    Score(f1_regret_bnd )=0.391，threshold_source=val
[INFO][BT][2026-03-26 18:47:20] 桶 bucket_id=L1_age=<=30|L2_job=blue_collar：
    parent_id=L1_age=<=30，parent_Score=0.370, bucket_Score=0.391,
    Gain=+0.021, is_weak=False
【INFO】【2026-03-26 18:47:20】【阈值】桶 L1_age=<=30|L2_job=no_income 标记为弱桶，阈值将回退使用 L1_age=<=30 的阈值
[INFO][BT][2026-03-26 18:47:20] 桶 bucket_id=L1_age=<=30|L2_job=no_income level=2：
    n_train=242, n_val=115,
    BAC=0.705, F1=0.691, AUC=0.898,
    Regret=0.180, BND_ratio=0.191, POS_coverage=0.226,
    Score(f1_regret_bnd )=0.319，threshold_source=val
[INFO][BT][2026-03-26 18:47:20] 桶 bucket_id=L1_age=<=30|L2_job=no_income：
    parent_id=L1_age=<=30，parent_Score=0.370, bucket_Score=0.319,
    Gain=-0.050, is_weak=True
【INFO】【2026-03-26 18:47:21】【阈值】桶 L1_age=<=30|L2_job=self_emp 标记为弱桶，阈值将回退使用 L1_age=<=30 的阈值
[INFO][BT][2026-03-26 18:47:21] 桶 bucket_id=L1_age=<=30|L2_job=self_emp level=2：
    n_train=108, n_val=87,
    BAC=0.734, F1=0.690, AUC=0.913,
    Regret=0.126, BND_ratio=0.195, POS_coverage=0.172,
    Score(f1_regret_bnd )=0.368，threshold_source=val
[INFO][BT][2026-03-26 18:47:21] 桶 bucket_id=L1_age=<=30|L2_job=self_emp：
    parent_id=L1_age=<=30，parent_Score=0.370, bucket_Score=0.368,
    Gain=-0.002, is_weak=True
【INFO】【2026-03-26 18:47:21】【阈值】桶 L1_age=<=30|L2_job=white_collar 标记为弱桶，阈值将回退使用 L1_age=<=30 的阈值
[INFO][BT][2026-03-26 18:47:21] 桶 bucket_id=L1_age=<=30|L2_job=white_collar level=2：
    n_train=607, n_val=244,
    BAC=0.735, F1=0.645, AUC=0.909,
    Regret=0.157, BND_ratio=0.160, POS_coverage=0.213,
    Score(f1_regret_bnd )=0.329，threshold_source=val
[INFO][BT][2026-03-26 18:47:21] 桶 bucket_id=L1_age=<=30|L2_job=white_collar：
    parent_id=L1_age=<=30，parent_Score=0.370, bucket_Score=0.329,
    Gain=-0.041, is_weak=True
【INFO】【2026-03-26 18:47:22】【阈值】桶 L1_age=<=30|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=<=30 的阈值
[INFO][BT][2026-03-26 18:47:22] 桶 bucket_id=L1_age=<=30|L2_job=others level=2：
    n_train=11, n_val=8,
    BAC=0.938, F1=1.000, AUC=1.000,
    Regret=0.026, BND_ratio=0.105, POS_coverage=0.158,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:47:22] 桶 bucket_id=L1_age=<=30|L2_job=others：
    parent_id=L1_age=<=30，parent_Score=0.370, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:47:22】【阈值】桶 L1_age=>60|L2_job=retired 标记为弱桶，阈值将回退使用 L1_age=>60 的阈值
[INFO][BT][2026-03-26 18:47:22] 桶 bucket_id=L1_age=>60|L2_job=retired level=2：
    n_train=148, n_val=110,
    BAC=0.630, F1=0.703, AUC=0.787,
    Regret=0.282, BND_ratio=0.091, POS_coverage=0.736,
    Score(f1_regret_bnd )=0.330，threshold_source=val
[INFO][BT][2026-03-26 18:47:22] 桶 bucket_id=L1_age=>60|L2_job=retired：
    parent_id=L1_age=>60，parent_Score=0.350, bucket_Score=0.330,
    Gain=-0.019, is_weak=True
【INFO】【2026-03-26 18:47:23】【阈值】桶 L1_age=>60|L2_job=white_collar（n_val=35，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:47:23] 桶 bucket_id=L1_age=>60|L2_job=white_collar level=2：
    n_train=89, n_val=35,
    BAC=0.679, F1=0.789, AUC=0.819,
    Regret=0.236, BND_ratio=0.114, POS_coverage=0.629,
    Score(f1_regret_bnd )=0.439，threshold_source=val
[INFO][BT][2026-03-26 18:47:23] 桶 bucket_id=L1_age=>60|L2_job=white_collar：
    parent_id=L1_age=>60，parent_Score=0.350, bucket_Score=0.439,
    Gain=+0.090, is_weak=False
【INFO】【2026-03-26 18:47:23】【阈值】桶 L1_age=>60|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=>60 的阈值
[INFO][BT][2026-03-26 18:47:23] 桶 bucket_id=L1_age=>60|L2_job=others level=2：
    n_train=93, n_val=25,
    BAC=0.809, F1=0.810, AUC=0.924,
    Regret=0.189, BND_ratio=0.076, POS_coverage=0.314,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:47:23] 桶 bucket_id=L1_age=>60|L2_job=others：
    parent_id=L1_age=>60，parent_Score=0.350, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:47:23】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=cellular（n_val=836，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:47:23] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular level=3：
    n_train=1858, n_val=836,
    BAC=0.789, F1=0.671, AUC=0.941,
    Regret=0.091, BND_ratio=0.028, POS_coverage=0.091,
    Score(f1_regret_bnd )=0.552，threshold_source=val
[INFO][BT][2026-03-26 18:47:23] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.494, bucket_Score=0.552,
    Gain=+0.058, is_weak=False
【INFO】【2026-03-26 18:47:24】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=telephone（n_val=57，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:47:24] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone level=3：
    n_train=145, n_val=57,
    BAC=0.756, F1=0.667, AUC=0.954,
    Regret=0.092, BND_ratio=0.070, POS_coverage=0.088,
    Score(f1_regret_bnd )=0.504，threshold_source=val
[INFO][BT][2026-03-26 18:47:24] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.494, bucket_Score=0.504,
    Gain=+0.010, is_weak=False
【INFO】【2026-03-26 18:47:24】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=unknown 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=blue_collar 的阈值
[INFO][BT][2026-03-26 18:47:24] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown level=3：
    n_train=1358, n_val=572,
    BAC=0.647, F1=0.440, AUC=0.959,
    Regret=0.067, BND_ratio=0.068, POS_coverage=0.033,
    Score(f1_regret_bnd )=0.305，threshold_source=val
[INFO][BT][2026-03-26 18:47:24] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.494, bucket_Score=0.305,
    Gain=-0.189, is_weak=True
【INFO】【2026-03-26 18:47:24】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=cellular（n_val=117，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:47:24] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular level=3：
    n_train=230, n_val=117,
    BAC=0.785, F1=0.696, AUC=0.898,
    Regret=0.173, BND_ratio=0.034, POS_coverage=0.188,
    Score(f1_regret_bnd )=0.488，threshold_source=val
[INFO][BT][2026-03-26 18:47:24] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.148, bucket_Score=0.488,
    Gain=+0.341, is_weak=False
【INFO】【2026-03-26 18:47:25】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=unknown（n_val=34，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:47:25] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown level=3：
    n_train=96, n_val=34,
    BAC=0.618, F1=0.400, AUC=0.935,
    Regret=0.096, BND_ratio=0.118, POS_coverage=0.059,
    Score(f1_regret_bnd )=0.187，threshold_source=val
[INFO][BT][2026-03-26 18:47:25] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.148, bucket_Score=0.187,
    Gain=+0.039, is_weak=False
【INFO】【2026-03-26 18:47:25】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=others 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=no_income 的阈值
[INFO][BT][2026-03-26 18:47:25] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others level=3：
    n_train=20, n_val=10,
    BAC=0.740, F1=0.750, AUC=0.960,
    Regret=0.092, BND_ratio=0.167, POS_coverage=0.100,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:47:25] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.148, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:47:26】【阈值】桶 L1_age=30-40|L2_job=self_emp|L3_contact=cellular 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=self_emp 的阈值
[INFO][BT][2026-03-26 18:47:26] 桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular level=3：
    n_train=469, n_val=214,
    BAC=0.797, F1=0.655, AUC=0.924,
    Regret=0.107, BND_ratio=0.117, POS_coverage=0.150,
    Score(f1_regret_bnd )=0.430，threshold_source=val
[INFO][BT][2026-03-26 18:47:26] 桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=self_emp，parent_Score=0.475, bucket_Score=0.430,
    Gain=-0.045, is_weak=True
【INFO】【2026-03-26 18:47:26】【阈值】桶 L1_age=30-40|L2_job=self_emp|L3_contact=unknown 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=self_emp 的阈值
[INFO][BT][2026-03-26 18:47:26] 桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=unknown level=3：
    n_train=171, n_val=79,
    BAC=0.500, F1=0.000, AUC=0.936,
    Regret=0.025, BND_ratio=0.000, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.025，threshold_source=val

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [18:47:46] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 18:47:47】[BASELINE] 全局 XGB 模型训练完成
【INFO】【2026-03-26 18:47:47】[BASELINE] 阈值搜索开始
【INFO】【2026-03-26 18:47:48】[BASELINE] 最佳阈值找到: alpha=0.3000, beta=0.1000, regret=0.1132
【INFO】【2026-03-26 18:47:48】【桶树】已为样本生成桶ID，共 79 个组合
【INFO】【2026-03-26 18:47:48】[BASELINE] 测试集桶映射完成，共 79 个桶

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)

【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=unknown|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar|L3_contact=unknown: BAC=0.4904, Regret=0.0487, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar|L3_contact=unknown: BAC=0.7722, Regret=0.0586, Precision=0.4444, Recall=0.5714
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=retired|L3_contact=unknown: BAC=1.0000, Regret=0.0625, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar|L3_contact=unknown: BAC=0.7100, Regret=0.0622, Precision=0.4444, Recall=0.4444
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp|L3_contact=unknown: BAC=0.7500, Regret=0.0859, Precision=1.0000, Recall=0.5000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar|L3_contact=unknown: BAC=0.7169, Regret=0.0585, Precision=0.4545, Recall=0.4545
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar|L3_contact=unknown: BAC=0.6971, Regret=0.0312, Precision=0.6667, Recall=0.4000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar|L3_contact=unknown: BAC=0.8519, Regret=0.0372, Precision=0.5333, Recall=0.7273
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=no_income|L3_contact=unknown: BAC=0.7500, Regret=0.0312, Precision=1.0000, Recall=0.5000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar|L3_contact=unknown: BAC=0.6963, Regret=0.0448, Precision=0.3125, Recall=0.4167
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=no_income|L3_contact=unknown: BAC=0.9844, Regret=0.0455, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=retired|L3_contact=unknown: BAC=0.9286, Regret=0.0536, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=unknown|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=no_income|L3_contact=unknown: BAC=1.0000, Regret=0.0208, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=retired|L3_contact=unknown: BAC=0.9583, Regret=0.0625, Precision=0.3636, Recall=1.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp|L3_contact=unknown: BAC=0.9500, Regret=0.0667, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp|L3_contact=unknown: BAC=0.9412, Regret=0.1111, Precision=0.3333, Recall=1.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp|L3_contact=unknown: BAC=0.6449, Regret=0.1173, Precision=0.3333, Recall=0.3333
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar|L3_contact=unknown: BAC=0.7348, Regret=0.1177, Precision=0.4444, Recall=0.5333
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=no_income|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=unknown|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=retired|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=unknown|L3_contact=unknown: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar|L3_contact=cellular: BAC=0.8103, Regret=0.1629, Precision=0.6721, Recall=0.7069
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar|L3_contact=cellular: BAC=0.8067, Regret=0.1524, Precision=0.6296, Recall=0.6986
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar|L3_contact=cellular: BAC=0.8111, Regret=0.1369, Precision=0.5869, Recall=0.7070
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp|L3_contact=cellular: BAC=0.7222, Regret=0.1494, Precision=0.5556, Recall=0.5000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar|L3_contact=cellular: BAC=0.8194, Regret=0.1101, Precision=0.5000, Recall=0.7164
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar|L3_contact=cellular: BAC=0.8094, Regret=0.1211, Precision=0.4954, Recall=0.7013
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar|L3_contact=cellular: BAC=0.7344, Regret=0.1109, Precision=0.4000, Recall=0.5455
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar|L3_contact=cellular: BAC=0.8108, Regret=0.0971, Precision=0.5778, Recall=0.6667
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=no_income|L3_contact=telephone: BAC=1.0000, Regret=0.0750, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=unknown|L3_contact=cellular: BAC=0.4167, Regret=0.2500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar|L3_contact=telephone: BAC=0.8229, Regret=0.0926, Precision=0.8000, Recall=0.6667
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=no_income|L3_contact=cellular: BAC=0.7323, Regret=0.1934, Precision=0.5556, Recall=0.5556
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=unknown|L3_contact=cellular: BAC=0.7500, Regret=0.1667, Precision=1.0000, Recall=0.5000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar|L3_contact=telephone: BAC=0.7214, Regret=0.0799, Precision=0.2000, Recall=0.5000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp|L3_contact=telephone: BAC=0.6667, Regret=0.2273, Precision=1.0000, Recall=0.3333
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar|L3_contact=telephone: BAC=0.8193, Regret=0.1301, Precision=0.5000, Recall=0.7143
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=retired|L3_contact=cellular: BAC=0.7886, Regret=0.1397, Precision=0.5294, Recall=0.6429
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar|L3_contact=cellular: BAC=0.7939, Regret=0.1803, Precision=0.6050, Recall=0.7129
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar|L3_contact=telephone: BAC=0.7909, Regret=0.0542, Precision=0.7500, Recall=0.6000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp|L3_contact=cellular: BAC=0.7863, Regret=0.1168, Precision=0.4375, Recall=0.6364
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp|L3_contact=cellular: BAC=0.9815, Regret=0.0593, Precision=0.7143, Recall=1.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=no_income|L3_contact=cellular: BAC=0.7278, Regret=0.2870, Precision=0.5570, Recall=0.7857
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp|L3_contact=cellular: BAC=0.8218, Regret=0.1528, Precision=0.8182, Recall=0.6923
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=no_income|L3_contact=cellular: BAC=0.9242, Regret=0.1118, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=retired|L3_contact=telephone: BAC=0.9444, Regret=0.1071, Precision=0.6000, Recall=1.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar|L3_contact=telephone: BAC=0.6572, Regret=0.1102, Precision=0.6667, Recall=0.3333
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar|L3_contact=telephone: BAC=0.7465, Regret=0.1207, Precision=0.5000, Recall=0.5714
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar|L3_contact=telephone: BAC=1.0000, Regret=0.0139, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=retired|L3_contact=cellular: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp|L3_contact=telephone: BAC=0.9286, Regret=0.1333, Precision=0.3333, Recall=1.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=no_income|L3_contact=cellular: BAC=0.8068, Regret=0.1735, Precision=0.5600, Recall=0.7778
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=unknown|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=retired|L3_contact=cellular: BAC=0.6742, Regret=0.2883, Precision=0.6322, Recall=0.8730
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=unknown|L3_contact=telephone: BAC=0.8000, Regret=0.1500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=retired|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=no_income|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=no_income|L3_contact=telephone: BAC=0.5556, Regret=0.3333, Precision=0.2000, Recall=0.3333
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=no_income|L3_contact=telephone: BAC=0.5000, Regret=0.3750, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=unknown|L3_contact=cellular: BAC=0.9000, Regret=0.1667, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=retired|L3_contact=telephone: BAC=0.7171, Regret=0.2803, Precision=0.5714, Recall=0.8000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=unknown|L3_contact=cellular: BAC=1.0000, Regret=0.1250, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=white_collar|L3_contact=cellular: BAC=0.6268, Regret=0.4083, Precision=0.4706, Recall=0.7273
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=unknown|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=unknown|L3_contact=telephone: BAC=0.5000, Regret=0.5000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar|L3_contact=cellular: BAC=0.7619, Regret=0.2115, Precision=0.7500, Recall=0.8571
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=self_emp|L3_contact=cellular: BAC=0.8750, Regret=0.3750, Precision=1.0000, Recall=0.7500
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar|L3_contact=telephone: BAC=0.6667, Regret=0.5833, Precision=1.0000, Recall=0.3333
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=white_collar|L3_contact=telephone: BAC=0.0000, Regret=0.7917, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=no_income|L3_contact=telephone: BAC=1.0000, Regret=0.2500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp|L3_contact=telephone: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=unknown|L3_contact=cellular: BAC=0.5000, Regret=0.5000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=no_income|L3_contact=cellular: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=self_emp|L3_contact=telephone: BAC=0.8333, Regret=0.2500, Precision=1.0000, Recall=0.6667
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=unknown: BAC=0.4500, Regret=0.1591, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40: BAC=0.8075, Regret=0.1069, Precision=0.5422, Recall=0.6797
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=blue_collar: BAC=0.7010, Regret=0.0900, Precision=0.3889, Recall=0.4516
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60: BAC=0.8061, Regret=0.1024, Precision=0.5484, Recall=0.6711
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=blue_collar: BAC=0.8219, Regret=0.1170, Precision=0.6528, Recall=0.7015
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30: BAC=0.8031, Regret=0.1576, Precision=0.5955, Recall=0.7104
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=retired: BAC=1.0000, Regret=0.0625, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=white_collar: BAC=0.8065, Regret=0.1202, Precision=0.5754, Recall=0.6833
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=self_emp: BAC=0.9273, Regret=0.0590, Precision=0.7778, Recall=0.8750
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=white_collar: BAC=0.8042, Regret=0.1026, Precision=0.5040, Recall=0.6702
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50: BAC=0.7984, Regret=0.0944, Precision=0.5115, Recall=0.6491
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=white_collar: BAC=0.8106, Regret=0.1183, Precision=0.6170, Recall=0.6824
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=blue_collar: BAC=0.8176, Regret=0.0736, Precision=0.5385, Recall=0.6731
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=no_income: BAC=0.7504, Regret=0.2535, Precision=0.5412, Recall=0.7541
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=blue_collar: BAC=0.8068, Regret=0.0821, Precision=0.4828, Recall=0.6667
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=no_income: BAC=0.8444, Regret=0.1328, Precision=0.5714, Recall=0.8000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=retired: BAC=0.9565, Regret=0.0326, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=unknown: BAC=0.7500, Regret=0.0714, Precision=1.0000, Recall=0.5000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=no_income: BAC=0.9500, Regret=0.0804, Precision=0.5455, Recall=1.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=retired: BAC=0.8430, Regret=0.1092, Precision=0.4848, Recall=0.7619
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=30-40|L2_job=self_emp: BAC=0.7570, Regret=0.1087, Precision=0.4000, Recall=0.5714
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=self_emp: BAC=0.8232, Regret=0.1404, Precision=0.7143, Recall=0.7143
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=self_emp: BAC=0.7197, Regret=0.1370, Precision=0.4667, Recall=0.5000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=white_collar: BAC=0.7931, Regret=0.1597, Precision=0.5839, Recall=0.6897
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=40-50|L2_job=no_income: BAC=0.7381, Regret=0.1528, Precision=0.5000, Recall=0.5556
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=50-60|L2_job=unknown: BAC=0.9545, Regret=0.0761, Precision=0.3333, Recall=1.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=retired: BAC=0.6980, Regret=0.2840, Precision=0.6148, Recall=0.8523
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60: BAC=0.6818, Regret=0.3168, Precision=0.5938, Recall=0.8120
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=<=30|L2_job=unknown: BAC=1.0000, Regret=0.0625, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=white_collar: BAC=0.5417, Regret=0.4722, Precision=0.3636, Recall=0.6667
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=unknown: BAC=0.5000, Regret=0.5000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=blue_collar: BAC=0.7389, Regret=0.3289, Precision=0.7778, Recall=0.7000
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=self_emp: BAC=0.8571, Regret=0.3250, Precision=1.0000, Recall=0.7143
【INFO】【2026-03-26 18:47:51】[BASELINE] 桶 L1_age=>60|L2_job=no_income: BAC=1.0000, Regret=0.1250, Precision=0.0000, Recall=0.0000

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)

【INFO】【2026-03-26 18:47:51】【K折实验】所有结果已写入 results 目录

,model,Precision_mean,Precision_std,Recall_mean,Recall_std,F1_mean,F1_std,BAC_mean,BAC_std,AUC_mean,...,MCC_mean,MCC_std,Kappa_mean,Kappa_std,BND_ratio_mean,BND_ratio_std,POS_Coverage_mean,POS_Coverage_std,Regret_mean,Regret_std
0,BTTWD,0.548081,0.009321,0.732271,0.014770,0.626890,0.010255,0.826132,0.007536,0.932804,...,0.577294,0.012045,0.569252,0.011773,0.079427,0.002704,0.147309,0.007812,0.117571,0.003856
1,LogReg,0.623769,0.018441,0.436565,0.014859,0.513241,0.008340,0.700773,0.006167,0.906632,...,0.470631,0.008159,0.461357,0.008428,0.000000,0.000000,NaN,NaN,0.155018,0.002173
2,RandomForest,0.601240,0.015321,0.582903,0.016315,0.591893,0.015156,0.765839,0.008840,0.931319,...,0.538881,0.017029,0.538777,0.017038,0.000000,0.000000,NaN,NaN,0.131511,0.004791
3,KNN,0.560451,0.013462,0.508036,0.006213,0.532867,0.007157,0.727591,0.003210,0.877080,...,0.475154,0.008858,0.474378,0.008585,0.000000,0.000000,NaN,NaN,0.150107,0.002215
4,XGBoost,0.606381,0.010677,0.603890,0.013179,0.605067,0.010262,0.775969,0.006619,0.935239,...,0.552913,0.011429,0.552873,0.011455,0.000000,0.000000,NaN,NaN,0.127082,0.003287

【INFO】【2026-03-26 18:47:53】【步骤6摘要】BTTWD 与基线的 k 折结果已生成并保存。

In [8]:
# 步骤7：桶级别分析
bucket_metrics_path = os.path.join(root_path, cfg['OUTPUT']['results_dir'], 'bucket_metrics.csv')
if os.path.exists(bucket_metrics_path):
    bucket_metrics_df = pd.read_csv(bucket_metrics_path)
    display(bucket_metrics_df.head())
    bucket_metrics_df.plot(x='bucket_id', y='pos_rate_all', kind='bar', figsize=(12,4), title='桶正类比例')
    plt.ylabel('正类比例')
    plt.xticks(rotation=90)
    plt.tight_layout()
    plt.savefig(fig_bucket, bbox_inches='tight')
    plt.close()
log_info('【步骤7摘要】桶级指标（如存在）已整理，可用于局部化分析。')

,bucket_id,layer,parent_bucket_id,n_train,n_val,pos_rate_train,pos_rate_val,alpha,beta,regret_val,...,use_gain_weak_backoff,threshold_data_source,parent_with_threshold,n_test,pos_rate_test,BND_ratio_test,POS_Coverage_test,regret_test,fold,pos_rate
0,ROOT,L1,NaN,7594,3252,0.115881,0.118081,0.2,0.1,0.112623,...,True,val,NaN,NaN,NaN,NaN,NaN,NaN,1,0.116982
1,L1_age=30-40,L1,ROOT,3001,1295,0.100300,0.114286,0.2,0.1,0.110618,...,True,val,NaN,NaN,NaN,NaN,NaN,NaN,1,0.101531
2,L1_age=40-50,L1,ROOT,1859,923,0.091985,0.092091,0.4,0.2,0.087486,...,True,val,NaN,NaN,NaN,NaN,NaN,NaN,1,0.090015
3,L1_age=30-40|L2_job=white_collar,L2,L1_age=30-40,1648,756,0.111650,0.116402,0.4,0.2,0.101521,...,True,val,NaN,NaN,NaN,NaN,NaN,NaN,1,0.117017
4,L1_age=50-60,L1,ROOT,1408,605,0.090199,0.109091,0.3,0.1,0.097934,...,True,val,NaN,NaN,NaN,NaN,NaN,NaN,1,0.099423

C:\Users\xzq20.HUANLI\AppData\Local\Temp\ipykernel_17640\2693955862.py:9: UserWarning: Tight layout not applied. The bottom and top margins cannot be made large enough to accommodate all Axes decorations.
  plt.tight_layout()

【INFO】【2026-03-26 18:47:59】【步骤7摘要】桶级指标（如存在）已整理，可用于局部化分析。

In [9]:
# 步骤8：结果汇总
log_info('【步骤8】检查结果文件与图表。')
results_dir = os.path.join(root_path, cfg['OUTPUT']['results_dir'])
figs_dir = os.path.join(root_path, cfg['OUTPUT']['figs_dir'])
os.makedirs(results_dir, exist_ok=True)
os.makedirs(figs_dir, exist_ok=True)
print(os.listdir(results_dir))
print(os.listdir(figs_dir))
log_info('【全部步骤完成】Bank Marketing 数据集的 BT-TWD 实验结束。')

【INFO】【2026-03-26 18:47:59】【步骤8】检查结果文件与图表。
['bank.xlsx', 'baseline_bucket_metrics.csv', 'bttwd_bucket_stats_clean.py', 'bucket_fallback_stats.csv', 'bucket_metrics.csv', 'bucket_metrics_gain.csv', 'bucket_metrics_gain_test_per_fold.csv', 'bucket_thresholds.csv', 'bucket_thresholds_per_fold.csv', 'bucket_tree_structure.csv', 'fallback_off_tsne', 'fallback_on_tsne', 'metrics_kfold_per_fold.csv', 'metrics_kfold_summary.csv', 'metrics_overview.csv', 'per_sample_test_predictions.csv', 'tsne_fallback']
['bank_class_distribution.png', 'bucket_metrics_bar.png', 'class_distribution.png', 'metrics_compare.png']
【INFO】【2026-03-26 18:47:59】【全部步骤完成】Bank Marketing 数据集的 BT-TWD 实验结束。

In [10]:
# 步骤9：t-SNE 可视化弱桶对比
from bttwdlib import visualize_fallback_with_tsne
from IPython.display import Image

# 调用 t-SNE 可视化函数，参数从 YAML 配置中读取
tsne_output_dir = os.path.join(root_path, cfg["OUTPUT"]["results_dir"], "tsne_fallback")
os.makedirs(tsne_output_dir, exist_ok=True)
results = visualize_fallback_with_tsne(config_path=cfg_path, output_dir=tsne_output_dir)

# 显示保存的图片
Image(filename=results["figure_path"])

# 输出其他结果路径
print(f"t-SNE 嵌入结果保存路径：{results['embedding_path']}")
print(f"弱桶对比摘要保存路径：{results['summary_path']}")
print(f"可视化图片保存路径：{results['figure_path']}")

【INFO】【2026-03-26 18:48:00】【配置加载】已读取 e:\yan\组\三支决策\机器学习\BT_TWD\configs\bank_bttwd.yaml
【INFO】【2026-03-26 18:48:00】【数据加载】文本表格 E:\yan\组\三支决策\机器学习\BT_TWD\data\bank\bank-full.csv 已读取，样本数=45211，列数=17
【INFO】【2026-03-26 18:48:00】【数据加载】标签列 y 已处理完成：dropna_target=False, 丢弃样本=0, 最终样本数=45211, 正类比例=11.70%
【INFO】【2026-03-26 18:48:00】【数据加载】银行营销数据集已读取，标签已映射为0/1，样本数=45211，正类比例=11.70%
【INFO】【2026-03-26 18:48:00】【数据集信息】名称=bank_full，样本数=45211，目标列=y，正类比例=11.70%
【INFO】【2026-03-26 18:48:00】【预处理】连续特征=7个，类别特征=9个
【INFO】【2026-03-26 18:48:00】【预处理】编码后维度=42
[t-SNE] Computing 121 nearest neighbors...
[t-SNE] Indexed 45211 samples in 0.004s...
[t-SNE] Computed neighbors for 45211 samples in 3.109s...
[t-SNE] Computed conditional probabilities for sample 1000 / 45211
[t-SNE] Computed conditional probabilities for sample 2000 / 45211
[t-SNE] Computed conditional probabilities for sample 3000 / 45211
[t-SNE] Computed conditional probabilities for sample 4000 / 45211
[t-SNE] Computed conditional probabilities for sample 5000 / 45211
[t-SNE] Computed conditional probabilities for sample 6000 / 45211
[t-SNE] Computed conditional probabilities for sample 7000 / 45211
[t-SNE] Computed conditional probabilities for sample 8000 / 45211
[t-SNE] Computed conditional probabilities for sample 9000 / 45211
[t-SNE] Computed conditional probabilities for sample 10000 / 45211
[t-SNE] Computed conditional probabilities for sample 11000 / 45211
[t-SNE] Computed conditional probabilities for sample 12000 / 45211
[t-SNE] Computed conditional probabilities for sample 13000 / 45211
[t-SNE] Computed conditional probabilities for sample 14000 / 45211
[t-SNE] Computed conditional probabilities for sample 15000 / 45211
[t-SNE] Computed conditional probabilities for sample 16000 / 45211
[t-SNE] Computed conditional probabilities for sample 17000 / 45211
[t-SNE] Computed conditional probabilities for sample 18000 / 45211
[t-SNE] Computed conditional probabilities for sample 19000 / 45211
[t-SNE] Computed conditional probabilities for sample 20000 / 45211
[t-SNE] Computed conditional probabilities for sample 21000 / 45211
[t-SNE] Computed conditional probabilities for sample 22000 / 45211
[t-SNE] Computed conditional probabilities for sample 23000 / 45211
[t-SNE] Computed conditional probabilities for sample 24000 / 45211
[t-SNE] Computed conditional probabilities for sample 25000 / 45211
[t-SNE] Computed conditional probabilities for sample 26000 / 45211
[t-SNE] Computed conditional probabilities for sample 27000 / 45211
[t-SNE] Computed conditional probabilities for sample 28000 / 45211
[t-SNE] Computed conditional probabilities for sample 29000 / 45211
[t-SNE] Computed conditional probabilities for sample 30000 / 45211
[t-SNE] Computed conditional probabilities for sample 31000 / 45211
[t-SNE] Computed conditional probabilities for sample 32000 / 45211
[t-SNE] Computed conditional probabilities for sample 33000 / 45211
[t-SNE] Computed conditional probabilities for sample 34000 / 45211
[t-SNE] Computed conditional probabilities for sample 35000 / 45211
[t-SNE] Computed conditional probabilities for sample 36000 / 45211
[t-SNE] Computed conditional probabilities for sample 37000 / 45211
[t-SNE] Computed conditional probabilities for sample 38000 / 45211
[t-SNE] Computed conditional probabilities for sample 39000 / 45211
[t-SNE] Computed conditional probabilities for sample 40000 / 45211
[t-SNE] Computed conditional probabilities for sample 41000 / 45211
[t-SNE] Computed conditional probabilities for sample 42000 / 45211
[t-SNE] Computed conditional probabilities for sample 43000 / 45211
[t-SNE] Computed conditional probabilities for sample 44000 / 45211
[t-SNE] Computed conditional probabilities for sample 45000 / 45211
[t-SNE] Computed conditional probabilities for sample 45211 / 45211
[t-SNE] Mean sigma: 0.693740
[t-SNE] KL divergence after 250 iterations with early exaggeration: 100.775360
[t-SNE] KL divergence after 1000 iterations: 2.569224
【INFO】【2026-03-26 18:51:11】[t-SNE] Finished embedding computation; adjusted perplexity=40.00, output shape=(45211, 2)
【INFO】【2026-03-26 18:51:11】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=1.0

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [18:51:11] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 18:51:11】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=45211
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="30-40"，n_samples=17687
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="40-50"，n_samples=11239
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="50-60"，n_samples=8067
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=<=30，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="<=30"，n_samples=7030
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=>60，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule=">60"，n_samples=1188
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=6041
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=635
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=1185
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=9739
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40|L2_job=others，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=87
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=4221
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=359
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50|L2_job=retired，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="retired"，n_samples=112
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=873
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50|L2_job=unknown，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="unknown"，n_samples=103
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=5571
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=2453
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=265
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=retired，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="retired"，n_samples=1237
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=588
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=3431
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=others，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=93
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=2327
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=972
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=383
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=3325
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=<=30|L2_job=others，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=23
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=>60|L2_job=retired，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="retired"，n_samples=875
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=160
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=>60|L2_job=others，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=153
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=3380
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=262
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=2399
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=432
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=163
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=40
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=835
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=310
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=40
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=7237
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=295
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=2207
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=2319
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=314
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1588
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=238
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=40-50|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=121
[INFO][BT][2026-03-26 18:51:12] 桶 bucket_id=L1_age=40-50|L2_job=retired 不再细分：3 个子桶样本数不足 min_bucket_size=100
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=554
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=255
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=64
[INFO][BT][2026-03-26 18:51:12] 桶 bucket_id=L1_age=40-50|L2_job=unknown 不再细分：3 个子桶样本数不足 min_bucket_size=100
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=3747
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=315
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1509
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1316
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=289
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=848
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=179
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=86
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=722
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=telephone，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=114
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=401
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=345
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=185
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=58
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=2207
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=345
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=879
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1336
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=895
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=96
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=733
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=144
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=95
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=283
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=100
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=2434
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=794
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=97
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=cellular，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=583
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=telephone，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=281
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=others，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=11
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=>60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=131
[INFO][BT][2026-03-26 18:51:12] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar|L3_contact=others，level=3，parent_id=L1_age=>60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=29
[INFO][BT][2026-03-26 18:51:16] 桶树构建完成：总桶数=84，最大层数=3，叶子桶数=59
【INFO】【2026-03-26 18:51:16】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 18:51:16】【阈值】桶 ROOT（n_val=4066，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:51:16] 桶 bucket_id=ROOT level=0：
    n_train=9491, n_val=4066,
    BAC=0.746, F1=0.610, AUC=0.932,
    Regret=0.116, BND_ratio=0.077, POS_coverage=0.114,
    Score(f1_regret_bnd )=0.417，threshold_source=val
【INFO】【2026-03-26 18:51:17】【阈值】桶 L1_age=30-40（n_val=1614，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:51:17] 桶 bucket_id=L1_age=30-40 level=1：
    n_train=3749, n_val=1614,
    BAC=0.781, F1=0.638, AUC=0.933,
    Regret=0.109, BND_ratio=0.104, POS_coverage=0.139,
    Score(f1_regret_bnd )=0.425，threshold_source=val
[INFO][BT][2026-03-26 18:51:17] 桶 bucket_id=L1_age=30-40：
    parent_id=ROOT，parent_Score=0.417, bucket_Score=0.425,
    Gain=+0.009, is_weak=False
【INFO】【2026-03-26 18:51:17】【阈值】桶 L1_age=40-50 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:51:17] 桶 bucket_id=L1_age=40-50 level=1：
    n_train=2475, n_val=1043,
    BAC=0.724, F1=0.561, AUC=0.926,
    Regret=0.106, BND_ratio=0.066, POS_coverage=0.087,
    Score(f1_regret_bnd )=0.389，threshold_source=val
[INFO][BT][2026-03-26 18:51:17] 桶 bucket_id=L1_age=40-50：
    parent_id=ROOT，parent_Score=0.417, bucket_Score=0.389,
    Gain=-0.028, is_weak=True
【INFO】【2026-03-26 18:51:17】【阈值】桶 L1_age=50-60（n_val=822，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:51:17] 桶 bucket_id=L1_age=50-60 level=1：
    n_train=1714, n_val=822,
    BAC=0.856, F1=0.697, AUC=0.955,
    Regret=0.089, BND_ratio=0.055, POS_coverage=0.172,
    Score(f1_regret_bnd )=0.553，threshold_source=val
[INFO][BT][2026-03-26 18:51:17] 桶 bucket_id=L1_age=50-60：
    parent_id=ROOT，parent_Score=0.417, bucket_Score=0.553,
    Gain=+0.136, is_weak=False
【INFO】【2026-03-26 18:51:18】【阈值】桶 L1_age=<=30 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:51:18] 桶 bucket_id=L1_age=<=30 level=1：
    n_train=1510, n_val=611,
    BAC=0.725, F1=0.663, AUC=0.914,
    Regret=0.150, BND_ratio=0.173, POS_coverage=0.178,
    Score(f1_regret_bnd )=0.340，threshold_source=val
[INFO][BT][2026-03-26 18:51:18] 桶 bucket_id=L1_age=<=30：
    parent_id=ROOT，parent_Score=0.417, bucket_Score=0.340,
    Gain=-0.077, is_weak=True
【INFO】【2026-03-26 18:51:18】【阈值】桶 L1_age=>60 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 18:51:18] 桶 bucket_id=L1_age=>60 level=1：
    n_train=253, n_val=166,
    BAC=0.536, F1=0.658, AUC=0.772,
    Regret=0.321, BND_ratio=0.283, POS_coverage=0.506,
    Score(f1_regret_bnd )=0.054，threshold_source=val
[INFO][BT][2026-03-26 18:51:18] 桶 bucket_id=L1_age=>60：
    parent_id=ROOT，parent_Score=0.417, bucket_Score=0.054,
    Gain=-0.363, is_weak=True
【INFO】【2026-03-26 18:51:18】【阈值】桶 L1_age=30-40|L2_job=blue_collar（n_val=594，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:51:18] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar level=2：
    n_train=1269, n_val=594,
    BAC=0.788, F1=0.633, AUC=0.950,
    Regret=0.073, BND_ratio=0.086, POS_coverage=0.089,
    Score(f1_regret_bnd )=0.474，threshold_source=val
[INFO][BT][2026-03-26 18:51:18] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar：
    parent_id=L1_age=30-40，parent_Score=0.425, bucket_Score=0.474,
    Gain=+0.048, is_weak=False
【INFO】【2026-03-26 18:51:18】【阈值】桶 L1_age=30-40|L2_job=no_income（n_val=94，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:51:18] 桶 bucket_id=L1_age=30-40|L2_job=no_income level=2：
    n_train=154, n_val=94,
    BAC=0.772, F1=0.667, AUC=0.913,
    Regret=0.122, BND_ratio=0.096, POS_coverage=0.149,
    Score(f1_regret_bnd )=0.449，threshold_source=val
[INFO][BT][2026-03-26 18:51:18] 桶 bucket_id=L1_age=30-40|L2_job=no_income：
    parent_id=L1_age=30-40，parent_Score=0.425, bucket_Score=0.449,
    Gain=+0.023, is_weak=False
【INFO】【2026-03-26 18:51:19】【阈值】桶 L1_age=30-40|L2_job=self_emp（n_val=181，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:51:19] 桶 bucket_id=L1_age=30-40|L2_job=self_emp level=2：
    n_train=264, n_val=181,
    BAC=0.810, F1=0.643, AUC=0.969,
    Regret=0.066, BND_ratio=0.099, POS_coverage=0.088,
    Score(f1_regret_bnd )=0.477，threshold_source=val
[INFO][BT][2026-03-26 18:51:19] 桶 bucket_id=L1_age=30-40|L2_job=self_emp：
    parent_id=L1_age=30-40，parent_Score=0.425, bucket_Score=0.477,
    Gain=+0.052, is_weak=False
【INFO】【2026-03-26 18:51:19】【阈值】桶 L1_age=30-40|L2_job=white_collar 标记为弱桶，阈值将回退使用 L1_age=30-40 的阈值
[INFO][BT][2026-03-26 18:51:19] 桶 bucket_id=L1_age=30-40|L2_job=white_collar level=2：
    n_train=2038, n_val=938,
    BAC=0.733, F1=0.584, AUC=0.918,
    Regret=0.116, BND_ratio=0.079, POS_coverage=0.110,
    Score(f1_regret_bnd )=0.389，threshold_source=val
[INFO][BT][2026-03-26 18:51:19] 桶 bucket_id=L1_age=30-40|L2_job=white_collar：
    parent_id=L1_age=30-40，parent_Score=0.425, bucket_Score=0.389,
    Gain=-0.037, is_weak=True
【INFO】【2026-03-26 18:51:19】【阈值】桶 L1_age=30-40|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=30-40 的阈值
[INFO][BT][2026-03-26 18:51:19] 桶 bucket_id=L1_age=30-40|L2_job=others level=2：
    n_train=60, n_val=27,
    BAC=0.897, F1=0.800, AUC=0.995,
    Regret=0.037, BND_ratio=0.046, POS_coverage=0.092,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:51:19] 桶 bucket_id=L1_age=30-40|L2_job=others：
    parent_id=L1_age=30-40，parent_Score=0.425, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:51:20】【阈值】桶 L1_age=40-50|L2_job=blue_collar（n_val=376，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:51:20] 桶 bucket_id=L1_age=40-50|L2_job=blue_collar level=2：
    n_train=888, n_val=376,
    BAC=0.848, F1=0.676, AUC=0.960,
    Regret=0.068, BND_ratio=0.056, POS_coverage=0.104,
    Score(f1_regret_bnd )=0.553，threshold_source=val
[INFO][BT][2026-03-26 18:51:20] 桶 bucket_id=L1_age=40-50|L2_job=blue_collar：
    parent_id=L1_age=40-50，parent_Score=0.389, bucket_Score=0.553,
    Gain=+0.164, is_weak=False
【INFO】【2026-03-26 18:51:20】【阈值】桶 L1_age=40-50|L2_job=no_income 标记为弱桶，阈值将回退使用 L1_age=40-50 的阈值
[INFO][BT][2026-03-26 18:51:20] 桶 bucket_id=L1_age=40-50|L2_job=no_income level=2：
    n_train=141, n_val=101,
    BAC=0.605, F1=0.609, AUC=0.917,
    Regret=0.149, BND_ratio=0.277, POS_coverage=0.079,
    Score(f1_regret_bnd )=0.183，threshold_source=val
[INFO][BT][2026-03-26 18:51:20] 桶 bucket_id=L1_age=40-50|L2_job=no_income：
    parent_id=L1_age=40-50，parent_Score=0.389, bucket_Score=0.183,
    Gain=-0.206, is_weak=True
【INFO】【2026-03-26 18:51:20】【阈值】桶 L1_age=40-50|L2_job=retired 标记为弱桶，阈值将回退使用 L1_age=40-50 的阈值
[INFO][BT][2026-03-26 18:51:20] 桶 bucket_id=L1_age=40-50|L2_job=retired level=2：
    n_train=84, n_val=28,
    BAC=0.463, F1=0.000, AUC=0.926,
    Regret=0.054, BND_ratio=0.107, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.161，threshold_source=val
[INFO][BT][2026-03-26 18:51:20] 桶 bucket_id=L1_age=40-50|L2_job=retired：
    parent_id=L1_age=40-50，parent_Score=0.389, bucket_Score=-0.161,
    Gain=-0.549, is_weak=True
【INFO】【2026-03-26 18:51:21】【阈值】桶 L1_age=40-50|L2_job=self_emp（n_val=160，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:51:21] 桶 bucket_id=L1_age=40-50|L2_job=self_emp level=2：
    n_train=205, n_val=160,
    BAC=0.683, F1=0.571, AUC=0.944,
    Regret=0.092, BND_ratio=0.075, POS_coverage=0.044,
    Score(f1_regret_bnd )=0.404，threshold_source=val
[INFO][BT][2026-03-26 18:51:21] 桶 bucket_id=L1_age=40-50|L2_job=self_emp：
    parent_id=L1_age=40-50，parent_Score=0.389, bucket_Score=0.404,
    Gain=+0.016, is_weak=False
【INFO】【2026-03-26 18:51:21】【阈值】桶 L1_age=40-50|L2_job=unknown 标记为弱桶，阈值将回退使用 L1_age=40-50 的阈值
[INFO][BT][2026-03-26 18:51:21] 桶 bucket_id=L1_age=40-50|L2_job=unknown level=2：
    n_train=74, n_val=29,
    BAC=0.500, F1=0.000, AUC=0.778,
    Regret=0.138, BND_ratio=0.000, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.138，threshold_source=val
[INFO][BT][2026-03-26 18:51:21] 桶 bucket_id=L1_age=40-50|L2_job=unknown：
    parent_id=L1_age=40-50，parent_Score=0.389, bucket_Score=-0.138,
    Gain=-0.526, is_weak=True
【INFO】【2026-03-26 18:51:21】【阈值】桶 L1_age=40-50|L2_job=white_collar（n_val=567，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:51:21] 桶 bucket_id=L1_age=40-50|L2_job=white_collar level=2：
    n_train=1170, n_val=567,
    BAC=0.777, F1=0.617, AUC=0.939,
    Regret=0.102, BND_ratio=0.058, POS_coverage=0.123,
    Score(f1_regret_bnd )=0.456，threshold_source=val
[INFO][BT][2026-03-26 18:51:21] 桶 bucket_id=L1_age=40-50|L2_job=white_collar：
    parent_id=L1_age=40-50，parent_Score=0.389, bucket_Score=0.456,
    Gain=+0.068, is_weak=False
【INFO】【2026-03-26 18:51:21】【阈值】桶 L1_age=50-60|L2_job=blue_collar（n_val=280，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:51:21] 桶 bucket_id=L1_age=50-60|L2_job=blue_collar level=2：
    n_train=509, n_val=280,
    BAC=0.862, F1=0.762, AUC=0.983,
    Regret=0.043, BND_ratio=0.029, POS_coverage=0.075,
    Score(f1_regret_bnd )=0.690，threshold_source=val
[INFO][BT][2026-03-26 18:51:21] 桶 bucket_id=L1_age=50-60|L2_job=blue_collar：
    parent_id=L1_age=50-60，parent_Score=0.553, bucket_Score=0.690,
    Gain=+0.138, is_weak=False
【INFO】【2026-03-26 18:51:22】【阈值】桶 L1_age=50-60|L2_job=no_income 标记为弱桶，阈值将回退使用 L1_age=50-60 的阈值
[INFO][BT][2026-03-26 18:51:22] 桶 bucket_id=L1_age=50-60|L2_job=no_income level=2：
    n_train=97, n_val=79,
    BAC=0.789, F1=0.733, AUC=0.951,
    Regret=0.120, BND_ratio=0.114, POS_coverage=0.190,
    Score(f1_regret_bnd )=0.499，threshold_source=val
[INFO][BT][2026-03-26 18:51:22] 桶 bucket_id=L1_age=50-60|L2_job=no_income：
    parent_id=L1_age=50-60，parent_Score=0.553, bucket_Score=0.499,
    Gain=-0.054, is_weak=True
【INFO】【2026-03-26 18:51:22】【阈值】桶 L1_age=50-60|L2_job=retired 标记为弱桶，阈值将回退使用 L1_age=50-60 的阈值
[INFO][BT][2026-03-26 18:51:22] 桶 bucket_id=L1_age=50-60|L2_job=retired level=2：
    n_train=314, n_val=134,
    BAC=0.756, F1=0.667, AUC=0.929,
    Regret=0.116, BND_ratio=0.119, POS_coverage=0.134,
    Score(f1_regret_bnd )=0.432，threshold_source=val
[INFO][BT][2026-03-26 18:51:22] 桶 bucket_id=L1_age=50-60|L2_job=retired：
    parent_id=L1_age=50-60，parent_Score=0.553, bucket_Score=0.432,
    Gain=-0.121, is_weak=True
【INFO】【2026-03-26 18:51:22】【阈值】桶 L1_age=50-60|L2_job=self_emp 标记为弱桶，阈值将回退使用 L1_age=50-60 的阈值
[INFO][BT][2026-03-26 18:51:22] 桶 bucket_id=L1_age=50-60|L2_job=self_emp level=2：
    n_train=150, n_val=181,
    BAC=0.691, F1=0.533, AUC=0.950,
    Regret=0.073, BND_ratio=0.011, POS_coverage=0.028,
    Score(f1_regret_bnd )=0.449，threshold_source=val
[INFO][BT][2026-03-26 18:51:22] 桶 bucket_id=L1_age=50-60|L2_job=self_emp：
    parent_id=L1_age=50-60，parent_Score=0.553, bucket_Score=0.449,
    Gain=-0.104, is_weak=True
【INFO】【2026-03-26 18:51:23】【阈值】桶 L1_age=50-60|L2_job=white_collar 标记为弱桶，阈值将回退使用 L1_age=50-60 的阈值
[INFO][BT][2026-03-26 18:51:23] 桶 bucket_id=L1_age=50-60|L2_job=white_collar level=2：
    n_train=700, n_val=326,
    BAC=0.677, F1=0.584, AUC=0.910,
    Regret=0.158, BND_ratio=0.153, POS_coverage=0.126,
    Score(f1_regret_bnd )=0.273，threshold_source=val
[INFO][BT][2026-03-26 18:51:23] 桶 bucket_id=L1_age=50-60|L2_job=white_collar：
    parent_id=L1_age=50-60，parent_Score=0.553, bucket_Score=0.273,
    Gain=-0.280, is_weak=True
【INFO】【2026-03-26 18:51:23】【阈值】桶 L1_age=50-60|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=50-60 的阈值
[INFO][BT][2026-03-26 18:51:23] 桶 bucket_id=L1_age=50-60|L2_job=others level=2：
    n_train=71, n_val=22,
    BAC=0.790, F1=0.762, AUC=0.969,
    Regret=0.075, BND_ratio=0.140, POS_coverage=0.108,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:51:23] 桶 bucket_id=L1_age=50-60|L2_job=others：
    parent_id=L1_age=50-60，parent_Score=0.553, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:51:23】【阈值】桶 L1_age=<=30|L2_job=blue_collar（n_val=214，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:51:23] 桶 bucket_id=L1_age=<=30|L2_job=blue_collar level=2：
    n_train=550, n_val=214,
    BAC=0.740, F1=0.596, AUC=0.943,
    Regret=0.103, BND_ratio=0.121, POS_coverage=0.117,
    Score(f1_regret_bnd )=0.371，threshold_source=val
[INFO][BT][2026-03-26 18:51:23] 桶 bucket_id=L1_age=<=30|L2_job=blue_collar：
    parent_id=L1_age=<=30，parent_Score=0.340, bucket_Score=0.371,
    Gain=+0.031, is_weak=False
【INFO】【2026-03-26 18:51:24】【阈值】桶 L1_age=<=30|L2_job=no_income（n_val=134，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:51:24] 桶 bucket_id=L1_age=<=30|L2_job=no_income level=2：
    n_train=252, n_val=134,
    BAC=0.822, F1=0.742, AUC=0.896,
    Regret=0.142, BND_ratio=0.097, POS_coverage=0.269,
    Score(f1_regret_bnd )=0.503，threshold_source=val
[INFO][BT][2026-03-26 18:51:24] 桶 bucket_id=L1_age=<=30|L2_job=no_income：
    parent_id=L1_age=<=30，parent_Score=0.340, bucket_Score=0.503,
    Gain=+0.163, is_weak=False
【INFO】【2026-03-26 18:51:24】【阈值】桶 L1_age=<=30|L2_job=self_emp（n_val=118，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:51:24] 桶 bucket_id=L1_age=<=30|L2_job=self_emp level=2：
    n_train=127, n_val=118,
    BAC=0.842, F1=0.774, AUC=0.951,
    Regret=0.123, BND_ratio=0.093, POS_coverage=0.305,
    Score(f1_regret_bnd )=0.558，threshold_source=val
[INFO][BT][2026-03-26 18:51:24] 桶 bucket_id=L1_age=<=30|L2_job=self_emp：
    parent_id=L1_age=<=30，parent_Score=0.340, bucket_Score=0.558,
    Gain=+0.218, is_weak=False
【INFO】【2026-03-26 18:51:24】【阈值】桶 L1_age=<=30|L2_job=white_collar（n_val=317，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:51:24] 桶 bucket_id=L1_age=<=30|L2_job=white_collar level=2：
    n_train=748, n_val=317,
    BAC=0.763, F1=0.609, AUC=0.903,
    Regret=0.140, BND_ratio=0.047, POS_coverage=0.151,
    Score(f1_regret_bnd )=0.421，threshold_source=val
[INFO][BT][2026-03-26 18:51:24] 桶 bucket_id=L1_age=<=30|L2_job=white_collar：
    parent_id=L1_age=<=30，parent_Score=0.340, bucket_Score=0.421,
    Gain=+0.081, is_weak=False
【INFO】【2026-03-26 18:51:24】【阈值】桶 L1_age=<=30|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=<=30 的阈值
[INFO][BT][2026-03-26 18:51:24] 桶 bucket_id=L1_age=<=30|L2_job=others level=2：
    n_train=18, n_val=5,
    BAC=0.822, F1=0.857, AUC=0.987,
    Regret=0.065, BND_ratio=0.130, POS_coverage=0.130,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:51:24] 桶 bucket_id=L1_age=<=30|L2_job=others：
    parent_id=L1_age=<=30，parent_Score=0.340, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:51:25】【阈值】桶 L1_age=>60|L2_job=retired（n_val=133，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:51:25] 桶 bucket_id=L1_age=>60|L2_job=retired level=2：
    n_train=193, n_val=133,
    BAC=0.612, F1=0.729, AUC=0.804,
    Regret=0.278, BND_ratio=0.211, POS_coverage=0.534,
    Score(f1_regret_bnd )=0.240，threshold_source=val
[INFO][BT][2026-03-26 18:51:25] 桶 bucket_id=L1_age=>60|L2_job=retired：
    parent_id=L1_age=>60，parent_Score=0.054, bucket_Score=0.240,
    Gain=+0.186, is_weak=False
【INFO】【2026-03-26 18:51:25】【阈值】桶 L1_age=>60|L2_job=white_collar（n_val=49，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 18:51:25] 桶 bucket_id=L1_age=>60|L2_job=white_collar level=2：
    n_train=111, n_val=49,
    BAC=0.625, F1=0.745, AUC=0.778,
    Regret=0.270, BND_ratio=0.184, POS_coverage=0.571,
    Score(f1_regret_bnd )=0.291，threshold_source=val
[INFO][BT][2026-03-26 18:51:25] 桶 bucket_id=L1_age=>60|L2_job=white_collar：
    parent_id=L1_age=>60，parent_Score=0.054, bucket_Score=0.291,
    Gain=+0.237, is_weak=False
【INFO】【2026-03-26 18:51:25】【阈值】桶 L1_age=>60|L2_job=others 标记为弱桶，阈值将回退使用 L1_age=>60 的阈值
[INFO][BT][2026-03-26 18:51:25] 桶 bucket_id=L1_age=>60|L2_job=others level=2：
    n_train=111, n_val=42,
    BAC=0.616, F1=0.746, AUC=0.880,
    Regret=0.243, BND_ratio=0.281, POS_coverage=0.438,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:51:25] 桶 bucket_id=L1_age=>60|L2_job=others：
    parent_id=L1_age=>60，parent_Score=0.054, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:51:26】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=cellular 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=blue_collar 的阈值
[INFO][BT][2026-03-26 18:51:26] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular level=3：
    n_train=2386, n_val=994,
    BAC=0.730, F1=0.569, AUC=0.933,
    Regret=0.107, BND_ratio=0.072, POS_coverage=0.098,
    Score(f1_regret_bnd )=0.389，threshold_source=val
[INFO][BT][2026-03-26 18:51:26] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.474, bucket_Score=0.389,
    Gain=-0.085, is_weak=True
【INFO】【2026-03-26 18:51:26】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=telephone（n_val=75，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:51:26] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone level=3：
    n_train=187, n_val=75,
    BAC=0.965, F1=0.889, AUC=0.986,
    Regret=0.023, BND_ratio=0.053, POS_coverage=0.067,
    Score(f1_regret_bnd )=0.812，threshold_source=val
[INFO][BT][2026-03-26 18:51:26] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.474, bucket_Score=0.812,
    Gain=+0.339, is_weak=False
【INFO】【2026-03-26 18:51:26】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=unknown 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=blue_collar 的阈值
[INFO][BT][2026-03-26 18:51:26] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown level=3：
    n_train=1660, n_val=739,
    BAC=0.605, F1=0.409, AUC=0.939,
    Regret=0.060, BND_ratio=0.087, POS_coverage=0.016,
    Score(f1_regret_bnd )=0.263，threshold_source=val
[INFO][BT][2026-03-26 18:51:26] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=0.474, bucket_Score=0.263,
    Gain=-0.211, is_weak=True
【INFO】【2026-03-26 18:51:26】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=cellular 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=no_income 的阈值
[INFO][BT][2026-03-26 18:51:26] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular level=3：
    n_train=298, n_val=134,
    BAC=0.712, F1=0.654, AUC=0.902,
    Regret=0.164, BND_ratio=0.179, POS_coverage=0.201,
    Score(f1_regret_bnd )=0.311，threshold_source=val
[INFO][BT][2026-03-26 18:51:26] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.449, bucket_Score=0.311,
    Gain=-0.138, is_weak=True
【INFO】【2026-03-26 18:51:27】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=unknown（n_val=43，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:51:27] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown level=3：
    n_train=120, n_val=43,
    BAC=0.950, F1=0.857, AUC=0.983,
    Regret=0.035, BND_ratio=0.070, POS_coverage=0.093,
    Score(f1_regret_bnd )=0.752，threshold_source=val
[INFO][BT][2026-03-26 18:51:27] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.449, bucket_Score=0.752,
    Gain=+0.304, is_weak=False
【INFO】【2026-03-26 18:51:27】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=others 标记为弱桶，阈值将回退使用 L1_age=30-40|L2_job=no_income 的阈值
[INFO][BT][2026-03-26 18:51:27] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others level=3：
    n_train=29, n_val=11,
    BAC=0.760, F1=0.727, AUC=0.971,
    Regret=0.094, BND_ratio=0.150, POS_coverage=0.125,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:51:27] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=0.449, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 18:51:27】【阈值】桶 L1_age=30-40|L2_job=self_emp|L3_contact=cellular（n_val=259，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:51:27] 桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular level=3：
    n_train=576, n_val=259,
    BAC=0.789, F1=0.732, AUC=0.939,
    Regret=0.101, BND_ratio=0.127, POS_coverage=0.139,
    Score(f1_regret_bnd )=0.504，threshold_source=val

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [18:51:54] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 18:51:54】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=45211
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="30-40"，n_samples=17687
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="40-50"，n_samples=11239
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="50-60"，n_samples=8067
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=<=30，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule="<=30"，n_samples=7030
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=>60，level=1，parent_id=ROOT，split_name=L1_age，split_type=numeric_bin，split_rule=">60"，n_samples=1188
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=6041
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=635
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=1185
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=9739
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40|L2_job=others，level=2，parent_id=L1_age=30-40，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=87
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=4221
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=359
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50|L2_job=retired，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="retired"，n_samples=112
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=873
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50|L2_job=unknown，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="unknown"，n_samples=103
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar，level=2，parent_id=L1_age=40-50，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=5571
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=2453
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=265
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=retired，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="retired"，n_samples=1237
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=588
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=3431
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=others，level=2，parent_id=L1_age=50-60，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=93
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="blue_collar"，n_samples=2327
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="no_income"，n_samples=972
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="self_emp"，n_samples=383
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=3325
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=<=30|L2_job=others，level=2，parent_id=L1_age=<=30，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=23
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=>60|L2_job=retired，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="retired"，n_samples=875
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="white_collar"，n_samples=160
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=>60|L2_job=others，level=2，parent_id=L1_age=>60，split_name=L2_job，split_type=categorical_group，split_rule="others"，n_samples=153
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=3380
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=262
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=2399
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=432
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=163
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=30-40|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=40
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=835
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=310
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=30-40|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=40
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=7237
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=295
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=30-40|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=30-40|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=2207
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=2319
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=314
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1588
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=238
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=40-50|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=121
[INFO][BT][2026-03-26 18:51:55] 桶 bucket_id=L1_age=40-50|L2_job=retired 不再细分：3 个子桶样本数不足 min_bucket_size=100
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=554
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=255
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=40-50|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=64
[INFO][BT][2026-03-26 18:51:55] 桶 bucket_id=L1_age=40-50|L2_job=unknown 不再细分：3 个子桶样本数不足 min_bucket_size=100
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=3747
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=315
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=40-50|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=40-50|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=1509
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1316
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=telephone，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=289
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=848
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=179
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=86
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=722
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=telephone，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=114
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=retired|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=401
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=345
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=185
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=50-60|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=58
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=2207
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=telephone，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=345
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=50-60|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=50-60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=879
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=1336
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=895
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=<=30|L2_job=blue_collar|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=blue_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=96
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=733
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=144
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=<=30|L2_job=no_income|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=no_income，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=95
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=283
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=<=30|L2_job=self_emp|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=self_emp，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=100
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=2434
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=unknown，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="unknown"，n_samples=794
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=<=30|L2_job=white_collar|L3_contact=others，level=3，parent_id=L1_age=<=30|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=97
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=cellular，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=583
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=telephone，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="telephone"，n_samples=281
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=>60|L2_job=retired|L3_contact=others，level=3，parent_id=L1_age=>60|L2_job=retired，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=11
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar|L3_contact=cellular，level=3，parent_id=L1_age=>60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="cellular"，n_samples=131
[INFO][BT][2026-03-26 18:51:55] 创建桶 bucket_id=L1_age=>60|L2_job=white_collar|L3_contact=others，level=3，parent_id=L1_age=>60|L2_job=white_collar，split_name=L3_contact，split_type=categorical_group，split_rule="others"，n_samples=29
[INFO][BT][2026-03-26 18:51:59] 桶树构建完成：总桶数=84，最大层数=3，叶子桶数=59
【INFO】【2026-03-26 18:51:59】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 18:51:59】【阈值】桶 ROOT（n_val=4066，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:51:59] 桶 bucket_id=ROOT level=0：
    n_train=9491, n_val=4066,
    BAC=0.746, F1=0.610, AUC=0.932,
    Regret=0.116, BND_ratio=0.077, POS_coverage=0.114,
    Score(f1_regret_bnd )=nan，threshold_source=val
【INFO】【2026-03-26 18:52:00】【阈值】桶 L1_age=30-40（n_val=1614，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:52:00] 桶 bucket_id=L1_age=30-40 level=1：
    n_train=3749, n_val=1614,
    BAC=0.781, F1=0.638, AUC=0.933,
    Regret=0.109, BND_ratio=0.104, POS_coverage=0.139,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:00] 桶 bucket_id=L1_age=30-40：
    parent_id=ROOT，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:00】【阈值】桶 L1_age=40-50（n_val=1043，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:52:00] 桶 bucket_id=L1_age=40-50 level=1：
    n_train=2475, n_val=1043,
    BAC=0.724, F1=0.561, AUC=0.926,
    Regret=0.106, BND_ratio=0.066, POS_coverage=0.087,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:00] 桶 bucket_id=L1_age=40-50：
    parent_id=ROOT，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:00】【阈值】桶 L1_age=50-60（n_val=822，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:52:00] 桶 bucket_id=L1_age=50-60 level=1：
    n_train=1714, n_val=822,
    BAC=0.856, F1=0.697, AUC=0.955,
    Regret=0.089, BND_ratio=0.055, POS_coverage=0.172,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:00] 桶 bucket_id=L1_age=50-60：
    parent_id=ROOT，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:01】【阈值】桶 L1_age=<=30（n_val=611，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:52:01] 桶 bucket_id=L1_age=<=30 level=1：
    n_train=1510, n_val=611,
    BAC=0.725, F1=0.663, AUC=0.914,
    Regret=0.150, BND_ratio=0.173, POS_coverage=0.178,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:01] 桶 bucket_id=L1_age=<=30：
    parent_id=ROOT，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:01】【阈值】桶 L1_age=>60（n_val=166，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 18:52:01] 桶 bucket_id=L1_age=>60 level=1：
    n_train=253, n_val=166,
    BAC=0.536, F1=0.658, AUC=0.772,
    Regret=0.321, BND_ratio=0.283, POS_coverage=0.506,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:01] 桶 bucket_id=L1_age=>60：
    parent_id=ROOT，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:01】【阈值】桶 L1_age=30-40|L2_job=blue_collar（n_val=594，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:52:01] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar level=2：
    n_train=1269, n_val=594,
    BAC=0.788, F1=0.633, AUC=0.950,
    Regret=0.073, BND_ratio=0.086, POS_coverage=0.089,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:01] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar：
    parent_id=L1_age=30-40，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:02】【阈值】桶 L1_age=30-40|L2_job=no_income（n_val=94，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:52:02] 桶 bucket_id=L1_age=30-40|L2_job=no_income level=2：
    n_train=154, n_val=94,
    BAC=0.772, F1=0.667, AUC=0.913,
    Regret=0.122, BND_ratio=0.096, POS_coverage=0.149,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:02] 桶 bucket_id=L1_age=30-40|L2_job=no_income：
    parent_id=L1_age=30-40，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:02】【阈值】桶 L1_age=30-40|L2_job=self_emp（n_val=181，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:52:02] 桶 bucket_id=L1_age=30-40|L2_job=self_emp level=2：
    n_train=264, n_val=181,
    BAC=0.810, F1=0.643, AUC=0.969,
    Regret=0.066, BND_ratio=0.099, POS_coverage=0.088,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:02] 桶 bucket_id=L1_age=30-40|L2_job=self_emp：
    parent_id=L1_age=30-40，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:02】【阈值】桶 L1_age=30-40|L2_job=white_collar（n_val=938，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:52:02] 桶 bucket_id=L1_age=30-40|L2_job=white_collar level=2：
    n_train=2038, n_val=938,
    BAC=0.733, F1=0.584, AUC=0.918,
    Regret=0.116, BND_ratio=0.079, POS_coverage=0.110,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:02] 桶 bucket_id=L1_age=30-40|L2_job=white_collar：
    parent_id=L1_age=30-40，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:02】【阈值】桶 L1_age=30-40|L2_job=others（n_val=27，source=all) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:52:02] 桶 bucket_id=L1_age=30-40|L2_job=others level=2：
    n_train=60, n_val=27,
    BAC=0.897, F1=0.800, AUC=0.995,
    Regret=0.037, BND_ratio=0.046, POS_coverage=0.092,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:52:02] 桶 bucket_id=L1_age=30-40|L2_job=others：
    parent_id=L1_age=30-40，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:03】【阈值】桶 L1_age=40-50|L2_job=blue_collar（n_val=376，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:52:03] 桶 bucket_id=L1_age=40-50|L2_job=blue_collar level=2：
    n_train=888, n_val=376,
    BAC=0.848, F1=0.676, AUC=0.960,
    Regret=0.068, BND_ratio=0.056, POS_coverage=0.104,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:03] 桶 bucket_id=L1_age=40-50|L2_job=blue_collar：
    parent_id=L1_age=40-50，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:03】【阈值】桶 L1_age=40-50|L2_job=no_income（n_val=101，source=val) 使用本地阈值 α=0.6000, β=0.1000
[INFO][BT][2026-03-26 18:52:03] 桶 bucket_id=L1_age=40-50|L2_job=no_income level=2：
    n_train=141, n_val=101,
    BAC=0.605, F1=0.609, AUC=0.917,
    Regret=0.149, BND_ratio=0.277, POS_coverage=0.079,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:03] 桶 bucket_id=L1_age=40-50|L2_job=no_income：
    parent_id=L1_age=40-50，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:03】【阈值】桶 L1_age=40-50|L2_job=retired（n_val=28，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 18:52:03] 桶 bucket_id=L1_age=40-50|L2_job=retired level=2：
    n_train=84, n_val=28,
    BAC=0.463, F1=0.000, AUC=0.926,
    Regret=0.054, BND_ratio=0.107, POS_coverage=0.000,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:03] 桶 bucket_id=L1_age=40-50|L2_job=retired：
    parent_id=L1_age=40-50，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:04】【阈值】桶 L1_age=40-50|L2_job=self_emp（n_val=160，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:52:04] 桶 bucket_id=L1_age=40-50|L2_job=self_emp level=2：
    n_train=205, n_val=160,
    BAC=0.683, F1=0.571, AUC=0.944,
    Regret=0.092, BND_ratio=0.075, POS_coverage=0.044,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:04] 桶 bucket_id=L1_age=40-50|L2_job=self_emp：
    parent_id=L1_age=40-50，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:04】【阈值】桶 L1_age=40-50|L2_job=unknown（n_val=29，source=val) 使用本地阈值 α=0.9000, β=0.8000
[INFO][BT][2026-03-26 18:52:04] 桶 bucket_id=L1_age=40-50|L2_job=unknown level=2：
    n_train=74, n_val=29,
    BAC=0.500, F1=0.000, AUC=0.778,
    Regret=0.138, BND_ratio=0.000, POS_coverage=0.000,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:04] 桶 bucket_id=L1_age=40-50|L2_job=unknown：
    parent_id=L1_age=40-50，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:04】【阈值】桶 L1_age=40-50|L2_job=white_collar（n_val=567，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:52:04] 桶 bucket_id=L1_age=40-50|L2_job=white_collar level=2：
    n_train=1170, n_val=567,
    BAC=0.777, F1=0.617, AUC=0.939,
    Regret=0.102, BND_ratio=0.058, POS_coverage=0.123,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:04] 桶 bucket_id=L1_age=40-50|L2_job=white_collar：
    parent_id=L1_age=40-50，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:04】【阈值】桶 L1_age=50-60|L2_job=blue_collar（n_val=280，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:52:04] 桶 bucket_id=L1_age=50-60|L2_job=blue_collar level=2：
    n_train=509, n_val=280,
    BAC=0.862, F1=0.762, AUC=0.983,
    Regret=0.043, BND_ratio=0.029, POS_coverage=0.075,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:04] 桶 bucket_id=L1_age=50-60|L2_job=blue_collar：
    parent_id=L1_age=50-60，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:05】【阈值】桶 L1_age=50-60|L2_job=no_income（n_val=79，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:52:05] 桶 bucket_id=L1_age=50-60|L2_job=no_income level=2：
    n_train=97, n_val=79,
    BAC=0.789, F1=0.733, AUC=0.951,
    Regret=0.120, BND_ratio=0.114, POS_coverage=0.190,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:05] 桶 bucket_id=L1_age=50-60|L2_job=no_income：
    parent_id=L1_age=50-60，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:05】【阈值】桶 L1_age=50-60|L2_job=retired（n_val=134，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:52:05] 桶 bucket_id=L1_age=50-60|L2_job=retired level=2：
    n_train=314, n_val=134,
    BAC=0.756, F1=0.667, AUC=0.929,
    Regret=0.116, BND_ratio=0.119, POS_coverage=0.134,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:05] 桶 bucket_id=L1_age=50-60|L2_job=retired：
    parent_id=L1_age=50-60，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:05】【阈值】桶 L1_age=50-60|L2_job=self_emp（n_val=181，source=val) 使用本地阈值 α=0.6000, β=0.5000
[INFO][BT][2026-03-26 18:52:05] 桶 bucket_id=L1_age=50-60|L2_job=self_emp level=2：
    n_train=150, n_val=181,
    BAC=0.691, F1=0.533, AUC=0.950,
    Regret=0.073, BND_ratio=0.011, POS_coverage=0.028,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:05] 桶 bucket_id=L1_age=50-60|L2_job=self_emp：
    parent_id=L1_age=50-60，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:06】【阈值】桶 L1_age=50-60|L2_job=white_collar（n_val=326，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:52:06] 桶 bucket_id=L1_age=50-60|L2_job=white_collar level=2：
    n_train=700, n_val=326,
    BAC=0.677, F1=0.584, AUC=0.910,
    Regret=0.158, BND_ratio=0.153, POS_coverage=0.126,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:06] 桶 bucket_id=L1_age=50-60|L2_job=white_collar：
    parent_id=L1_age=50-60，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:06】【阈值】桶 L1_age=50-60|L2_job=others（n_val=22，source=all) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 18:52:06] 桶 bucket_id=L1_age=50-60|L2_job=others level=2：
    n_train=71, n_val=22,
    BAC=0.790, F1=0.762, AUC=0.969,
    Regret=0.075, BND_ratio=0.140, POS_coverage=0.108,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:52:06] 桶 bucket_id=L1_age=50-60|L2_job=others：
    parent_id=L1_age=50-60，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:06】【阈值】桶 L1_age=<=30|L2_job=blue_collar（n_val=214，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:52:06] 桶 bucket_id=L1_age=<=30|L2_job=blue_collar level=2：
    n_train=550, n_val=214,
    BAC=0.740, F1=0.596, AUC=0.943,
    Regret=0.103, BND_ratio=0.121, POS_coverage=0.117,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:06] 桶 bucket_id=L1_age=<=30|L2_job=blue_collar：
    parent_id=L1_age=<=30，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:06】【阈值】桶 L1_age=<=30|L2_job=no_income（n_val=134，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:52:06] 桶 bucket_id=L1_age=<=30|L2_job=no_income level=2：
    n_train=252, n_val=134,
    BAC=0.822, F1=0.742, AUC=0.896,
    Regret=0.142, BND_ratio=0.097, POS_coverage=0.269,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:06] 桶 bucket_id=L1_age=<=30|L2_job=no_income：
    parent_id=L1_age=<=30，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:07】【阈值】桶 L1_age=<=30|L2_job=self_emp（n_val=118，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 18:52:07] 桶 bucket_id=L1_age=<=30|L2_job=self_emp level=2：
    n_train=127, n_val=118,
    BAC=0.842, F1=0.774, AUC=0.951,
    Regret=0.123, BND_ratio=0.093, POS_coverage=0.305,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:07] 桶 bucket_id=L1_age=<=30|L2_job=self_emp：
    parent_id=L1_age=<=30，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:07】【阈值】桶 L1_age=<=30|L2_job=white_collar（n_val=317，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:52:07] 桶 bucket_id=L1_age=<=30|L2_job=white_collar level=2：
    n_train=748, n_val=317,
    BAC=0.763, F1=0.609, AUC=0.903,
    Regret=0.140, BND_ratio=0.047, POS_coverage=0.151,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:07] 桶 bucket_id=L1_age=<=30|L2_job=white_collar：
    parent_id=L1_age=<=30，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:07】【阈值】桶 L1_age=<=30|L2_job=others（n_val=5，source=all) 使用本地阈值 α=0.5000, β=0.3000
[INFO][BT][2026-03-26 18:52:07] 桶 bucket_id=L1_age=<=30|L2_job=others level=2：
    n_train=18, n_val=5,
    BAC=0.822, F1=0.857, AUC=0.987,
    Regret=0.065, BND_ratio=0.130, POS_coverage=0.130,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:52:07] 桶 bucket_id=L1_age=<=30|L2_job=others：
    parent_id=L1_age=<=30，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:07】【阈值】桶 L1_age=>60|L2_job=retired（n_val=133，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:52:07] 桶 bucket_id=L1_age=>60|L2_job=retired level=2：
    n_train=193, n_val=133,
    BAC=0.612, F1=0.729, AUC=0.804,
    Regret=0.278, BND_ratio=0.211, POS_coverage=0.534,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:07] 桶 bucket_id=L1_age=>60|L2_job=retired：
    parent_id=L1_age=>60，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:08】【阈值】桶 L1_age=>60|L2_job=white_collar（n_val=49，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 18:52:08] 桶 bucket_id=L1_age=>60|L2_job=white_collar level=2：
    n_train=111, n_val=49,
    BAC=0.625, F1=0.745, AUC=0.778,
    Regret=0.270, BND_ratio=0.184, POS_coverage=0.571,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:08] 桶 bucket_id=L1_age=>60|L2_job=white_collar：
    parent_id=L1_age=>60，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:08】【阈值】桶 L1_age=>60|L2_job=others（n_val=42，source=all) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 18:52:08] 桶 bucket_id=L1_age=>60|L2_job=others level=2：
    n_train=111, n_val=42,
    BAC=0.616, F1=0.746, AUC=0.880,
    Regret=0.243, BND_ratio=0.281, POS_coverage=0.438,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:52:08] 桶 bucket_id=L1_age=>60|L2_job=others：
    parent_id=L1_age=>60，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:08】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=cellular（n_val=994，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:52:08] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular level=3：
    n_train=2386, n_val=994,
    BAC=0.730, F1=0.569, AUC=0.933,
    Regret=0.107, BND_ratio=0.072, POS_coverage=0.098,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:08] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:09】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=telephone（n_val=75，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:52:09] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone level=3：
    n_train=187, n_val=75,
    BAC=0.965, F1=0.889, AUC=0.986,
    Regret=0.023, BND_ratio=0.053, POS_coverage=0.067,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:09] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=telephone：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:09】【阈值】桶 L1_age=30-40|L2_job=blue_collar|L3_contact=unknown（n_val=739，source=val) 使用本地阈值 α=0.6000, β=0.1000
[INFO][BT][2026-03-26 18:52:09] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown level=3：
    n_train=1660, n_val=739,
    BAC=0.605, F1=0.409, AUC=0.939,
    Regret=0.060, BND_ratio=0.087, POS_coverage=0.016,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:09] 桶 bucket_id=L1_age=30-40|L2_job=blue_collar|L3_contact=unknown：
    parent_id=L1_age=30-40|L2_job=blue_collar，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:09】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=cellular（n_val=134，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 18:52:09] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular level=3：
    n_train=298, n_val=134,
    BAC=0.712, F1=0.654, AUC=0.902,
    Regret=0.164, BND_ratio=0.179, POS_coverage=0.201,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:09] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=cellular：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:09】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=unknown（n_val=43，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 18:52:09] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown level=3：
    n_train=120, n_val=43,
    BAC=0.950, F1=0.857, AUC=0.983,
    Regret=0.035, BND_ratio=0.070, POS_coverage=0.093,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 18:52:09] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=unknown：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:10】【阈值】桶 L1_age=30-40|L2_job=no_income|L3_contact=others（n_val=11，source=all) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 18:52:10] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others level=3：
    n_train=29, n_val=11,
    BAC=0.760, F1=0.727, AUC=0.971,
    Regret=0.094, BND_ratio=0.150, POS_coverage=0.125,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 18:52:10] 桶 bucket_id=L1_age=30-40|L2_job=no_income|L3_contact=others：
    parent_id=L1_age=30-40|L2_job=no_income，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 18:52:10】【阈值】桶 L1_age=30-40|L2_job=self_emp|L3_contact=cellular（n_val=259，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 18:52:10] 桶 bucket_id=L1_age=30-40|L2_job=self_emp|L3_contact=cellular level=3：
    n_train=576, n_val=259,
    BAC=0.789, F1=0.732, AUC=0.939,
    Regret=0.101, BND_ratio=0.127, POS_coverage=0.139,
    Score(f1_regret_bnd )=nan，threshold_source=val

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\tsne_visualizer.py:389: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  fig.tight_layout()

【INFO】【2026-03-26 18:52:44】[t-SNE] Comparison figure saved to: e:\yan\组\三支决策\机器学习\BT_TWD\results\bank_bttwd\tsne_fallback\tsne_backoff_bank_full.png
【INFO】【2026-03-26 18:52:44】[t-SNE] Comparison figure saved to: e:\yan\组\三支决策\机器学习\BT_TWD\results\bank_bttwd\tsne_fallback\tsne_backoff_bank_full.pdf
t-SNE 嵌入结果保存路径：e:\yan\组\三支决策\机器学习\BT_TWD\results\bank_bttwd\tsne_fallback\tsne_fallback_embedding.csv
弱桶对比摘要保存路径：e:\yan\组\三支决策\机器学习\BT_TWD\results\bank_bttwd\tsne_fallback\tsne_fallback_summary.csv
可视化图片保存路径：e:\yan\组\三支决策\机器学习\BT_TWD\results\bank_bttwd\tsne_fallback\tsne_backoff_bank_full.png