diabetic 数据集 BT-TWD 可行性实验

本 notebook 按步骤运行：加载配置 → 读取数据 → 预处理 → 桶树划分 → 基线与 BTTWD k 折实验 → 桶级分析。

In [1]:
# 步骤0：环境与路径设置
import os, sys
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif'] = ['Microsoft YaHei']
plt.rcParams['axes.unicode_minus'] = False

# 将项目根目录加入路径，便于导入 bttwdlib
root_path = os.path.abspath(os.path.join(os.getcwd(), '..'))
if root_path not in sys.path:
    sys.path.append(root_path)

from bttwdlib import (
    load_yaml_cfg,
    show_cfg,
    load_dataset,
    prepare_features_and_labels,
    BucketTree,
    run_kfold_experiments,
    log_info,
    set_global_seed,
)

cfg_path = Path(root_path) / "configs" / "diabetic_bttwd.yaml"
cfg = load_yaml_cfg(cfg_path)
set_global_seed(cfg.get('SEED', {}).get('global_seed', 42))
log_info('【步骤0摘要】环境准备完毕，路径与随机种子已设置。')

【INFO】【2026-03-26 16:22:57】【配置加载】已读取 e:\yan\组\三支决策\机器学习\BT_TWD\configs\diabetic_bttwd.yaml
【INFO】【2026-03-26 16:23:01】【步骤0摘要】环境准备完毕，路径与随机种子已设置。

In [2]:
# 步骤1：加载配置
show_cfg(cfg)
log_info('【步骤1摘要】配置文件加载完成，关键参数检查通过。')

【INFO】【2026-03-26 16:23:01】【配置-数据】数据集=diabetic, k折=5, 目标列=readmitted, 正类="<30"
【INFO】【2026-03-26 16:23:01】【配置-BTTWD】阈值模式=bucket_wise, 全局模型=xgb, 桶内模型=none, 后验估计器(兼容字段)=logreg
【INFO】【2026-03-26 16:23:01】【配置-基线】LogReg启用=True, RandomForest启用=True, KNN启用=True, XGBoost启用=True
【INFO】【2026-03-26 16:23:01】【步骤1摘要】配置文件加载完成，关键参数检查通过。

In [3]:
# 步骤2：加载原始数据
df_raw, target_col_model = load_dataset(cfg)  # 这里返回的是用于建模的标签列，例如 "label"

display(df_raw.head())
print("用于建模的标签列:", target_col_model)

# 1）画 0/1 标签（流失/未流失）的比例
class_counts = df_raw[target_col_model].value_counts(normalize=True)
ax = class_counts.plot(kind='bar', title='流失 vs 未流失比例')
plt.ylabel('比例')

fig_path = os.path.join(root_path, cfg['OUTPUT']['figs_dir'], 'class_distribution.png')
os.makedirs(os.path.dirname(fig_path), exist_ok=True)
plt.savefig(fig_path, bbox_inches='tight')
plt.close()

# 2）如果想看原始标签列的分布，可以另外单独分析：
raw_target_col = cfg['DATA']['target_col']  # 这里是原始标签列
print("原始目标列:", raw_target_col)
print(df_raw[raw_target_col].describe())

log_info('【步骤2摘要】Telco Churn 原始数据加载与基本统计完成。')

【INFO】【2026-03-26 16:23:02】【数据加载】文本表格 ..\data\diabetic\diabetic_data.csv 已读取，样本数=101766，列数=50
【INFO】【2026-03-26 16:23:02】【数据加载】标签列 readmitted 已处理完成：dropna_target=False, 丢弃样本=0, 最终样本数=101766, 正类比例=11.16%
【INFO】【2026-03-26 16:23:02】【数据集信息】名称=diabetic，样本数=101766，目标列=readmitted，正类比例=11.16%

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,0
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,0
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,0
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,0
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,0

用于建模的标签列: readmitted
原始目标列: readmitted
count    101766.000000
mean          0.111599
std           0.314874
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: readmitted, dtype: float64
【INFO】【2026-03-26 16:23:02】【步骤2摘要】Telco Churn 原始数据加载与基本统计完成。

In [4]:
# 步骤3：预处理与特征工程
X, y, meta = prepare_features_and_labels(df_raw, cfg)
log_info(f'【预处理】编码特征维度={X.shape[1]}，样本数={X.shape[0]}')
log_info(f"【步骤3摘要】特征预处理完成：连续={len(meta['continuous_cols'])}，类别={len(meta['categorical_cols'])}，编码维度={X.shape[1]}。")

【INFO】【2026-03-26 16:23:02】【预处理】连续特征=8个，类别特征=35个
【INFO】【2026-03-26 16:23:05】【预处理】编码后维度=215
【INFO】【2026-03-26 16:23:05】【预处理】编码特征维度=215，样本数=101766
【INFO】【2026-03-26 16:23:05】【步骤3摘要】特征预处理完成：连续=8，类别=35，编码维度=215。

In [5]:
# 步骤4：构建桶树并检查划分
feature_cols_for_bucket = [c for c in df_raw.columns if c != target_col_model]

bucket_tree = BucketTree(
    cfg['BTTWD']['bucket_levels'],
    feature_names=feature_cols_for_bucket
)

bucket_ids_full = bucket_tree.assign_buckets(df_raw[feature_cols_for_bucket])

bucket_df = bucket_ids_full.value_counts().reset_index()
bucket_df.columns = ['bucket_id', 'count']

bucket_df['pos_rate'] = (
    df_raw.groupby(bucket_ids_full)[target_col_model]
    .apply(lambda s: (s == 1).mean())
    .values
)
display(bucket_df.head())
bucket_df.set_index('bucket_id')['count'].plot(kind='bar', figsize=(12,4), title='桶样本数分布')
fig_bucket = os.path.join(root_path, cfg['OUTPUT']['figs_dir'], 'bucket_metrics_bar.png')
plt.savefig(fig_bucket, bbox_inches='tight')
plt.close()
log_info(f'【步骤4摘要】桶树划分完成，共有 {bucket_ids_full.nunique()} 个叶子桶。')

【INFO】【2026-03-26 16:23:05】【桶树】已为样本生成桶ID，共 45 个组合

                                           bucket_id  count  pos_rate
0  L1_number_inpatient=no_prev_inpt|L2_number_eme...  51675  0.000000
1  L1_number_inpatient=no_prev_inpt|L2_number_eme...  24868  0.241497
2  L1_number_inpatient=no_prev_inpt|L2_number_eme...   6863  0.071429
3  L1_number_inpatient=few_prev_inpt|L2_number_em...   4965  0.157895
4  L1_number_inpatient=few_prev_inpt|L2_number_em...   3819  0.187050

【INFO】【2026-03-26 16:23:07】【步骤4摘要】桶树划分完成，共有 45 个叶子桶。

In [6]:
# 步骤5：运行基线模型 k 折实验
# 基线部分在 run_kfold_experiments 内统一调度
log_info('【步骤5】基线模型将在整体交叉验证中一并运行。')
log_info('【步骤5摘要】基线模型性能将作为后续对比基准。')

【INFO】【2026-03-26 16:23:07】【步骤5】基线模型将在整体交叉验证中一并运行。
【INFO】【2026-03-26 16:23:07】【步骤5摘要】基线模型性能将作为后续对比基准。

In [7]:
import numpy as np
import pandas as pd

print("y 全局标签分布：", np.unique(y, return_counts=True))

print("原始标签列分布：")
print(df_raw[cfg['DATA']['target_col']].value_counts())

y 全局标签分布： (array([0, 1]), array([90409, 11357], dtype=int64))
原始标签列分布：
readmitted
0    90409
1    11357
Name: count, dtype: int64

In [8]:
# 步骤6：运行 BTTWD k 折实验（含基线）
results = run_kfold_experiments(X, y, df_raw.drop(columns=[cfg['DATA']['target_col']]), cfg)
summary_df = pd.read_csv(os.path.join(root_path, cfg['OUTPUT']['results_dir'], 'metrics_kfold_summary.csv'))
display(summary_df)
summary_df.plot(x='model', kind='bar', figsize=(8,4), title='模型指标对比')
fig_compare = os.path.join(root_path, cfg['OUTPUT']['figs_dir'], 'metrics_compare.png')
plt.savefig(fig_compare, bbox_inches='tight')
plt.close()
log_info('【步骤6摘要】BTTWD 与基线的 k 折结果已生成并保存。')

【INFO】【2026-03-26 16:23:07】【基线-LogReg】使用决策阈值=0.300（fixed 模式）

d:\Anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\baselines.py:109: RuntimeWarning: Mean of empty slice
  summary[f"{col}_mean"] = float(np.nanmean(arr))
d:\Anaconda3\Lib\site-packages\numpy\lib\nanfunctions.py:1879: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

【INFO】【2026-03-26 16:24:54】【基线-LogReg】整体指标：AUC_mean=0.669, AUC_std=0.007, BAC_mean=0.530, BAC_std=0.003, BND_ratio_mean=0.000, BND_ratio_std=0.000, F1_mean=0.127, F1_std=0.009, Kappa_mean=0.091, Kappa_std=0.010, MCC_mean=0.123, MCC_std=0.013, POS_Coverage_mean=nan, POS_Coverage_std=nan, Precision_mean=0.358, Precision_std=0.029, Recall_mean=0.077, Recall_std=0.006, Regret_mean=0.427, Regret_std=0.003
【INFO】【2026-03-26 16:24:54】【基线-RF】使用决策阈值=0.300（fixed 模式）

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\baselines.py:109: RuntimeWarning: Mean of empty slice
  summary[f"{col}_mean"] = float(np.nanmean(arr))
d:\Anaconda3\Lib\site-packages\numpy\lib\nanfunctions.py:1879: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

【INFO】【2026-03-26 16:26:21】【基线-RF】整体指标：AUC_mean=0.651, AUC_std=0.007, BAC_mean=0.536, BAC_std=0.002, BND_ratio_mean=0.000, BND_ratio_std=0.000, F1_mean=0.146, F1_std=0.005, Kappa_mean=0.106, Kappa_std=0.005, MCC_mean=0.137, MCC_std=0.006, POS_Coverage_mean=nan, POS_Coverage_std=nan, Precision_mean=0.367, Precision_std=0.013, Recall_mean=0.091, Recall_std=0.003, Regret_mean=0.423, Regret_std=0.002
【INFO】【2026-03-26 16:26:22】【基线-KNN】使用决策阈值=0.300（fixed 模式）

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\baselines.py:109: RuntimeWarning: Mean of empty slice
  summary[f"{col}_mean"] = float(np.nanmean(arr))
d:\Anaconda3\Lib\site-packages\numpy\lib\nanfunctions.py:1879: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

【INFO】【2026-03-26 16:26:47】【基线-KNN】整体指标：AUC_mean=0.568, AUC_std=0.009, BAC_mean=0.545, BAC_std=0.005, BND_ratio_mean=0.000, BND_ratio_std=0.000, F1_mean=0.195, F1_std=0.008, Kappa_mean=0.081, Kappa_std=0.009, MCC_mean=0.081, MCC_std=0.010, POS_Coverage_mean=nan, POS_Coverage_std=nan, Precision_mean=0.175, Precision_std=0.007, Recall_mean=0.221, Recall_std=0.011, Regret_mean=0.464, Regret_std=0.005
【INFO】【2026-03-26 16:26:47】【基线-XGB】使用决策阈值=0.300（fixed 模式）

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:26:48] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:26:49] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:26:52] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:26:54] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:26:57] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\baselines.py:109: RuntimeWarning: Mean of empty slice
  summary[f"{col}_mean"] = float(np.nanmean(arr))
d:\Anaconda3\Lib\site-packages\numpy\lib\nanfunctions.py:1879: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

【INFO】【2026-03-26 16:26:59】【基线-XGB】整体指标：AUC_mean=0.679, AUC_std=0.006, BAC_mean=0.539, BAC_std=0.002, BND_ratio_mean=0.000, BND_ratio_std=0.000, F1_mean=0.157, F1_std=0.006, Kappa_mean=0.117, Kappa_std=0.007, MCC_mean=0.149, MCC_std=0.010, POS_Coverage_mean=nan, POS_Coverage_std=nan, Precision_mean=0.387, Precision_std=0.023, Recall_mean=0.098, Recall_std=0.004, Regret_mean=0.420, Regret_std=0.003
【INFO】【2026-03-26 16:26:59】【K折实验】正在执行第 1/5 折...
【INFO】【2026-03-26 16:26:59】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=0.5

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:27:00] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:27:02】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=81412
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="few_prev_inpt"，n_samples=8719
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="many_prev_inpt"，n_samples=2896
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="no_prev_inpt"，n_samples=69797
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=370
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=7979
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=370
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=417
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=2226
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=253
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=513
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=68280
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=1004
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=227
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=143
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=3969
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="OtherDisp"，n_samples=728
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=3016
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=266
[INFO][BT][2026-03-26 16:27:04] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er 不再细分：5 个子桶样本数不足 min_bucket_size=200
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=288
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=129
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=1115
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=859
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=252
[INFO][BT][2026-03-26 16:27:04] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er 不再细分：5 个子桶样本数不足 min_bucket_size=200
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=350
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=163
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Expired"，n_samples=1023
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=41344
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="OtherDisp"，n_samples=5537
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="SNF_Rehab"，n_samples=444
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=19932
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=555
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=369
[INFO][BT][2026-03-26 16:27:04] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=80
[INFO][BT][2026-03-26 16:27:10] 桶树构建完成：总桶数=34，最大层数=3，叶子桶数=23
【INFO】【2026-03-26 16:27:10】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 16:27:11】【阈值】桶 ROOT（n_val=4884，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:27:11] 桶 bucket_id=ROOT level=0：
    n_train=11397, n_val=4884,
    BAC=0.480, F1=0.081, AUC=0.676,
    Regret=0.394, BND_ratio=0.094, POS_coverage=0.011,
    Score(f1_regret_bnd )=-0.360，threshold_source=val
【INFO】【2026-03-26 16:27:11】【阈值】桶 L1_number_inpatient=few_prev_inpt 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:27:11] 桶 bucket_id=L1_number_inpatient=few_prev_inpt level=1：
    n_train=1219, n_val=704,
    BAC=0.046, F1=0.071, AUC=0.560,
    Regret=0.571, BND_ratio=0.940, POS_coverage=0.014,
    Score(f1_regret_bnd )=-0.970，threshold_source=val
[INFO][BT][2026-03-26 16:27:11] 桶 bucket_id=L1_number_inpatient=few_prev_inpt：
    parent_id=ROOT，parent_Score=-0.360, bucket_Score=-0.970,
    Gain=-0.610, is_weak=True
【INFO】【2026-03-26 16:27:11】【阈值】桶 L1_number_inpatient=many_prev_inpt 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:27:11] 桶 bucket_id=L1_number_inpatient=many_prev_inpt level=1：
    n_train=545, n_val=331,
    BAC=0.250, F1=0.473, AUC=0.648,
    Regret=0.588, BND_ratio=0.650, POS_coverage=0.332,
    Score(f1_regret_bnd )=-0.440，threshold_source=val
[INFO][BT][2026-03-26 16:27:11] 桶 bucket_id=L1_number_inpatient=many_prev_inpt：
    parent_id=ROOT，parent_Score=-0.360, bucket_Score=-0.440,
    Gain=-0.080, is_weak=True
【INFO】【2026-03-26 16:27:12】【阈值】桶 L1_number_inpatient=no_prev_inpt（n_val=4318，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:27:12] 桶 bucket_id=L1_number_inpatient=no_prev_inpt level=1：
    n_train=9770, n_val=4318,
    BAC=0.492, F1=0.038, AUC=0.606,
    Regret=0.361, BND_ratio=0.039, POS_coverage=0.003,
    Score(f1_regret_bnd )=-0.342，threshold_source=val
[INFO][BT][2026-03-26 16:27:12] 桶 bucket_id=L1_number_inpatient=no_prev_inpt：
    parent_id=ROOT，parent_Score=-0.360, bucket_Score=-0.342,
    Gain=+0.018, is_weak=False
【INFO】【2026-03-26 16:27:12】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er（n_val=125，source=val) 使用本地阈值 α=0.5000, β=0.3000
[INFO][BT][2026-03-26 16:27:12] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=245, n_val=125,
    BAC=0.432, F1=0.111, AUC=0.575,
    Regret=0.500, BND_ratio=0.200, POS_coverage=0.008,
    Score(f1_regret_bnd )=-0.489，threshold_source=val
[INFO][BT][2026-03-26 16:27:12] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-0.970, bucket_Score=-0.489,
    Gain=+0.481, is_weak=False
【INFO】【2026-03-26 16:27:12】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er（n_val=527，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:27:12] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=1116, n_val=527,
    BAC=0.115, F1=0.162, AUC=0.605,
    Regret=0.532, BND_ratio=0.848, POS_coverage=0.044,
    Score(f1_regret_bnd )=-0.794，threshold_source=val
[INFO][BT][2026-03-26 16:27:12] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-0.970, bucket_Score=-0.794,
    Gain=+0.176, is_weak=False
【INFO】【2026-03-26 16:27:13】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er（n_val=101，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:27:13] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=269, n_val=101,
    BAC=0.262, F1=0.000, AUC=0.662,
    Regret=0.530, BND_ratio=0.525, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.792，threshold_source=val
[INFO][BT][2026-03-26 16:27:13] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-0.970, bucket_Score=-0.792,
    Gain=+0.178, is_weak=False
【INFO】【2026-03-26 16:27:13】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er（n_val=120，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 16:27:13] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=136, n_val=120,
    BAC=0.326, F1=0.556, AUC=0.612,
    Regret=0.567, BND_ratio=0.483, POS_coverage=0.500,
    Score(f1_regret_bnd )=-0.253，threshold_source=val
[INFO][BT][2026-03-26 16:27:13] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.440, bucket_Score=-0.253,
    Gain=+0.187, is_weak=False
【INFO】【2026-03-26 16:27:13】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:27:13] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=459, n_val=186,
    BAC=0.268, F1=0.384, AUC=0.695,
    Regret=0.548, BND_ratio=0.661, POS_coverage=0.156,
    Score(f1_regret_bnd )=-0.495，threshold_source=val
[INFO][BT][2026-03-26 16:27:13] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.440, bucket_Score=-0.495,
    Gain=-0.056, is_weak=True
【INFO】【2026-03-26 16:27:13】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:27:13] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=175, n_val=78,
    BAC=0.316, F1=0.625, AUC=0.754,
    Regret=0.520, BND_ratio=0.617, POS_coverage=0.375,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:27:13] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.440, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:27:14】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:27:14] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=165, n_val=164,
    BAC=0.157, F1=0.125, AUC=0.549,
    Regret=0.570, BND_ratio=0.738, POS_coverage=0.030,
    Score(f1_regret_bnd )=-0.814，threshold_source=val
[INFO][BT][2026-03-26 16:27:14] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.342, bucket_Score=-0.814,
    Gain=-0.472, is_weak=True
【INFO】【2026-03-26 16:27:14】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:27:14] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=9560, n_val=4204,
    BAC=0.493, F1=0.029, AUC=0.626,
    Regret=0.370, BND_ratio=0.033, POS_coverage=0.003,
    Score(f1_regret_bnd )=-0.357，threshold_source=val
[INFO][BT][2026-03-26 16:27:14] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.342, bucket_Score=-0.357,
    Gain=-0.015, is_weak=True
【INFO】【2026-03-26 16:27:15】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:27:15] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=181, n_val=309,
    BAC=0.203, F1=0.000, AUC=0.586,
    Regret=0.481, BND_ratio=0.612, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.786，threshold_source=val
[INFO][BT][2026-03-26 16:27:15] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.342, bucket_Score=-0.786,
    Gain=-0.444, is_weak=True
【INFO】【2026-03-26 16:27:15】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:15] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=154, n_val=73,
    BAC=0.212, F1=0.447, AUC=0.728,
    Regret=0.564, BND_ratio=0.802, POS_coverage=0.189,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:27:15] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.489, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:27:15】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:15] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=91, n_val=52,
    BAC=0.556, F1=0.457, AUC=0.731,
    Regret=0.503, BND_ratio=0.182, POS_coverage=0.063,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:27:15] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.489, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:27:16】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:16] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=2762, n_val=1207,
    BAC=0.022, F1=0.000, AUC=0.515,
    Regret=0.570, BND_ratio=0.961, POS_coverage=0.000,
    Score(f1_regret_bnd )=-1.051，threshold_source=val
[INFO][BT][2026-03-26 16:27:16] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.794, bucket_Score=-1.051,
    Gain=-0.256, is_weak=True
【INFO】【2026-03-26 16:27:16】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp（n_val=221，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:27:16] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp level=3：
    n_train=507, n_val=221,
    BAC=0.317, F1=0.179, AUC=0.708,
    Regret=0.507, BND_ratio=0.498, POS_coverage=0.045,
    Score(f1_regret_bnd )=-0.577，threshold_source=val
[INFO][BT][2026-03-26 16:27:16] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.794, bucket_Score=-0.577,
    Gain=+0.217, is_weak=False
【INFO】【2026-03-26 16:27:16】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:16] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer level=3：
    n_train=2117, n_val=899,
    BAC=0.009, F1=0.034, AUC=0.545,
    Regret=0.593, BND_ratio=0.994, POS_coverage=0.006,
    Score(f1_regret_bnd )=-1.057，threshold_source=val
[INFO][BT][2026-03-26 16:27:16] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.794, bucket_Score=-1.057,
    Gain=-0.263, is_weak=True
【INFO】【2026-03-26 16:27:17】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:17] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=203, n_val=63,
    BAC=0.451, F1=0.222, AUC=0.919,
    Regret=0.160, BND_ratio=0.263, POS_coverage=0.011,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:27:17] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.794, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:27:17】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home（n_val=87，source=val) 使用本地阈值 α=0.4000, β=0.0000
[INFO][BT][2026-03-26 16:27:17] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=201, n_val=87,
    BAC=0.319, F1=0.597, AUC=0.631,
    Regret=0.546, BND_ratio=0.529, POS_coverage=0.471,
    Score(f1_regret_bnd )=-0.213，threshold_source=val
[INFO][BT][2026-03-26 16:27:17] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.253, bucket_Score=-0.213,
    Gain=+0.040, is_weak=False
【INFO】【2026-03-26 16:27:17】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:17] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=96, n_val=33,
    BAC=0.595, F1=0.638, AUC=0.773,
    Regret=0.457, BND_ratio=0.186, POS_coverage=0.527,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:27:17] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.253, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:27:18】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:18] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=761, n_val=354,
    BAC=0.098, F1=0.275, AUC=0.603,
    Regret=0.614, BND_ratio=0.884, POS_coverage=0.116,
    Score(f1_regret_bnd )=-0.781，threshold_source=val
[INFO][BT][2026-03-26 16:27:18] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.495, bucket_Score=-0.781,
    Gain=-0.286, is_weak=True
【INFO】【2026-03-26 16:27:18】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:18] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer level=3：
    n_train=612, n_val=247,
    BAC=0.171, F1=0.400, AUC=0.599,
    Regret=0.597, BND_ratio=0.798, POS_coverage=0.202,
    Score(f1_regret_bnd )=-0.596，threshold_source=val
[INFO][BT][2026-03-26 16:27:18] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.495, bucket_Score=-0.596,
    Gain=-0.100, is_weak=True
【INFO】【2026-03-26 16:27:18】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:18] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=185, n_val=67,
    BAC=0.497, F1=0.544, AUC=0.772,
    Regret=0.460, BND_ratio=0.409, POS_coverage=0.397,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:27:18] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.495, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:27:19】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home（n_val=120，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:27:19] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=230, n_val=120,
    BAC=0.183, F1=0.154, AUC=0.558,
    Regret=0.571, BND_ratio=0.708, POS_coverage=0.033,
    Score(f1_regret_bnd )=-0.771，threshold_source=val
[INFO][BT][2026-03-26 16:27:19] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.814, bucket_Score=-0.771,
    Gain=+0.043, is_weak=False
【INFO】【2026-03-26 16:27:19】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:19] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=119, n_val=44,
    BAC=0.276, F1=0.465, AUC=0.780,
    Regret=0.488, BND_ratio=0.730, POS_coverage=0.080,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:27:19] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.814, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:27:19】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:19] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired level=3：
    n_train=708, n_val=315,
    BAC=nan, F1=nan, AUC=nan,
    Regret=nan, BND_ratio=nan, POS_coverage=nan,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:27:19] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired：
    parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.357, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:27:20】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home（n_val=12336，source=val) 使用本地阈值 α=0.5000, β=0.4000
[INFO][BT][2026-03-26 16:27:20] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=29008, n_val=12336,

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:27:30] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:27:32】[BASELINE] 全局 XGB 模型训练完成
【INFO】【2026-03-26 16:27:32】[BASELINE] 阈值搜索开始
【INFO】【2026-03-26 16:27:34】[BASELINE] 最佳阈值找到: alpha=0.4000, beta=0.2000, regret=0.4064
【INFO】【2026-03-26 16:27:34】【桶树】已为样本生成桶ID，共 43 个组合
【INFO】【2026-03-26 16:27:34】[BASELINE] 测试集桶映射完成，共 43 个桶

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)

【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home: BAC=0.4999, Regret=0.2999, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5076, Regret=0.4938, Precision=0.8333, Recall=0.0157
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5658, Regret=0.3929, Precision=0.6579, Recall=0.1429
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5681, Regret=0.5829, Precision=0.4545, Recall=0.2586
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home: BAC=0.5026, Regret=0.5612, Precision=0.5000, Recall=0.0065
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.4994, Regret=0.6657, Precision=0.2222, Recall=0.0488
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5103, Regret=0.6756, Precision=0.3571, Recall=0.0342
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home: BAC=0.5180, Regret=0.6559, Precision=0.3429, Recall=0.1446
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home: BAC=0.5250, Regret=0.7164, Precision=1.0000, Recall=0.0500
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5500, Regret=0.6442, Precision=1.0000, Recall=0.1000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=0.5048, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.6250, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=0.3000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home: BAC=0.5619, Regret=0.6104, Precision=0.3958, Recall=0.7037
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5000, Regret=0.5706, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home: BAC=0.4208, Regret=0.6774, Precision=0.4118, Recall=0.4667
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.7781, Regret=0.4800, Precision=0.7857, Recall=0.6471
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.4539, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5667, Regret=0.6250, Precision=0.5000, Recall=0.3333
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.6829, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5000, Regret=0.5658, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=1.0000, Regret=0.5000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.1667, Regret=0.7500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5000, Regret=0.1500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=1.0000, Regret=0.1000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=1.0000, Regret=0.3750, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.4917, Regret=0.6591, Precision=0.4444, Recall=0.4000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5707, Regret=0.6290, Precision=0.3333, Recall=0.7778
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.2500, Regret=0.8333, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.4167, Regret=0.7500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=0.5000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=1.0000, Regret=0.5000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=2.6667, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=1.0000, Regret=0.2500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er: BAC=0.5104, Regret=0.3603, Precision=0.6863, Recall=0.0219
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt: BAC=0.5100, Regret=0.3643, Precision=0.6863, Recall=0.0211
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er: BAC=0.5654, Regret=0.6053, Precision=0.4643, Recall=0.2422
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt: BAC=0.5699, Regret=0.6085, Precision=0.4239, Recall=0.3451
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er: BAC=0.5067, Regret=0.5971, Precision=0.3200, Recall=0.0233
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt: BAC=0.5073, Regret=0.6032, Precision=0.3226, Recall=0.0258
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er: BAC=0.4952, Regret=0.7059, Precision=0.2000, Recall=0.0417
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er: BAC=0.5250, Regret=0.6225, Precision=1.0000, Recall=0.0500
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er: BAC=0.5000, Regret=0.5862, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er: BAC=0.5764, Regret=0.6068, Precision=0.3714, Recall=0.7027
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er: BAC=0.5000, Regret=0.5020, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:27:36】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er: BAC=0.4665, Regret=0.6417, Precision=0.4333, Recall=0.4643

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)

【INFO】【2026-03-26 16:27:36】【K折实验】正在执行第 2/5 折...
【INFO】【2026-03-26 16:27:36】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=0.5

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:27:37] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:27:40】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=81413
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="few_prev_inpt"，n_samples=8721
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="many_prev_inpt"，n_samples=2930
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="no_prev_inpt"，n_samples=69762
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=378
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=7964
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=379
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=432
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=2245
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=253
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=543
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=68210
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=1009
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=236
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=142
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Expired"，n_samples=207
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=3922
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="OtherDisp"，n_samples=710
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=3056
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=69
[INFO][BT][2026-03-26 16:27:42] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er 不再细分：5 个子桶样本数不足 min_bucket_size=200
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=297
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=135
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=1138
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=854
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=253
[INFO][BT][2026-03-26 16:27:42] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er 不再细分：5 个子桶样本数不足 min_bucket_size=200
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=369
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=174
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Expired"，n_samples=1033
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=41440
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="OtherDisp"，n_samples=5500
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="SNF_Rehab"，n_samples=436
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=19801
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=575
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=359
[INFO][BT][2026-03-26 16:27:42] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=75
[INFO][BT][2026-03-26 16:27:50] 桶树构建完成：总桶数=35，最大层数=3，叶子桶数=24
【INFO】【2026-03-26 16:27:50】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 16:27:51】【阈值】桶 ROOT（n_val=4884，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:27:51] 桶 bucket_id=ROOT level=0：
    n_train=11397, n_val=4884,
    BAC=0.481, F1=0.079, AUC=0.681,
    Regret=0.403, BND_ratio=0.091, POS_coverage=0.010,
    Score(f1_regret_bnd )=-0.370，threshold_source=val
【INFO】【2026-03-26 16:27:51】【阈值】桶 L1_number_inpatient=few_prev_inpt 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:27:51] 桶 bucket_id=L1_number_inpatient=few_prev_inpt level=1：
    n_train=1215, n_val=704,
    BAC=0.040, F1=0.028, AUC=0.595,
    Regret=0.591, BND_ratio=0.938, POS_coverage=0.003,
    Score(f1_regret_bnd )=-1.031，threshold_source=val
[INFO][BT][2026-03-26 16:27:51] 桶 bucket_id=L1_number_inpatient=few_prev_inpt：
    parent_id=ROOT，parent_Score=-0.370, bucket_Score=-1.031,
    Gain=-0.662, is_weak=True
【INFO】【2026-03-26 16:27:52】【阈值】桶 L1_number_inpatient=many_prev_inpt 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:27:52] 桶 bucket_id=L1_number_inpatient=many_prev_inpt level=1：
    n_train=547, n_val=346,
    BAC=0.224, F1=0.439, AUC=0.610,
    Regret=0.597, BND_ratio=0.685, POS_coverage=0.298,
    Score(f1_regret_bnd )=-0.500，threshold_source=val
[INFO][BT][2026-03-26 16:27:52] 桶 bucket_id=L1_number_inpatient=many_prev_inpt：
    parent_id=ROOT，parent_Score=-0.370, bucket_Score=-0.500,
    Gain=-0.131, is_weak=True
【INFO】【2026-03-26 16:27:52】【阈值】桶 L1_number_inpatient=no_prev_inpt 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:27:52] 桶 bucket_id=L1_number_inpatient=no_prev_inpt level=1：
    n_train=9771, n_val=4322,
    BAC=0.342, F1=0.041, AUC=0.680,
    Regret=0.370, BND_ratio=0.361, POS_coverage=0.003,
    Score(f1_regret_bnd )=-0.510，threshold_source=val
[INFO][BT][2026-03-26 16:27:52] 桶 bucket_id=L1_number_inpatient=no_prev_inpt：
    parent_id=ROOT，parent_Score=-0.370, bucket_Score=-0.510,
    Gain=-0.140, is_weak=True
【INFO】【2026-03-26 16:27:53】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:27:53] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=272, n_val=106,
    BAC=0.000, F1=0.000, AUC=0.542,
    Regret=0.632, BND_ratio=1.000, POS_coverage=0.000,
    Score(f1_regret_bnd )=-1.132，threshold_source=val
[INFO][BT][2026-03-26 16:27:53] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-1.031, bucket_Score=-1.132,
    Gain=-0.101, is_weak=True
【INFO】【2026-03-26 16:27:53】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er（n_val=544，source=val) 使用本地阈值 α=0.5000, β=0.1000
[INFO][BT][2026-03-26 16:27:53] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=1268, n_val=544,
    BAC=0.093, F1=0.044, AUC=0.616,
    Regret=0.516, BND_ratio=0.858, POS_coverage=0.004,
    Score(f1_regret_bnd )=-0.901，threshold_source=val
[INFO][BT][2026-03-26 16:27:53] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-1.031, bucket_Score=-0.901,
    Gain=+0.130, is_weak=False
【INFO】【2026-03-26 16:27:53】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er（n_val=115，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:27:53] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=264, n_val=115,
    BAC=0.126, F1=0.267, AUC=0.590,
    Regret=0.557, BND_ratio=0.870, POS_coverage=0.087,
    Score(f1_regret_bnd )=-0.725，threshold_source=val
[INFO][BT][2026-03-26 16:27:53] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-1.031, bucket_Score=-0.725,
    Gain=+0.307, is_weak=False
【INFO】【2026-03-26 16:27:54】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er（n_val=133，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:27:54] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=133, n_val=133,
    BAC=0.434, F1=0.497, AUC=0.530,
    Regret=0.635, BND_ratio=0.218, POS_coverage=0.774,
    Score(f1_regret_bnd )=-0.248，threshold_source=val
[INFO][BT][2026-03-26 16:27:54] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.500, bucket_Score=-0.248,
    Gain=+0.252, is_weak=False
【INFO】【2026-03-26 16:27:54】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er（n_val=193，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 16:27:54] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=456, n_val=193,
    BAC=0.468, F1=0.527, AUC=0.628,
    Regret=0.573, BND_ratio=0.202, POS_coverage=0.720,
    Score(f1_regret_bnd )=-0.147，threshold_source=val
[INFO][BT][2026-03-26 16:27:54] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.500, bucket_Score=-0.147,
    Gain=+0.353, is_weak=False
【INFO】【2026-03-26 16:27:54】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:27:54] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=175, n_val=78,
    BAC=0.400, F1=0.602, AUC=0.712,
    Regret=0.542, BND_ratio=0.383, POS_coverage=0.605,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:27:54] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.500, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:27:55】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:27:55] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=163, n_val=179,
    BAC=0.016, F1=0.057, AUC=0.603,
    Regret=0.589, BND_ratio=0.983, POS_coverage=0.017,
    Score(f1_regret_bnd )=-1.024，threshold_source=val
[INFO][BT][2026-03-26 16:27:55] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.510, bucket_Score=-1.024,
    Gain=-0.514, is_weak=True
【INFO】【2026-03-26 16:27:55】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er（n_val=4182，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 16:27:55] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=9559, n_val=4182,
    BAC=0.356, F1=0.038, AUC=0.676,
    Regret=0.366, BND_ratio=0.331, POS_coverage=0.003,
    Score(f1_regret_bnd )=-0.494，threshold_source=val
[INFO][BT][2026-03-26 16:27:55] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.510, bucket_Score=-0.494,
    Gain=+0.016, is_weak=False
【INFO】【2026-03-26 16:27:56】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er（n_val=306，source=val) 使用本地阈值 α=0.7000, β=0.2000
[INFO][BT][2026-03-26 16:27:56] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=185, n_val=306,
    BAC=0.459, F1=0.000, AUC=0.644,
    Regret=0.448, BND_ratio=0.092, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.493，threshold_source=val
[INFO][BT][2026-03-26 16:27:56] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.510, bucket_Score=-0.493,
    Gain=+0.016, is_weak=False
【INFO】【2026-03-26 16:27:56】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:56] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=173, n_val=63,
    BAC=0.268, F1=0.149, AUC=0.716,
    Regret=0.581, BND_ratio=0.581, POS_coverage=0.034,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:27:56] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-1.132, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:27:57】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:57] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=99, n_val=43,
    BAC=0.541, F1=0.258, AUC=0.714,
    Regret=0.461, BND_ratio=0.092, POS_coverage=0.056,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:27:57] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-1.132, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:27:57】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:57] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired level=3：
    n_train=148, n_val=59,
    BAC=nan, F1=nan, AUC=nan,
    Regret=nan, BND_ratio=nan, POS_coverage=nan,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:27:57] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.901, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:27:57】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:57] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=2710, n_val=1212,
    BAC=0.020, F1=0.000, AUC=0.563,
    Regret=0.576, BND_ratio=0.962, POS_coverage=0.000,
    Score(f1_regret_bnd )=-1.057，threshold_source=val
[INFO][BT][2026-03-26 16:27:57] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.901, bucket_Score=-1.057,
    Gain=-0.156, is_weak=True
【INFO】【2026-03-26 16:27:57】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp（n_val=221，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 16:27:57] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp level=3：
    n_train=489, n_val=221,
    BAC=0.131, F1=0.212, AUC=0.595,
    Regret=0.597, BND_ratio=0.814, POS_coverage=0.081,
    Score(f1_regret_bnd )=-0.792，threshold_source=val
[INFO][BT][2026-03-26 16:27:57] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.901, bucket_Score=-0.792,
    Gain=+0.108, is_weak=False
【INFO】【2026-03-26 16:27:58】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:58] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer level=3：
    n_train=2146, n_val=910,
    BAC=0.005, F1=0.021, AUC=0.529,
    Regret=0.600, BND_ratio=0.995, POS_coverage=0.005,
    Score(f1_regret_bnd )=-1.076，threshold_source=val
[INFO][BT][2026-03-26 16:27:58] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.901, bucket_Score=-1.076,
    Gain=-0.175, is_weak=True
【INFO】【2026-03-26 16:27:58】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:58] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=52, n_val=17,
    BAC=0.450, F1=0.462, AUC=0.861,
    Regret=0.283, BND_ratio=0.449, POS_coverage=0.058,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:27:58] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.901, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:27:58】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home（n_val=90，source=val) 使用本地阈值 α=0.2000, β=0.0000
[INFO][BT][2026-03-26 16:27:58] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=207, n_val=90,
    BAC=0.500, F1=0.529, AUC=0.492,
    Regret=0.639, BND_ratio=0.011, POS_coverage=0.989,
    Score(f1_regret_bnd )=-0.116，threshold_source=val
[INFO][BT][2026-03-26 16:27:58] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.248, bucket_Score=-0.116,
    Gain=+0.132, is_weak=False
【INFO】【2026-03-26 16:27:59】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:59] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=92, n_val=43,
    BAC=0.633, F1=0.654, AUC=0.769,
    Regret=0.452, BND_ratio=0.178, POS_coverage=0.452,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:27:59] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.248, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:27:59】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:27:59] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=804, n_val=334,
    BAC=0.065, F1=0.205, AUC=0.560,
    Regret=0.618, BND_ratio=0.937, POS_coverage=0.057,
    Score(f1_regret_bnd )=-0.882，threshold_source=val
[INFO][BT][2026-03-26 16:27:59] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.147, bucket_Score=-0.882,
    Gain=-0.735, is_weak=True
【INFO】【2026-03-26 16:28:00】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:28:00] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer level=3：
    n_train=585, n_val=269,
    BAC=0.218, F1=0.422, AUC=0.598,
    Regret=0.610, BND_ratio=0.691, POS_coverage=0.309,
    Score(f1_regret_bnd )=-0.533，threshold_source=val
[INFO][BT][2026-03-26 16:28:00] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.147, bucket_Score=-0.533,
    Gain=-0.386, is_weak=True
【INFO】【2026-03-26 16:28:00】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:28:00] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=179, n_val=74,
    BAC=0.419, F1=0.434, AUC=0.789,
    Regret=0.455, BND_ratio=0.455, POS_coverage=0.170,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:28:00] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.147, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:28:00】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home（n_val=118，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 16:28:00] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=251, n_val=118,
    BAC=0.089, F1=0.000, AUC=0.531,
    Regret=0.572, BND_ratio=0.822, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.983，threshold_source=val
[INFO][BT][2026-03-26 16:28:00] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-1.024, bucket_Score=-0.983,
    Gain=+0.041, is_weak=False
【INFO】【2026-03-26 16:28:01】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:28:01] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=113, n_val=61,
    BAC=0.397, F1=0.514, AUC=0.785,
    Regret=0.497, BND_ratio=0.569, POS_coverage=0.213,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:28:01] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-1.024, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:28:01】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:28:01] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired level=3：
    n_train=715, n_val=318,

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:28:12] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:28:14】[BASELINE] 全局 XGB 模型训练完成
【INFO】【2026-03-26 16:28:14】[BASELINE] 阈值搜索开始
【INFO】【2026-03-26 16:28:16】[BASELINE] 最佳阈值找到: alpha=0.4000, beta=0.2000, regret=0.4006
【INFO】【2026-03-26 16:28:16】【桶树】已为样本生成桶ID，共 43 个组合
【INFO】【2026-03-26 16:28:16】[BASELINE] 测试集桶映射完成，共 43 个桶

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)

【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.2883, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5035, Regret=0.4782, Precision=0.5556, Recall=0.0079
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=0.2411, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5234, Regret=0.4292, Precision=0.4000, Recall=0.0622
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5105, Regret=0.6606, Precision=0.5714, Recall=0.0260
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home: BAC=0.5447, Regret=0.6857, Precision=0.6667, Recall=0.1163
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home: BAC=0.5023, Regret=0.6155, Precision=0.5000, Recall=0.0057
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5451, Regret=0.6333, Precision=0.5000, Recall=0.1667
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home: BAC=0.5833, Regret=0.6897, Precision=1.0000, Recall=0.1667
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.4778, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.4938, Regret=0.6105, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home: BAC=0.6000, Regret=0.5741, Precision=0.6667, Recall=0.3333
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5938, Regret=0.5962, Precision=0.5000, Recall=0.5000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.6964, Regret=0.5370, Precision=0.4667, Recall=0.5833
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5876, Regret=0.5151, Precision=0.5625, Recall=0.2195
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.4242, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=1.2895, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.8333, Regret=0.4000, Precision=1.0000, Recall=0.6667
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=0.7857, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home: BAC=0.5333, Regret=0.6852, Precision=1.0000, Recall=0.0667
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home: BAC=0.5368, Regret=0.5735, Precision=0.4737, Recall=0.6000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5000, Regret=0.5385, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5000, Regret=0.7857, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.0000, Regret=1.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5162, Regret=0.8000, Precision=0.6000, Recall=0.2143
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.3333, Regret=0.7500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5000, Regret=0.6000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.4500, Regret=0.5455, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5000, Regret=0.4167, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5000, Regret=0.5500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=0.6667, Precision=0.3333, Recall=1.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.4000, Regret=0.8000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.7500, Regret=0.5000, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=1.0000, Regret=0.5000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er: BAC=0.5047, Regret=0.3516, Precision=0.4359, Recall=0.0108
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt: BAC=0.5048, Regret=0.3559, Precision=0.4286, Recall=0.0111
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er: BAC=0.5153, Regret=0.6153, Precision=0.5600, Recall=0.0371
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt: BAC=0.5154, Regret=0.6115, Precision=0.5161, Recall=0.0388
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er: BAC=0.5582, Regret=0.6419, Precision=0.5556, Recall=0.1796
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt: BAC=0.5696, Regret=0.6356, Precision=0.5210, Recall=0.2605
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er: BAC=0.5326, Regret=0.6436, Precision=0.4000, Recall=0.1053
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er: BAC=0.4935, Regret=0.4946, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er: BAC=0.4954, Regret=0.5060, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er: BAC=0.5412, Regret=0.6750, Precision=0.5714, Recall=0.2759
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er: BAC=0.5607, Regret=0.5784, Precision=0.4706, Recall=0.5714
【INFO】【2026-03-26 16:28:18】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er: BAC=0.5238, Regret=0.6783, Precision=1.0000, Recall=0.0476

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)

【INFO】【2026-03-26 16:28:18】【K折实验】正在执行第 3/5 折...
【INFO】【2026-03-26 16:28:18】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=0.5

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:28:19] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:28:22】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=81413
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="few_prev_inpt"，n_samples=8848
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="many_prev_inpt"，n_samples=2904
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="no_prev_inpt"，n_samples=69661
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=391
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=8079
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=378
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=437
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=2224
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=243
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=519
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=68143
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=999
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=235
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=156
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=4002
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="OtherDisp"，n_samples=734
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=3073
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=270
[INFO][BT][2026-03-26 16:28:24] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er 不再细分：5 个子桶样本数不足 min_bucket_size=200
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=296
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=141
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=1114
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=856
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=254
[INFO][BT][2026-03-26 16:28:24] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er 不再细分：5 个子桶样本数不足 min_bucket_size=200
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=362
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=157
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Expired"，n_samples=1026
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=41290
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="OtherDisp"，n_samples=5437
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="SNF_Rehab"，n_samples=450
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=19940
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=560
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=360
[INFO][BT][2026-03-26 16:28:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=79
[INFO][BT][2026-03-26 16:28:31] 桶树构建完成：总桶数=34，最大层数=3，叶子桶数=23
【INFO】【2026-03-26 16:28:31】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 16:28:31】【阈值】桶 ROOT 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:28:31] 桶 bucket_id=ROOT level=0：
    n_train=11396, n_val=4883,
    BAC=0.323, F1=0.097, AUC=0.693,
    Regret=0.396, BND_ratio=0.427, POS_coverage=0.011,
    Score(f1_regret_bnd )=-0.513，threshold_source=val
【INFO】【2026-03-26 16:28:32】【阈值】桶 L1_number_inpatient=few_prev_inpt 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:28:32] 桶 bucket_id=L1_number_inpatient=few_prev_inpt level=1：
    n_train=1212, n_val=753,
    BAC=0.021, F1=0.000, AUC=0.596,
    Regret=0.569, BND_ratio=0.965, POS_coverage=0.000,
    Score(f1_regret_bnd )=-1.052，threshold_source=val
[INFO][BT][2026-03-26 16:28:32] 桶 bucket_id=L1_number_inpatient=few_prev_inpt：
    parent_id=ROOT，parent_Score=-0.513, bucket_Score=-1.052,
    Gain=-0.539, is_weak=True
【INFO】【2026-03-26 16:28:32】【阈值】桶 L1_number_inpatient=many_prev_inpt（n_val=349，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 16:28:32] 桶 bucket_id=L1_number_inpatient=many_prev_inpt level=1：
    n_train=542, n_val=349,
    BAC=0.261, F1=0.519, AUC=0.657,
    Regret=0.566, BND_ratio=0.653, POS_coverage=0.324,
    Score(f1_regret_bnd )=-0.374，threshold_source=val
[INFO][BT][2026-03-26 16:28:32] 桶 bucket_id=L1_number_inpatient=many_prev_inpt：
    parent_id=ROOT，parent_Score=-0.513, bucket_Score=-0.374,
    Gain=+0.139, is_weak=False
【INFO】【2026-03-26 16:28:33】【阈值】桶 L1_number_inpatient=no_prev_inpt（n_val=4278，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:28:33] 桶 bucket_id=L1_number_inpatient=no_prev_inpt level=1：
    n_train=9776, n_val=4278,
    BAC=0.493, F1=0.037, AUC=0.644,
    Regret=0.373, BND_ratio=0.039, POS_coverage=0.003,
    Score(f1_regret_bnd )=-0.355，threshold_source=val
[INFO][BT][2026-03-26 16:28:33] 桶 bucket_id=L1_number_inpatient=no_prev_inpt：
    parent_id=ROOT，parent_Score=-0.513, bucket_Score=-0.355,
    Gain=+0.158, is_weak=False
【INFO】【2026-03-26 16:28:33】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:28:33] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=268, n_val=123,
    BAC=0.005, F1=0.000, AUC=0.571,
    Regret=0.606, BND_ratio=0.992, POS_coverage=0.000,
    Score(f1_regret_bnd )=-1.102，threshold_source=val
[INFO][BT][2026-03-26 16:28:33] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-1.052, bucket_Score=-1.102,
    Gain=-0.050, is_weak=True
【INFO】【2026-03-26 16:28:33】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er（n_val=573，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 16:28:33] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=1257, n_val=573,
    BAC=0.084, F1=0.043, AUC=0.602,
    Regret=0.520, BND_ratio=0.871, POS_coverage=0.005,
    Score(f1_regret_bnd )=-0.912，threshold_source=val
[INFO][BT][2026-03-26 16:28:33] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-1.052, bucket_Score=-0.912,
    Gain=+0.139, is_weak=False
【INFO】【2026-03-26 16:28:34】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er（n_val=124，source=val) 使用本地阈值 α=0.5000, β=0.2000
[INFO][BT][2026-03-26 16:28:34] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=254, n_val=124,
    BAC=0.208, F1=0.000, AUC=0.593,
    Regret=0.540, BND_ratio=0.597, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.839，threshold_source=val
[INFO][BT][2026-03-26 16:28:34] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-1.052, bucket_Score=-0.839,
    Gain=+0.213, is_weak=False
【INFO】【2026-03-26 16:28:34】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er（n_val=146，source=val) 使用本地阈值 α=0.4000, β=0.0000
[INFO][BT][2026-03-26 16:28:34] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=291, n_val=146,
    BAC=0.339, F1=0.611, AUC=0.665,
    Regret=0.538, BND_ratio=0.507, POS_coverage=0.493,
    Score(f1_regret_bnd )=-0.180，threshold_source=val
[INFO][BT][2026-03-26 16:28:34] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.374, bucket_Score=-0.180,
    Gain=+0.194, is_weak=False
【INFO】【2026-03-26 16:28:34】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:28:34] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=446, n_val=200,
    BAC=0.299, F1=0.410, AUC=0.701,
    Regret=0.530, BND_ratio=0.625, POS_coverage=0.170,
    Score(f1_regret_bnd )=-0.433，threshold_source=val
[INFO][BT][2026-03-26 16:28:34] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.374, bucket_Score=-0.433,
    Gain=-0.059, is_weak=True
【INFO】【2026-03-26 16:28:35】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:28:35] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=170, n_val=73,
    BAC=0.439, F1=0.650, AUC=0.730,
    Regret=0.510, BND_ratio=0.288, POS_coverage=0.704,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:28:35] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.374, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:28:35】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:28:35] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=154, n_val=155,
    BAC=0.399, F1=0.087, AUC=0.621,
    Regret=0.452, BND_ratio=0.258, POS_coverage=0.019,
    Score(f1_regret_bnd )=-0.494，threshold_source=val
[INFO][BT][2026-03-26 16:28:35] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.355, bucket_Score=-0.494,
    Gain=-0.138, is_weak=True
【INFO】【2026-03-26 16:28:36】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er（n_val=4176，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:28:36] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=9565, n_val=4176,
    BAC=0.497, F1=0.038, AUC=0.643,
    Regret=0.366, BND_ratio=0.031, POS_coverage=0.003,
    Score(f1_regret_bnd )=-0.344，threshold_source=val
[INFO][BT][2026-03-26 16:28:36] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.355, bucket_Score=-0.344,
    Gain=+0.012, is_weak=False
【INFO】【2026-03-26 16:28:36】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:28:36] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=181, n_val=302,
    BAC=0.152, F1=0.000, AUC=0.551,
    Regret=0.515, BND_ratio=0.719, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.874，threshold_source=val
[INFO][BT][2026-03-26 16:28:36] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.355, bucket_Score=-0.874,
    Gain=-0.519, is_weak=True
【INFO】【2026-03-26 16:28:36】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:28:36] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=158, n_val=77,
    BAC=0.274, F1=0.164, AUC=0.755,
    Regret=0.551, BND_ratio=0.587, POS_coverage=0.021,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:28:36] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-1.102, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:28:37】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:28:37] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=110, n_val=46,
    BAC=0.221, F1=0.067, AUC=0.726,
    Regret=0.516, BND_ratio=0.622, POS_coverage=0.013,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:28:37] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-1.102, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:28:37】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:28:37] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=2700, n_val=1302,
    BAC=0.018, F1=0.000, AUC=0.566,
    Regret=0.573, BND_ratio=0.969, POS_coverage=0.000,
    Score(f1_regret_bnd )=-1.058，threshold_source=val
[INFO][BT][2026-03-26 16:28:37] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.912, bucket_Score=-1.058,
    Gain=-0.146, is_weak=True
【INFO】【2026-03-26 16:28:37】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp（n_val=206，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 16:28:37] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp level=3：
    n_train=528, n_val=206,
    BAC=0.139, F1=0.237, AUC=0.611,
    Regret=0.585, BND_ratio=0.830, POS_coverage=0.053,
    Score(f1_regret_bnd )=-0.763，threshold_source=val
[INFO][BT][2026-03-26 16:28:37] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.912, bucket_Score=-0.763,
    Gain=+0.150, is_weak=False
【INFO】【2026-03-26 16:28:38】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:28:38] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer level=3：
    n_train=2133, n_val=940,
    BAC=0.015, F1=0.042, AUC=0.534,
    Regret=0.595, BND_ratio=0.984, POS_coverage=0.009,
    Score(f1_regret_bnd )=-1.045，threshold_source=val
[INFO][BT][2026-03-26 16:28:38] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.912, bucket_Score=-1.045,
    Gain=-0.133, is_weak=True
【INFO】【2026-03-26 16:28:38】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:28:38] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=186, n_val=84,
    BAC=0.483, F1=0.125, AUC=0.960,
    Regret=0.111, BND_ratio=0.141, POS_coverage=0.007,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:28:38] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.912, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:28:39】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:28:39] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=193, n_val=103,
    BAC=0.357, F1=0.591, AUC=0.676,
    Regret=0.539, BND_ratio=0.495, POS_coverage=0.485,
    Score(f1_regret_bnd )=-0.195，threshold_source=val
[INFO][BT][2026-03-26 16:28:39] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.180, bucket_Score=-0.195,
    Gain=-0.015, is_weak=True
【INFO】【2026-03-26 16:28:39】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:28:39] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=98, n_val=43,
    BAC=0.407, F1=0.630, AUC=0.762,
    Regret=0.504, BND_ratio=0.496, POS_coverage=0.418,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:28:39] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.180, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:28:39】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:28:39] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=779, n_val=335,
    BAC=0.207, F1=0.408, AUC=0.608,
    Regret=0.609, BND_ratio=0.710, POS_coverage=0.287,
    Score(f1_regret_bnd )=-0.556，threshold_source=val
[INFO][BT][2026-03-26 16:28:39] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.433, bucket_Score=-0.556,
    Gain=-0.123, is_weak=True
【INFO】【2026-03-26 16:28:40】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:28:40] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer level=3：
    n_train=624, n_val=232,
    BAC=0.194, F1=0.319, AUC=0.653,
    Regret=0.560, BND_ratio=0.763, POS_coverage=0.116,
    Score(f1_regret_bnd )=-0.623，threshold_source=val
[INFO][BT][2026-03-26 16:28:40] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.433, bucket_Score=-0.623,
    Gain=-0.190, is_weak=True
【INFO】【2026-03-26 16:28:40】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:28:40] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=167, n_val=87,
    BAC=0.472, F1=0.569, AUC=0.810,
    Regret=0.404, BND_ratio=0.469, POS_coverage=0.240,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:28:40] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.433, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:28:40】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home（n_val=100，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:28:40] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=262, n_val=100,
    BAC=0.433, F1=0.167, AUC=0.621,
    Regret=0.380, BND_ratio=0.240, POS_coverage=0.010,
    Score(f1_regret_bnd )=-0.333，threshold_source=val
[INFO][BT][2026-03-26 16:28:40] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.494, bucket_Score=-0.333,
    Gain=+0.160, is_weak=False
【INFO】【2026-03-26 16:28:41】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:28:41] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=102, n_val=55,
    BAC=0.456, F1=0.222, AUC=0.822,
    Regret=0.395, BND_ratio=0.287, POS_coverage=0.038,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:28:41] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.494, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:28:41】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:28:41] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired level=3：
    n_train=745, n_val=281,
    BAC=nan, F1=nan, AUC=nan,
    Regret=nan, BND_ratio=nan, POS_coverage=nan,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:28:41] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired：
    parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.344, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:28:41】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home（n_val=12295，source=val) 使用本地阈值 α=0.5000, β=0.4000
[INFO][BT][2026-03-26 16:28:41] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home level=3：

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:28:51] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:28:54】[BASELINE] 全局 XGB 模型训练完成
【INFO】【2026-03-26 16:28:54】[BASELINE] 阈值搜索开始
【INFO】【2026-03-26 16:28:55】[BASELINE] 最佳阈值找到: alpha=0.4000, beta=0.2000, regret=0.3998
【INFO】【2026-03-26 16:28:55】【桶树】已为样本生成桶ID，共 43 个组合
【INFO】【2026-03-26 16:28:55】[BASELINE] 测试集桶映射完成，共 43 个桶

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)

【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5673, Regret=0.4127, Precision=0.6122, Recall=0.1500
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.3093, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5029, Regret=0.4623, Precision=0.5000, Recall=0.0067
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5026, Regret=0.6595, Precision=0.5000, Recall=0.0069
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home: BAC=0.4994, Regret=0.6324, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home: BAC=0.5061, Regret=0.6993, Precision=0.3478, Recall=0.0860
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5714, Regret=0.5600, Precision=0.6000, Recall=0.1714
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=0.5459, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5276, Regret=0.6683, Precision=0.3750, Recall=0.1552
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.3912, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.7750, Regret=0.3889, Precision=0.7500, Recall=0.7500
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.4938, Regret=0.4521, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=0.6429, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.7288, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home: BAC=0.5723, Regret=0.6812, Precision=0.4583, Recall=0.4400
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=1.0000, Regret=0.2500, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5000, Regret=0.3667, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.4583, Regret=0.8452, Precision=0.1667, Recall=0.0833
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.5398, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.5676, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5705, Regret=0.4667, Precision=0.5000, Recall=0.1667
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.4500, Regret=0.3636, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=2.6667, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home: BAC=0.5387, Regret=0.6974, Precision=0.4444, Recall=0.2857
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.6625, Regret=0.5714, Precision=0.4545, Recall=0.6250
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5000, Regret=0.7245, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.4345, Regret=0.7105, Precision=0.2857, Recall=0.2857
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.2500, Regret=0.8333, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5000, Regret=1.5000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.6667, Regret=0.5000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=1.0000, Regret=0.5000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=1.0000, Regret=0.3750, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=0.7500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=1.0000, Regret=0.5000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=1.0000, Regret=0.5000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er: BAC=0.5098, Regret=0.3587, Precision=0.5965, Recall=0.0211
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt: BAC=0.5097, Regret=0.3612, Precision=0.5738, Recall=0.0210
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er: BAC=0.5081, Regret=0.6182, Precision=0.5385, Recall=0.0200
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt: BAC=0.5068, Regret=0.6193, Precision=0.4667, Recall=0.0182
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er: BAC=0.5179, Regret=0.6790, Precision=0.3684, Recall=0.1257
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt: BAC=0.5363, Regret=0.6703, Precision=0.4054, Recall=0.2018
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er: BAC=0.4957, Regret=0.4050, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er: BAC=0.4844, Regret=0.6481, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er: BAC=0.5698, Regret=0.6495, Precision=0.4412, Recall=0.4412
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er: BAC=0.5185, Regret=0.5827, Precision=0.5000, Recall=0.0455
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er: BAC=0.5000, Regret=0.6170, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:28:57】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er: BAC=0.5900, Regret=0.6286, Precision=0.4500, Recall=0.4091

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)

【INFO】【2026-03-26 16:28:58】【K折实验】正在执行第 4/5 折...
【INFO】【2026-03-26 16:28:58】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=0.5

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:28:58] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:29:00】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=81413
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="few_prev_inpt"，n_samples=8810
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="many_prev_inpt"，n_samples=2931
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="no_prev_inpt"，n_samples=69672
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=382
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=8035
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=393
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=431
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=2252
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=248
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=534
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=68122
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=1016
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=238
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=144
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Expired"，n_samples=212
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=3977
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="OtherDisp"，n_samples=724
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=3051
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=71
[INFO][BT][2026-03-26 16:29:02] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er 不再细分：5 个子桶样本数不足 min_bucket_size=200
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=288
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=143
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=1146
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=853
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=253
[INFO][BT][2026-03-26 16:29:02] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er 不再细分：5 个子桶样本数不足 min_bucket_size=200
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=367
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=167
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Expired"，n_samples=1042
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=41272
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="OtherDisp"，n_samples=5452
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="SNF_Rehab"，n_samples=433
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=19923
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=572
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=373
[INFO][BT][2026-03-26 16:29:02] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=71
[INFO][BT][2026-03-26 16:29:08] 桶树构建完成：总桶数=35，最大层数=3，叶子桶数=24
【INFO】【2026-03-26 16:29:08】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 16:29:08】【阈值】桶 ROOT（n_val=4883，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:29:08] 桶 bucket_id=ROOT level=0：
    n_train=11396, n_val=4883,
    BAC=0.487, F1=0.088, AUC=0.671,
    Regret=0.397, BND_ratio=0.083, POS_coverage=0.009,
    Score(f1_regret_bnd )=-0.350，threshold_source=val
【INFO】【2026-03-26 16:29:09】【阈值】桶 L1_number_inpatient=few_prev_inpt 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:29:09] 桶 bucket_id=L1_number_inpatient=few_prev_inpt level=1：
    n_train=1231, n_val=702,
    BAC=0.044, F1=0.027, AUC=0.570,
    Regret=0.581, BND_ratio=0.934, POS_coverage=0.004,
    Score(f1_regret_bnd )=-1.022，threshold_source=val
[INFO][BT][2026-03-26 16:29:09] 桶 bucket_id=L1_number_inpatient=few_prev_inpt：
    parent_id=ROOT，parent_Score=-0.350, bucket_Score=-1.022,
    Gain=-0.671, is_weak=True
【INFO】【2026-03-26 16:29:09】【阈值】桶 L1_number_inpatient=many_prev_inpt（n_val=340，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:29:09] 桶 bucket_id=L1_number_inpatient=many_prev_inpt level=1：
    n_train=547, n_val=340,
    BAC=0.360, F1=0.500, AUC=0.633,
    Regret=0.593, BND_ratio=0.421, POS_coverage=0.547,
    Score(f1_regret_bnd )=-0.303，threshold_source=val
[INFO][BT][2026-03-26 16:29:09] 桶 bucket_id=L1_number_inpatient=many_prev_inpt：
    parent_id=ROOT，parent_Score=-0.350, bucket_Score=-0.303,
    Gain=+0.047, is_weak=False
【INFO】【2026-03-26 16:29:10】【阈值】桶 L1_number_inpatient=no_prev_inpt 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:29:10] 桶 bucket_id=L1_number_inpatient=no_prev_inpt level=1：
    n_train=9756, n_val=4298,
    BAC=0.490, F1=0.037, AUC=0.637,
    Regret=0.413, BND_ratio=0.044, POS_coverage=0.003,
    Score(f1_regret_bnd )=-0.398，threshold_source=val
[INFO][BT][2026-03-26 16:29:10] 桶 bucket_id=L1_number_inpatient=no_prev_inpt：
    parent_id=ROOT，parent_Score=-0.350, bucket_Score=-0.398,
    Gain=-0.047, is_weak=True
【INFO】【2026-03-26 16:29:10】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:29:10] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=274, n_val=108,
    BAC=0.000, F1=0.000, AUC=0.557,
    Regret=0.616, BND_ratio=1.000, POS_coverage=0.000,
    Score(f1_regret_bnd )=-1.116，threshold_source=val
[INFO][BT][2026-03-26 16:29:10] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-1.022, bucket_Score=-1.116,
    Gain=-0.094, is_weak=True
【INFO】【2026-03-26 16:29:10】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er（n_val=550，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 16:29:10] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=1280, n_val=550,
    BAC=0.101, F1=0.068, AUC=0.621,
    Regret=0.518, BND_ratio=0.842, POS_coverage=0.013,
    Score(f1_regret_bnd )=-0.871，threshold_source=val
[INFO][BT][2026-03-26 16:29:10] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-1.022, bucket_Score=-0.871,
    Gain=+0.151, is_weak=False
【INFO】【2026-03-26 16:29:10】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er（n_val=109，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 16:29:10] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=284, n_val=109,
    BAC=0.056, F1=0.000, AUC=0.584,
    Regret=0.546, BND_ratio=0.908, POS_coverage=0.000,
    Score(f1_regret_bnd )=-1.000，threshold_source=val
[INFO][BT][2026-03-26 16:29:10] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-1.022, bucket_Score=-1.000,
    Gain=+0.022, is_weak=False
【INFO】【2026-03-26 16:29:11】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er（n_val=129，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 16:29:11] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=141, n_val=129,
    BAC=0.508, F1=0.554, AUC=0.547,
    Regret=0.597, BND_ratio=0.054, POS_coverage=0.922,
    Score(f1_regret_bnd )=-0.070，threshold_source=val
[INFO][BT][2026-03-26 16:29:11] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.303, bucket_Score=-0.070,
    Gain=+0.233, is_weak=False
【INFO】【2026-03-26 16:29:11】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:29:11] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=444, n_val=207,
    BAC=0.180, F1=0.156, AUC=0.630,
    Regret=0.577, BND_ratio=0.729, POS_coverage=0.053,
    Score(f1_regret_bnd )=-0.786，threshold_source=val
[INFO][BT][2026-03-26 16:29:11] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.303, bucket_Score=-0.786,
    Gain=-0.483, is_weak=True
【INFO】【2026-03-26 16:29:11】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:29:11] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=176, n_val=72,
    BAC=0.420, F1=0.645, AUC=0.748,
    Regret=0.508, BND_ratio=0.387, POS_coverage=0.597,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:11] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.303, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:11】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:29:11] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=173, n_val=153,
    BAC=0.000, F1=0.000, AUC=0.543,
    Regret=0.588, BND_ratio=1.000, POS_coverage=0.000,
    Score(f1_regret_bnd )=-1.088，threshold_source=val
[INFO][BT][2026-03-26 16:29:11] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.398, bucket_Score=-1.088,
    Gain=-0.690, is_weak=True
【INFO】【2026-03-26 16:29:12】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er（n_val=4208，source=val) 使用本地阈值 α=0.6000, β=0.2000
[INFO][BT][2026-03-26 16:29:12] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=9535, n_val=4208,
    BAC=0.484, F1=0.005, AUC=0.640,
    Regret=0.337, BND_ratio=0.040, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.351，threshold_source=val
[INFO][BT][2026-03-26 16:29:12] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.398, bucket_Score=-0.351,
    Gain=+0.046, is_weak=False
【INFO】【2026-03-26 16:29:12】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:29:12] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=183, n_val=293,
    BAC=0.202, F1=0.047, AUC=0.591,
    Regret=0.476, BND_ratio=0.638, POS_coverage=0.010,
    Score(f1_regret_bnd )=-0.749，threshold_source=val
[INFO][BT][2026-03-26 16:29:12] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.398, bucket_Score=-0.749,
    Gain=-0.351, is_weak=True
【INFO】【2026-03-26 16:29:12】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:12] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=173, n_val=65,
    BAC=0.302, F1=0.068, AUC=0.747,
    Regret=0.559, BND_ratio=0.504, POS_coverage=0.008,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:12] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-1.116, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:13】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:13] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=101, n_val=43,
    BAC=0.253, F1=0.194, AUC=0.788,
    Regret=0.458, BND_ratio=0.632, POS_coverage=0.035,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:13] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-1.116, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:13】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:13] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired level=3：
    n_train=151, n_val=61,
    BAC=nan, F1=nan, AUC=nan,
    Regret=nan, BND_ratio=nan, POS_coverage=nan,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:13] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.871, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:13】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:13] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=2819, n_val=1158,
    BAC=0.025, F1=0.010, AUC=0.571,
    Regret=0.579, BND_ratio=0.960, POS_coverage=0.001,
    Score(f1_regret_bnd )=-1.050，threshold_source=val
[INFO][BT][2026-03-26 16:29:13] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.871, bucket_Score=-1.050,
    Gain=-0.179, is_weak=True
【INFO】【2026-03-26 16:29:13】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp（n_val=233，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:29:13] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp level=3：
    n_train=491, n_val=233,
    BAC=0.399, F1=0.324, AUC=0.696,
    Regret=0.504, BND_ratio=0.408, POS_coverage=0.090,
    Score(f1_regret_bnd )=-0.385，threshold_source=val
[INFO][BT][2026-03-26 16:29:13] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.871, bucket_Score=-0.385,
    Gain=+0.486, is_weak=False
【INFO】【2026-03-26 16:29:13】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:13] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer level=3：
    n_train=2099, n_val=952,
    BAC=0.013, F1=0.000, AUC=0.545,
    Regret=0.597, BND_ratio=0.976, POS_coverage=0.000,
    Score(f1_regret_bnd )=-1.085，threshold_source=val
[INFO][BT][2026-03-26 16:29:13] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.871, bucket_Score=-1.085,
    Gain=-0.214, is_weak=True
【INFO】【2026-03-26 16:29:14】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:14] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=49, n_val=22,
    BAC=0.383, F1=0.143, AUC=0.808,
    Regret=0.423, BND_ratio=0.380, POS_coverage=0.014,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:14] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.871, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:14】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:14] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=201, n_val=87,
    BAC=0.145, F1=0.375, AUC=0.568,
    Regret=0.621, BND_ratio=0.805, POS_coverage=0.195,
    Score(f1_regret_bnd )=-0.648，threshold_source=val
[INFO][BT][2026-03-26 16:29:14] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.070, bucket_Score=-0.648,
    Gain=-0.578, is_weak=True
【INFO】【2026-03-26 16:29:14】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:14] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=101, n_val=42,
    BAC=0.418, F1=0.598, AUC=0.734,
    Regret=0.483, BND_ratio=0.476, POS_coverage=0.413,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:14] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.070, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:15】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:15] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=794, n_val=352,
    BAC=0.170, F1=0.148, AUC=0.598,
    Regret=0.622, BND_ratio=0.739, POS_coverage=0.057,
    Score(f1_regret_bnd )=-0.844，threshold_source=val
[INFO][BT][2026-03-26 16:29:15] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.786, bucket_Score=-0.844,
    Gain=-0.058, is_weak=True
【INFO】【2026-03-26 16:29:15】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer（n_val=258，source=val) 使用本地阈值 α=0.3000, β=0.0000
[INFO][BT][2026-03-26 16:29:15] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer level=3：
    n_train=595, n_val=258,
    BAC=0.289, F1=0.453, AUC=0.612,
    Regret=0.612, BND_ratio=0.574, POS_coverage=0.426,
    Score(f1_regret_bnd )=-0.446，threshold_source=val
[INFO][BT][2026-03-26 16:29:15] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.786, bucket_Score=-0.446,
    Gain=+0.340, is_weak=False
【INFO】【2026-03-26 16:29:15】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:15] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=167, n_val=86,
    BAC=0.448, F1=0.547, AUC=0.805,
    Regret=0.427, BND_ratio=0.490, POS_coverage=0.225,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:15] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.786, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:15】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:15] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=260, n_val=107,
    BAC=0.000, F1=0.000, AUC=0.498,
    Regret=0.589, BND_ratio=1.000, POS_coverage=0.000,
    Score(f1_regret_bnd )=-1.089，threshold_source=val
[INFO][BT][2026-03-26 16:29:15] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-1.088, bucket_Score=-1.089,
    Gain=-0.001, is_weak=True
【INFO】【2026-03-26 16:29:16】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:16] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=121, n_val=46,
    BAC=0.396, F1=0.493, AUC=0.775,
    Regret=0.482, BND_ratio=0.563, POS_coverage=0.246,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:16] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-1.088, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:16】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er 的阈值

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:29:24] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:29:26】[BASELINE] 全局 XGB 模型训练完成
【INFO】【2026-03-26 16:29:26】[BASELINE] 阈值搜索开始
【INFO】【2026-03-26 16:29:27】[BASELINE] 最佳阈值找到: alpha=0.4000, beta=0.2000, regret=0.3975
【INFO】【2026-03-26 16:29:27】【桶树】已为样本生成桶ID，共 42 个组合
【INFO】【2026-03-26 16:29:27】[BASELINE] 测试集桶映射完成，共 42 个桶

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)

【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.3028, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5021, Regret=0.4504, Precision=0.4286, Recall=0.0051
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5349, Regret=0.4185, Precision=0.4848, Recall=0.0838
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.6619, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5930, Regret=0.6135, Precision=0.6000, Recall=0.2449
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home: BAC=0.5775, Regret=0.6061, Precision=0.4865, Recall=0.2535
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=0.5348, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5029, Regret=0.6992, Precision=0.3333, Recall=0.0123
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.4643, Regret=0.5588, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5544, Regret=0.6327, Precision=0.4444, Recall=0.2069
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.5814, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5000, Regret=0.5370, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.6964, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home: BAC=0.6078, Regret=0.6688, Precision=0.6061, Recall=0.5405
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.4519, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.4940, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5814, Regret=0.6429, Precision=0.4615, Recall=0.3750
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5000, Regret=0.3667, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5000, Regret=0.6897, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5000, Regret=0.4565, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home: BAC=0.6018, Regret=0.6765, Precision=0.5833, Recall=0.4667
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.4643, Regret=0.6429, Precision=0.2857, Recall=0.2857
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.4608, Regret=0.6923, Precision=0.3000, Recall=0.3333
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.7500, Regret=0.5000, Precision=1.0000, Recall=0.5000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.4667, Regret=0.3438, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5000, Regret=1.2000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.6667, Regret=0.3333, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5000, Regret=1.6250, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5000, Regret=0.3750, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=1.0000, Regret=0.2500, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=1.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.3333, Regret=2.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er: BAC=0.5053, Regret=0.3523, Precision=0.4750, Recall=0.0120
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt: BAC=0.5051, Regret=0.3546, Precision=0.4634, Recall=0.0117
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er: BAC=0.5140, Regret=0.6577, Precision=0.5185, Recall=0.0360
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt: BAC=0.5123, Regret=0.6578, Precision=0.4828, Recall=0.0332
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er: BAC=0.5736, Regret=0.6067, Precision=0.4744, Recall=0.2517
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt: BAC=0.5912, Regret=0.6223, Precision=0.5069, Recall=0.3288
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er: BAC=0.5000, Regret=0.6456, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er: BAC=0.4976, Regret=0.4564, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er: BAC=0.4861, Regret=0.6722, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er: BAC=0.6052, Regret=0.6359, Precision=0.5814, Recall=0.5319
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er: BAC=0.5000, Regret=0.4718, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:28】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er: BAC=0.5343, Regret=0.7308, Precision=0.4783, Recall=0.3929

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)

【INFO】【2026-03-26 16:29:28】【K折实验】正在执行第 5/5 折...
【INFO】【2026-03-26 16:29:29】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=0.5

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:29:29] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:29:31】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=81413
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="few_prev_inpt"，n_samples=8810
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="many_prev_inpt"，n_samples=2891
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="no_prev_inpt"，n_samples=69712
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=367
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=8075
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=368
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=419
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=2217
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=255
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=523
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=68189
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=1000
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=240
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=127
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Expired"，n_samples=200
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=3990
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="OtherDisp"，n_samples=740
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=3080
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=65
[INFO][BT][2026-03-26 16:29:32] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er 不再细分：5 个子桶样本数不足 min_bucket_size=200
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=291
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=128
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=1127
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=834
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=256
[INFO][BT][2026-03-26 16:29:32] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er 不再细分：5 个子桶样本数不足 min_bucket_size=200
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=352
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=171
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Expired"，n_samples=1004
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=41354
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="OtherDisp"，n_samples=5526
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="SNF_Rehab"，n_samples=429
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=19876
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=566
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=355
[INFO][BT][2026-03-26 16:29:32] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=79
[INFO][BT][2026-03-26 16:29:37] 桶树构建完成：总桶数=35，最大层数=3，叶子桶数=24
【INFO】【2026-03-26 16:29:37】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 16:29:37】【阈值】桶 ROOT 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:29:37] 桶 bucket_id=ROOT level=0：
    n_train=11396, n_val=4883,
    BAC=0.319, F1=0.090, AUC=0.697,
    Regret=0.404, BND_ratio=0.433, POS_coverage=0.011,
    Score(f1_regret_bnd )=-0.530，threshold_source=val
【INFO】【2026-03-26 16:29:37】【阈值】桶 L1_number_inpatient=few_prev_inpt 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:29:37] 桶 bucket_id=L1_number_inpatient=few_prev_inpt level=1：
    n_train=1226, n_val=714,
    BAC=0.027, F1=0.000, AUC=0.552,
    Regret=0.595, BND_ratio=0.954, POS_coverage=0.000,
    Score(f1_regret_bnd )=-1.072，threshold_source=val
[INFO][BT][2026-03-26 16:29:37] 桶 bucket_id=L1_number_inpatient=few_prev_inpt：
    parent_id=ROOT，parent_Score=-0.530, bucket_Score=-1.072,
    Gain=-0.542, is_weak=True
【INFO】【2026-03-26 16:29:38】【阈值】桶 L1_number_inpatient=many_prev_inpt（n_val=331，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 16:29:38] 桶 bucket_id=L1_number_inpatient=many_prev_inpt level=1：
    n_train=541, n_val=331,
    BAC=0.247, F1=0.495, AUC=0.625,
    Regret=0.573, BND_ratio=0.701, POS_coverage=0.290,
    Score(f1_regret_bnd )=-0.428，threshold_source=val
[INFO][BT][2026-03-26 16:29:38] 桶 bucket_id=L1_number_inpatient=many_prev_inpt：
    parent_id=ROOT，parent_Score=-0.530, bucket_Score=-0.428,
    Gain=+0.102, is_weak=False
【INFO】【2026-03-26 16:29:38】【阈值】桶 L1_number_inpatient=no_prev_inpt（n_val=4298，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:29:38] 桶 bucket_id=L1_number_inpatient=no_prev_inpt level=1：
    n_train=9771, n_val=4298,
    BAC=0.494, F1=0.033, AUC=0.654,
    Regret=0.368, BND_ratio=0.034, POS_coverage=0.003,
    Score(f1_regret_bnd )=-0.352，threshold_source=val
[INFO][BT][2026-03-26 16:29:38] 桶 bucket_id=L1_number_inpatient=no_prev_inpt：
    parent_id=ROOT，parent_Score=-0.530, bucket_Score=-0.352,
    Gain=+0.178, is_weak=False
【INFO】【2026-03-26 16:29:38】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er（n_val=106，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:29:38] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=261, n_val=106,
    BAC=0.101, F1=0.250, AUC=0.528,
    Regret=0.590, BND_ratio=0.887, POS_coverage=0.104,
    Score(f1_regret_bnd )=-0.783，threshold_source=val
[INFO][BT][2026-03-26 16:29:38] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-1.072, bucket_Score=-0.783,
    Gain=+0.289, is_weak=False
【INFO】【2026-03-26 16:29:39】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er（n_val=723，source=val) 使用本地阈值 α=0.7000, β=0.1000
[INFO][BT][2026-03-26 16:29:39] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=1261, n_val=723,
    BAC=0.080, F1=0.000, AUC=0.588,
    Regret=0.547, BND_ratio=0.867, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.981，threshold_source=val
[INFO][BT][2026-03-26 16:29:39] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-1.072, bucket_Score=-0.981,
    Gain=+0.091, is_weak=False
【INFO】【2026-03-26 16:29:39】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:29:39] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=250, n_val=118,
    BAC=0.028, F1=0.000, AUC=0.503,
    Regret=0.606, BND_ratio=0.958, POS_coverage=0.000,
    Score(f1_regret_bnd )=-1.085，threshold_source=val
[INFO][BT][2026-03-26 16:29:39] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-1.072, bucket_Score=-1.085,
    Gain=-0.013, is_weak=True
【INFO】【2026-03-26 16:29:39】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er（n_val=114，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:29:39] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=134, n_val=114,
    BAC=0.322, F1=0.500, AUC=0.582,
    Regret=0.588, BND_ratio=0.500, POS_coverage=0.474,
    Score(f1_regret_bnd )=-0.338，threshold_source=val
[INFO][BT][2026-03-26 16:29:39] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.428, bucket_Score=-0.338,
    Gain=+0.090, is_weak=False
【INFO】【2026-03-26 16:29:39】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er（n_val=211，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:29:39] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=435, n_val=211,
    BAC=0.333, F1=0.539, AUC=0.695,
    Regret=0.564, BND_ratio=0.573, POS_coverage=0.360,
    Score(f1_regret_bnd )=-0.312，threshold_source=val
[INFO][BT][2026-03-26 16:29:39] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.428, bucket_Score=-0.312,
    Gain=+0.116, is_weak=False
【INFO】【2026-03-26 16:29:40】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:29:40] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=179, n_val=76,
    BAC=0.327, F1=0.620, AUC=0.700,
    Regret=0.518, BND_ratio=0.588, POS_coverage=0.365,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:40] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.428, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:40】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:29:40] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=171, n_val=161,
    BAC=0.019, F1=0.071, AUC=0.561,
    Regret=0.578, BND_ratio=0.988, POS_coverage=0.012,
    Score(f1_regret_bnd )=-1.000，threshold_source=val
[INFO][BT][2026-03-26 16:29:40] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.352, bucket_Score=-1.000,
    Gain=-0.648, is_weak=True
【INFO】【2026-03-26 16:29:40】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:29:40] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=9556, n_val=4191,
    BAC=0.491, F1=0.020, AUC=0.646,
    Regret=0.365, BND_ratio=0.031, POS_coverage=0.002,
    Score(f1_regret_bnd )=-0.361，threshold_source=val
[INFO][BT][2026-03-26 16:29:40] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.352, bucket_Score=-0.361,
    Gain=-0.008, is_weak=True
【INFO】【2026-03-26 16:29:41】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:29:41] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=184, n_val=282,
    BAC=0.199, F1=0.000, AUC=0.562,
    Regret=0.507, BND_ratio=0.613, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.814，threshold_source=val
[INFO][BT][2026-03-26 16:29:41] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.352, bucket_Score=-0.814,
    Gain=-0.462, is_weak=True
【INFO】【2026-03-26 16:29:41】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:41] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=168, n_val=72,
    BAC=0.153, F1=0.419, AUC=0.752,
    Regret=0.562, BND_ratio=0.887, POS_coverage=0.104,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:41] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.783, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:41】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:41] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=93, n_val=34,
    BAC=0.234, F1=0.105, AUC=0.695,
    Regret=0.433, BND_ratio=0.614, POS_coverage=0.016,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:41] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.783, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:41】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:41] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired level=3：
    n_train=128, n_val=72,
    BAC=nan, F1=nan, AUC=nan,
    Regret=nan, BND_ratio=nan, POS_coverage=nan,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:41] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.981, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:41】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:41] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=2761, n_val=1229,
    BAC=0.016, F1=0.000, AUC=0.548,
    Regret=0.584, BND_ratio=0.971, POS_coverage=0.000,
    Score(f1_regret_bnd )=-1.070，threshold_source=val
[INFO][BT][2026-03-26 16:29:41] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.981, bucket_Score=-1.070,
    Gain=-0.089, is_weak=True
【INFO】【2026-03-26 16:29:42】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp（n_val=199，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:29:42] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp level=3：
    n_train=541, n_val=199,
    BAC=0.175, F1=0.310, AUC=0.573,
    Regret=0.613, BND_ratio=0.749, POS_coverage=0.181,
    Score(f1_regret_bnd )=-0.678，threshold_source=val
[INFO][BT][2026-03-26 16:29:42] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.981, bucket_Score=-0.678,
    Gain=+0.303, is_weak=False
【INFO】【2026-03-26 16:29:42】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:42] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer level=3：
    n_train=2147, n_val=933,
    BAC=0.015, F1=0.031, AUC=0.551,
    Regret=0.596, BND_ratio=0.979, POS_coverage=0.010,
    Score(f1_regret_bnd )=-1.054，threshold_source=val
[INFO][BT][2026-03-26 16:29:42] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.981, bucket_Score=-1.054,
    Gain=-0.073, is_weak=True
【INFO】【2026-03-26 16:29:42】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:42] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=44, n_val=21,
    BAC=0.038, F1=0.133, AUC=0.709,
    Regret=0.592, BND_ratio=0.969, POS_coverage=0.031,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:42] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.981, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:42】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:42] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=213, n_val=78,
    BAC=0.364, F1=0.610, AUC=0.727,
    Regret=0.519, BND_ratio=0.481, POS_coverage=0.481,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:42] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.338, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:43】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:43] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=92, n_val=36,
    BAC=0.563, F1=0.627, AUC=0.774,
    Regret=0.477, BND_ratio=0.266, POS_coverage=0.477,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:43] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.338, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:43】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:43] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=764, n_val=363,
    BAC=0.108, F1=0.297, AUC=0.612,
    Regret=0.613, BND_ratio=0.873, POS_coverage=0.127,
    Score(f1_regret_bnd )=-0.752，threshold_source=val
[INFO][BT][2026-03-26 16:29:43] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.312, bucket_Score=-0.752,
    Gain=-0.441, is_weak=True
【INFO】【2026-03-26 16:29:43】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:43] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer level=3：
    n_train=577, n_val=257,
    BAC=0.180, F1=0.446, AUC=0.615,
    Regret=0.578, BND_ratio=0.821, POS_coverage=0.179,
    Score(f1_regret_bnd )=-0.542，threshold_source=val
[INFO][BT][2026-03-26 16:29:43] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.312, bucket_Score=-0.542,
    Gain=-0.230, is_weak=True
【INFO】【2026-03-26 16:29:43】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:43] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=168, n_val=88,
    BAC=0.440, F1=0.576, AUC=0.802,
    Regret=0.449, BND_ratio=0.504, POS_coverage=0.219,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:43] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.312, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:44】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home（n_val=114，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:29:44] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=238, n_val=114,
    BAC=0.154, F1=0.000, AUC=0.597,
    Regret=0.566, BND_ratio=0.711, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.921，threshold_source=val
[INFO][BT][2026-03-26 16:29:44] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-1.000, bucket_Score=-0.921,
    Gain=+0.079, is_weak=False
【INFO】【2026-03-26 16:29:44】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:29:44] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=124, n_val=47,
    BAC=0.432, F1=0.121, AUC=0.809,
    Regret=0.444, BND_ratio=0.269, POS_coverage=0.012,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:44] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-1.000, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:44】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er 的阈值

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:29:52] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:29:53】[BASELINE] 全局 XGB 模型训练完成
【INFO】【2026-03-26 16:29:53】[BASELINE] 阈值搜索开始
【INFO】【2026-03-26 16:29:54】[BASELINE] 最佳阈值找到: alpha=0.4000, beta=0.2000, regret=0.4011
【INFO】【2026-03-26 16:29:54】【桶树】已为样本生成桶ID，共 45 个组合
【INFO】【2026-03-26 16:29:54】[BASELINE] 测试集桶映射完成，共 45 个桶

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)

【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.2969, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5031, Regret=0.4800, Precision=0.3846, Recall=0.0081
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5012, Regret=0.6529, Precision=0.2222, Recall=0.0141
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5525, Regret=0.4764, Precision=0.5000, Recall=0.1269
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home: BAC=0.5505, Regret=0.6378, Precision=0.4688, Recall=0.1852
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home: BAC=0.4994, Regret=0.6549, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.6383, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=0.3866, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5848, Regret=0.7337, Precision=0.6471, Recall=0.2200
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.6889, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5512, Regret=0.6043, Precision=0.4231, Recall=0.1897
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home: BAC=0.5763, Regret=0.5878, Precision=0.4194, Recall=0.5200
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.6378, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5000, Regret=0.8081, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home: BAC=0.5278, Regret=0.7037, Precision=0.3750, Recall=0.3333
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5564, Regret=0.6061, Precision=0.5000, Recall=0.4286
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.4750, Regret=0.3043, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.4127, Regret=0.8243, Precision=0.1111, Recall=0.1111
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.5000, Regret=0.7326, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.6000, Regret=0.4815, Precision=1.0000, Recall=0.2000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.4878, Regret=0.3587, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer: BAC=0.6310, Regret=0.5800, Precision=0.5000, Recall=0.4286
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=0.5000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.3333, Regret=0.8333, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.8333, Regret=0.3333, Precision=1.0000, Recall=0.6667
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=1.0000, Regret=0.2500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.3333, Regret=0.6250, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home: BAC=0.5000, Regret=0.7500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=1.0000, Regret=0.3333, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=1.0000, Regret=0.2500, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=0.3000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.5000, Regret=1.5000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=OtherDisp: BAC=0.5000, Regret=0.5000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=1.0000, Regret=0.0000, Precision=1.0000, Recall=1.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=SNF_Rehab: BAC=0.0000, Regret=1.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Expired: BAC=1.0000, Regret=0.0000, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er: BAC=0.5084, Regret=0.3604, Precision=0.4762, Recall=0.0189
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt: BAC=0.5083, Regret=0.3666, Precision=0.4844, Recall=0.0187
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er: BAC=0.5130, Regret=0.6394, Precision=0.4643, Recall=0.0354
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt: BAC=0.5115, Regret=0.6377, Precision=0.4483, Recall=0.0321
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er: BAC=0.5396, Regret=0.6185, Precision=0.3803, Recall=0.1824
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt: BAC=0.5599, Regret=0.6124, Precision=0.4135, Recall=0.2644
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er: BAC=0.5000, Regret=0.6634, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er: BAC=0.4944, Regret=0.5288, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er: BAC=0.5788, Regret=0.5783, Precision=0.4565, Recall=0.5000
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er: BAC=0.5200, Regret=0.5852, Precision=1.0000, Recall=0.0400
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er: BAC=0.5819, Regret=0.6207, Precision=0.4375, Recall=0.3889
【INFO】【2026-03-26 16:29:56】[BASELINE] 桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er: BAC=0.5000, Regret=0.7143, Precision=0.0000, Recall=0.0000

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:697: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

【INFO】【2026-03-26 16:29:56】【K折实验】所有结果已写入 results 目录

,model,Precision_mean,Precision_std,Recall_mean,Recall_std,F1_mean,F1_std,BAC_mean,BAC_std,AUC_mean,...,MCC_mean,MCC_std,Kappa_mean,Kappa_std,BND_ratio_mean,BND_ratio_std,POS_Coverage_mean,POS_Coverage_std,Regret_mean,Regret_std
0,BTTWD,0.275114,0.011300,0.242319,0.012921,0.257519,0.010254,0.581014,0.005510,0.676102,...,0.171369,0.010872,0.170875,0.010911,0.147603,0.004935,0.01815,0.007188,0.393358,0.004287
1,LogReg,0.357968,0.028869,0.077397,0.006008,0.127210,0.009444,0.529955,0.003162,0.669471,...,0.122930,0.013118,0.091111,0.009546,0.000000,0.000000,NaN,NaN,0.427382,0.003136
2,RandomForest,0.366786,0.013253,0.091221,0.003174,0.146084,0.004819,0.535711,0.001665,0.651329,...,0.136902,0.006437,0.106347,0.004922,0.000000,0.000000,NaN,NaN,0.423265,0.001668
3,KNN,0.174797,0.007325,0.221185,0.010735,0.195245,0.008468,0.545007,0.005332,0.567914,...,0.081385,0.009514,0.080645,0.009416,0.000000,0.000000,NaN,NaN,0.464192,0.005247
4,XGBoost,0.387136,0.022915,0.098354,0.003774,0.156824,0.006376,0.539372,0.002322,0.678575,...,0.149406,0.010335,0.116842,0.007240,0.000000,0.000000,NaN,NaN,0.419914,0.002598

【INFO】【2026-03-26 16:29:57】【步骤6摘要】BTTWD 与基线的 k 折结果已生成并保存。

In [9]:
# 步骤7：桶级别分析
bucket_metrics_path = os.path.join(root_path, cfg['OUTPUT']['results_dir'], 'bucket_metrics.csv')
if os.path.exists(bucket_metrics_path):
    bucket_metrics_df = pd.read_csv(bucket_metrics_path)
    display(bucket_metrics_df.head())
    bucket_metrics_df.plot(x='bucket_id', y='pos_rate_all', kind='bar', figsize=(12,4), title='桶正类比例')
    plt.ylabel('正类比例')
    plt.xticks(rotation=90)
    plt.tight_layout()
    plt.savefig(fig_bucket, bbox_inches='tight')
    plt.close()
log_info('【步骤7摘要】桶级指标已整理，可用于局部化分析。')

,bucket_id,layer,parent_bucket_id,n_train,n_val,pos_rate_train,pos_rate_val,alpha,beta,regret_val,...,use_gain_weak_backoff,threshold_data_source,parent_with_threshold,n_test,pos_rate_test,BND_ratio_test,POS_Coverage_test,regret_test,fold,pos_rate
0,ROOT,L1,NaN,11397,4884,0.110994,0.111179,0.4,0.2,0.393837,...,True,val,NaN,NaN,NaN,NaN,NaN,NaN,1,0.111593
1,L1_number_inpatient=no_prev_inpt,L1,ROOT,9770,4318,0.092323,0.093330,0.4,0.2,0.360931,...,True,val,NaN,NaN,NaN,NaN,NaN,NaN,1,0.094130
2,L1_number_inpatient=no_prev_inpt|L2_number_eme...,L2,L1_number_inpatient=no_prev_inpt,9560,4204,0.091109,0.096337,0.4,0.2,0.369767,...,True,val,L1_number_inpatient=no_prev_inpt,NaN,NaN,NaN,NaN,NaN,1,0.093029
3,L1_number_inpatient=no_prev_inpt|L2_number_eme...,L3,L1_number_inpatient=no_prev_inpt|L2_number_eme...,29008,12336,0.073394,0.077983,0.5,0.4,0.311933,...,True,val,NaN,10331.0,0.075017,0.0,0.000097,0.300165,1,0.074763
4,L1_number_inpatient=no_prev_inpt|L2_number_eme...,L3,L1_number_inpatient=no_prev_inpt|L2_number_eme...,13892,6040,0.120933,0.124503,0.4,0.2,0.480712,...,True,val,L1_number_inpatient=no_prev_inpt,4936.0,0.129254,0.0,0.002431,0.493821,1,0.122015

C:\Users\xzq20.HUANLI\AppData\Local\Temp\ipykernel_19820\946468196.py:9: UserWarning: Tight layout not applied. The bottom and top margins cannot be made large enough to accommodate all Axes decorations.
  plt.tight_layout()

【INFO】【2026-03-26 16:30:00】【步骤7摘要】桶级指标已整理，可用于局部化分析。

In [10]:
# 步骤8：结果汇总
log_info('【步骤8】检查结果文件与图表。')
print(os.listdir(os.path.join(root_path, cfg['OUTPUT']['results_dir'])))
print(os.listdir(os.path.join(root_path, cfg['OUTPUT']['figs_dir'])))
log_info('【全部步骤完成】Telco Churn 数据集上的 BT-TWD 实验结束。')

【INFO】【2026-03-26 16:30:00】【步骤8】检查结果文件与图表。
['analysis_results', 'baseline_bucket_metrics.csv', 'bucket_fallback_stats.csv', 'bucket_metrics.csv', 'bucket_metrics_gain.csv', 'bucket_metrics_gain_test_per_fold.csv', 'bucket_thresholds.csv', 'bucket_thresholds_per_fold.csv', 'bucket_tree_structure.csv', 'fallback_off_tsne', 'fallback_on_tsne', 'metrics_kfold_per_fold.csv', 'metrics_kfold_summary.csv', 'metrics_overview.csv', 'per_sample_test_predictions.csv', 'tsne_fallback']
['bank_class_distribution.png', 'bucket_metrics_bar.png', 'class_distribution.png', 'metrics_compare.png']
【INFO】【2026-03-26 16:30:00】【全部步骤完成】Telco Churn 数据集上的 BT-TWD 实验结束。

In [11]:
# 步骤9：t-SNE 可视化弱桶对比
from bttwdlib import visualize_fallback_with_tsne
from IPython.display import Image

# 调用 t-SNE 可视化函数，参数从 YAML 配置中读取
tsne_output_dir = os.path.join(root_path, cfg["OUTPUT"]["results_dir"], "tsne_fallback")
os.makedirs(tsne_output_dir, exist_ok=True)
results = visualize_fallback_with_tsne(config_path=cfg_path, output_dir=tsne_output_dir)

# 显示保存的图片
Image(filename=results["figure_path"])

# 输出其他结果路径
print(f"t-SNE 嵌入结果保存路径：{results['embedding_path']}")
print(f"弱桶对比摘要保存路径：{results['summary_path']}")
print(f"可视化图片保存路径：{results['figure_path']}")

【INFO】【2026-03-26 16:30:00】【配置加载】已读取 e:\yan\组\三支决策\机器学习\BT_TWD\configs\diabetic_bttwd.yaml
【INFO】【2026-03-26 16:30:00】【数据加载】文本表格 ..\data\diabetic\diabetic_data.csv 已读取，样本数=101766，列数=50
【INFO】【2026-03-26 16:30:00】【数据加载】标签列 readmitted 已处理完成：dropna_target=False, 丢弃样本=0, 最终样本数=101766, 正类比例=11.16%
【INFO】【2026-03-26 16:30:00】【数据集信息】名称=diabetic，样本数=101766，目标列=readmitted，正类比例=11.16%
【INFO】【2026-03-26 16:30:01】【预处理】连续特征=8个，类别特征=35个
【INFO】【2026-03-26 16:30:02】【预处理】编码后维度=215
[t-SNE] Computing 121 nearest neighbors...
[t-SNE] Indexed 101766 samples in 0.048s...
[t-SNE] Computed neighbors for 101766 samples in 32.206s...
[t-SNE] Computed conditional probabilities for sample 1000 / 101766
[t-SNE] Computed conditional probabilities for sample 2000 / 101766
[t-SNE] Computed conditional probabilities for sample 3000 / 101766
[t-SNE] Computed conditional probabilities for sample 4000 / 101766
[t-SNE] Computed conditional probabilities for sample 5000 / 101766
[t-SNE] Computed conditional probabilities for sample 6000 / 101766
[t-SNE] Computed conditional probabilities for sample 7000 / 101766
[t-SNE] Computed conditional probabilities for sample 8000 / 101766
[t-SNE] Computed conditional probabilities for sample 9000 / 101766
[t-SNE] Computed conditional probabilities for sample 10000 / 101766
[t-SNE] Computed conditional probabilities for sample 11000 / 101766
[t-SNE] Computed conditional probabilities for sample 12000 / 101766
[t-SNE] Computed conditional probabilities for sample 13000 / 101766
[t-SNE] Computed conditional probabilities for sample 14000 / 101766
[t-SNE] Computed conditional probabilities for sample 15000 / 101766
[t-SNE] Computed conditional probabilities for sample 16000 / 101766
[t-SNE] Computed conditional probabilities for sample 17000 / 101766
[t-SNE] Computed conditional probabilities for sample 18000 / 101766
[t-SNE] Computed conditional probabilities for sample 19000 / 101766
[t-SNE] Computed conditional probabilities for sample 20000 / 101766
[t-SNE] Computed conditional probabilities for sample 21000 / 101766
[t-SNE] Computed conditional probabilities for sample 22000 / 101766
[t-SNE] Computed conditional probabilities for sample 23000 / 101766
[t-SNE] Computed conditional probabilities for sample 24000 / 101766
[t-SNE] Computed conditional probabilities for sample 25000 / 101766
[t-SNE] Computed conditional probabilities for sample 26000 / 101766
[t-SNE] Computed conditional probabilities for sample 27000 / 101766
[t-SNE] Computed conditional probabilities for sample 28000 / 101766
[t-SNE] Computed conditional probabilities for sample 29000 / 101766
[t-SNE] Computed conditional probabilities for sample 30000 / 101766
[t-SNE] Computed conditional probabilities for sample 31000 / 101766
[t-SNE] Computed conditional probabilities for sample 32000 / 101766
[t-SNE] Computed conditional probabilities for sample 33000 / 101766
[t-SNE] Computed conditional probabilities for sample 34000 / 101766
[t-SNE] Computed conditional probabilities for sample 35000 / 101766
[t-SNE] Computed conditional probabilities for sample 36000 / 101766
[t-SNE] Computed conditional probabilities for sample 37000 / 101766
[t-SNE] Computed conditional probabilities for sample 38000 / 101766
[t-SNE] Computed conditional probabilities for sample 39000 / 101766
[t-SNE] Computed conditional probabilities for sample 40000 / 101766
[t-SNE] Computed conditional probabilities for sample 41000 / 101766
[t-SNE] Computed conditional probabilities for sample 42000 / 101766
[t-SNE] Computed conditional probabilities for sample 43000 / 101766
[t-SNE] Computed conditional probabilities for sample 44000 / 101766
[t-SNE] Computed conditional probabilities for sample 45000 / 101766
[t-SNE] Computed conditional probabilities for sample 46000 / 101766
[t-SNE] Computed conditional probabilities for sample 47000 / 101766
[t-SNE] Computed conditional probabilities for sample 48000 / 101766
[t-SNE] Computed conditional probabilities for sample 49000 / 101766
[t-SNE] Computed conditional probabilities for sample 50000 / 101766
[t-SNE] Computed conditional probabilities for sample 51000 / 101766
[t-SNE] Computed conditional probabilities for sample 52000 / 101766
[t-SNE] Computed conditional probabilities for sample 53000 / 101766
[t-SNE] Computed conditional probabilities for sample 54000 / 101766
[t-SNE] Computed conditional probabilities for sample 55000 / 101766
[t-SNE] Computed conditional probabilities for sample 56000 / 101766
[t-SNE] Computed conditional probabilities for sample 57000 / 101766
[t-SNE] Computed conditional probabilities for sample 58000 / 101766
[t-SNE] Computed conditional probabilities for sample 59000 / 101766
[t-SNE] Computed conditional probabilities for sample 60000 / 101766
[t-SNE] Computed conditional probabilities for sample 61000 / 101766
[t-SNE] Computed conditional probabilities for sample 62000 / 101766
[t-SNE] Computed conditional probabilities for sample 63000 / 101766
[t-SNE] Computed conditional probabilities for sample 64000 / 101766
[t-SNE] Computed conditional probabilities for sample 65000 / 101766
[t-SNE] Computed conditional probabilities for sample 66000 / 101766
[t-SNE] Computed conditional probabilities for sample 67000 / 101766
[t-SNE] Computed conditional probabilities for sample 68000 / 101766
[t-SNE] Computed conditional probabilities for sample 69000 / 101766
[t-SNE] Computed conditional probabilities for sample 70000 / 101766
[t-SNE] Computed conditional probabilities for sample 71000 / 101766
[t-SNE] Computed conditional probabilities for sample 72000 / 101766
[t-SNE] Computed conditional probabilities for sample 73000 / 101766
[t-SNE] Computed conditional probabilities for sample 74000 / 101766
[t-SNE] Computed conditional probabilities for sample 75000 / 101766
[t-SNE] Computed conditional probabilities for sample 76000 / 101766
[t-SNE] Computed conditional probabilities for sample 77000 / 101766
[t-SNE] Computed conditional probabilities for sample 78000 / 101766
[t-SNE] Computed conditional probabilities for sample 79000 / 101766
[t-SNE] Computed conditional probabilities for sample 80000 / 101766
[t-SNE] Computed conditional probabilities for sample 81000 / 101766
[t-SNE] Computed conditional probabilities for sample 82000 / 101766
[t-SNE] Computed conditional probabilities for sample 83000 / 101766
[t-SNE] Computed conditional probabilities for sample 84000 / 101766
[t-SNE] Computed conditional probabilities for sample 85000 / 101766
[t-SNE] Computed conditional probabilities for sample 86000 / 101766
[t-SNE] Computed conditional probabilities for sample 87000 / 101766
[t-SNE] Computed conditional probabilities for sample 88000 / 101766
[t-SNE] Computed conditional probabilities for sample 89000 / 101766
[t-SNE] Computed conditional probabilities for sample 90000 / 101766
[t-SNE] Computed conditional probabilities for sample 91000 / 101766
[t-SNE] Computed conditional probabilities for sample 92000 / 101766
[t-SNE] Computed conditional probabilities for sample 93000 / 101766
[t-SNE] Computed conditional probabilities for sample 94000 / 101766
[t-SNE] Computed conditional probabilities for sample 95000 / 101766
[t-SNE] Computed conditional probabilities for sample 96000 / 101766
[t-SNE] Computed conditional probabilities for sample 97000 / 101766
[t-SNE] Computed conditional probabilities for sample 98000 / 101766
[t-SNE] Computed conditional probabilities for sample 99000 / 101766
[t-SNE] Computed conditional probabilities for sample 100000 / 101766
[t-SNE] Computed conditional probabilities for sample 101000 / 101766
[t-SNE] Computed conditional probabilities for sample 101766 / 101766
[t-SNE] Mean sigma: 0.895419
[t-SNE] KL divergence after 250 iterations with early exaggeration: 118.107895
[t-SNE] KL divergence after 1000 iterations: 4.411602
【INFO】【2026-03-26 16:37:44】[t-SNE] Finished embedding computation; adjusted perplexity=40.00, output shape=(101766, 2)
【INFO】【2026-03-26 16:37:44】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=0.5

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:37:44] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:37:45】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=101766
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="few_prev_inpt"，n_samples=10977
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="many_prev_inpt"，n_samples=3638
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="no_prev_inpt"，n_samples=87151
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=472
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=10033
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=472
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=534
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=2791
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=313
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=658
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=85236
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=1257
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=294
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=178
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Expired"，n_samples=252
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=4965
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="OtherDisp"，n_samples=909
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=3819
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=88
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=211
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=215
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=46
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=365
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=169
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=1410
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="OtherDisp"，n_samples=232
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=1064
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=85
[INFO][BT][2026-03-26 16:37:46] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er 不再细分：5 个子桶样本数不足 min_bucket_size=200
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=450
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=208
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Expired"，n_samples=1282
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=51675
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="OtherDisp"，n_samples=6863
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="SNF_Rehab"，n_samples=548
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=24868
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=707
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=454
[INFO][BT][2026-03-26 16:37:46] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=96
[INFO][BT][2026-03-26 16:37:52] 桶树构建完成：总桶数=39，最大层数=3，叶子桶数=27
【INFO】【2026-03-26 16:37:52】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 16:37:52】【阈值】桶 ROOT（n_val=6104，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:37:52] 桶 bucket_id=ROOT level=0：
    n_train=14245, n_val=6104,
    BAC=0.484, F1=0.092, AUC=0.661,
    Regret=0.395, BND_ratio=0.089, POS_coverage=0.011,
    Score(f1_regret_bnd )=-0.347，threshold_source=val
【INFO】【2026-03-26 16:37:52】【阈值】桶 L1_number_inpatient=few_prev_inpt 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:37:52] 桶 bucket_id=L1_number_inpatient=few_prev_inpt level=1：
    n_train=1510, n_val=914,
    BAC=0.035, F1=0.037, AUC=0.558,
    Regret=0.573, BND_ratio=0.945, POS_coverage=0.009,
    Score(f1_regret_bnd )=-1.009，threshold_source=val
[INFO][BT][2026-03-26 16:37:52] 桶 bucket_id=L1_number_inpatient=few_prev_inpt：
    parent_id=ROOT，parent_Score=-0.347, bucket_Score=-1.009,
    Gain=-0.662, is_weak=True
【INFO】【2026-03-26 16:37:52】【阈值】桶 L1_number_inpatient=many_prev_inpt（n_val=409，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:37:52] 桶 bucket_id=L1_number_inpatient=many_prev_inpt level=1：
    n_train=513, n_val=409,
    BAC=0.387, F1=0.536, AUC=0.659,
    Regret=0.588, BND_ratio=0.384, POS_coverage=0.609,
    Score(f1_regret_bnd )=-0.243，threshold_source=val
[INFO][BT][2026-03-26 16:37:52] 桶 bucket_id=L1_number_inpatient=many_prev_inpt：
    parent_id=ROOT，parent_Score=-0.347, bucket_Score=-0.243,
    Gain=+0.103, is_weak=False
【INFO】【2026-03-26 16:37:53】【阈值】桶 L1_number_inpatient=no_prev_inpt 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:37:53] 桶 bucket_id=L1_number_inpatient=no_prev_inpt level=1：
    n_train=12221, n_val=5207,
    BAC=0.489, F1=0.008, AUC=0.645,
    Regret=0.348, BND_ratio=0.033, POS_coverage=0.001,
    Score(f1_regret_bnd )=-0.357，threshold_source=val
[INFO][BT][2026-03-26 16:37:53] 桶 bucket_id=L1_number_inpatient=no_prev_inpt：
    parent_id=ROOT，parent_Score=-0.347, bucket_Score=-0.357,
    Gain=-0.010, is_weak=True
【INFO】【2026-03-26 16:37:53】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:37:53] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=164, n_val=143,
    BAC=0.018, F1=0.000, AUC=0.599,
    Regret=0.601, BND_ratio=0.972, POS_coverage=0.000,
    Score(f1_regret_bnd )=-1.087，threshold_source=val
[INFO][BT][2026-03-26 16:37:53] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-1.009, bucket_Score=-1.087,
    Gain=-0.079, is_weak=True
【INFO】【2026-03-26 16:37:53】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er（n_val=699，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:37:53] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=1577, n_val=699,
    BAC=0.111, F1=0.137, AUC=0.648,
    Regret=0.516, BND_ratio=0.850, POS_coverage=0.033,
    Score(f1_regret_bnd )=-0.803，threshold_source=val
[INFO][BT][2026-03-26 16:37:53] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-1.009, bucket_Score=-0.803,
    Gain=+0.205, is_weak=False
【INFO】【2026-03-26 16:37:54】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er（n_val=145，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:37:54] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=327, n_val=145,
    BAC=0.271, F1=0.074, AUC=0.638,
    Regret=0.521, BND_ratio=0.531, POS_coverage=0.007,
    Score(f1_regret_bnd )=-0.712，threshold_source=val
[INFO][BT][2026-03-26 16:37:54] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=-1.009, bucket_Score=-0.712,
    Gain=+0.296, is_weak=False
【INFO】【2026-03-26 16:37:54】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er（n_val=143，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:37:54] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=184, n_val=143,
    BAC=0.421, F1=0.620, AUC=0.677,
    Regret=0.535, BND_ratio=0.301, POS_coverage=0.692,
    Score(f1_regret_bnd )=-0.065，threshold_source=val
[INFO][BT][2026-03-26 16:37:54] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.243, bucket_Score=-0.065,
    Gain=+0.178, is_weak=False
【INFO】【2026-03-26 16:37:54】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:37:54] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=567, n_val=243,
    BAC=0.221, F1=0.261, AUC=0.622,
    Regret=0.562, BND_ratio=0.671, POS_coverage=0.136,
    Score(f1_regret_bnd )=-0.636，threshold_source=val
[INFO][BT][2026-03-26 16:37:54] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.243, bucket_Score=-0.636,
    Gain=-0.393, is_weak=True
【INFO】【2026-03-26 16:37:54】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er（n_val=101，source=val) 使用本地阈值 α=0.3000, β=0.0000
[INFO][BT][2026-03-26 16:37:54] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=212, n_val=101,
    BAC=0.408, F1=0.559, AUC=0.564,
    Regret=0.589, BND_ratio=0.277, POS_coverage=0.723,
    Score(f1_regret_bnd )=-0.169，threshold_source=val
[INFO][BT][2026-03-26 16:37:54] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=-0.243, bucket_Score=-0.169,
    Gain=+0.074, is_weak=False
【INFO】【2026-03-26 16:37:54】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:37:54] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=201, n_val=202,
    BAC=0.154, F1=0.162, AUC=0.672,
    Regret=0.510, BND_ratio=0.782, POS_coverage=0.030,
    Score(f1_regret_bnd )=-0.739，threshold_source=val
[INFO][BT][2026-03-26 16:37:54] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.357, bucket_Score=-0.739,
    Gain=-0.382, is_weak=True
【INFO】【2026-03-26 16:37:55】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:37:55] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=11952, n_val=5207,
    BAC=0.490, F1=0.004, AUC=0.635,
    Regret=0.361, BND_ratio=0.028, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.371，threshold_source=val
[INFO][BT][2026-03-26 16:37:55] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.357, bucket_Score=-0.371,
    Gain=-0.014, is_weak=True
【INFO】【2026-03-26 16:37:55】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er 标记为弱桶，阈值将回退使用 L1_number_inpatient=no_prev_inpt 的阈值
[INFO][BT][2026-03-26 16:37:55] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=226, n_val=206,
    BAC=0.500, F1=0.000, AUC=0.597,
    Regret=0.388, BND_ratio=0.000, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.388，threshold_source=val
[INFO][BT][2026-03-26 16:37:55] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=-0.357, bucket_Score=-0.388,
    Gain=-0.032, is_weak=True
【INFO】【2026-03-26 16:37:55】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:37:55] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=206, n_val=88,
    BAC=0.000, F1=0.000, AUC=0.537,
    Regret=0.619, BND_ratio=1.000, POS_coverage=0.000,
    Score(f1_regret_bnd )=-1.119，threshold_source=val
[INFO][BT][2026-03-26 16:37:55] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-1.087, bucket_Score=-1.119,
    Gain=-0.032, is_weak=True
【INFO】【2026-03-26 16:37:55】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:37:55] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=123, n_val=55,
    BAC=0.249, F1=0.167, AUC=0.685,
    Regret=0.494, BND_ratio=0.607, POS_coverage=0.034,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:37:55] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-1.087, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:37:55】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:37:55] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired level=3：
    n_train=181, n_val=71,
    BAC=nan, F1=nan, AUC=nan,
    Regret=nan, BND_ratio=nan, POS_coverage=nan,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:37:55] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.803, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:37:56】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:37:56] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=3416, n_val=1549,
    BAC=0.018, F1=0.015, AUC=0.583,
    Regret=0.578, BND_ratio=0.970, POS_coverage=0.004,
    Score(f1_regret_bnd )=-1.049，threshold_source=val
[INFO][BT][2026-03-26 16:37:56] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.803, bucket_Score=-1.049,
    Gain=-0.245, is_weak=True
【INFO】【2026-03-26 16:37:56】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp（n_val=278，source=val) 使用本地阈值 α=0.3000, β=0.0000
[INFO][BT][2026-03-26 16:37:56] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp level=3：
    n_train=631, n_val=278,
    BAC=0.180, F1=0.370, AUC=0.621,
    Regret=0.595, BND_ratio=0.791, POS_coverage=0.209,
    Score(f1_regret_bnd )=-0.621，threshold_source=val
[INFO][BT][2026-03-26 16:37:56] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.803, bucket_Score=-0.621,
    Gain=+0.182, is_weak=False
【INFO】【2026-03-26 16:37:56】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:37:56] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer level=3：
    n_train=2610, n_val=1209,
    BAC=0.014, F1=0.033, AUC=0.529,
    Regret=0.593, BND_ratio=0.983, POS_coverage=0.007,
    Score(f1_regret_bnd )=-1.051，threshold_source=val
[INFO][BT][2026-03-26 16:37:56] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.803, bucket_Score=-1.051,
    Gain=-0.248, is_weak=True
【INFO】【2026-03-26 16:37:56】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:37:56] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=65, n_val=23,
    BAC=0.333, F1=0.211, AUC=0.826,
    Regret=0.386, BND_ratio=0.511, POS_coverage=0.034,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:37:56] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.803, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:37:57】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er 的阈值
[INFO][BT][2026-03-26 16:37:57] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=144, n_val=67,
    BAC=0.286, F1=0.048, AUC=0.707,
    Regret=0.514, BND_ratio=0.507, POS_coverage=0.005,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:37:57] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，parent_Score=-0.712, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:37:57】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er 的阈值
[INFO][BT][2026-03-26 16:37:57] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer level=3：
    n_train=146, n_val=69,
    BAC=0.237, F1=0.154, AUC=0.704,
    Regret=0.505, BND_ratio=0.628, POS_coverage=0.014,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:37:57] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，parent_Score=-0.712, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:37:57】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er 的阈值
[INFO][BT][2026-03-26 16:37:57] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=37, n_val=9,
    BAC=0.282, F1=0.000, AUC=0.864,
    Regret=0.337, BND_ratio=0.522, POS_coverage=0.000,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:37:57] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，parent_Score=-0.712, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:37:57】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:37:57] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=258, n_val=107,
    BAC=0.402, F1=0.622, AUC=0.665,
    Regret=0.537, BND_ratio=0.318, POS_coverage=0.682,
    Score(f1_regret_bnd )=-0.074，threshold_source=val
[INFO][BT][2026-03-26 16:37:57] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.065, bucket_Score=-0.074,
    Gain=-0.009, is_weak=True
【INFO】【2026-03-26 16:37:57】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er 的阈值
[INFO][BT][2026-03-26 16:37:57] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=133, n_val=36,
    BAC=0.560, F1=0.667, AUC=0.779,
    Regret=0.464, BND_ratio=0.302, POS_coverage=0.420,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:37:57] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=-0.065, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:37:58】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home（n_val=406，source=val) 使用本地阈值 α=0.3000, β=0.0000
[INFO][BT][2026-03-26 16:37:58] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=1004, n_val=406,
    BAC=0.261, F1=0.426, AUC=0.607,
    Regret=0.621, BND_ratio=0.603, POS_coverage=0.397,
    Score(f1_regret_bnd )=-0.496，threshold_source=val
[INFO][BT][2026-03-26 16:37:58] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.636, bucket_Score=-0.496,
    Gain=+0.140, is_weak=False
【INFO】【2026-03-26 16:37:58】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 的阈值
[INFO][BT][2026-03-26 16:37:58] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp level=3：
    n_train=160, n_val=72,
    BAC=0.307, F1=0.492, AUC=0.745,
    Regret=0.530, BND_ratio=0.642, POS_coverage=0.224,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:37:58] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=-0.636, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:37:58】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer 标记为弱桶，阈值将回退使用 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er 的阈值

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:38:21] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:38:23】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=101766
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="few_prev_inpt"，n_samples=10977
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="many_prev_inpt"，n_samples=3638
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt，level=1，parent_id=ROOT，split_name=L1_number_inpatient，split_type=numeric_bin，split_rule="no_prev_inpt"，n_samples=87151
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=472
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=10033
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=few_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=472
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=534
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=2791
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=many_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=313
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="multi_prev_er"，n_samples=658
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="no_prev_er"，n_samples=85236
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，level=2，parent_id=L1_number_inpatient=no_prev_inpt，split_name=L2_number_emergency，split_type=numeric_bin，split_rule="one_prev_er"，n_samples=1257
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=294
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=178
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Expired"，n_samples=252
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=4965
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="OtherDisp"，n_samples=909
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=3819
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=88
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=211
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=215
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=46
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=365
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=169
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=1410
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="OtherDisp"，n_samples=232
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=1064
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=85
[INFO][BT][2026-03-26 16:38:24] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er 不再细分：5 个子桶样本数不足 min_bucket_size=200
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=450
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=208
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Expired"，n_samples=1282
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=51675
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="OtherDisp"，n_samples=6863
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=SNF_Rehab，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="SNF_Rehab"，n_samples=548
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=24868
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Home"，n_samples=707
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="Transfer"，n_samples=454
[INFO][BT][2026-03-26 16:38:24] 创建桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=others，level=3，parent_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er，split_name=L3_discharge_disposition_id，split_type=category_group，split_rule="others"，n_samples=96
[INFO][BT][2026-03-26 16:38:30] 桶树构建完成：总桶数=39，最大层数=3，叶子桶数=27
【INFO】【2026-03-26 16:38:30】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 16:38:31】【阈值】桶 ROOT（n_val=6104，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:38:31] 桶 bucket_id=ROOT level=0：
    n_train=14245, n_val=6104,
    BAC=0.484, F1=0.092, AUC=0.661,
    Regret=0.395, BND_ratio=0.089, POS_coverage=0.011,
    Score(f1_regret_bnd )=nan，threshold_source=val
【INFO】【2026-03-26 16:38:31】【阈值】桶 L1_number_inpatient=few_prev_inpt（n_val=914，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 16:38:31] 桶 bucket_id=L1_number_inpatient=few_prev_inpt level=1：
    n_train=1510, n_val=914,
    BAC=0.035, F1=0.037, AUC=0.558,
    Regret=0.573, BND_ratio=0.945, POS_coverage=0.009,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:31] 桶 bucket_id=L1_number_inpatient=few_prev_inpt：
    parent_id=ROOT，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:31】【阈值】桶 L1_number_inpatient=many_prev_inpt（n_val=409，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:38:31] 桶 bucket_id=L1_number_inpatient=many_prev_inpt level=1：
    n_train=513, n_val=409,
    BAC=0.387, F1=0.536, AUC=0.659,
    Regret=0.588, BND_ratio=0.384, POS_coverage=0.609,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:31] 桶 bucket_id=L1_number_inpatient=many_prev_inpt：
    parent_id=ROOT，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:32】【阈值】桶 L1_number_inpatient=no_prev_inpt（n_val=5207，source=val) 使用本地阈值 α=0.5000, β=0.2000
[INFO][BT][2026-03-26 16:38:32] 桶 bucket_id=L1_number_inpatient=no_prev_inpt level=1：
    n_train=12221, n_val=5207,
    BAC=0.489, F1=0.008, AUC=0.645,
    Regret=0.348, BND_ratio=0.033, POS_coverage=0.001,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:32] 桶 bucket_id=L1_number_inpatient=no_prev_inpt：
    parent_id=ROOT，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:32】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er（n_val=143，source=val) 使用本地阈值 α=0.6000, β=0.1000
[INFO][BT][2026-03-26 16:38:32] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=164, n_val=143,
    BAC=0.018, F1=0.000, AUC=0.599,
    Regret=0.601, BND_ratio=0.972, POS_coverage=0.000,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:32] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:32】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er（n_val=699，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:38:32] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=1577, n_val=699,
    BAC=0.111, F1=0.137, AUC=0.648,
    Regret=0.516, BND_ratio=0.850, POS_coverage=0.033,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:32] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:32】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er（n_val=145，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:38:32] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=327, n_val=145,
    BAC=0.271, F1=0.074, AUC=0.638,
    Regret=0.521, BND_ratio=0.531, POS_coverage=0.007,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:32] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=few_prev_inpt，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:33】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er（n_val=143，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:38:33] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=184, n_val=143,
    BAC=0.421, F1=0.620, AUC=0.677,
    Regret=0.535, BND_ratio=0.301, POS_coverage=0.692,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:33] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:33】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er（n_val=243，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:38:33] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=567, n_val=243,
    BAC=0.221, F1=0.261, AUC=0.622,
    Regret=0.562, BND_ratio=0.671, POS_coverage=0.136,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:33] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:33】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er（n_val=101，source=val) 使用本地阈值 α=0.3000, β=0.0000
[INFO][BT][2026-03-26 16:38:33] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=212, n_val=101,
    BAC=0.408, F1=0.559, AUC=0.564,
    Regret=0.589, BND_ratio=0.277, POS_coverage=0.723,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:33] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=many_prev_inpt，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:33】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er（n_val=202，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:38:33] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er level=2：
    n_train=201, n_val=202,
    BAC=0.154, F1=0.162, AUC=0.672,
    Regret=0.510, BND_ratio=0.782, POS_coverage=0.030,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:33] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=multi_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:34】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er（n_val=5207，source=val) 使用本地阈值 α=0.5000, β=0.2000
[INFO][BT][2026-03-26 16:38:34] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er level=2：
    n_train=11952, n_val=5207,
    BAC=0.490, F1=0.004, AUC=0.635,
    Regret=0.361, BND_ratio=0.028, POS_coverage=0.000,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:34] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=no_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:34】【阈值】桶 L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er（n_val=206，source=val) 使用本地阈值 α=0.6000, β=0.5000
[INFO][BT][2026-03-26 16:38:34] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er level=2：
    n_train=226, n_val=206,
    BAC=0.500, F1=0.000, AUC=0.597,
    Regret=0.388, BND_ratio=0.000, POS_coverage=0.000,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:34] 桶 bucket_id=L1_number_inpatient=no_prev_inpt|L2_number_emergency=one_prev_er：
    parent_id=L1_number_inpatient=no_prev_inpt，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:34】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home（n_val=88，source=val) 使用本地阈值 α=0.4000, β=0.0000
[INFO][BT][2026-03-26 16:38:34] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=206, n_val=88,
    BAC=0.000, F1=0.000, AUC=0.537,
    Regret=0.619, BND_ratio=1.000, POS_coverage=0.000,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:34] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:34】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others（n_val=55，source=all) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:38:34] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=123, n_val=55,
    BAC=0.249, F1=0.167, AUC=0.685,
    Regret=0.494, BND_ratio=0.607, POS_coverage=0.034,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:38:34] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:34】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired（n_val=71，source=all) 使用本地阈值 α=1.0000, β=1.0000
[INFO][BT][2026-03-26 16:38:34] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired level=3：
    n_train=181, n_val=71,
    BAC=nan, F1=nan, AUC=nan,
    Regret=nan, BND_ratio=nan, POS_coverage=nan,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:38:34] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Expired：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:35】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home（n_val=1549，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:38:35] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=3416, n_val=1549,
    BAC=0.018, F1=0.015, AUC=0.583,
    Regret=0.578, BND_ratio=0.970, POS_coverage=0.004,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:35] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:35】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp（n_val=278，source=val) 使用本地阈值 α=0.3000, β=0.0000
[INFO][BT][2026-03-26 16:38:35] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp level=3：
    n_train=631, n_val=278,
    BAC=0.180, F1=0.370, AUC=0.621,
    Regret=0.595, BND_ratio=0.791, POS_coverage=0.209,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:35] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:35】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer（n_val=1209，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 16:38:35] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer level=3：
    n_train=2610, n_val=1209,
    BAC=0.014, F1=0.033, AUC=0.529,
    Regret=0.593, BND_ratio=0.983, POS_coverage=0.007,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:35] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:35】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others（n_val=23，source=all) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:38:35] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=65, n_val=23,
    BAC=0.333, F1=0.211, AUC=0.826,
    Regret=0.386, BND_ratio=0.511, POS_coverage=0.034,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:38:35] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:36】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home（n_val=67，source=all) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:38:36] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=144, n_val=67,
    BAC=0.286, F1=0.048, AUC=0.707,
    Regret=0.514, BND_ratio=0.507, POS_coverage=0.005,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:38:36] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:36】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer（n_val=69，source=all) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:38:36] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer level=3：
    n_train=146, n_val=69,
    BAC=0.237, F1=0.154, AUC=0.704,
    Regret=0.505, BND_ratio=0.628, POS_coverage=0.014,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:38:36] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=Transfer：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:36】【阈值】桶 L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=others（n_val=9，source=all) 使用本地阈值 α=0.5000, β=0.2000
[INFO][BT][2026-03-26 16:38:36] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=37, n_val=9,
    BAC=0.282, F1=0.000, AUC=0.864,
    Regret=0.337, BND_ratio=0.522, POS_coverage=0.000,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:38:36] 桶 bucket_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=few_prev_inpt|L2_number_emergency=one_prev_er，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:37】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home（n_val=107，source=val) 使用本地阈值 α=0.3000, β=0.0000
[INFO][BT][2026-03-26 16:38:37] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=258, n_val=107,
    BAC=0.402, F1=0.622, AUC=0.665,
    Regret=0.537, BND_ratio=0.318, POS_coverage=0.682,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:37] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:37】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others（n_val=36，source=all) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 16:38:37] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others level=3：
    n_train=133, n_val=36,
    BAC=0.560, F1=0.667, AUC=0.779,
    Regret=0.464, BND_ratio=0.302, POS_coverage=0.420,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:38:37] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er|L3_discharge_disposition_id=others：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=multi_prev_er，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:37】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home（n_val=406，source=val) 使用本地阈值 α=0.3000, β=0.0000
[INFO][BT][2026-03-26 16:38:37] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home level=3：
    n_train=1004, n_val=406,
    BAC=0.261, F1=0.426, AUC=0.607,
    Regret=0.621, BND_ratio=0.603, POS_coverage=0.397,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:37] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Home：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:37】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp（n_val=72，source=all) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:38:37] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp level=3：
    n_train=160, n_val=72,
    BAC=0.307, F1=0.492, AUC=0.745,
    Regret=0.530, BND_ratio=0.642, POS_coverage=0.224,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:38:37] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=OtherDisp：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:38:38】【阈值】桶 L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer（n_val=321，source=val) 使用本地阈值 α=0.5000, β=0.2000
[INFO][BT][2026-03-26 16:38:38] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer level=3：
    n_train=743, n_val=321,
    BAC=0.089, F1=0.133, AUC=0.593,
    Regret=0.611, BND_ratio=0.879, POS_coverage=0.031,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:38:38] 桶 bucket_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er|L3_discharge_disposition_id=Transfer：
    parent_id=L1_number_inpatient=many_prev_inpt|L2_number_emergency=no_prev_er，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\tsne_visualizer.py:389: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  fig.tight_layout()

【INFO】【2026-03-26 16:39:20】[t-SNE] Comparison figure saved to: e:\yan\组\三支决策\机器学习\BT_TWD\results\diabetic_bttwd\tsne_fallback\tsne_backoff_diabetic.png
【INFO】【2026-03-26 16:39:20】[t-SNE] Comparison figure saved to: e:\yan\组\三支决策\机器学习\BT_TWD\results\diabetic_bttwd\tsne_fallback\tsne_backoff_diabetic.pdf
t-SNE 嵌入结果保存路径：e:\yan\组\三支决策\机器学习\BT_TWD\results\diabetic_bttwd\tsne_fallback\tsne_fallback_embedding.csv
弱桶对比摘要保存路径：e:\yan\组\三支决策\机器学习\BT_TWD\results\diabetic_bttwd\tsne_fallback\tsne_fallback_summary.csv
可视化图片保存路径：e:\yan\组\三支决策\机器学习\BT_TWD\results\diabetic_bttwd\tsne_fallback\tsne_backoff_diabetic.png