weatherAUS 数据集 BT-TWD 可行性实验

本 notebook 按步骤运行：加载配置 → 读取数据 → 预处理 → 桶树划分 → 基线与 BTTWD k 折实验 → 桶级分析。

In [1]:
# 步骤0：环境与路径设置
import os, sys
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif'] = ['Microsoft YaHei']
plt.rcParams['axes.unicode_minus'] = False

# 将项目根目录加入路径，便于导入 bttwdlib
root_path = os.path.abspath(os.path.join(os.getcwd(), '..'))
if root_path not in sys.path:
    sys.path.append(root_path)

from bttwdlib import (
    load_yaml_cfg,
    show_cfg,
    load_dataset,
    prepare_features_and_labels,
    BucketTree,
    run_kfold_experiments,
    log_info,
    set_global_seed,
)

cfg_path = Path(root_path) / "configs" / "credit_default_bttwd.yaml"
cfg = load_yaml_cfg(cfg_path)
set_global_seed(cfg.get('SEED', {}).get('global_seed', 42))
log_info('【步骤0摘要】环境准备完毕，路径与随机种子已设置。')

【INFO】【2026-03-26 16:22:55】【配置加载】已读取 e:\yan\组\三支决策\机器学习\BT_TWD\configs\credit_default_bttwd.yaml
【INFO】【2026-03-26 16:23:00】【步骤0摘要】环境准备完毕，路径与随机种子已设置。

In [2]:
# 步骤1：加载配置
show_cfg(cfg)
log_info('【步骤1摘要】配置文件加载完成，关键参数检查通过。')

【INFO】【2026-03-26 16:23:00】【配置-数据】数据集=credit_default, k折=None, 目标列=default payment next month, 正类="1"
【INFO】【2026-03-26 16:23:00】【配置-BTTWD】阈值模式=bucket_wise, 全局模型=xgb, 桶内模型=none, 后验估计器(兼容字段)=logreg
【INFO】【2026-03-26 16:23:00】【配置-基线】LogReg启用=True, RandomForest启用=True, KNN启用=True, XGBoost启用=True
【INFO】【2026-03-26 16:23:00】【步骤1摘要】配置文件加载完成，关键参数检查通过。

In [3]:
# 步骤2：加载原始数据
df_raw, target_col_model = load_dataset(cfg)  # 这里返回的是用于建模的标签列，例如 "label"

display(df_raw.head())
print("用于建模的标签列:", target_col_model)


# 1）画 0/1 标签（流失/未流失）的比例
class_counts = df_raw[target_col_model].value_counts(normalize=True)
ax = class_counts.plot(kind='bar', title='流失 vs 未流失比例')
plt.ylabel('比例')

fig_path = os.path.join(root_path, cfg['OUTPUT']['figs_dir'], 'class_distribution.png')
os.makedirs(os.path.dirname(fig_path), exist_ok=True)
plt.savefig(fig_path, bbox_inches='tight')
plt.close()

# 2）如果想看原始标签列的分布，可以另外单独分析：
raw_target_col = cfg['DATA']['target_col']  # 这里是原始标签列
print("原始目标列:", raw_target_col)
print(df_raw[raw_target_col].describe())

log_info('【步骤2摘要】Telco Churn 原始数据加载与基本统计完成。')

【INFO】【2026-03-26 16:23:03】【数据加载】目标列 default payment next month 已检测为 0/1 标签，跳过映射逻辑
【INFO】【2026-03-26 16:23:03】【数据集信息】名称=credit_default，样本数=30000，目标列=default payment next month，正类比例=22.12%

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

用于建模的标签列: default payment next month
原始目标列: default payment next month
count    30000.000000
mean         0.221200
std          0.415062
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: default payment next month, dtype: float64
【INFO】【2026-03-26 16:23:03】【步骤2摘要】Telco Churn 原始数据加载与基本统计完成。

In [4]:
# 步骤3：预处理与特征工程
X, y, meta = prepare_features_and_labels(df_raw, cfg)
log_info(f'【预处理】编码特征维度={X.shape[1]}，样本数={X.shape[0]}')
log_info(f"【步骤3摘要】特征预处理完成：连续={len(meta['continuous_cols'])}，类别={len(meta['categorical_cols'])}，编码维度={X.shape[1]}。")

【INFO】【2026-03-26 16:23:03】【预处理】缺失值填充策略=median
【INFO】【2026-03-26 16:23:03】已生成 credit_default 派生特征：ever_delay / max_delay / max_delay_bin
【INFO】【2026-03-26 16:23:03】ever_delay 分布：
ever_delay
0    19931
1    10069
【INFO】【2026-03-26 16:23:03】max_delay_bin 分布：
max_delay_bin
0      19931
1-2     8876
3-4     1007
5+       186
【INFO】【2026-03-26 16:23:03】max_delay_bins=[-0.1, 0, 2, 4, 9], labels=['0', '1-2', '3-4', '5+']
【INFO】【2026-03-26 16:23:03】【预处理】连续特征=14个，类别特征=5个
【INFO】【2026-03-26 16:23:03】【预处理】编码后维度=33
【INFO】【2026-03-26 16:23:03】【预处理】编码特征维度=33，样本数=30000
【INFO】【2026-03-26 16:23:03】【步骤3摘要】特征预处理完成：连续=14，类别=5，编码维度=33。

In [5]:
# 步骤4：构建桶树并检查划分（✅与主流程一致：使用步骤3生成的 df_processed）
df_processed = meta.get("df_processed", df_raw)

# 只取桶层真正用到的列，避免把一堆无关列塞进分桶检查
bucket_cols = []
for lvl in cfg["BTTWD"]["bucket_levels"]:
    col_name = lvl.get("col") or lvl.get("feature")
    if col_name and col_name not in bucket_cols:
        bucket_cols.append(col_name)

bucket_tree = BucketTree(
    cfg["BTTWD"]["bucket_levels"],
    feature_names=bucket_cols
)

# ✅关键：用 df_processed（已包含 ever_delay / max_delay_bin）
bucket_ids_full = bucket_tree.assign_buckets(df_processed[bucket_cols])

bucket_df = bucket_ids_full.value_counts().reset_index()
bucket_df.columns = ["bucket_id", "count"]

# 正类比例也用 df_processed 对齐（目标列仍在 df_processed 里）
bucket_df["pos_rate"] = (
    df_processed.groupby(bucket_ids_full)[target_col_model]
    .apply(lambda s: (s == 1).mean())
    .values
)

display(bucket_df.head())

bucket_df.set_index("bucket_id")["count"].plot(
    kind="bar", figsize=(12, 4), title="桶样本数分布"
)
fig_bucket = os.path.join(root_path, cfg["OUTPUT"]["figs_dir"], "bucket_metrics_bar.png")
plt.savefig(fig_bucket, bbox_inches="tight")
plt.close()

log_info(f"【步骤4摘要】桶树划分完成，共有 {bucket_ids_full.nunique()} 个叶子桶。")

【INFO】【2026-03-26 16:23:03】【桶树】已为样本生成桶ID，共 12 个组合

                                           bucket_id  count  pos_rate
0  L1_ever_delay=no_delay|L2_max_delay_bin=none|L...   7565  0.697674
1  L1_ever_delay=no_delay|L2_max_delay_bin=none|L...   6468  0.612500
2  L1_ever_delay=no_delay|L2_max_delay_bin=none|L...   5898  0.646766
3  L1_ever_delay=has_delay|L2_max_delay_bin=mild|...   4044  0.317972
4  L1_ever_delay=has_delay|L2_max_delay_bin=mild|...   2879  0.447577

【INFO】【2026-03-26 16:23:04】【步骤4摘要】桶树划分完成，共有 12 个叶子桶。

In [6]:
# 步骤5：运行基线模型 k 折实验
# 基线部分在 run_kfold_experiments 内统一调度
log_info('【步骤5】基线模型将在整体交叉验证中一并运行。')
log_info('【步骤5摘要】基线模型性能将作为后续对比基准。')

【INFO】【2026-03-26 16:23:04】【步骤5】基线模型将在整体交叉验证中一并运行。
【INFO】【2026-03-26 16:23:04】【步骤5摘要】基线模型性能将作为后续对比基准。

In [7]:
import numpy as np
import pandas as pd

print("y 全局标签分布：", np.unique(y, return_counts=True))

print("原始标签列分布：")
print(df_raw[cfg['DATA']['target_col']].value_counts())

y 全局标签分布： (array([0, 1]), array([23364,  6636], dtype=int64))
原始标签列分布：
default payment next month
0    23364
1     6636
Name: count, dtype: int64

In [8]:
# 步骤6：运行 BTTWD k 折实验（含基线）——✅使用 df_processed 作为分桶输入
df_processed = meta.get("df_processed", df_raw)

# 训练/分桶用的 df 不能包含标签列
target_col = cfg["DATA"]["target_col"]
X_df_for_bucket = df_processed.drop(columns=[target_col], errors="ignore")

results = run_kfold_experiments(X, y, X_df_for_bucket, cfg)

summary_path = os.path.join(root_path, cfg["OUTPUT"]["results_dir"], "metrics_kfold_summary.csv")
summary_df = pd.read_csv(summary_path)
display(summary_df)

【INFO】【2026-03-26 16:23:04】【基线-LogReg】使用决策阈值=0.300（fixed 模式）

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\baselines.py:109: RuntimeWarning: Mean of empty slice
  summary[f"{col}_mean"] = float(np.nanmean(arr))
d:\Anaconda3\Lib\site-packages\numpy\lib\nanfunctions.py:1879: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

【INFO】【2026-03-26 16:23:06】【基线-LogReg】整体指标：AUC_mean=0.745, AUC_std=0.006, BAC_mean=0.702, BAC_std=0.005, BND_ratio_mean=0.000, BND_ratio_std=0.000, F1_mean=0.520, F1_std=0.006, Kappa_mean=0.353, Kappa_std=0.009, MCC_mean=0.363, MCC_std=0.009, POS_Coverage_mean=nan, POS_Coverage_std=nan, Precision_mean=0.445, Precision_std=0.007, Recall_mean=0.627, Recall_std=0.014, Regret_mean=0.421, Regret_std=0.007
【INFO】【2026-03-26 16:23:06】【基线-RF】使用决策阈值=0.300（fixed 模式）

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\baselines.py:109: RuntimeWarning: Mean of empty slice
  summary[f"{col}_mean"] = float(np.nanmean(arr))
d:\Anaconda3\Lib\site-packages\numpy\lib\nanfunctions.py:1879: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

【INFO】【2026-03-26 16:23:30】【基线-RF】整体指标：AUC_mean=0.755, AUC_std=0.004, BAC_mean=0.698, BAC_std=0.007, BND_ratio_mean=0.000, BND_ratio_std=0.000, F1_mean=0.517, F1_std=0.009, Kappa_mean=0.355, Kappa_std=0.011, MCC_mean=0.361, MCC_std=0.012, POS_Coverage_mean=nan, POS_Coverage_std=nan, Precision_mean=0.455, Precision_std=0.008, Recall_mean=0.599, Recall_std=0.014, Regret_mean=0.425, Regret_std=0.009
【INFO】【2026-03-26 16:23:30】【基线-KNN】使用决策阈值=0.300（fixed 模式）

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\baselines.py:109: RuntimeWarning: Mean of empty slice
  summary[f"{col}_mean"] = float(np.nanmean(arr))
d:\Anaconda3\Lib\site-packages\numpy\lib\nanfunctions.py:1879: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

【INFO】【2026-03-26 16:23:37】【基线-KNN】整体指标：AUC_mean=0.690, AUC_std=0.007, BAC_mean=0.653, BAC_std=0.008, BND_ratio_mean=0.000, BND_ratio_std=0.000, F1_mean=0.456, F1_std=0.009, Kappa_mean=0.246, Kappa_std=0.012, MCC_mean=0.263, MCC_std=0.013, POS_Coverage_mean=nan, POS_Coverage_std=nan, Precision_mean=0.363, Precision_std=0.007, Recall_mean=0.613, Recall_std=0.016, Regret_mean=0.495, Regret_std=0.011
【INFO】【2026-03-26 16:23:37】【基线-XGB】使用决策阈值=0.300（fixed 模式）

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:23:37] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:23:41] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:23:46] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:23:49] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:23:53] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\baselines.py:109: RuntimeWarning: Mean of empty slice
  summary[f"{col}_mean"] = float(np.nanmean(arr))
d:\Anaconda3\Lib\site-packages\numpy\lib\nanfunctions.py:1879: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

【INFO】【2026-03-26 16:23:55】【基线-XGB】整体指标：AUC_mean=0.762, AUC_std=0.004, BAC_mean=0.701, BAC_std=0.007, BND_ratio_mean=0.000, BND_ratio_std=0.000, F1_mean=0.523, F1_std=0.010, Kappa_mean=0.368, Kappa_std=0.013, MCC_mean=0.372, MCC_std=0.013, POS_Coverage_mean=nan, POS_Coverage_std=nan, Precision_mean=0.471, Precision_std=0.010, Recall_mean=0.589, Recall_std=0.013, Regret_mean=0.419, Regret_std=0.010
【INFO】【2026-03-26 16:23:55】【K折实验】正在执行第 1/5 折...
【INFO】【2026-03-26 16:23:55】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=0.5

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:23:56] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:23:59】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 16:24:01] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=24000
[INFO][BT][2026-03-26 16:24:01] 创建桶 bucket_id=L1_ever_delay=has_delay，level=1，parent_id=ROOT，split_name=L1_ever_delay，split_type=numeric_bin，split_rule="has_delay"，n_samples=7994
[INFO][BT][2026-03-26 16:24:01] 创建桶 bucket_id=L1_ever_delay=no_delay，level=1，parent_id=ROOT，split_name=L1_ever_delay，split_type=numeric_bin，split_rule="no_delay"，n_samples=16006
[INFO][BT][2026-03-26 16:24:01] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="medium"，n_samples=813
[INFO][BT][2026-03-26 16:24:01] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="mild"，n_samples=7037
[INFO][BT][2026-03-26 16:24:01] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="others"，n_samples=144
[INFO][BT][2026-03-26 16:24:01] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，level=2，parent_id=L1_ever_delay=no_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="none"，n_samples=16006
[INFO][BT][2026-03-26 16:24:01] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=581
[INFO][BT][2026-03-26 16:24:01] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="others"，n_samples=232
[INFO][BT][2026-03-26 16:24:01] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="high_limit"，n_samples=1515
[INFO][BT][2026-03-26 16:24:01] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=3251
[INFO][BT][2026-03-26 16:24:01] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="mid_limit"，n_samples=2271
[INFO][BT][2026-03-26 16:24:01] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="high_limit"，n_samples=6062
[INFO][BT][2026-03-26 16:24:01] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=4787
[INFO][BT][2026-03-26 16:24:01] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="mid_limit"，n_samples=5157
[INFO][BT][2026-03-26 16:24:05] 桶树构建完成：总桶数=15，最大层数=3，叶子桶数=9
【INFO】【2026-03-26 16:24:05】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 16:24:06】【阈值】桶 ROOT（n_val=1439，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:24:06] 桶 bucket_id=ROOT level=0：
    n_train=3360, n_val=1439,
    BAC=0.565, F1=0.471, AUC=0.745,
    Regret=0.415, BND_ratio=0.202, POS_coverage=0.185,
    Score(f1_regret_bnd )=-0.045，threshold_source=val
【INFO】【2026-03-26 16:24:07】【阈值】桶 L1_ever_delay=has_delay 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:24:07] 桶 bucket_id=L1_ever_delay=has_delay level=1：
    n_train=1193, n_val=518,
    BAC=0.389, F1=0.617, AUC=0.622,
    Regret=0.509, BND_ratio=0.371, POS_coverage=0.597,
    Score(f1_regret_bnd )=-0.077，threshold_source=val
[INFO][BT][2026-03-26 16:24:07] 桶 bucket_id=L1_ever_delay=has_delay：
    parent_id=ROOT，parent_Score=-0.045, bucket_Score=-0.077,
    Gain=-0.032, is_weak=True
【INFO】【2026-03-26 16:24:08】【阈值】桶 L1_ever_delay=no_delay 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:24:08] 桶 bucket_id=L1_ever_delay=no_delay level=1：
    n_train=2236, n_val=965,
    BAC=0.494, F1=0.017, AUC=0.641,
    Regret=0.342, BND_ratio=0.025, POS_coverage=0.002,
    Score(f1_regret_bnd )=-0.337，threshold_source=val
[INFO][BT][2026-03-26 16:24:08] 桶 bucket_id=L1_ever_delay=no_delay：
    parent_id=ROOT，parent_Score=-0.045, bucket_Score=-0.337,
    Gain=-0.292, is_weak=True
【INFO】【2026-03-26 16:24:09】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium（n_val=239，source=val) 使用本地阈值 α=0.2000, β=0.0000
[INFO][BT][2026-03-26 16:24:09] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium level=2：
    n_train=244, n_val=239,
    BAC=0.500, F1=0.764, AUC=0.596,
    Regret=0.383, BND_ratio=0.004, POS_coverage=0.996,
    Score(f1_regret_bnd )=0.379，threshold_source=val
[INFO][BT][2026-03-26 16:24:09] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.077, bucket_Score=0.379,
    Gain=+0.456, is_weak=False
【INFO】【2026-03-26 16:24:10】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay 的阈值
[INFO][BT][2026-03-26 16:24:10] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild level=2：
    n_train=991, n_val=415,
    BAC=0.397, F1=0.532, AUC=0.637,
    Regret=0.540, BND_ratio=0.354, POS_coverage=0.513,
    Score(f1_regret_bnd )=-0.185，threshold_source=val
[INFO][BT][2026-03-26 16:24:10] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.077, bucket_Score=-0.185,
    Gain=-0.108, is_weak=True
【INFO】【2026-03-26 16:24:11】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=others 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay 的阈值
[INFO][BT][2026-03-26 16:24:11] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others level=2：
    n_train=88, n_val=56,
    BAC=0.510, F1=0.836, AUC=0.806,
    Regret=0.292, BND_ratio=0.090, POS_coverage=0.896,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:24:11] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.077, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:24:12】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none 标记为弱桶，阈值将回退使用 L1_ever_delay=no_delay 的阈值
[INFO][BT][2026-03-26 16:24:12] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none level=2：
    n_train=2235, n_val=964,
    BAC=0.435, F1=0.018, AUC=0.641,
    Regret=0.342, BND_ratio=0.150, POS_coverage=0.002,
    Score(f1_regret_bnd )=-0.399，threshold_source=val
[INFO][BT][2026-03-26 16:24:12] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none：
    parent_id=L1_ever_delay=no_delay，parent_Score=-0.337, bucket_Score=-0.399,
    Gain=-0.062, is_weak=True
【INFO】【2026-03-26 16:24:13】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值
[INFO][BT][2026-03-26 16:24:13] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit level=3：
    n_train=412, n_val=169,
    BAC=0.497, F1=0.745, AUC=0.578,
    Regret=0.402, BND_ratio=0.030, POS_coverage=0.964,
    Score(f1_regret_bnd )=0.328，threshold_source=val
[INFO][BT][2026-03-26 16:24:13] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，parent_Score=0.379, bucket_Score=0.328,
    Gain=-0.051, is_weak=True
【INFO】【2026-03-26 16:24:14】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值
[INFO][BT][2026-03-26 16:24:14] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others level=3：
    n_train=162, n_val=70,
    BAC=0.566, F1=0.825, AUC=0.797,
    Regret=0.296, BND_ratio=0.060, POS_coverage=0.879,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:24:14] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，parent_Score=0.379, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:24:14】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值
[INFO][BT][2026-03-26 16:24:14] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit level=3：
    n_train=1087, n_val=428,
    BAC=0.187, F1=0.406, AUC=0.597,
    Regret=0.571, BND_ratio=0.706, POS_coverage=0.294,
    Score(f1_regret_bnd )=-0.518，threshold_source=val
[INFO][BT][2026-03-26 16:24:14] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.185, bucket_Score=-0.518,
    Gain=-0.333, is_weak=True
【INFO】【2026-03-26 16:24:15】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit（n_val=985，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:24:15] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit level=3：
    n_train=2266, n_val=985,
    BAC=0.408, F1=0.592, AUC=0.587,
    Regret=0.533, BND_ratio=0.288, POS_coverage=0.665,
    Score(f1_regret_bnd )=-0.085，threshold_source=val
[INFO][BT][2026-03-26 16:24:15] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.185, bucket_Score=-0.085,
    Gain=+0.100, is_weak=False
【INFO】【2026-03-26 16:24:16】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit（n_val=666，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 16:24:16] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit level=3：
    n_train=1605, n_val=666,
    BAC=0.339, F1=0.582, AUC=0.689,
    Regret=0.504, BND_ratio=0.517, POS_coverage=0.444,
    Score(f1_regret_bnd )=-0.180，threshold_source=val
[INFO][BT][2026-03-26 16:24:16] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.185, bucket_Score=-0.180,
    Gain=+0.005, is_weak=False
【INFO】【2026-03-26 16:24:18】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit（n_val=1775，source=val) 使用本地阈值 α=0.5000, β=0.3000
[INFO][BT][2026-03-26 16:24:18] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit level=3：
    n_train=4287, n_val=1775,
    BAC=0.498, F1=0.024, AUC=0.651,
    Regret=0.275, BND_ratio=0.020, POS_coverage=0.001,
    Score(f1_regret_bnd )=-0.262，threshold_source=val
[INFO][BT][2026-03-26 16:24:18] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.399, bucket_Score=-0.262,
    Gain=+0.138, is_weak=False
【INFO】【2026-03-26 16:24:19】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=no_delay|L2_max_delay_bin=none 的阈值
[INFO][BT][2026-03-26 16:24:19] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit level=3：
    n_train=3310, n_val=1477,
    BAC=0.482, F1=0.000, AUC=0.568,
    Regret=0.444, BND_ratio=0.039, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.463，threshold_source=val
[INFO][BT][2026-03-26 16:24:19] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.399, bucket_Score=-0.463,
    Gain=-0.064, is_weak=True
【INFO】【2026-03-26 16:24:20】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit（n_val=1574，source=val) 使用本地阈值 α=0.5000, β=0.2000
[INFO][BT][2026-03-26 16:24:20] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit level=3：
    n_train=3583, n_val=1574,
    BAC=0.449, F1=0.000, AUC=0.666,
    Regret=0.325, BND_ratio=0.118, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.384，threshold_source=val
[INFO][BT][2026-03-26 16:24:20] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.399, bucket_Score=-0.384,
    Gain=+0.015, is_weak=False
[INFO][BT][2026-03-26 16:24:20] 桶 bucket_id=L1_ever_delay=has_delay 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:24:20] 桶 bucket_id=L1_ever_delay=no_delay 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:24:20] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:24:20] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:24:20] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:24:20] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值(alpha=0.2000,beta=0.0000)
[INFO][BT][2026-03-26 16:24:20] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值(alpha=0.2000,beta=0.0000)
[INFO][BT][2026-03-26 16:24:20] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:24:20] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
【INFO】【2026-03-26 16:24:20】【BTTWD】桶统计摘要：总桶数=15，非空桶=15，强桶=6，弱桶=9
【INFO】【2026-03-26 16:24:20】【BTTWD】共生成 9 个叶子桶，其中有效桶 0 个（已训练局部模型）
【INFO】【2026-03-26 16:24:20】【资源评估-K折第1折】当前配置：父桶贡献=开启，最小样本限制=开启，回退机制=开启；训练耗时=24.602 秒，最大内存占用≈2221.01 MB
[INFO][BT][2026-03-26 16:24:23] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit：
    assigned_samples=139,
    used_local_decision=0,
    fallback_to_parent=139,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium,
    is_weak=True
[INFO][BT][2026-03-26 16:24:23] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium：
    assigned_samples=0,
    used_local_decision=194,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay,
    is_weak=False
[INFO][BT][2026-03-26 16:24:23] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others：
    assigned_samples=55,
    used_local_decision=0,
    fallback_to_parent=55,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium,
    is_weak=True
[INFO][BT][2026-03-26 16:24:23] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit：
    assigned_samples=438,
    used_local_decision=0,
    fallback_to_parent=438,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=True
[INFO][BT][2026-03-26 16:24:23] 预测统计：bucket_id=ROOT：
    assigned_samples=0,
    used_local_decision=1591,
    fallback_to_parent=0,
    parent_id=ROOT,
    is_weak=False
[INFO][BT][2026-03-26 16:24:23] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit：
    assigned_samples=793,
    used_local_decision=793,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=False
[INFO][BT][2026-03-26 16:24:23] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit：
    assigned_samples=608,
    used_local_decision=608,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=False
[INFO][BT][2026-03-26 16:24:23] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others：
    assigned_samples=42,
    used_local_decision=0,
    fallback_to_parent=42,
    parent_id=L1_ever_delay=has_delay,
    is_weak=True
[INFO][BT][2026-03-26 16:24:23] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit：
    assigned_samples=1503,
    used_local_decision=1503,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=False
[INFO][BT][2026-03-26 16:24:23] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit：
    assigned_samples=1111,
    used_local_decision=0,
    fallback_to_parent=1111,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=True
[INFO][BT][2026-03-26 16:24:23] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit：
    assigned_samples=1311,
    used_local_decision=1311,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=False
[INFO][BT][2026-03-26 16:24:23] 回退汇总：
    总样本数=6000,
    使用叶子桶决策的样本比例=70.250%,
    使用中间桶决策的样本比例=3.233%,
    回退到全局桶决策的样本比例=26.517%
【INFO】【2026-03-26 16:24:24】【BTTWD】三支指标(含后悔)：Precision=0.446, Recall=0.653, F1=0.530, BAC=0.711, AUC=0.765, MCC=0.375, Kappa=0.362, BND_ratio=0.181, POS_Coverage=0.199, Regret=0.392
【INFO】【2026-03-26 16:24:25】[BASELINE] 数据拆分完成（train/val/test）
【INFO】【2026-03-26 16:24:25】[BASELINE] 全局 XGB 模型开始训练

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:24:25] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:24:30】[BASELINE] 全局 XGB 模型训练完成
【INFO】【2026-03-26 16:24:30】[BASELINE] 阈值搜索开始
【INFO】【2026-03-26 16:24:31】[BASELINE] 最佳阈值找到: alpha=0.4000, beta=0.2000, regret=0.4069
【INFO】【2026-03-26 16:24:31】【桶树】已为样本生成桶ID，共 12 个组合
【INFO】【2026-03-26 16:24:31】[BASELINE] 测试集桶映射完成，共 12 个桶
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit: BAC=0.5119, Regret=0.2640, Precision=0.4444, Recall=0.0274
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit: BAC=0.5944, Regret=0.5370, Precision=0.4659, Recall=0.5778
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit: BAC=0.5698, Regret=0.5107, Precision=0.5413, Recall=0.7584
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit: BAC=0.5871, Regret=0.5634, Precision=0.4031, Recall=0.4194
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit: BAC=0.4983, Regret=0.2759, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit: BAC=0.5081, Regret=0.4563, Precision=0.7500, Recall=0.0173
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=high_limit: BAC=0.4286, Regret=0.2647, Precision=0.8000, Recall=0.8571
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit: BAC=0.5203, Regret=0.3831, Precision=0.6288, Recall=0.9651
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe|L3_LIMIT_BAL=low_limit: BAC=0.5000, Regret=0.4062, Precision=0.5938, Recall=1.0000
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=mid_limit: BAC=0.5064, Regret=0.4145, Precision=0.6875, Recall=0.8462
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe|L3_LIMIT_BAL=high_limit: BAC=0.5000, Regret=0.4000, Precision=0.6000, Recall=1.0000
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe|L3_LIMIT_BAL=mid_limit: BAC=0.5000, Regret=0.8000, Precision=0.2000, Recall=1.0000
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none: BAC=0.5065, Regret=0.3224, Precision=0.4118, Recall=0.0159
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=no_delay: BAC=0.5065, Regret=0.3224, Precision=0.4118, Recall=0.0159
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild: BAC=0.6070, Regret=0.5319, Precision=0.5005, Recall=0.6463
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=has_delay: BAC=0.6134, Regret=0.5160, Precision=0.5256, Recall=0.6956
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium: BAC=0.5084, Regret=0.3789, Precision=0.6536, Recall=0.9286
【INFO】【2026-03-26 16:24:33】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe: BAC=0.5000, Regret=0.4524, Precision=0.5476, Recall=1.0000
【INFO】【2026-03-26 16:24:33】【K折实验】正在执行第 2/5 折...
【INFO】【2026-03-26 16:24:33】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=0.5

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:24:34] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:24:35】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 16:24:37] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=24000
[INFO][BT][2026-03-26 16:24:37] 创建桶 bucket_id=L1_ever_delay=has_delay，level=1，parent_id=ROOT，split_name=L1_ever_delay，split_type=numeric_bin，split_rule="has_delay"，n_samples=8089
[INFO][BT][2026-03-26 16:24:37] 创建桶 bucket_id=L1_ever_delay=no_delay，level=1，parent_id=ROOT，split_name=L1_ever_delay，split_type=numeric_bin，split_rule="no_delay"，n_samples=15911
[INFO][BT][2026-03-26 16:24:37] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="medium"，n_samples=780
[INFO][BT][2026-03-26 16:24:37] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="mild"，n_samples=7158
[INFO][BT][2026-03-26 16:24:37] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="others"，n_samples=151
[INFO][BT][2026-03-26 16:24:37] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，level=2，parent_id=L1_ever_delay=no_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="none"，n_samples=15911
[INFO][BT][2026-03-26 16:24:37] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=563
[INFO][BT][2026-03-26 16:24:37] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="others"，n_samples=217
[INFO][BT][2026-03-26 16:24:37] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="high_limit"，n_samples=1575
[INFO][BT][2026-03-26 16:24:37] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=3247
[INFO][BT][2026-03-26 16:24:37] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="mid_limit"，n_samples=2336
[INFO][BT][2026-03-26 16:24:37] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="high_limit"，n_samples=6067
[INFO][BT][2026-03-26 16:24:37] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=4676
[INFO][BT][2026-03-26 16:24:37] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="mid_limit"，n_samples=5168
[INFO][BT][2026-03-26 16:24:42] 桶树构建完成：总桶数=15，最大层数=3，叶子桶数=9
【INFO】【2026-03-26 16:24:42】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 16:24:43】【阈值】桶 ROOT（n_val=1439，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:24:43] 桶 bucket_id=ROOT level=0：
    n_train=3360, n_val=1439,
    BAC=0.596, F1=0.503, AUC=0.781,
    Regret=0.373, BND_ratio=0.190, POS_coverage=0.199,
    Score(f1_regret_bnd )=0.035，threshold_source=val
【INFO】【2026-03-26 16:24:44】【阈值】桶 L1_ever_delay=has_delay 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:24:44] 桶 bucket_id=L1_ever_delay=has_delay level=1：
    n_train=1218, n_val=519,
    BAC=0.389, F1=0.624, AUC=0.671,
    Regret=0.503, BND_ratio=0.370, POS_coverage=0.597,
    Score(f1_regret_bnd )=-0.064，threshold_source=val
[INFO][BT][2026-03-26 16:24:44] 桶 bucket_id=L1_ever_delay=has_delay：
    parent_id=ROOT，parent_Score=0.035, bucket_Score=-0.064,
    Gain=-0.099, is_weak=True
【INFO】【2026-03-26 16:24:45】【阈值】桶 L1_ever_delay=no_delay 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:24:45] 桶 bucket_id=L1_ever_delay=no_delay level=1：
    n_train=2225, n_val=957,
    BAC=0.492, F1=0.000, AUC=0.621,
    Regret=0.304, BND_ratio=0.021, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.314，threshold_source=val
[INFO][BT][2026-03-26 16:24:45] 桶 bucket_id=L1_ever_delay=no_delay：
    parent_id=ROOT，parent_Score=0.035, bucket_Score=-0.314,
    Gain=-0.349, is_weak=True
【INFO】【2026-03-26 16:24:46】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium（n_val=221，source=val) 使用本地阈值 α=0.1000, β=0.0000
[INFO][BT][2026-03-26 16:24:46] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium level=2：
    n_train=234, n_val=221,
    BAC=0.500, F1=0.758, AUC=0.510,
    Regret=0.389, BND_ratio=0.000, POS_coverage=1.000,
    Score(f1_regret_bnd )=0.369，threshold_source=val
[INFO][BT][2026-03-26 16:24:46] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.064, bucket_Score=0.369,
    Gain=+0.434, is_weak=False
【INFO】【2026-03-26 16:24:47】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild（n_val=428，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:24:47] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild level=2：
    n_train=1001, n_val=428,
    BAC=0.442, F1=0.604, AUC=0.651,
    Regret=0.494, BND_ratio=0.318, POS_coverage=0.572,
    Score(f1_regret_bnd )=-0.049，threshold_source=val
[INFO][BT][2026-03-26 16:24:47] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.064, bucket_Score=-0.049,
    Gain=+0.015, is_weak=False
【INFO】【2026-03-26 16:24:48】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=others 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay 的阈值
[INFO][BT][2026-03-26 16:24:48] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others level=2：
    n_train=105, n_val=46,
    BAC=0.576, F1=0.824, AUC=0.807,
    Regret=0.296, BND_ratio=0.113, POS_coverage=0.801,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:24:48] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.064, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:24:49】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none（n_val=956，source=val) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 16:24:49] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none level=2：
    n_train=2224, n_val=956,
    BAC=0.500, F1=0.019, AUC=0.686,
    Regret=0.317, BND_ratio=0.016, POS_coverage=0.001,
    Score(f1_regret_bnd )=-0.306，threshold_source=val
[INFO][BT][2026-03-26 16:24:49] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none：
    parent_id=L1_ever_delay=no_delay，parent_Score=-0.314, bucket_Score=-0.306,
    Gain=+0.008, is_weak=False
【INFO】【2026-03-26 16:24:50】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值
[INFO][BT][2026-03-26 16:24:50] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit level=3：
    n_train=406, n_val=157,
    BAC=0.500, F1=0.747, AUC=0.461,
    Regret=0.404, BND_ratio=0.006, POS_coverage=0.994,
    Score(f1_regret_bnd )=0.339，threshold_source=val
[INFO][BT][2026-03-26 16:24:50] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，parent_Score=0.369, bucket_Score=0.339,
    Gain=-0.030, is_weak=True
【INFO】【2026-03-26 16:24:50】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值
[INFO][BT][2026-03-26 16:24:50] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others level=3：
    n_train=153, n_val=64,
    BAC=0.552, F1=0.848, AUC=0.841,
    Regret=0.279, BND_ratio=0.124, POS_coverage=0.811,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:24:50] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，parent_Score=0.369, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:24:52】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值
[INFO][BT][2026-03-26 16:24:52] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit level=3：
    n_train=1123, n_val=452,
    BAC=0.171, F1=0.398, AUC=0.620,
    Regret=0.560, BND_ratio=0.763, POS_coverage=0.237,
    Score(f1_regret_bnd )=-0.543，threshold_source=val
[INFO][BT][2026-03-26 16:24:52] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.049, bucket_Score=-0.543,
    Gain=-0.494, is_weak=True
【INFO】【2026-03-26 16:24:53】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit（n_val=996，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:24:53] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit level=3：
    n_train=2251, n_val=996,
    BAC=0.456, F1=0.637, AUC=0.620,
    Regret=0.497, BND_ratio=0.212, POS_coverage=0.740,
    Score(f1_regret_bnd )=0.034，threshold_source=val
[INFO][BT][2026-03-26 16:24:53] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.049, bucket_Score=0.034,
    Gain=+0.083, is_weak=False
【INFO】【2026-03-26 16:24:54】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值
[INFO][BT][2026-03-26 16:24:54] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit level=3：
    n_train=1637, n_val=699,
    BAC=0.373, F1=0.543, AUC=0.638,
    Regret=0.531, BND_ratio=0.426, POS_coverage=0.479,
    Score(f1_regret_bnd )=-0.201，threshold_source=val
[INFO][BT][2026-03-26 16:24:54] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.049, bucket_Score=-0.201,
    Gain=-0.152, is_weak=True
【INFO】【2026-03-26 16:24:54】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit（n_val=1832，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:24:54] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit level=3：
    n_train=4235, n_val=1832,
    BAC=0.484, F1=0.091, AUC=0.709,
    Regret=0.264, BND_ratio=0.094, POS_coverage=0.009,
    Score(f1_regret_bnd )=-0.220，threshold_source=val
[INFO][BT][2026-03-26 16:24:54] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.306, bucket_Score=-0.220,
    Gain=+0.086, is_weak=False
【INFO】【2026-03-26 16:24:55】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=no_delay|L2_max_delay_bin=none 的阈值
[INFO][BT][2026-03-26 16:24:55] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit level=3：
    n_train=3281, n_val=1395,
    BAC=0.484, F1=0.000, AUC=0.556,
    Regret=0.424, BND_ratio=0.039, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.444，threshold_source=val
[INFO][BT][2026-03-26 16:24:55] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.306, bucket_Score=-0.444,
    Gain=-0.137, is_weak=True
【INFO】【2026-03-26 16:24:56】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=no_delay|L2_max_delay_bin=none 的阈值
[INFO][BT][2026-03-26 16:24:56] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit level=3：
    n_train=3609, n_val=1559,
    BAC=0.500, F1=0.000, AUC=0.603,
    Regret=0.335, BND_ratio=0.000, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.335，threshold_source=val
[INFO][BT][2026-03-26 16:24:56] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.306, bucket_Score=-0.335,
    Gain=-0.028, is_weak=True
[INFO][BT][2026-03-26 16:24:56] 桶 bucket_id=L1_ever_delay=has_delay 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:24:56] 桶 bucket_id=L1_ever_delay=no_delay 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:24:56] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:24:56] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值(alpha=0.1000,beta=0.0000)
[INFO][BT][2026-03-26 16:24:56] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值(alpha=0.1000,beta=0.0000)
[INFO][BT][2026-03-26 16:24:56] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:24:56] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:24:56] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=no_delay|L2_max_delay_bin=none 的阈值(alpha=0.4000,beta=0.3000)
[INFO][BT][2026-03-26 16:24:56] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=no_delay|L2_max_delay_bin=none 的阈值(alpha=0.4000,beta=0.3000)
【INFO】【2026-03-26 16:24:56】【BTTWD】桶统计摘要：总桶数=15，非空桶=15，强桶=6，弱桶=9
【INFO】【2026-03-26 16:24:56】【BTTWD】共生成 9 个叶子桶，其中有效桶 0 个（已训练局部模型）
【INFO】【2026-03-26 16:24:56】【资源评估-K折第2折】当前配置：父桶贡献=开启，最小样本限制=开启，回退机制=开启；训练耗时=22.516 秒，最大内存占用≈2220.80 MB
[INFO][BT][2026-03-26 16:24:58] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit：
    assigned_samples=157,
    used_local_decision=0,
    fallback_to_parent=157,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium,
    is_weak=True
[INFO][BT][2026-03-26 16:24:58] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium：
    assigned_samples=0,
    used_local_decision=227,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay,
    is_weak=False
[INFO][BT][2026-03-26 16:24:58] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others：
    assigned_samples=70,
    used_local_decision=0,
    fallback_to_parent=70,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium,
    is_weak=True
[INFO][BT][2026-03-26 16:24:58] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit：
    assigned_samples=378,
    used_local_decision=0,
    fallback_to_parent=378,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=True
[INFO][BT][2026-03-26 16:24:58] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild：
    assigned_samples=0,
    used_local_decision=921,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay,
    is_weak=False
[INFO][BT][2026-03-26 16:24:58] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit：
    assigned_samples=797,
    used_local_decision=797,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=False
[INFO][BT][2026-03-26 16:24:58] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit：
    assigned_samples=543,
    used_local_decision=0,
    fallback_to_parent=543,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=True
[INFO][BT][2026-03-26 16:24:58] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others：
    assigned_samples=35,
    used_local_decision=0,
    fallback_to_parent=35,
    parent_id=L1_ever_delay=has_delay,
    is_weak=True
[INFO][BT][2026-03-26 16:24:58] 预测统计：bucket_id=ROOT：
    assigned_samples=0,
    used_local_decision=35,
    fallback_to_parent=0,
    parent_id=ROOT,
    is_weak=False
[INFO][BT][2026-03-26 16:24:58] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit：
    assigned_samples=1498,
    used_local_decision=1498,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=False
[INFO][BT][2026-03-26 16:24:58] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit：
    assigned_samples=1222,
    used_local_decision=0,
    fallback_to_parent=1222,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=True
[INFO][BT][2026-03-26 16:24:58] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none：
    assigned_samples=0,
    used_local_decision=2522,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=no_delay,
    is_weak=False
[INFO][BT][2026-03-26 16:24:58] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit：
    assigned_samples=1300,
    used_local_decision=0,
    fallback_to_parent=1300,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=True
[INFO][BT][2026-03-26 16:24:58] 回退汇总：
    总样本数=6000,
    使用叶子桶决策的样本比例=38.250%,
    使用中间桶决策的样本比例=61.167%,
    回退到全局桶决策的样本比例=0.583%
【INFO】【2026-03-26 16:24:58】【BTTWD】三支指标(含后悔)：Precision=0.433, Recall=0.628, F1=0.513, BAC=0.697, AUC=0.753, MCC=0.351, Kappa=0.340, BND_ratio=0.136, POS_Coverage=0.196, Regret=0.412
【INFO】【2026-03-26 16:24:59】[BASELINE] 数据拆分完成（train/val/test）
【INFO】【2026-03-26 16:24:59】[BASELINE] 全局 XGB 模型开始训练

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:25:00] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:25:12】[BASELINE] 全局 XGB 模型训练完成
【INFO】【2026-03-26 16:25:12】[BASELINE] 阈值搜索开始
【INFO】【2026-03-26 16:25:13】[BASELINE] 最佳阈值找到: alpha=0.4000, beta=0.2000, regret=0.4001
【INFO】【2026-03-26 16:25:13】【桶树】已为样本生成桶ID，共 11 个组合
【INFO】【2026-03-26 16:25:13】[BASELINE] 测试集桶映射完成，共 11 个桶
【INFO】【2026-03-26 16:25:14】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit: BAC=0.5785, Regret=0.5445, Precision=0.4690, Recall=0.8193
【INFO】【2026-03-26 16:25:14】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit: BAC=0.4990, Regret=0.4327, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:25:14】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit: BAC=0.5957, Regret=0.5317, Precision=0.5158, Recall=0.3769
【INFO】【2026-03-26 16:25:14】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit: BAC=0.5055, Regret=0.2739, Precision=0.2857, Recall=0.0146
【INFO】【2026-03-26 16:25:14】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit: BAC=0.5057, Regret=0.3619, Precision=0.6667, Recall=0.0122
【INFO】【2026-03-26 16:25:14】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit: BAC=0.5802, Regret=0.5520, Precision=0.4912, Recall=0.5161
【INFO】【2026-03-26 16:25:14】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=mid_limit: BAC=0.4893, Regret=0.4348, Precision=0.5814, Recall=0.9259
【INFO】【2026-03-26 16:25:14】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit: BAC=0.5064, Regret=0.3854, Precision=0.6209, Recall=0.9794
【INFO】【2026-03-26 16:25:14】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe|L3_LIMIT_BAL=low_limit: BAC=0.6000, Regret=0.2727, Precision=0.7419, Recall=1.0000
【INFO】【2026-03-26 16:25:14】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=high_limit: BAC=0.4062, Regret=0.5208, Precision=0.6190, Recall=0.8125
【INFO】【2026-03-26 16:25:14】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe|L3_LIMIT_BAL=mid_limit: BAC=0.5000, Regret=0.5000, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 16:25:14】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild: BAC=0.5927, Regret=0.5441, Precision=0.4795, Recall=0.6377
【INFO】【2026-03-26 16:25:14】[BASELINE] 桶 L1_ever_delay=has_delay: BAC=0.6024, Regret=0.5241, Precision=0.5117, Recall=0.6999
【INFO】【2026-03-26 16:25:14】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none: BAC=0.5030, Regret=0.3506, Precision=0.3333, Recall=0.0083
【INFO】【2026-03-26 16:25:14】[BASELINE] 桶 L1_ever_delay=no_delay: BAC=0.5030, Regret=0.3506, Precision=0.3333, Recall=0.0083
【INFO】【2026-03-26 16:25:14】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium: BAC=0.4922, Regret=0.4097, Precision=0.6129, Recall=0.9500
【INFO】【2026-03-26 16:25:14】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe: BAC=0.5909, Regret=0.2857, Precision=0.7273, Recall=1.0000
【INFO】【2026-03-26 16:25:15】【K折实验】正在执行第 3/5 折...
【INFO】【2026-03-26 16:25:15】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=0.5

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:25:15] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:25:30】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 16:25:31] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=24000
[INFO][BT][2026-03-26 16:25:31] 创建桶 bucket_id=L1_ever_delay=has_delay，level=1，parent_id=ROOT，split_name=L1_ever_delay，split_type=numeric_bin，split_rule="has_delay"，n_samples=8031
[INFO][BT][2026-03-26 16:25:31] 创建桶 bucket_id=L1_ever_delay=no_delay，level=1，parent_id=ROOT，split_name=L1_ever_delay，split_type=numeric_bin，split_rule="no_delay"，n_samples=15969
[INFO][BT][2026-03-26 16:25:31] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="medium"，n_samples=812
[INFO][BT][2026-03-26 16:25:31] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="mild"，n_samples=7073
[INFO][BT][2026-03-26 16:25:31] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="others"，n_samples=146
[INFO][BT][2026-03-26 16:25:31] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，level=2，parent_id=L1_ever_delay=no_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="none"，n_samples=15969
[INFO][BT][2026-03-26 16:25:31] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=583
[INFO][BT][2026-03-26 16:25:31] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="others"，n_samples=229
[INFO][BT][2026-03-26 16:25:31] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="high_limit"，n_samples=1569
[INFO][BT][2026-03-26 16:25:31] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=3208
[INFO][BT][2026-03-26 16:25:31] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="mid_limit"，n_samples=2296
[INFO][BT][2026-03-26 16:25:31] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="high_limit"，n_samples=6051
[INFO][BT][2026-03-26 16:25:31] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=4687
[INFO][BT][2026-03-26 16:25:31] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="mid_limit"，n_samples=5231
[INFO][BT][2026-03-26 16:25:34] 桶树构建完成：总桶数=15，最大层数=3，叶子桶数=9
【INFO】【2026-03-26 16:25:34】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 16:25:35】【阈值】桶 ROOT（n_val=1439，source=val) 使用本地阈值 α=0.5000, β=0.2000
[INFO][BT][2026-03-26 16:25:35] 桶 bucket_id=ROOT level=0：
    n_train=3359, n_val=1439,
    BAC=0.501, F1=0.375, AUC=0.776,
    Regret=0.366, BND_ratio=0.268, POS_coverage=0.122,
    Score(f1_regret_bnd )=-0.125，threshold_source=val
【INFO】【2026-03-26 16:25:36】【阈值】桶 L1_ever_delay=has_delay（n_val=522，source=val) 使用本地阈值 α=0.3000, β=0.0000
[INFO][BT][2026-03-26 16:25:36] 桶 bucket_id=L1_ever_delay=has_delay level=1：
    n_train=1200, n_val=522,
    BAC=0.439, F1=0.617, AUC=0.642,
    Regret=0.532, BND_ratio=0.215, POS_coverage=0.785,
    Score(f1_regret_bnd )=-0.022，threshold_source=val
[INFO][BT][2026-03-26 16:25:36] 桶 bucket_id=L1_ever_delay=has_delay：
    parent_id=ROOT，parent_Score=-0.125, bucket_Score=-0.022,
    Gain=+0.102, is_weak=False
【INFO】【2026-03-26 16:25:37】【阈值】桶 L1_ever_delay=no_delay 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:25:37] 桶 bucket_id=L1_ever_delay=no_delay level=1：
    n_train=2241, n_val=952,
    BAC=0.508, F1=0.066, AUC=0.657,
    Regret=0.340, BND_ratio=0.017, POS_coverage=0.009,
    Score(f1_regret_bnd )=-0.282，threshold_source=val
[INFO][BT][2026-03-26 16:25:37] 桶 bucket_id=L1_ever_delay=no_delay：
    parent_id=ROOT，parent_Score=-0.125, bucket_Score=-0.282,
    Gain=-0.157, is_weak=True
【INFO】【2026-03-26 16:25:38】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium（n_val=270，source=val) 使用本地阈值 α=0.2000, β=0.0000
[INFO][BT][2026-03-26 16:25:38] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium level=2：
    n_train=231, n_val=270,
    BAC=0.500, F1=0.725, AUC=0.551,
    Regret=0.431, BND_ratio=0.004, POS_coverage=0.996,
    Score(f1_regret_bnd )=0.292，threshold_source=val
[INFO][BT][2026-03-26 16:25:38] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.022, bucket_Score=0.292,
    Gain=+0.314, is_weak=False
【INFO】【2026-03-26 16:25:39】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild（n_val=423，source=val) 使用本地阈值 α=0.2000, β=0.1000
[INFO][BT][2026-03-26 16:25:39] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild level=2：
    n_train=989, n_val=423,
    BAC=0.506, F1=0.592, AUC=0.580,
    Regret=0.556, BND_ratio=0.087, POS_coverage=0.877,
    Score(f1_regret_bnd )=-0.007，threshold_source=val
[INFO][BT][2026-03-26 16:25:39] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.022, bucket_Score=-0.007,
    Gain=+0.015, is_weak=False
【INFO】【2026-03-26 16:25:40】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=others 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay 的阈值
[INFO][BT][2026-03-26 16:25:40] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others level=2：
    n_train=102, n_val=44,
    BAC=0.579, F1=0.856, AUC=0.862,
    Regret=0.269, BND_ratio=0.164, POS_coverage=0.747,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:25:40] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.022, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:25:41】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none 标记为弱桶，阈值将回退使用 L1_ever_delay=no_delay 的阈值
[INFO][BT][2026-03-26 16:25:41] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none level=2：
    n_train=2241, n_val=952,
    BAC=0.500, F1=0.000, AUC=0.623,
    Regret=0.306, BND_ratio=0.000, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.306，threshold_source=val
[INFO][BT][2026-03-26 16:25:41] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none：
    parent_id=L1_ever_delay=no_delay，parent_Score=-0.282, bucket_Score=-0.306,
    Gain=-0.024, is_weak=True
【INFO】【2026-03-26 16:25:41】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值
[INFO][BT][2026-03-26 16:25:41] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit level=3：
    n_train=388, n_val=195,
    BAC=0.500, F1=0.715, AUC=0.549,
    Regret=0.444, BND_ratio=0.005, POS_coverage=0.995,
    Score(f1_regret_bnd )=0.269，threshold_source=val
[INFO][BT][2026-03-26 16:25:41] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，parent_Score=0.292, bucket_Score=0.269,
    Gain=-0.023, is_weak=True
【INFO】【2026-03-26 16:25:42】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值
[INFO][BT][2026-03-26 16:25:42] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others level=3：
    n_train=154, n_val=75,
    BAC=0.476, F1=0.812, AUC=0.769,
    Regret=0.320, BND_ratio=0.144, POS_coverage=0.847,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:25:42] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，parent_Score=0.292, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:25:43】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值
[INFO][BT][2026-03-26 16:25:43] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit level=3：
    n_train=1102, n_val=467,
    BAC=0.300, F1=0.349, AUC=0.661,
    Regret=0.523, BND_ratio=0.576, POS_coverage=0.152,
    Score(f1_regret_bnd )=-0.462，threshold_source=val
[INFO][BT][2026-03-26 16:25:43] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.007, bucket_Score=-0.462,
    Gain=-0.455, is_weak=True
【INFO】【2026-03-26 16:25:44】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值
[INFO][BT][2026-03-26 16:25:44] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit level=3：
    n_train=2251, n_val=957,
    BAC=0.403, F1=0.606, AUC=0.563,
    Regret=0.529, BND_ratio=0.253, POS_coverage=0.739,
    Score(f1_regret_bnd )=-0.050，threshold_source=val
[INFO][BT][2026-03-26 16:25:44] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.007, bucket_Score=-0.050,
    Gain=-0.042, is_weak=True
【INFO】【2026-03-26 16:25:44】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值
[INFO][BT][2026-03-26 16:25:44] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit level=3：
    n_train=1597, n_val=699,
    BAC=0.382, F1=0.569, AUC=0.595,
    Regret=0.555, BND_ratio=0.328, POS_coverage=0.672,
    Score(f1_regret_bnd )=-0.150，threshold_source=val
[INFO][BT][2026-03-26 16:25:44] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.007, bucket_Score=-0.150,
    Gain=-0.143, is_weak=True
【INFO】【2026-03-26 16:25:45】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit（n_val=1795，source=val) 使用本地阈值 α=0.5000, β=0.3000
[INFO][BT][2026-03-26 16:25:45] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit level=3：
    n_train=4256, n_val=1795,
    BAC=0.495, F1=0.022, AUC=0.657,
    Regret=0.285, BND_ratio=0.023, POS_coverage=0.002,
    Score(f1_regret_bnd )=-0.274，threshold_source=val
[INFO][BT][2026-03-26 16:25:45] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.306, bucket_Score=-0.274,
    Gain=+0.031, is_weak=False
【INFO】【2026-03-26 16:25:46】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=no_delay|L2_max_delay_bin=none 的阈值
[INFO][BT][2026-03-26 16:25:46] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit level=3：
    n_train=3320, n_val=1367,
    BAC=0.389, F1=0.000, AUC=0.573,
    Regret=0.420, BND_ratio=0.235, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.538，threshold_source=val
[INFO][BT][2026-03-26 16:25:46] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.306, bucket_Score=-0.538,
    Gain=-0.232, is_weak=True
【INFO】【2026-03-26 16:25:47】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=no_delay|L2_max_delay_bin=none 的阈值
[INFO][BT][2026-03-26 16:25:47] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit level=3：
    n_train=3630, n_val=1601,
    BAC=0.464, F1=0.000, AUC=0.653,
    Regret=0.320, BND_ratio=0.085, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.362，threshold_source=val
[INFO][BT][2026-03-26 16:25:47] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.306, bucket_Score=-0.362,
    Gain=-0.056, is_weak=True
[INFO][BT][2026-03-26 16:25:47] 桶 bucket_id=L1_ever_delay=no_delay 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.5000,beta=0.2000)
[INFO][BT][2026-03-26 16:25:47] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay 的阈值(alpha=0.3000,beta=0.0000)
[INFO][BT][2026-03-26 16:25:47] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.5000,beta=0.2000)
[INFO][BT][2026-03-26 16:25:47] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值(alpha=0.2000,beta=0.0000)
[INFO][BT][2026-03-26 16:25:47] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值(alpha=0.2000,beta=0.0000)
[INFO][BT][2026-03-26 16:25:47] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值(alpha=0.2000,beta=0.1000)
[INFO][BT][2026-03-26 16:25:47] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值(alpha=0.2000,beta=0.1000)
[INFO][BT][2026-03-26 16:25:47] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值(alpha=0.2000,beta=0.1000)
[INFO][BT][2026-03-26 16:25:47] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.5000,beta=0.2000)
[INFO][BT][2026-03-26 16:25:47] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.5000,beta=0.2000)
【INFO】【2026-03-26 16:25:47】【BTTWD】桶统计摘要：总桶数=15，非空桶=15，强桶=5，弱桶=10
【INFO】【2026-03-26 16:25:47】【BTTWD】共生成 9 个叶子桶，其中有效桶 0 个（已训练局部模型）
【INFO】【2026-03-26 16:25:47】【资源评估-K折第3折】当前配置：父桶贡献=开启，最小样本限制=开启，回退机制=开启；训练耗时=31.975 秒，最大内存占用≈2223.77 MB
[INFO][BT][2026-03-26 16:25:49] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit：
    assigned_samples=137,
    used_local_decision=0,
    fallback_to_parent=137,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium,
    is_weak=True
[INFO][BT][2026-03-26 16:25:49] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium：
    assigned_samples=0,
    used_local_decision=195,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay,
    is_weak=False
[INFO][BT][2026-03-26 16:25:49] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others：
    assigned_samples=58,
    used_local_decision=0,
    fallback_to_parent=58,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium,
    is_weak=True
[INFO][BT][2026-03-26 16:25:49] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit：
    assigned_samples=384,
    used_local_decision=0,
    fallback_to_parent=384,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=True
[INFO][BT][2026-03-26 16:25:49] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild：
    assigned_samples=0,
    used_local_decision=1803,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay,
    is_weak=False
[INFO][BT][2026-03-26 16:25:49] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit：
    assigned_samples=836,
    used_local_decision=0,
    fallback_to_parent=836,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=True
[INFO][BT][2026-03-26 16:25:49] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit：
    assigned_samples=583,
    used_local_decision=0,
    fallback_to_parent=583,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=True
[INFO][BT][2026-03-26 16:25:49] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others：
    assigned_samples=40,
    used_local_decision=0,
    fallback_to_parent=40,
    parent_id=L1_ever_delay=has_delay,
    is_weak=True
[INFO][BT][2026-03-26 16:25:49] 预测统计：bucket_id=L1_ever_delay=has_delay：
    assigned_samples=0,
    used_local_decision=40,
    fallback_to_parent=0,
    parent_id=ROOT,
    is_weak=False
[INFO][BT][2026-03-26 16:25:49] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit：
    assigned_samples=1514,
    used_local_decision=1514,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=False
[INFO][BT][2026-03-26 16:25:49] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit：
    assigned_samples=1211,
    used_local_decision=0,
    fallback_to_parent=1211,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=True
[INFO][BT][2026-03-26 16:25:49] 预测统计：bucket_id=ROOT：
    assigned_samples=0,
    used_local_decision=2448,
    fallback_to_parent=0,
    parent_id=ROOT,
    is_weak=False
[INFO][BT][2026-03-26 16:25:49] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit：
    assigned_samples=1237,
    used_local_decision=0,
    fallback_to_parent=1237,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=True
[INFO][BT][2026-03-26 16:25:49] 回退汇总：
    总样本数=6000,
    使用叶子桶决策的样本比例=25.233%,
    使用中间桶决策的样本比例=33.967%,
    回退到全局桶决策的样本比例=40.800%
【INFO】【2026-03-26 16:25:49】【BTTWD】三支指标(含后悔)：Precision=0.444, Recall=0.650, F1=0.528, BAC=0.709, AUC=0.758, MCC=0.372, Kappa=0.359, BND_ratio=0.092, POS_Coverage=0.304, Regret=0.410
【INFO】【2026-03-26 16:25:50】[BASELINE] 数据拆分完成（train/val/test）
【INFO】【2026-03-26 16:25:50】[BASELINE] 全局 XGB 模型开始训练

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:25:51] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:26:05】[BASELINE] 全局 XGB 模型训练完成
【INFO】【2026-03-26 16:26:05】[BASELINE] 阈值搜索开始
【INFO】【2026-03-26 16:26:06】[BASELINE] 最佳阈值找到: alpha=0.4000, beta=0.2000, regret=0.4051
【INFO】【2026-03-26 16:26:06】【桶树】已为样本生成桶ID，共 12 个组合
【INFO】【2026-03-26 16:26:06】[BASELINE] 测试集桶映射完成，共 12 个桶
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit: BAC=0.5028, Regret=0.3300, Precision=0.3333, Recall=0.0074
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit: BAC=0.5020, Regret=0.4408, Precision=0.2222, Recall=0.0108
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit: BAC=0.5010, Regret=0.2687, Precision=0.1250, Recall=0.0071
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit: BAC=0.5883, Regret=0.5245, Precision=0.4803, Recall=0.8000
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit: BAC=0.5876, Regret=0.5339, Precision=0.5057, Recall=0.5542
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit: BAC=0.5411, Regret=0.5612, Precision=0.3866, Recall=0.3651
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit: BAC=0.5129, Regret=0.3850, Precision=0.6194, Recall=0.9881
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=mid_limit: BAC=0.4833, Regret=0.3036, Precision=0.7073, Recall=0.9667
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe|L3_LIMIT_BAL=low_limit: BAC=0.4773, Regret=0.2411, Precision=0.7778, Recall=0.9545
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=high_limit: BAC=0.6429, Regret=0.3750, Precision=0.6429, Recall=1.0000
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe|L3_LIMIT_BAL=mid_limit: BAC=0.6000, Regret=0.5714, Precision=0.3333, Recall=1.0000
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe|L3_LIMIT_BAL=high_limit: BAC=0.7500, Regret=0.3000, Precision=0.7500, Recall=1.0000
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none: BAC=0.5021, Regret=0.3404, Precision=0.2000, Recall=0.0087
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=no_delay: BAC=0.5021, Regret=0.3404, Precision=0.2000, Recall=0.0087
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild: BAC=0.5878, Regret=0.5354, Precision=0.4756, Recall=0.6411
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=has_delay: BAC=0.6003, Regret=0.5147, Precision=0.5088, Recall=0.6998
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium: BAC=0.5196, Regret=0.3667, Precision=0.6402, Recall=0.9837
【INFO】【2026-03-26 16:26:07】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe: BAC=0.5584, Regret=0.3063, Precision=0.7027, Recall=0.9630
【INFO】【2026-03-26 16:26:07】【K折实验】正在执行第 4/5 折...
【INFO】【2026-03-26 16:26:07】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=0.5

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:26:08] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:26:22】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 16:26:22] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=24000
[INFO][BT][2026-03-26 16:26:22] 创建桶 bucket_id=L1_ever_delay=has_delay，level=1，parent_id=ROOT，split_name=L1_ever_delay，split_type=numeric_bin，split_rule="has_delay"，n_samples=8122
[INFO][BT][2026-03-26 16:26:22] 创建桶 bucket_id=L1_ever_delay=no_delay，level=1，parent_id=ROOT，split_name=L1_ever_delay，split_type=numeric_bin，split_rule="no_delay"，n_samples=15878
[INFO][BT][2026-03-26 16:26:22] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="medium"，n_samples=829
[INFO][BT][2026-03-26 16:26:22] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="mild"，n_samples=7145
[INFO][BT][2026-03-26 16:26:22] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="others"，n_samples=148
[INFO][BT][2026-03-26 16:26:22] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，level=2，parent_id=L1_ever_delay=no_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="none"，n_samples=15878
[INFO][BT][2026-03-26 16:26:22] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=592
[INFO][BT][2026-03-26 16:26:22] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="others"，n_samples=237
[INFO][BT][2026-03-26 16:26:22] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="high_limit"，n_samples=1586
[INFO][BT][2026-03-26 16:26:22] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=3215
[INFO][BT][2026-03-26 16:26:22] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="mid_limit"，n_samples=2344
[INFO][BT][2026-03-26 16:26:22] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="high_limit"，n_samples=6017
[INFO][BT][2026-03-26 16:26:22] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=4709
[INFO][BT][2026-03-26 16:26:22] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="mid_limit"，n_samples=5152
[INFO][BT][2026-03-26 16:26:24] 桶树构建完成：总桶数=15，最大层数=3，叶子桶数=9
【INFO】【2026-03-26 16:26:24】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 16:26:25】【阈值】桶 ROOT（n_val=1439，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:26:25] 桶 bucket_id=ROOT level=0：
    n_train=3359, n_val=1439,
    BAC=0.559, F1=0.452, AUC=0.717,
    Regret=0.438, BND_ratio=0.190, POS_coverage=0.205,
    Score(f1_regret_bnd )=-0.081，threshold_source=val
【INFO】【2026-03-26 16:26:25】【阈值】桶 L1_ever_delay=has_delay 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:26:25] 桶 bucket_id=L1_ever_delay=has_delay level=1：
    n_train=1214, n_val=527,
    BAC=0.394, F1=0.608, AUC=0.659,
    Regret=0.518, BND_ratio=0.353, POS_coverage=0.615,
    Score(f1_regret_bnd )=-0.086，threshold_source=val
[INFO][BT][2026-03-26 16:26:25] 桶 bucket_id=L1_ever_delay=has_delay：
    parent_id=ROOT，parent_Score=-0.081, bucket_Score=-0.086,
    Gain=-0.005, is_weak=True
【INFO】【2026-03-26 16:26:26】【阈值】桶 L1_ever_delay=no_delay 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:26:26] 桶 bucket_id=L1_ever_delay=no_delay level=1：
    n_train=2223, n_val=951,
    BAC=0.445, F1=0.000, AUC=0.635,
    Regret=0.329, BND_ratio=0.122, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.390，threshold_source=val
[INFO][BT][2026-03-26 16:26:26] 桶 bucket_id=L1_ever_delay=no_delay：
    parent_id=ROOT，parent_Score=-0.081, bucket_Score=-0.390,
    Gain=-0.309, is_weak=True
【INFO】【2026-03-26 16:26:26】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium（n_val=250，source=val) 使用本地阈值 α=0.1000, β=0.0000
[INFO][BT][2026-03-26 16:26:26] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium level=2：
    n_train=248, n_val=250,
    BAC=0.500, F1=0.780, AUC=0.504,
    Regret=0.360, BND_ratio=0.000, POS_coverage=1.000,
    Score(f1_regret_bnd )=0.420，threshold_source=val
[INFO][BT][2026-03-26 16:26:26] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.086, bucket_Score=0.420,
    Gain=+0.506, is_weak=False
【INFO】【2026-03-26 16:26:26】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay 的阈值
[INFO][BT][2026-03-26 16:26:26] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild level=2：
    n_train=999, n_val=428,
    BAC=0.325, F1=0.505, AUC=0.578,
    Regret=0.566, BND_ratio=0.458, POS_coverage=0.500,
    Score(f1_regret_bnd )=-0.290，threshold_source=val
[INFO][BT][2026-03-26 16:26:26] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.086, bucket_Score=-0.290,
    Gain=-0.204, is_weak=True
【INFO】【2026-03-26 16:26:27】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=others 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay 的阈值
[INFO][BT][2026-03-26 16:26:27] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others level=2：
    n_train=99, n_val=49,
    BAC=0.546, F1=0.840, AUC=0.843,
    Regret=0.299, BND_ratio=0.203, POS_coverage=0.709,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:26:27] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.086, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:26:27】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none（n_val=950，source=val) 使用本地阈值 α=0.5000, β=0.2000
[INFO][BT][2026-03-26 16:26:27] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none level=2：
    n_train=2222, n_val=950,
    BAC=0.453, F1=0.019, AUC=0.667,
    Regret=0.307, BND_ratio=0.124, POS_coverage=0.001,
    Score(f1_regret_bnd )=-0.351，threshold_source=val
[INFO][BT][2026-03-26 16:26:27] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none：
    parent_id=L1_ever_delay=no_delay，parent_Score=-0.390, bucket_Score=-0.351,
    Gain=+0.039, is_weak=False
【INFO】【2026-03-26 16:26:28】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值
[INFO][BT][2026-03-26 16:26:28] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit level=3：
    n_train=413, n_val=179,
    BAC=0.491, F1=0.783, AUC=0.540,
    Regret=0.358, BND_ratio=0.039, POS_coverage=0.961,
    Score(f1_regret_bnd )=0.406，threshold_source=val
[INFO][BT][2026-03-26 16:26:28] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，parent_Score=0.420, bucket_Score=0.406,
    Gain=-0.014, is_weak=True
【INFO】【2026-03-26 16:26:28】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值
[INFO][BT][2026-03-26 16:26:28] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others level=3：
    n_train=166, n_val=71,
    BAC=0.471, F1=0.821, AUC=0.773,
    Regret=0.309, BND_ratio=0.190, POS_coverage=0.797,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:26:28] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，parent_Score=0.420, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:26:28】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值
[INFO][BT][2026-03-26 16:26:28] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit level=3：
    n_train=1090, n_val=496,
    BAC=0.245, F1=0.254, AUC=0.624,
    Regret=0.567, BND_ratio=0.625, POS_coverage=0.109,
    Score(f1_regret_bnd )=-0.626，threshold_source=val
[INFO][BT][2026-03-26 16:26:28] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.290, bucket_Score=-0.626,
    Gain=-0.336, is_weak=True
【INFO】【2026-03-26 16:26:29】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit（n_val=946，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 16:26:29] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit level=3：
    n_train=2269, n_val=946,
    BAC=0.387, F1=0.561, AUC=0.569,
    Regret=0.561, BND_ratio=0.288, POS_coverage=0.689,
    Score(f1_regret_bnd )=-0.144，threshold_source=val
[INFO][BT][2026-03-26 16:26:29] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.290, bucket_Score=-0.144,
    Gain=+0.145, is_weak=False
【INFO】【2026-03-26 16:26:29】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit（n_val=700，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 16:26:29] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit level=3：
    n_train=1644, n_val=700,
    BAC=0.328, F1=0.572, AUC=0.663,
    Regret=0.511, BND_ratio=0.516, POS_coverage=0.456,
    Score(f1_regret_bnd )=-0.197，threshold_source=val
[INFO][BT][2026-03-26 16:26:29] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.290, bucket_Score=-0.197,
    Gain=+0.093, is_weak=False
【INFO】【2026-03-26 16:26:30】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit（n_val=1803，source=val) 使用本地阈值 α=0.7000, β=0.2000
[INFO][BT][2026-03-26 16:26:30] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit level=3：
    n_train=4214, n_val=1803,
    BAC=0.460, F1=0.000, AUC=0.668,
    Regret=0.289, BND_ratio=0.096, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.337，threshold_source=val
[INFO][BT][2026-03-26 16:26:30] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.351, bucket_Score=-0.337,
    Gain=+0.014, is_weak=False
【INFO】【2026-03-26 16:26:30】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=no_delay|L2_max_delay_bin=none 的阈值
[INFO][BT][2026-03-26 16:26:30] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit level=3：
    n_train=3351, n_val=1358,
    BAC=0.409, F1=0.000, AUC=0.575,
    Regret=0.452, BND_ratio=0.197, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.551，threshold_source=val
[INFO][BT][2026-03-26 16:26:30] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.351, bucket_Score=-0.551,
    Gain=-0.200, is_weak=True
【INFO】【2026-03-26 16:26:31】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=no_delay|L2_max_delay_bin=none 的阈值
[INFO][BT][2026-03-26 16:26:31] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit level=3：
    n_train=3554, n_val=1598,
    BAC=0.455, F1=0.000, AUC=0.664,
    Regret=0.302, BND_ratio=0.104, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.354，threshold_source=val
[INFO][BT][2026-03-26 16:26:31] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.351, bucket_Score=-0.354,
    Gain=-0.003, is_weak=True
[INFO][BT][2026-03-26 16:26:31] 桶 bucket_id=L1_ever_delay=has_delay 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:26:31] 桶 bucket_id=L1_ever_delay=no_delay 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:26:31] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:26:31] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:26:31] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值(alpha=0.1000,beta=0.0000)
[INFO][BT][2026-03-26 16:26:31] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值(alpha=0.1000,beta=0.0000)
[INFO][BT][2026-03-26 16:26:31] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:26:31] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=no_delay|L2_max_delay_bin=none 的阈值(alpha=0.5000,beta=0.2000)
[INFO][BT][2026-03-26 16:26:31] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=no_delay|L2_max_delay_bin=none 的阈值(alpha=0.5000,beta=0.2000)
【INFO】【2026-03-26 16:26:31】【BTTWD】桶统计摘要：总桶数=15，非空桶=15，强桶=6，弱桶=9
【INFO】【2026-03-26 16:26:31】【BTTWD】共生成 9 个叶子桶，其中有效桶 0 个（已训练局部模型）
【INFO】【2026-03-26 16:26:31】【资源评估-K折第4折】当前配置：父桶贡献=开启，最小样本限制=开启，回退机制=开启；训练耗时=23.501 秒，最大内存占用≈2232.03 MB
[INFO][BT][2026-03-26 16:26:33] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit：
    assigned_samples=128,
    used_local_decision=0,
    fallback_to_parent=128,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium,
    is_weak=True
[INFO][BT][2026-03-26 16:26:33] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium：
    assigned_samples=0,
    used_local_decision=178,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay,
    is_weak=False
[INFO][BT][2026-03-26 16:26:33] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others：
    assigned_samples=50,
    used_local_decision=0,
    fallback_to_parent=50,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium,
    is_weak=True
[INFO][BT][2026-03-26 16:26:33] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit：
    assigned_samples=367,
    used_local_decision=0,
    fallback_to_parent=367,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=True
[INFO][BT][2026-03-26 16:26:33] 预测统计：bucket_id=ROOT：
    assigned_samples=0,
    used_local_decision=405,
    fallback_to_parent=0,
    parent_id=ROOT,
    is_weak=False
[INFO][BT][2026-03-26 16:26:33] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit：
    assigned_samples=829,
    used_local_decision=829,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=False
[INFO][BT][2026-03-26 16:26:33] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit：
    assigned_samples=535,
    used_local_decision=535,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=False
[INFO][BT][2026-03-26 16:26:33] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others：
    assigned_samples=38,
    used_local_decision=0,
    fallback_to_parent=38,
    parent_id=L1_ever_delay=has_delay,
    is_weak=True
[INFO][BT][2026-03-26 16:26:33] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit：
    assigned_samples=1548,
    used_local_decision=1548,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=False
[INFO][BT][2026-03-26 16:26:33] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit：
    assigned_samples=1189,
    used_local_decision=0,
    fallback_to_parent=1189,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=True
[INFO][BT][2026-03-26 16:26:33] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none：
    assigned_samples=0,
    used_local_decision=2505,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=no_delay,
    is_weak=False
[INFO][BT][2026-03-26 16:26:33] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit：
    assigned_samples=1316,
    used_local_decision=0,
    fallback_to_parent=1316,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=True
[INFO][BT][2026-03-26 16:26:33] 回退汇总：
    总样本数=6000,
    使用叶子桶决策的样本比例=48.533%,
    使用中间桶决策的样本比例=44.717%,
    回退到全局桶决策的样本比例=6.750%
【INFO】【2026-03-26 16:26:33】【BTTWD】三支指标(含后悔)：Precision=0.456, Recall=0.644, F1=0.534, BAC=0.713, AUC=0.760, MCC=0.381, Kappa=0.371, BND_ratio=0.196, POS_Coverage=0.190, Regret=0.400
【INFO】【2026-03-26 16:26:33】[BASELINE] 数据拆分完成（train/val/test）
【INFO】【2026-03-26 16:26:33】[BASELINE] 全局 XGB 模型开始训练

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:26:33] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:26:37】[BASELINE] 全局 XGB 模型训练完成
【INFO】【2026-03-26 16:26:37】[BASELINE] 阈值搜索开始
【INFO】【2026-03-26 16:26:37】[BASELINE] 最佳阈值找到: alpha=0.4000, beta=0.2000, regret=0.4061
【INFO】【2026-03-26 16:26:37】【桶树】已为样本生成桶ID，共 12 个组合
【INFO】【2026-03-26 16:26:37】[BASELINE] 测试集桶映射完成，共 12 个桶
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit: BAC=0.5975, Regret=0.5673, Precision=0.4810, Recall=0.5644
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit: BAC=0.5038, Regret=0.4283, Precision=0.3333, Recall=0.0116
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit: BAC=0.5096, Regret=0.3262, Precision=0.6000, Recall=0.0210
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit: BAC=0.5603, Regret=0.5100, Precision=0.5134, Recall=0.7826
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit: BAC=0.5117, Regret=0.2878, Precision=0.5714, Recall=0.0255
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit: BAC=0.5849, Regret=0.5790, Precision=0.5000, Recall=0.3468
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit: BAC=0.5125, Regret=0.3770, Precision=0.6311, Recall=0.9625
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=mid_limit: BAC=0.5946, Regret=0.3176, Precision=0.6970, Recall=0.9583
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe|L3_LIMIT_BAL=low_limit: BAC=0.5000, Regret=0.3462, Precision=0.6538, Recall=1.0000
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe|L3_LIMIT_BAL=high_limit: BAC=0.5000, Regret=0.5000, Precision=0.5000, Recall=1.0000
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe|L3_LIMIT_BAL=mid_limit: BAC=0.5667, Regret=0.4062, Precision=0.6667, Recall=0.8000
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=high_limit: BAC=0.4444, Regret=0.5385, Precision=0.6667, Recall=0.8889
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild: BAC=0.5980, Regret=0.5423, Precision=0.5038, Recall=0.6457
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=has_delay: BAC=0.6062, Regret=0.5239, Precision=0.5294, Recall=0.6956
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none: BAC=0.5083, Regret=0.3415, Precision=0.5000, Recall=0.0190
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=no_delay: BAC=0.5083, Regret=0.3415, Precision=0.5000, Recall=0.0190
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium: BAC=0.5240, Regret=0.3764, Precision=0.6467, Recall=0.9558
【INFO】【2026-03-26 16:26:38】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe: BAC=0.5149, Regret=0.3750, Precision=0.6389, Recall=0.9583
【INFO】【2026-03-26 16:26:38】【K折实验】正在执行第 5/5 折...
【INFO】【2026-03-26 16:26:38】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=0.5

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:26:38] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:26:39】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 16:26:40] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=24000
[INFO][BT][2026-03-26 16:26:40] 创建桶 bucket_id=L1_ever_delay=has_delay，level=1，parent_id=ROOT，split_name=L1_ever_delay，split_type=numeric_bin，split_rule="has_delay"，n_samples=8040
[INFO][BT][2026-03-26 16:26:40] 创建桶 bucket_id=L1_ever_delay=no_delay，level=1，parent_id=ROOT，split_name=L1_ever_delay，split_type=numeric_bin，split_rule="no_delay"，n_samples=15960
[INFO][BT][2026-03-26 16:26:40] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="medium"，n_samples=794
[INFO][BT][2026-03-26 16:26:40] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="mild"，n_samples=7091
[INFO][BT][2026-03-26 16:26:40] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="others"，n_samples=155
[INFO][BT][2026-03-26 16:26:40] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，level=2，parent_id=L1_ever_delay=no_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="none"，n_samples=15960
[INFO][BT][2026-03-26 16:26:40] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=561
[INFO][BT][2026-03-26 16:26:40] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="others"，n_samples=233
[INFO][BT][2026-03-26 16:26:40] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="high_limit"，n_samples=1567
[INFO][BT][2026-03-26 16:26:40] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=3255
[INFO][BT][2026-03-26 16:26:40] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="mid_limit"，n_samples=2269
[INFO][BT][2026-03-26 16:26:40] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="high_limit"，n_samples=6063
[INFO][BT][2026-03-26 16:26:40] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=4733
[INFO][BT][2026-03-26 16:26:40] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="mid_limit"，n_samples=5164
[INFO][BT][2026-03-26 16:26:42] 桶树构建完成：总桶数=15，最大层数=3，叶子桶数=9
【INFO】【2026-03-26 16:26:42】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 16:26:43】【阈值】桶 ROOT（n_val=1440，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:26:43] 桶 bucket_id=ROOT level=0：
    n_train=3360, n_val=1440,
    BAC=0.584, F1=0.505, AUC=0.766,
    Regret=0.389, BND_ratio=0.204, POS_coverage=0.189,
    Score(f1_regret_bnd )=0.014，threshold_source=val
【INFO】【2026-03-26 16:26:43】【阈值】桶 L1_ever_delay=has_delay 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:26:43] 桶 bucket_id=L1_ever_delay=has_delay level=1：
    n_train=1208, n_val=522,
    BAC=0.367, F1=0.620, AUC=0.668,
    Regret=0.502, BND_ratio=0.410, POS_coverage=0.577,
    Score(f1_regret_bnd )=-0.087，threshold_source=val
[INFO][BT][2026-03-26 16:26:43] 桶 bucket_id=L1_ever_delay=has_delay：
    parent_id=ROOT，parent_Score=0.014, bucket_Score=-0.087,
    Gain=-0.101, is_weak=True
【INFO】【2026-03-26 16:26:44】【阈值】桶 L1_ever_delay=no_delay 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:26:44] 桶 bucket_id=L1_ever_delay=no_delay level=1：
    n_train=2237, n_val=955,
    BAC=0.489, F1=0.000, AUC=0.639,
    Regret=0.298, BND_ratio=0.027, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.312，threshold_source=val
[INFO][BT][2026-03-26 16:26:44] 桶 bucket_id=L1_ever_delay=no_delay：
    parent_id=ROOT，parent_Score=0.014, bucket_Score=-0.312,
    Gain=-0.326, is_weak=True
【INFO】【2026-03-26 16:26:44】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium（n_val=235，source=val) 使用本地阈值 α=0.4000, β=0.0000
[INFO][BT][2026-03-26 16:26:44] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium level=2：
    n_train=243, n_val=235,
    BAC=0.486, F1=0.763, AUC=0.571,
    Regret=0.383, BND_ratio=0.051, POS_coverage=0.949,
    Score(f1_regret_bnd )=0.354，threshold_source=val
[INFO][BT][2026-03-26 16:26:44] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.087, bucket_Score=0.354,
    Gain=+0.442, is_weak=False
【INFO】【2026-03-26 16:26:45】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild（n_val=427，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:26:45] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild level=2：
    n_train=988, n_val=427,
    BAC=0.439, F1=0.576, AUC=0.648,
    Regret=0.496, BND_ratio=0.333, POS_coverage=0.515,
    Score(f1_regret_bnd )=-0.086，threshold_source=val
[INFO][BT][2026-03-26 16:26:45] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.087, bucket_Score=-0.086,
    Gain=+0.001, is_weak=False
【INFO】【2026-03-26 16:26:45】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=others 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay 的阈值
[INFO][BT][2026-03-26 16:26:45] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others level=2：
    n_train=108, n_val=47,
    BAC=0.661, F1=0.857, AUC=0.894,
    Regret=0.248, BND_ratio=0.116, POS_coverage=0.723,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:26:45] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.087, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:26:46】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none 标记为弱桶，阈值将回退使用 L1_ever_delay=no_delay 的阈值
[INFO][BT][2026-03-26 16:26:46] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none level=2：
    n_train=2236, n_val=954,
    BAC=0.500, F1=0.000, AUC=0.613,
    Regret=0.324, BND_ratio=0.000, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.324，threshold_source=val
[INFO][BT][2026-03-26 16:26:46] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none：
    parent_id=L1_ever_delay=no_delay，parent_Score=-0.312, bucket_Score=-0.324,
    Gain=-0.012, is_weak=True
【INFO】【2026-03-26 16:26:46】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit（n_val=166，source=val) 使用本地阈值 α=0.1000, β=0.0000
[INFO][BT][2026-03-26 16:26:46] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit level=3：
    n_train=395, n_val=166,
    BAC=0.500, F1=0.757, AUC=0.560,
    Regret=0.392, BND_ratio=0.000, POS_coverage=1.000,
    Score(f1_regret_bnd )=0.365，threshold_source=val
[INFO][BT][2026-03-26 16:26:46] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，parent_Score=0.354, bucket_Score=0.365,
    Gain=+0.011, is_weak=False
【INFO】【2026-03-26 16:26:46】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值
[INFO][BT][2026-03-26 16:26:46] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others level=3：
    n_train=164, n_val=69,
    BAC=0.586, F1=0.835, AUC=0.791,
    Regret=0.288, BND_ratio=0.107, POS_coverage=0.794,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:26:46] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，parent_Score=0.354, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:26:47】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值
[INFO][BT][2026-03-26 16:26:47] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit level=3：
    n_train=1088, n_val=479,
    BAC=0.373, F1=0.414, AUC=0.699,
    Regret=0.501, BND_ratio=0.470, POS_coverage=0.223,
    Score(f1_regret_bnd )=-0.322，threshold_source=val
[INFO][BT][2026-03-26 16:26:47] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.086, bucket_Score=-0.322,
    Gain=-0.235, is_weak=True
【INFO】【2026-03-26 16:26:47】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit（n_val=999，source=val) 使用本地阈值 α=0.3000, β=0.1000
[INFO][BT][2026-03-26 16:26:47] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit level=3：
    n_train=2256, n_val=999,
    BAC=0.462, F1=0.643, AUC=0.589,
    Regret=0.512, BND_ratio=0.137, POS_coverage=0.855,
    Score(f1_regret_bnd )=0.062，threshold_source=val
[INFO][BT][2026-03-26 16:26:47] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.086, bucket_Score=0.062,
    Gain=+0.149, is_weak=False
【INFO】【2026-03-26 16:26:48】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值
[INFO][BT][2026-03-26 16:26:48] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit level=3：
    n_train=1604, n_val=665,
    BAC=0.382, F1=0.521, AUC=0.626,
    Regret=0.535, BND_ratio=0.405, POS_coverage=0.468,
    Score(f1_regret_bnd )=-0.215，threshold_source=val
[INFO][BT][2026-03-26 16:26:48] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.086, bucket_Score=-0.215,
    Gain=-0.129, is_weak=True
【INFO】【2026-03-26 16:26:48】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=no_delay|L2_max_delay_bin=none 的阈值
[INFO][BT][2026-03-26 16:26:48] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit level=3：
    n_train=4268, n_val=1795,
    BAC=0.456, F1=0.000, AUC=0.642,
    Regret=0.306, BND_ratio=0.100, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.357，threshold_source=val
[INFO][BT][2026-03-26 16:26:48] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.324, bucket_Score=-0.357,
    Gain=-0.033, is_weak=True
【INFO】【2026-03-26 16:26:48】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=no_delay|L2_max_delay_bin=none 的阈值
[INFO][BT][2026-03-26 16:26:48] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit level=3：
    n_train=3292, n_val=1441,
    BAC=0.405, F1=0.000, AUC=0.580,
    Regret=0.435, BND_ratio=0.203, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.536，threshold_source=val
[INFO][BT][2026-03-26 16:26:48] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.324, bucket_Score=-0.536,
    Gain=-0.213, is_weak=True
【INFO】【2026-03-26 16:26:49】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit（n_val=1539，source=val) 使用本地阈值 α=0.6000, β=0.5000
[INFO][BT][2026-03-26 16:26:49] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit level=3：
    n_train=3625, n_val=1539,
    BAC=0.500, F1=0.000, AUC=0.624,
    Regret=0.290, BND_ratio=0.000, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.290，threshold_source=val
[INFO][BT][2026-03-26 16:26:49] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.324, bucket_Score=-0.290,
    Gain=+0.033, is_weak=False
[INFO][BT][2026-03-26 16:26:49] 桶 bucket_id=L1_ever_delay=has_delay 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:26:49] 桶 bucket_id=L1_ever_delay=no_delay 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:26:49] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:26:49] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:26:49] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值(alpha=0.4000,beta=0.0000)
[INFO][BT][2026-03-26 16:26:49] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:26:49] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:26:49] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:26:49] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
【INFO】【2026-03-26 16:26:49】【BTTWD】桶统计摘要：总桶数=15，非空桶=15，强桶=6，弱桶=9
【INFO】【2026-03-26 16:26:49】【BTTWD】共生成 9 个叶子桶，其中有效桶 0 个（已训练局部模型）
【INFO】【2026-03-26 16:26:49】【资源评估-K折第5折】当前配置：父桶贡献=开启，最小样本限制=开启，回退机制=开启；训练耗时=10.684 秒，最大内存占用≈2236.93 MB
[INFO][BT][2026-03-26 16:26:51] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit：
    assigned_samples=159,
    used_local_decision=159,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium,
    is_weak=False
[INFO][BT][2026-03-26 16:26:51] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others：
    assigned_samples=54,
    used_local_decision=0,
    fallback_to_parent=54,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium,
    is_weak=True
[INFO][BT][2026-03-26 16:26:51] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium：
    assigned_samples=0,
    used_local_decision=54,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay,
    is_weak=False
[INFO][BT][2026-03-26 16:26:51] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit：
    assigned_samples=386,
    used_local_decision=0,
    fallback_to_parent=386,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=True
[INFO][BT][2026-03-26 16:26:51] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild：
    assigned_samples=0,
    used_local_decision=996,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay,
    is_weak=False
[INFO][BT][2026-03-26 16:26:51] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit：
    assigned_samples=789,
    used_local_decision=789,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=False
[INFO][BT][2026-03-26 16:26:51] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit：
    assigned_samples=610,
    used_local_decision=0,
    fallback_to_parent=610,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=True
[INFO][BT][2026-03-26 16:26:51] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others：
    assigned_samples=31,
    used_local_decision=0,
    fallback_to_parent=31,
    parent_id=L1_ever_delay=has_delay,
    is_weak=True
[INFO][BT][2026-03-26 16:26:51] 预测统计：bucket_id=ROOT：
    assigned_samples=0,
    used_local_decision=2698,
    fallback_to_parent=0,
    parent_id=ROOT,
    is_weak=False
[INFO][BT][2026-03-26 16:26:51] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit：
    assigned_samples=1502,
    used_local_decision=0,
    fallback_to_parent=1502,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=True
[INFO][BT][2026-03-26 16:26:51] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit：
    assigned_samples=1165,
    used_local_decision=0,
    fallback_to_parent=1165,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=True
[INFO][BT][2026-03-26 16:26:51] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit：
    assigned_samples=1304,
    used_local_decision=1304,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=False
[INFO][BT][2026-03-26 16:26:51] 回退汇总：
    总样本数=6000,
    使用叶子桶决策的样本比例=37.533%,
    使用中间桶决策的样本比例=17.500%,
    回退到全局桶决策的样本比例=44.967%
【INFO】【2026-03-26 16:26:51】【BTTWD】三支指标(含后悔)：Precision=0.423, Recall=0.629, F1=0.506, BAC=0.693, AUC=0.755, MCC=0.341, Kappa=0.329, BND_ratio=0.149, POS_Coverage=0.225, Regret=0.414
【INFO】【2026-03-26 16:26:51】[BASELINE] 数据拆分完成（train/val/test）
【INFO】【2026-03-26 16:26:51】[BASELINE] 全局 XGB 模型开始训练

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:26:51] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:26:52】[BASELINE] 全局 XGB 模型训练完成
【INFO】【2026-03-26 16:26:52】[BASELINE] 阈值搜索开始
【INFO】【2026-03-26 16:26:53】[BASELINE] 最佳阈值找到: alpha=0.4000, beta=0.2000, regret=0.3974
【INFO】【2026-03-26 16:26:53】【桶树】已为样本生成桶ID，共 12 个组合
【INFO】【2026-03-26 16:26:53】[BASELINE] 测试集桶映射完成，共 12 个桶

d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
d:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2394: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit: BAC=0.5317, Regret=0.2801, Precision=0.5263, Recall=0.0699
【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit: BAC=0.5968, Regret=0.5451, Precision=0.4817, Recall=0.6118
【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit: BAC=0.5026, Regret=0.4736, Precision=1.0000, Recall=0.0053
【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit: BAC=0.4991, Regret=0.3382, Precision=0.0000, Recall=0.0000
【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit: BAC=0.5938, Regret=0.5907, Precision=0.4592, Recall=0.3846
【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit: BAC=0.5845, Regret=0.5301, Precision=0.5009, Recall=0.7902
【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit: BAC=0.4994, Regret=0.4167, Precision=0.5909, Recall=0.9681
【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe|L3_LIMIT_BAL=high_limit: BAC=0.7500, Regret=0.1875, Precision=1.0000, Recall=0.7500
【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe|L3_LIMIT_BAL=low_limit: BAC=0.5260, Regret=0.4028, Precision=0.6250, Recall=0.9091
【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=mid_limit: BAC=0.4783, Regret=0.4145, Precision=0.5946, Recall=0.9565
【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe|L3_LIMIT_BAL=mid_limit: BAC=0.3333, Regret=1.0000, Precision=0.5714, Recall=0.6667
【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=high_limit: BAC=0.7500, Regret=0.1875, Precision=0.8571, Recall=1.0000
【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=no_delay|L2_max_delay_bin=none: BAC=0.5100, Regret=0.3560, Precision=0.5000, Recall=0.0232
【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=no_delay: BAC=0.5100, Regret=0.3560, Precision=0.5000, Recall=0.0232
【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild: BAC=0.6082, Regret=0.5483, Precision=0.4905, Recall=0.6624
【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=has_delay: BAC=0.6132, Regret=0.5327, Precision=0.5148, Recall=0.7124
【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium: BAC=0.5083, Regret=0.3991, Precision=0.6098, Recall=0.9690
【INFO】【2026-03-26 16:26:53】[BASELINE] 桶 L1_ever_delay=has_delay|L2_max_delay_bin=severe: BAC=0.4548, Regret=0.5484, Precision=0.6538, Recall=0.8095
【INFO】【2026-03-26 16:26:53】【K折实验】所有结果已写入 results 目录

,model,Precision_mean,Precision_std,Recall_mean,Recall_std,F1_mean,F1_std,BAC_mean,BAC_std,AUC_mean,...,MCC_mean,MCC_std,Kappa_mean,Kappa_std,BND_ratio_mean,BND_ratio_std,POS_Coverage_mean,POS_Coverage_std,Regret_mean,Regret_std
0,BTTWD,0.440527,0.012462,0.640595,0.011560,0.522013,0.011908,0.704692,0.008957,0.758020,...,0.363800,0.017024,0.352162,0.017285,0.150767,0.04062,0.2228,0.047591,0.405717,0.009148
1,LogReg,0.445227,0.007344,0.626579,0.013601,0.520454,0.006285,0.702350,0.005043,0.745270,...,0.362823,0.008697,0.353172,0.008633,0.000000,0.00000,NaN,NaN,0.420600,0.006671
2,RandomForest,0.455229,0.007578,0.598552,0.014403,0.517083,0.008805,0.697538,0.006730,0.755216,...,0.361081,0.011573,0.355029,0.011198,0.000000,0.00000,NaN,NaN,0.424867,0.008967
3,KNN,0.362512,0.006880,0.613016,0.015880,0.455562,0.009012,0.653409,0.007814,0.689636,...,0.263198,0.013130,0.245955,0.012017,0.000000,0.00000,NaN,NaN,0.495267,0.010505
4,XGBoost,0.470649,0.009512,0.589358,0.012818,0.523309,0.009693,0.700517,0.007042,0.762483,...,0.371966,0.012989,0.367809,0.012868,0.000000,0.00000,NaN,NaN,0.419167,0.009592

In [9]:
# 步骤7：桶级别分析
bucket_metrics_path = os.path.join(root_path, cfg['OUTPUT']['results_dir'], 'bucket_metrics.csv')
if os.path.exists(bucket_metrics_path):
    bucket_metrics_df = pd.read_csv(bucket_metrics_path)
    display(bucket_metrics_df.head())
    bucket_metrics_df.plot(x='bucket_id', y='pos_rate_all', kind='bar', figsize=(12,4), title='桶正类比例')
    plt.ylabel('正类比例')
    plt.xticks(rotation=90)
    plt.tight_layout()
    plt.savefig(fig_bucket, bbox_inches='tight')
    plt.close()
log_info('【步骤7摘要】桶级指标已整理，可用于局部化分析。')

,bucket_id,layer,parent_bucket_id,n_train,n_val,pos_rate_train,pos_rate_val,alpha,beta,regret_val,...,use_gain_weak_backoff,threshold_data_source,parent_with_threshold,n_test,pos_rate_test,BND_ratio_test,POS_Coverage_test,regret_test,fold,pos_rate
0,ROOT,L1,NaN,3360,1439,0.224702,0.207783,0.4,0.2,0.415045,...,True,val,NaN,NaN,NaN,NaN,NaN,NaN,1,0.221167
1,L1_ever_delay=no_delay,L1,ROOT,2236,965,0.123435,0.117098,0.4,0.2,0.341710,...,True,val,NaN,NaN,NaN,NaN,NaN,NaN,1,0.118268
2,L1_ever_delay=no_delay|L2_max_delay_bin=none,L2,L1_ever_delay=no_delay,2235,964,0.120805,0.115145,0.4,0.2,0.341546,...,True,val,NaN,NaN,NaN,NaN,NaN,NaN,1,0.118268
3,L1_ever_delay=has_delay,L1,ROOT,1193,518,0.438391,0.436293,0.4,0.2,0.508687,...,True,val,NaN,NaN,NaN,NaN,NaN,NaN,1,0.427195
4,L1_ever_delay=has_delay|L2_max_delay_bin=mild,L2,L1_ever_delay=has_delay,991,415,0.419778,0.402410,0.4,0.2,0.539759,...,True,val,NaN,NaN,NaN,NaN,NaN,NaN,1,0.399886

C:\Users\xzq20.HUANLI\AppData\Local\Temp\ipykernel_16536\946468196.py:9: UserWarning: Tight layout not applied. The bottom and top margins cannot be made large enough to accommodate all Axes decorations.
  plt.tight_layout()

【INFO】【2026-03-26 16:26:56】【步骤7摘要】桶级指标已整理，可用于局部化分析。

In [10]:
# 步骤8：结果汇总
log_info('【步骤8】检查结果文件与图表。')
print(os.listdir(os.path.join(root_path, cfg['OUTPUT']['results_dir'])))
print(os.listdir(os.path.join(root_path, cfg['OUTPUT']['figs_dir'])))
log_info('【全部步骤完成】Telco Churn 数据集上的 BT-TWD 实验结束。')

【INFO】【2026-03-26 16:26:56】【步骤8】检查结果文件与图表。
['baseline_bucket_metrics.csv', 'bucket_fallback_stats.csv', 'bucket_metrics.csv', 'bucket_metrics_gain.csv', 'bucket_metrics_gain_test_per_fold.csv', 'bucket_thresholds.csv', 'bucket_thresholds_per_fold.csv', 'bucket_tree_structure.csv', 'fallback_off_tsne', 'fallback_on_tsne', 'metrics_kfold_per_fold.csv', 'metrics_kfold_summary.csv', 'metrics_overview.csv', 'per_sample_test_predictions.csv', 'tsne_fallback']
['bank_class_distribution.png', 'bucket_metrics_bar.png', 'class_distribution.png', 'metrics_compare.png']
【INFO】【2026-03-26 16:26:56】【全部步骤完成】Telco Churn 数据集上的 BT-TWD 实验结束。

In [11]:
# 步骤9：t-SNE 可视化弱桶对比
from bttwdlib import visualize_fallback_with_tsne
from IPython.display import Image

# 调用 t-SNE 可视化函数，参数从 YAML 配置中读取
tsne_output_dir = os.path.join(root_path, cfg["OUTPUT"]["results_dir"], "tsne_fallback")
os.makedirs(tsne_output_dir, exist_ok=True)
results = visualize_fallback_with_tsne(config_path=cfg_path, output_dir=tsne_output_dir)

# 显示保存的图片
Image(filename=results["figure_path"])

# 输出其他结果路径
print(f"t-SNE 嵌入结果保存路径：{results['embedding_path']}")
print(f"弱桶对比摘要保存路径：{results['summary_path']}")
print(f"可视化图片保存路径：{results['figure_path']}")

【INFO】【2026-03-26 16:26:56】【配置加载】已读取 e:\yan\组\三支决策\机器学习\BT_TWD\configs\credit_default_bttwd.yaml
【INFO】【2026-03-26 16:26:59】【数据加载】目标列 default payment next month 已检测为 0/1 标签，跳过映射逻辑
【INFO】【2026-03-26 16:26:59】【数据集信息】名称=credit_default，样本数=30000，目标列=default payment next month，正类比例=22.12%
【INFO】【2026-03-26 16:26:59】【预处理】缺失值填充策略=median
【INFO】【2026-03-26 16:26:59】已生成 credit_default 派生特征：ever_delay / max_delay / max_delay_bin
【INFO】【2026-03-26 16:26:59】ever_delay 分布：
ever_delay
0    19931
1    10069
【INFO】【2026-03-26 16:26:59】max_delay_bin 分布：
max_delay_bin
0      19931
1-2     8876
3-4     1007
5+       186
【INFO】【2026-03-26 16:26:59】max_delay_bins=[-0.1, 0, 2, 4, 9], labels=['0', '1-2', '3-4', '5+']
【INFO】【2026-03-26 16:26:59】【预处理】连续特征=14个，类别特征=5个
【INFO】【2026-03-26 16:26:59】【预处理】编码后维度=33
[t-SNE] Computing 91 nearest neighbors...
[t-SNE] Indexed 30000 samples in 0.005s...
[t-SNE] Computed neighbors for 30000 samples in 1.345s...
[t-SNE] Computed conditional probabilities for sample 1000 / 30000
[t-SNE] Computed conditional probabilities for sample 2000 / 30000
[t-SNE] Computed conditional probabilities for sample 3000 / 30000
[t-SNE] Computed conditional probabilities for sample 4000 / 30000
[t-SNE] Computed conditional probabilities for sample 5000 / 30000
[t-SNE] Computed conditional probabilities for sample 6000 / 30000
[t-SNE] Computed conditional probabilities for sample 7000 / 30000
[t-SNE] Computed conditional probabilities for sample 8000 / 30000
[t-SNE] Computed conditional probabilities for sample 9000 / 30000
[t-SNE] Computed conditional probabilities for sample 10000 / 30000
[t-SNE] Computed conditional probabilities for sample 11000 / 30000
[t-SNE] Computed conditional probabilities for sample 12000 / 30000
[t-SNE] Computed conditional probabilities for sample 13000 / 30000
[t-SNE] Computed conditional probabilities for sample 14000 / 30000
[t-SNE] Computed conditional probabilities for sample 15000 / 30000
[t-SNE] Computed conditional probabilities for sample 16000 / 30000
[t-SNE] Computed conditional probabilities for sample 17000 / 30000
[t-SNE] Computed conditional probabilities for sample 18000 / 30000
[t-SNE] Computed conditional probabilities for sample 19000 / 30000
[t-SNE] Computed conditional probabilities for sample 20000 / 30000
[t-SNE] Computed conditional probabilities for sample 21000 / 30000
[t-SNE] Computed conditional probabilities for sample 22000 / 30000
[t-SNE] Computed conditional probabilities for sample 23000 / 30000
[t-SNE] Computed conditional probabilities for sample 24000 / 30000
[t-SNE] Computed conditional probabilities for sample 25000 / 30000
[t-SNE] Computed conditional probabilities for sample 26000 / 30000
[t-SNE] Computed conditional probabilities for sample 27000 / 30000
[t-SNE] Computed conditional probabilities for sample 28000 / 30000
[t-SNE] Computed conditional probabilities for sample 29000 / 30000
[t-SNE] Computed conditional probabilities for sample 30000 / 30000
[t-SNE] Mean sigma: 0.353063
[t-SNE] KL divergence after 250 iterations with early exaggeration: 86.870178
[t-SNE] KL divergence after 1000 iterations: 1.650497
【INFO】【2026-03-26 16:29:10】[t-SNE] Finished embedding computation; adjusted perplexity=30.00, output shape=(30000, 2)
【INFO】【2026-03-26 16:29:10】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=0.5

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:29:10] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:29:10】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 16:29:11] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=30000
[INFO][BT][2026-03-26 16:29:11] 创建桶 bucket_id=L1_ever_delay=has_delay，level=1，parent_id=ROOT，split_name=L1_ever_delay，split_type=numeric_bin，split_rule="has_delay"，n_samples=10069
[INFO][BT][2026-03-26 16:29:11] 创建桶 bucket_id=L1_ever_delay=no_delay，level=1，parent_id=ROOT，split_name=L1_ever_delay，split_type=numeric_bin，split_rule="no_delay"，n_samples=19931
[INFO][BT][2026-03-26 16:29:11] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="medium"，n_samples=1007
[INFO][BT][2026-03-26 16:29:11] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="mild"，n_samples=8876
[INFO][BT][2026-03-26 16:29:11] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="others"，n_samples=186
[INFO][BT][2026-03-26 16:29:11] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，level=2，parent_id=L1_ever_delay=no_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="none"，n_samples=19931
[INFO][BT][2026-03-26 16:29:11] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=720
[INFO][BT][2026-03-26 16:29:11] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=mid_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="mid_limit"，n_samples=201
[INFO][BT][2026-03-26 16:29:11] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="others"，n_samples=86
[INFO][BT][2026-03-26 16:29:11] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="high_limit"，n_samples=1953
[INFO][BT][2026-03-26 16:29:11] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=4044
[INFO][BT][2026-03-26 16:29:11] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="mid_limit"，n_samples=2879
[INFO][BT][2026-03-26 16:29:11] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="high_limit"，n_samples=7565
[INFO][BT][2026-03-26 16:29:11] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=5898
[INFO][BT][2026-03-26 16:29:11] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="mid_limit"，n_samples=6468
[INFO][BT][2026-03-26 16:29:13] 桶树构建完成：总桶数=16，最大层数=3，叶子桶数=10
【INFO】【2026-03-26 16:29:13】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 16:29:13】【阈值】桶 ROOT（n_val=1200，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:29:13] 桶 bucket_id=ROOT level=0：
    n_train=4799, n_val=1200,
    BAC=0.610, F1=0.512, AUC=0.773,
    Regret=0.370, BND_ratio=0.174, POS_coverage=0.205,
    Score(f1_regret_bnd )=0.055，threshold_source=val
【INFO】【2026-03-26 16:29:13】【阈值】桶 L1_ever_delay=has_delay 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:29:13] 桶 bucket_id=L1_ever_delay=has_delay level=1：
    n_train=1730, n_val=432,
    BAC=0.398, F1=0.631, AUC=0.673,
    Regret=0.507, BND_ratio=0.345, POS_coverage=0.655,
    Score(f1_regret_bnd )=-0.048，threshold_source=val
[INFO][BT][2026-03-26 16:29:13] 桶 bucket_id=L1_ever_delay=has_delay：
    parent_id=ROOT，parent_Score=0.055, bucket_Score=-0.048,
    Gain=-0.103, is_weak=True
【INFO】【2026-03-26 16:29:14】【阈值】桶 L1_ever_delay=no_delay 标记为弱桶，阈值将回退使用 ROOT 的阈值
[INFO][BT][2026-03-26 16:29:14] 桶 bucket_id=L1_ever_delay=no_delay level=1：
    n_train=3179, n_val=807,
    BAC=0.488, F1=0.000, AUC=0.659,
    Regret=0.379, BND_ratio=0.027, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.393，threshold_source=val
[INFO][BT][2026-03-26 16:29:14] 桶 bucket_id=L1_ever_delay=no_delay：
    parent_id=ROOT，parent_Score=0.055, bucket_Score=-0.393,
    Gain=-0.448, is_weak=True
【INFO】【2026-03-26 16:29:14】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium（n_val=205，source=val) 使用本地阈值 α=0.1000, β=0.0000
[INFO][BT][2026-03-26 16:29:14] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium level=2：
    n_train=334, n_val=205,
    BAC=0.500, F1=0.772, AUC=0.484,
    Regret=0.371, BND_ratio=0.000, POS_coverage=1.000,
    Score(f1_regret_bnd )=0.402，threshold_source=val
[INFO][BT][2026-03-26 16:29:14] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.048, bucket_Score=0.402,
    Gain=+0.450, is_weak=False
【INFO】【2026-03-26 16:29:14】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild（n_val=340，source=val) 使用本地阈值 α=0.3000, β=0.0000
[INFO][BT][2026-03-26 16:29:14] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild level=2：
    n_train=1433, n_val=340,
    BAC=0.448, F1=0.624, AUC=0.606,
    Regret=0.529, BND_ratio=0.200, POS_coverage=0.800,
    Score(f1_regret_bnd )=-0.005，threshold_source=val
[INFO][BT][2026-03-26 16:29:14] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.048, bucket_Score=-0.005,
    Gain=+0.043, is_weak=False
【INFO】【2026-03-26 16:29:15】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=others 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay 的阈值
[INFO][BT][2026-03-26 16:29:15] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others level=2：
    n_train=137, n_val=49,
    BAC=0.586, F1=0.831, AUC=0.855,
    Regret=0.281, BND_ratio=0.113, POS_coverage=0.796,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:15] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others：
    parent_id=L1_ever_delay=has_delay，parent_Score=-0.048, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:15】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none（n_val=806，source=val) 使用本地阈值 α=0.5000, β=0.3000
[INFO][BT][2026-03-26 16:29:15] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none level=2：
    n_train=3179, n_val=806,
    BAC=0.489, F1=0.000, AUC=0.597,
    Regret=0.365, BND_ratio=0.031, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.380，threshold_source=val
[INFO][BT][2026-03-26 16:29:15] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none：
    parent_id=L1_ever_delay=no_delay，parent_Score=-0.393, bucket_Score=-0.380,
    Gain=+0.013, is_weak=False
【INFO】【2026-03-26 16:29:15】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值
[INFO][BT][2026-03-26 16:29:15] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit level=3：
    n_train=584, n_val=136,
    BAC=0.500, F1=0.744, AUC=0.544,
    Regret=0.408, BND_ratio=0.007, POS_coverage=0.993,
    Score(f1_regret_bnd )=0.332，threshold_source=val
[INFO][BT][2026-03-26 16:29:15] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，parent_Score=0.402, bucket_Score=0.332,
    Gain=-0.069, is_weak=True
【INFO】【2026-03-26 16:29:15】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=mid_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值
[INFO][BT][2026-03-26 16:29:15] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=mid_limit level=3：
    n_train=160, n_val=41,
    BAC=0.577, F1=0.807, AUC=0.747,
    Regret=0.310, BND_ratio=0.104, POS_coverage=0.796,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:15] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=mid_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，parent_Score=0.402, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:16】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值
[INFO][BT][2026-03-26 16:29:16] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others level=3：
    n_train=58, n_val=28,
    BAC=0.590, F1=0.857, AUC=0.838,
    Regret=0.262, BND_ratio=0.070, POS_coverage=0.849,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:16] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，parent_Score=0.402, bucket_Score=nan,
    Gain=+nan, is_weak=True
【INFO】【2026-03-26 16:29:16】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值
[INFO][BT][2026-03-26 16:29:16] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit level=3：
    n_train=1585, n_val=368,
    BAC=0.415, F1=0.500, AUC=0.693,
    Regret=0.512, BND_ratio=0.421, POS_coverage=0.296,
    Score(f1_regret_bnd )=-0.223，threshold_source=val
[INFO][BT][2026-03-26 16:29:16] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.005, bucket_Score=-0.223,
    Gain=-0.218, is_weak=True
【INFO】【2026-03-26 16:29:16】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值
[INFO][BT][2026-03-26 16:29:16] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit level=3：
    n_train=3230, n_val=814,
    BAC=0.418, F1=0.593, AUC=0.580,
    Regret=0.541, BND_ratio=0.236, POS_coverage=0.754,
    Score(f1_regret_bnd )=-0.067，threshold_source=val
[INFO][BT][2026-03-26 16:29:16] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.005, bucket_Score=-0.067,
    Gain=-0.062, is_weak=True
【INFO】【2026-03-26 16:29:17】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值
[INFO][BT][2026-03-26 16:29:17] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit level=3：
    n_train=2350, n_val=529,
    BAC=0.231, F1=0.386, AUC=0.632,
    Regret=0.549, BND_ratio=0.656, POS_coverage=0.246,
    Score(f1_regret_bnd )=-0.491，threshold_source=val
[INFO][BT][2026-03-26 16:29:17] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=-0.005, bucket_Score=-0.491,
    Gain=-0.485, is_weak=True
【INFO】【2026-03-26 16:29:17】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit（n_val=1535，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:29:17] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit level=3：
    n_train=6030, n_val=1535,
    BAC=0.472, F1=0.023, AUC=0.701,
    Regret=0.300, BND_ratio=0.085, POS_coverage=0.002,
    Score(f1_regret_bnd )=-0.320，threshold_source=val
[INFO][BT][2026-03-26 16:29:17] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.380, bucket_Score=-0.320,
    Gain=+0.060, is_weak=False
【INFO】【2026-03-26 16:29:17】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit 标记为弱桶，阈值将回退使用 L1_ever_delay=no_delay|L2_max_delay_bin=none 的阈值
[INFO][BT][2026-03-26 16:29:17] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit level=3：
    n_train=4690, n_val=1208,
    BAC=0.404, F1=0.000, AUC=0.627,
    Regret=0.429, BND_ratio=0.212, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.535，threshold_source=val
[INFO][BT][2026-03-26 16:29:17] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.380, bucket_Score=-0.535,
    Gain=-0.154, is_weak=True
【INFO】【2026-03-26 16:29:18】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit（n_val=1292，source=val) 使用本地阈值 α=0.5000, β=0.3000
[INFO][BT][2026-03-26 16:29:18] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit level=3：
    n_train=5176, n_val=1292,
    BAC=0.493, F1=0.000, AUC=0.620,
    Regret=0.346, BND_ratio=0.016, POS_coverage=0.000,
    Score(f1_regret_bnd )=-0.354，threshold_source=val
[INFO][BT][2026-03-26 16:29:18] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=-0.380, bucket_Score=-0.354,
    Gain=+0.027, is_weak=False
[INFO][BT][2026-03-26 16:29:18] 桶 bucket_id=L1_ever_delay=has_delay 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:29:18] 桶 bucket_id=L1_ever_delay=no_delay 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:29:18] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others 样本不足或为弱桶，未单独搜索阈值，继承桶 ROOT 的阈值(alpha=0.4000,beta=0.2000)
[INFO][BT][2026-03-26 16:29:18] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值(alpha=0.1000,beta=0.0000)
[INFO][BT][2026-03-26 16:29:18] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=mid_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值(alpha=0.1000,beta=0.0000)
[INFO][BT][2026-03-26 16:29:18] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium 的阈值(alpha=0.1000,beta=0.0000)
[INFO][BT][2026-03-26 16:29:18] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值(alpha=0.3000,beta=0.0000)
[INFO][BT][2026-03-26 16:29:18] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值(alpha=0.3000,beta=0.0000)
[INFO][BT][2026-03-26 16:29:18] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild 的阈值(alpha=0.3000,beta=0.0000)
[INFO][BT][2026-03-26 16:29:18] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit 样本不足或为弱桶，未单独搜索阈值，继承桶 L1_ever_delay=no_delay|L2_max_delay_bin=none 的阈值(alpha=0.5000,beta=0.3000)
【INFO】【2026-03-26 16:29:18】【BTTWD】桶统计摘要：总桶数=16，非空桶=16，强桶=6，弱桶=10
【INFO】【2026-03-26 16:29:18】【BTTWD】共生成 10 个叶子桶，其中有效桶 0 个（已训练局部模型）
【INFO】【2026-03-26 16:29:18】【桶树】已为样本生成桶ID，共 12 个组合
[INFO][BT][2026-03-26 16:29:21] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit：
    assigned_samples=720,
    used_local_decision=0,
    fallback_to_parent=720,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium,
    is_weak=True
[INFO][BT][2026-03-26 16:29:21] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium：
    assigned_samples=0,
    used_local_decision=1007,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay,
    is_weak=False
[INFO][BT][2026-03-26 16:29:21] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=mid_limit：
    assigned_samples=201,
    used_local_decision=0,
    fallback_to_parent=201,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium,
    is_weak=True
[INFO][BT][2026-03-26 16:29:21] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others：
    assigned_samples=86,
    used_local_decision=0,
    fallback_to_parent=86,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium,
    is_weak=True
[INFO][BT][2026-03-26 16:29:21] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit：
    assigned_samples=1953,
    used_local_decision=0,
    fallback_to_parent=1953,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=True
[INFO][BT][2026-03-26 16:29:21] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild：
    assigned_samples=0,
    used_local_decision=8876,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay,
    is_weak=False
[INFO][BT][2026-03-26 16:29:21] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit：
    assigned_samples=4044,
    used_local_decision=0,
    fallback_to_parent=4044,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=True
[INFO][BT][2026-03-26 16:29:21] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit：
    assigned_samples=2879,
    used_local_decision=0,
    fallback_to_parent=2879,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=True
[INFO][BT][2026-03-26 16:29:21] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others：
    assigned_samples=186,
    used_local_decision=0,
    fallback_to_parent=186,
    parent_id=L1_ever_delay=has_delay,
    is_weak=True
[INFO][BT][2026-03-26 16:29:21] 预测统计：bucket_id=ROOT：
    assigned_samples=0,
    used_local_decision=186,
    fallback_to_parent=0,
    parent_id=ROOT,
    is_weak=False
[INFO][BT][2026-03-26 16:29:21] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit：
    assigned_samples=7565,
    used_local_decision=7565,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=False
[INFO][BT][2026-03-26 16:29:21] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit：
    assigned_samples=5898,
    used_local_decision=0,
    fallback_to_parent=5898,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=True
[INFO][BT][2026-03-26 16:29:21] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none：
    assigned_samples=0,
    used_local_decision=5898,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=no_delay,
    is_weak=False
[INFO][BT][2026-03-26 16:29:21] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit：
    assigned_samples=6468,
    used_local_decision=6468,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=False
[INFO][BT][2026-03-26 16:29:21] 回退汇总：
    总样本数=30000,
    使用叶子桶决策的样本比例=46.777%,
    使用中间桶决策的样本比例=52.603%,
    回退到全局桶决策的样本比例=0.620%
【INFO】【2026-03-26 16:29:23】[t-SNE] Saved fallback_on embedding data to: e:\yan\组\三支决策\机器学习\BT_TWD\results\credit_default_bttwd\tsne_fallback\fallback_on_tsne_embedding.csv
【INFO】【2026-03-26 16:29:23】[BT] 使用桶评分配置：mode=f1_regret_bnd, f1_weight=1.0, regret_weight=1.0, bnd_weight=0.5

C:\Users\xzq20.HUANLI\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [16:29:24] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

【INFO】【2026-03-26 16:29:25】【BTTWD】全局模型训练完成，用于兜底预测
[INFO][BT][2026-03-26 16:29:25] 创建桶 bucket_id=ROOT，level=0，parent_id=ROOT，split_name=ROOT，split_type=ROOT，split_rule="all"，n_samples=30000
[INFO][BT][2026-03-26 16:29:25] 创建桶 bucket_id=L1_ever_delay=has_delay，level=1，parent_id=ROOT，split_name=L1_ever_delay，split_type=numeric_bin，split_rule="has_delay"，n_samples=10069
[INFO][BT][2026-03-26 16:29:25] 创建桶 bucket_id=L1_ever_delay=no_delay，level=1，parent_id=ROOT，split_name=L1_ever_delay，split_type=numeric_bin，split_rule="no_delay"，n_samples=19931
[INFO][BT][2026-03-26 16:29:25] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="medium"，n_samples=1007
[INFO][BT][2026-03-26 16:29:25] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="mild"，n_samples=8876
[INFO][BT][2026-03-26 16:29:25] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others，level=2，parent_id=L1_ever_delay=has_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="others"，n_samples=186
[INFO][BT][2026-03-26 16:29:25] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，level=2，parent_id=L1_ever_delay=no_delay，split_name=L2_max_delay_bin，split_type=categorical_group，split_rule="none"，n_samples=19931
[INFO][BT][2026-03-26 16:29:25] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=720
[INFO][BT][2026-03-26 16:29:25] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=mid_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="mid_limit"，n_samples=201
[INFO][BT][2026-03-26 16:29:25] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="others"，n_samples=86
[INFO][BT][2026-03-26 16:29:25] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="high_limit"，n_samples=1953
[INFO][BT][2026-03-26 16:29:25] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=4044
[INFO][BT][2026-03-26 16:29:25] 创建桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit，level=3，parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="mid_limit"，n_samples=2879
[INFO][BT][2026-03-26 16:29:25] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="high_limit"，n_samples=7565
[INFO][BT][2026-03-26 16:29:25] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="low_limit"，n_samples=5898
[INFO][BT][2026-03-26 16:29:25] 创建桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit，level=3，parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，split_name=L3_LIMIT_BAL，split_type=numeric_bin，split_rule="mid_limit"，n_samples=6468
[INFO][BT][2026-03-26 16:29:27] 桶树构建完成：总桶数=16，最大层数=3，叶子桶数=10
【INFO】【2026-03-26 16:29:27】【BTTWD】bucket_estimator=none：不训练桶内局部模型，仅使用全局模型概率做桶内阈值搜索

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'F1' is missing or NaN, defaulting to 0.0.
  warnings.warn(
e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\bucket_gain.py:27: RuntimeWarning: compute_bucket_score: metric 'BND_ratio' is missing or NaN, defaulting to 0.0.
  warnings.warn(

【INFO】【2026-03-26 16:29:28】【阈值】桶 ROOT（n_val=1200，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:29:28] 桶 bucket_id=ROOT level=0：
    n_train=4799, n_val=1200,
    BAC=0.610, F1=0.512, AUC=0.773,
    Regret=0.370, BND_ratio=0.174, POS_coverage=0.205,
    Score(f1_regret_bnd )=nan，threshold_source=val
【INFO】【2026-03-26 16:29:28】【阈值】桶 L1_ever_delay=has_delay（n_val=432，source=val) 使用本地阈值 α=0.4000, β=0.0000
[INFO][BT][2026-03-26 16:29:28] 桶 bucket_id=L1_ever_delay=has_delay level=1：
    n_train=1730, n_val=432,
    BAC=0.398, F1=0.631, AUC=0.673,
    Regret=0.507, BND_ratio=0.345, POS_coverage=0.655,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:29:28] 桶 bucket_id=L1_ever_delay=has_delay：
    parent_id=ROOT，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:29:28】【阈值】桶 L1_ever_delay=no_delay（n_val=807，source=val) 使用本地阈值 α=0.5000, β=0.3000
[INFO][BT][2026-03-26 16:29:28] 桶 bucket_id=L1_ever_delay=no_delay level=1：
    n_train=3179, n_val=807,
    BAC=0.488, F1=0.000, AUC=0.659,
    Regret=0.379, BND_ratio=0.027, POS_coverage=0.000,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:29:28] 桶 bucket_id=L1_ever_delay=no_delay：
    parent_id=ROOT，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:29:28】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium（n_val=205，source=val) 使用本地阈值 α=0.1000, β=0.0000
[INFO][BT][2026-03-26 16:29:28] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium level=2：
    n_train=334, n_val=205,
    BAC=0.500, F1=0.772, AUC=0.484,
    Regret=0.371, BND_ratio=0.000, POS_coverage=1.000,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:29:28] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium：
    parent_id=L1_ever_delay=has_delay，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:29:29】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild（n_val=340，source=val) 使用本地阈值 α=0.3000, β=0.0000
[INFO][BT][2026-03-26 16:29:29] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild level=2：
    n_train=1433, n_val=340,
    BAC=0.448, F1=0.624, AUC=0.606,
    Regret=0.529, BND_ratio=0.200, POS_coverage=0.800,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:29:29] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild：
    parent_id=L1_ever_delay=has_delay，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:29:29】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=others（n_val=49，source=all) 使用本地阈值 α=0.5000, β=0.4000
[INFO][BT][2026-03-26 16:29:29] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others level=2：
    n_train=137, n_val=49,
    BAC=0.586, F1=0.831, AUC=0.855,
    Regret=0.281, BND_ratio=0.113, POS_coverage=0.796,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:29] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others：
    parent_id=L1_ever_delay=has_delay，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:29:30】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none（n_val=806，source=val) 使用本地阈值 α=0.5000, β=0.3000
[INFO][BT][2026-03-26 16:29:30] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none level=2：
    n_train=3179, n_val=806,
    BAC=0.489, F1=0.000, AUC=0.597,
    Regret=0.365, BND_ratio=0.031, POS_coverage=0.000,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:29:30] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none：
    parent_id=L1_ever_delay=no_delay，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:29:30】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit（n_val=136，source=val) 使用本地阈值 α=0.3000, β=0.0000
[INFO][BT][2026-03-26 16:29:30] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit level=3：
    n_train=584, n_val=136,
    BAC=0.500, F1=0.744, AUC=0.544,
    Regret=0.408, BND_ratio=0.007, POS_coverage=0.993,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:29:30] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:29:30】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=mid_limit（n_val=41，source=all) 使用本地阈值 α=0.5000, β=0.4000
[INFO][BT][2026-03-26 16:29:30] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=mid_limit level=3：
    n_train=160, n_val=41,
    BAC=0.577, F1=0.807, AUC=0.747,
    Regret=0.310, BND_ratio=0.104, POS_coverage=0.796,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:30] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=mid_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:29:31】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others（n_val=28，source=all) 使用本地阈值 α=0.4000, β=0.3000
[INFO][BT][2026-03-26 16:29:31] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others level=3：
    n_train=58, n_val=28,
    BAC=0.590, F1=0.857, AUC=0.838,
    Regret=0.262, BND_ratio=0.070, POS_coverage=0.849,
    Score(f1_regret_bnd )=nan，threshold_source=all
[INFO][BT][2026-03-26 16:29:31] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:29:31】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit（n_val=368，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:29:31] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit level=3：
    n_train=1585, n_val=368,
    BAC=0.415, F1=0.500, AUC=0.693,
    Regret=0.512, BND_ratio=0.421, POS_coverage=0.296,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:29:31] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:29:31】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit（n_val=814，source=val) 使用本地阈值 α=0.4000, β=0.1000
[INFO][BT][2026-03-26 16:29:31] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit level=3：
    n_train=3230, n_val=814,
    BAC=0.418, F1=0.593, AUC=0.580,
    Regret=0.541, BND_ratio=0.236, POS_coverage=0.754,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:29:31] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:29:31】【阈值】桶 L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit（n_val=529，source=val) 使用本地阈值 α=0.5000, β=0.2000
[INFO][BT][2026-03-26 16:29:31] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit level=3：
    n_train=2350, n_val=529,
    BAC=0.231, F1=0.386, AUC=0.632,
    Regret=0.549, BND_ratio=0.656, POS_coverage=0.246,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:29:31] 桶 bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit：
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:29:32】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit（n_val=1535，source=val) 使用本地阈值 α=0.4000, β=0.2000
[INFO][BT][2026-03-26 16:29:32] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit level=3：
    n_train=6030, n_val=1535,
    BAC=0.472, F1=0.023, AUC=0.701,
    Regret=0.300, BND_ratio=0.085, POS_coverage=0.002,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:29:32] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:29:32】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit（n_val=1208，source=val) 使用本地阈值 α=0.5000, β=0.2000
[INFO][BT][2026-03-26 16:29:32] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit level=3：
    n_train=4690, n_val=1208,
    BAC=0.404, F1=0.000, AUC=0.627,
    Regret=0.429, BND_ratio=0.212, POS_coverage=0.000,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:29:32] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:29:32】【阈值】桶 L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit（n_val=1292，source=val) 使用本地阈值 α=0.5000, β=0.3000
[INFO][BT][2026-03-26 16:29:32] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit level=3：
    n_train=5176, n_val=1292,
    BAC=0.493, F1=0.000, AUC=0.620,
    Regret=0.346, BND_ratio=0.016, POS_coverage=0.000,
    Score(f1_regret_bnd )=nan，threshold_source=val
[INFO][BT][2026-03-26 16:29:32] 桶 bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit：
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none，parent_Score=nan, bucket_Score=nan,
    Gain=+nan, is_weak=False
【INFO】【2026-03-26 16:29:32】【BTTWD】桶统计摘要：总桶数=16，非空桶=16，强桶=16，弱桶=0
【INFO】【2026-03-26 16:29:32】【BTTWD】共生成 10 个叶子桶，其中有效桶 0 个（已训练局部模型）
【INFO】【2026-03-26 16:29:33】【桶树】已为样本生成桶ID，共 12 个组合
[INFO][BT][2026-03-26 16:29:36] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=low_limit：
    assigned_samples=720,
    used_local_decision=720,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium,
    is_weak=False
[INFO][BT][2026-03-26 16:29:36] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=mid_limit：
    assigned_samples=201,
    used_local_decision=201,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium,
    is_weak=False
[INFO][BT][2026-03-26 16:29:36] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium|L3_LIMIT_BAL=others：
    assigned_samples=86,
    used_local_decision=86,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=medium,
    is_weak=False
[INFO][BT][2026-03-26 16:29:36] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=high_limit：
    assigned_samples=1953,
    used_local_decision=1953,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=False
[INFO][BT][2026-03-26 16:29:36] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=low_limit：
    assigned_samples=4044,
    used_local_decision=4044,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=False
[INFO][BT][2026-03-26 16:29:36] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild|L3_LIMIT_BAL=mid_limit：
    assigned_samples=2879,
    used_local_decision=2879,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay|L2_max_delay_bin=mild,
    is_weak=False
[INFO][BT][2026-03-26 16:29:36] 预测统计：bucket_id=L1_ever_delay=has_delay|L2_max_delay_bin=others：
    assigned_samples=186,
    used_local_decision=186,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=has_delay,
    is_weak=False
[INFO][BT][2026-03-26 16:29:36] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=high_limit：
    assigned_samples=7565,
    used_local_decision=7565,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=False
[INFO][BT][2026-03-26 16:29:36] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=low_limit：
    assigned_samples=5898,
    used_local_decision=5898,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=False
[INFO][BT][2026-03-26 16:29:36] 预测统计：bucket_id=L1_ever_delay=no_delay|L2_max_delay_bin=none|L3_LIMIT_BAL=mid_limit：
    assigned_samples=6468,
    used_local_decision=6468,
    fallback_to_parent=0,
    parent_id=L1_ever_delay=no_delay|L2_max_delay_bin=none,
    is_weak=False
[INFO][BT][2026-03-26 16:29:36] 回退汇总：
    总样本数=30000,
    使用叶子桶决策的样本比例=100.000%,
    使用中间桶决策的样本比例=0.000%,
    回退到全局桶决策的样本比例=0.000%
【INFO】【2026-03-26 16:29:38】[t-SNE] Saved fallback_off embedding data to: e:\yan\组\三支决策\机器学习\BT_TWD\results\credit_default_bttwd\tsne_fallback\fallback_off_tsne_embedding.csv
【INFO】【2026-03-26 16:29:39】[t-SNE] Saved t-SNE embedding with mode labels: e:\yan\组\三支决策\机器学习\BT_TWD\results\credit_default_bttwd\tsne_fallback\tsne_fallback_embedding.csv

e:\yan\组\三支决策\机器学习\BT_TWD\bttwdlib\tsne_visualizer.py:389: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  fig.tight_layout()

【INFO】【2026-03-26 16:29:46】[t-SNE] Comparison figure saved to: e:\yan\组\三支决策\机器学习\BT_TWD\results\credit_default_bttwd\tsne_fallback\tsne_backoff_credit_default.png
【INFO】【2026-03-26 16:29:46】[t-SNE] Comparison figure saved to: e:\yan\组\三支决策\机器学习\BT_TWD\results\credit_default_bttwd\tsne_fallback\tsne_backoff_credit_default.pdf
t-SNE 嵌入结果保存路径：e:\yan\组\三支决策\机器学习\BT_TWD\results\credit_default_bttwd\tsne_fallback\tsne_fallback_embedding.csv
弱桶对比摘要保存路径：e:\yan\组\三支决策\机器学习\BT_TWD\results\credit_default_bttwd\tsne_fallback\tsne_fallback_summary.csv
可视化图片保存路径：e:\yan\组\三支决策\机器学习\BT_TWD\results\credit_default_bttwd\tsne_fallback\tsne_backoff_credit_default.png