# Adult 数据集 Governance 实验

本 notebook 用于运行第二篇 governance 框架在 Adult 数据集上的实验。

In [1]:
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(PROJECT_ROOT))
os.chdir(PROJECT_ROOT)

print("当前项目目录：", PROJECT_ROOT)

当前项目目录： e:\yan\组\三支决策\机器学习\BT_TWD_v2

In [2]:
CONFIG_PATH = "configs/adult_bttwd.yaml"
print("当前配置文件：", CONFIG_PATH)

当前配置文件： configs/adult_bttwd.yaml

## 运行完整 governance 实验

In [3]:
import subprocess

cmd = [
    sys.executable,
    "scripts/run_governance_experiments.py",
    "--config",
    CONFIG_PATH,
]

print("运行命令：", " ".join(cmd))
result = subprocess.run(cmd, text=True, capture_output=True)

print("标准输出：")
print(result.stdout)

print("错误输出：")
print(result.stderr)

if result.returncode != 0:
    raise RuntimeError(f"实验运行失败，返回码：{result.returncode}")

运行命令： d:\Anaconda3\python.exe scripts/run_governance_experiments.py --config configs/adult_bttwd.yaml
标准输出：
【INFO】【2026-05-15 19:46:28】【数据加载完毕】样本数=32561，特征数=14，正类比例=0.24
【INFO】【2026-05-15 19:46:28】【数据加载】24720 条标签无法映射，未指定负类且未开启 dropna_target，已按 0 处理
【INFO】【2026-05-15 19:46:28】【数据加载】标签列 income 已处理完成：dropna_target=False, 丢弃样本=0, 最终样本数=32561, 正类比例=24.08%
【INFO】【2026-05-15 19:46:28】【数据集信息】名称=adult，样本数=32561，目标列=income，正类比例=24.08%
【INFO】【2026-05-15 19:46:28】【预处理】连续特征=6个，类别特征=8个
【INFO】【2026-05-15 19:46:28】【预处理】编码后维度=100
【INFO】【2026-05-15 19:46:28】【governance】adult_bttwd 第 1/5 折
【INFO】【2026-05-15 19:46:29】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:46:29】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:46:42】【governance】weak bucket resolver：strong=25，weak=44
【INFO】【2026-05-15 19:46:42】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:46:56】【governance】adult_bttwd 第 2/5 折
【INFO】【2026-05-15 19:46:57】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:46:57】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:47:09】【governance】weak bucket resolver：strong=22，weak=47
【INFO】【2026-05-15 19:47:09】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:47:24】【governance】adult_bttwd 第 3/5 折
【INFO】【2026-05-15 19:47:25】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:47:25】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:47:37】【governance】weak bucket resolver：strong=23，weak=46
【INFO】【2026-05-15 19:47:37】【桶树】已为样本生成桶ID，共 47 个组合
【INFO】【2026-05-15 19:47:51】【governance】adult_bttwd 第 4/5 折
【INFO】【2026-05-15 19:47:52】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:47:52】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:48:04】【governance】weak bucket resolver：strong=23，weak=46
【INFO】【2026-05-15 19:48:04】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:48:19】【governance】adult_bttwd 第 5/5 折
【INFO】【2026-05-15 19:48:19】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:48:19】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:48:31】【governance】weak bucket resolver：strong=24，weak=45
【INFO】【2026-05-15 19:48:31】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:48:46】【governance】结果已写入 E:\yan\组\三支决策\机器学习\BT_TWD_v2\outputs\governance\full

错误输出：

## 运行无 CP 消融

In [4]:
import subprocess

cmd = [
    sys.executable,
    "scripts/run_governance_experiments.py",
    "--config",
    CONFIG_PATH,
    "--disable-cp-validation",
]

print("运行命令：", " ".join(cmd))
result = subprocess.run(cmd, text=True, capture_output=True)

print("标准输出：")
print(result.stdout)

print("错误输出：")
print(result.stderr)

if result.returncode != 0:
    raise RuntimeError(f"无 CP 消融运行失败，返回码：{result.returncode}")

运行命令： d:\Anaconda3\python.exe scripts/run_governance_experiments.py --config configs/adult_bttwd.yaml --disable-cp-validation
标准输出：
【INFO】【2026-05-15 19:48:52】【数据加载完毕】样本数=32561，特征数=14，正类比例=0.24
【INFO】【2026-05-15 19:48:52】【数据加载】24720 条标签无法映射，未指定负类且未开启 dropna_target，已按 0 处理
【INFO】【2026-05-15 19:48:52】【数据加载】标签列 income 已处理完成：dropna_target=False, 丢弃样本=0, 最终样本数=32561, 正类比例=24.08%
【INFO】【2026-05-15 19:48:52】【数据集信息】名称=adult，样本数=32561，目标列=income，正类比例=24.08%
【INFO】【2026-05-15 19:48:52】【预处理】连续特征=6个，类别特征=8个
【INFO】【2026-05-15 19:48:52】【预处理】编码后维度=100
【INFO】【2026-05-15 19:48:52】【governance】adult_bttwd 第 1/5 折
【INFO】【2026-05-15 19:48:53】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:48:53】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:49:09】【governance】weak bucket resolver：strong=25，weak=44
【INFO】【2026-05-15 19:49:09】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:49:29】【governance】adult_bttwd 第 2/5 折
【INFO】【2026-05-15 19:49:30】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:49:30】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:49:47】【governance】weak bucket resolver：strong=22，weak=47
【INFO】【2026-05-15 19:49:47】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:50:07】【governance】adult_bttwd 第 3/5 折
【INFO】【2026-05-15 19:50:07】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:50:07】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:50:22】【governance】weak bucket resolver：strong=23，weak=46
【INFO】【2026-05-15 19:50:22】【桶树】已为样本生成桶ID，共 47 个组合
【INFO】【2026-05-15 19:50:39】【governance】adult_bttwd 第 4/5 折
【INFO】【2026-05-15 19:50:39】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:50:39】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:50:57】【governance】weak bucket resolver：strong=23，weak=46
【INFO】【2026-05-15 19:50:57】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:51:14】【governance】adult_bttwd 第 5/5 折
【INFO】【2026-05-15 19:51:14】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:51:14】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:51:28】【governance】weak bucket resolver：strong=24，weak=45
【INFO】【2026-05-15 19:51:28】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:51:44】【governance】结果已写入 E:\yan\组\三支决策\机器学习\BT_TWD_v2\outputs\governance\no_cp

错误输出：

## 运行无渐进更新消融

In [5]:
import subprocess

cmd = [
    sys.executable,
    "scripts/run_governance_experiments.py",
    "--config",
    CONFIG_PATH,
    "--disable-progressive-update",
]

print("运行命令：", " ".join(cmd))
result = subprocess.run(cmd, text=True, capture_output=True)

print("标准输出：")
print(result.stdout)

print("错误输出：")
print(result.stderr)

if result.returncode != 0:
    raise RuntimeError(f"无渐进更新消融运行失败，返回码：{result.returncode}")

运行命令： d:\Anaconda3\python.exe scripts/run_governance_experiments.py --config configs/adult_bttwd.yaml --disable-progressive-update
标准输出：
【INFO】【2026-05-15 19:51:51】【数据加载完毕】样本数=32561，特征数=14，正类比例=0.24
【INFO】【2026-05-15 19:51:51】【数据加载】24720 条标签无法映射，未指定负类且未开启 dropna_target，已按 0 处理
【INFO】【2026-05-15 19:51:51】【数据加载】标签列 income 已处理完成：dropna_target=False, 丢弃样本=0, 最终样本数=32561, 正类比例=24.08%
【INFO】【2026-05-15 19:51:51】【数据集信息】名称=adult，样本数=32561，目标列=income，正类比例=24.08%
【INFO】【2026-05-15 19:51:51】【预处理】连续特征=6个，类别特征=8个
【INFO】【2026-05-15 19:51:51】【预处理】编码后维度=100
【INFO】【2026-05-15 19:51:51】【governance】adult_bttwd 第 1/5 折
【INFO】【2026-05-15 19:51:52】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:51:52】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:52:09】【governance】weak bucket resolver：strong=25，weak=44
【INFO】【2026-05-15 19:52:09】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:52:28】【governance】adult_bttwd 第 2/5 折
【INFO】【2026-05-15 19:52:29】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:52:29】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:52:44】【governance】weak bucket resolver：strong=22，weak=47
【INFO】【2026-05-15 19:52:44】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:53:03】【governance】adult_bttwd 第 3/5 折
【INFO】【2026-05-15 19:53:03】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:53:03】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:53:19】【governance】weak bucket resolver：strong=23，weak=46
【INFO】【2026-05-15 19:53:19】【桶树】已为样本生成桶ID，共 47 个组合
【INFO】【2026-05-15 19:53:39】【governance】adult_bttwd 第 4/5 折
【INFO】【2026-05-15 19:53:39】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:53:39】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:53:57】【governance】weak bucket resolver：strong=23，weak=46
【INFO】【2026-05-15 19:53:57】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:54:16】【governance】adult_bttwd 第 5/5 折
【INFO】【2026-05-15 19:54:17】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:54:17】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:54:31】【governance】weak bucket resolver：strong=24，weak=45
【INFO】【2026-05-15 19:54:31】【桶树】已为样本生成桶ID，共 48 个组合
【INFO】【2026-05-15 19:54:54】【governance】结果已写入 E:\yan\组\三支决策\机器学习\BT_TWD_v2\outputs\governance\no_progressive

错误输出：

## 读取并展示结果摘要

In [6]:
import pandas as pd
from pathlib import Path

config_stem = Path(CONFIG_PATH).stem
output_root = Path("outputs/governance")
modes = ["full", "no_cp", "no_progressive"]

for mode in modes:
    print(f"\n===== {mode} 结果 =====")
    dataset_summary = output_root / mode / "dataset_summary.csv"
    fold_summary = output_root / mode / config_stem / "fold_summary.csv"
    sample_records = output_root / mode / config_stem / "sample_records.csv"

    if dataset_summary.exists():
        print("读取：", dataset_summary)
        display(pd.read_csv(dataset_summary))
    else:
        print("未找到 dataset_summary.csv：", dataset_summary)

    if fold_summary.exists():
        print("读取：", fold_summary)
        display(pd.read_csv(fold_summary))
    else:
        print("未找到 fold_summary.csv：", fold_summary)

    if sample_records.exists():
        print("样本级记录：", sample_records)
    else:
        print("未找到 sample_records.csv：", sample_records)

===== full 结果 =====
读取： outputs\governance\full\dataset_summary.csv

,dataset_name,final_regret,final_BAC,final_F1,final_accuracy,original_regret,original_BAC,original_F1,original_accuracy,closure_rate,...,cp_reject_final_error_rate,cp_rejected_pn_count,cp_rejected_pn_ratio,cp_rejected_original_error_rate,cp_rejected_final_error_rate,cp_rejected_final_regret,progressive_update_enabled,average_evidence_count,average_weight_entropy,progressive_closed_count
0,adult_bttwd,0.144675,0.835725,0.727232,0.856147,0.142824,0.817095,0.721184,0.865145,1.0,...,0.533324,2264,0.0766,0.541818,0.533324,0.402345,True,2,0.093273,5258

读取： outputs\governance\full\adult_bttwd\fold_summary.csv

,dataset_name,fold_id,final_regret,final_BAC,final_F1,final_accuracy,original_regret,original_BAC,original_F1,original_accuracy,...,cp_reject_final_error_rate,cp_rejected_pn_count,cp_rejected_pn_ratio,cp_rejected_original_error_rate,cp_rejected_final_error_rate,cp_rejected_final_regret,progressive_update_enabled,average_evidence_count,average_weight_entropy,progressive_closed_count
0,adult_bttwd,1,0.148204,0.830845,0.721637,0.853831,0.146131,0.812092,0.717651,0.865653,...,0.535469,437,0.074803,0.544622,0.535469,0.403318,True,0.369876,0.071209,1108
1,adult_bttwd,2,0.141086,0.840313,0.733140,0.859029,0.141086,0.816867,0.720025,0.864097,...,0.544643,448,0.074542,0.566964,0.544643,0.418527,True,0.349201,0.070721,950
2,adult_bttwd,3,0.142813,0.837163,0.730735,0.858876,0.141930,0.812855,0.718478,0.865940,...,0.496420,419,0.070539,0.501193,0.496420,0.372315,True,0.440878,0.102079,991
3,adult_bttwd,4,0.146384,0.834261,0.724058,0.853808,0.143619,0.820569,0.723005,0.864097,...,0.527721,487,0.083778,0.531828,0.527721,0.395791,True,0.447328,0.110608,1186
4,adult_bttwd,5,0.144886,0.836042,0.726587,0.855190,0.141354,0.823089,0.726761,0.865940,...,0.562368,473,0.079336,0.564482,0.562368,0.421776,True,0.435043,0.111749,1023

样本级记录： outputs\governance\full\adult_bttwd\sample_records.csv

===== no_cp 结果 =====
读取： outputs\governance\no_cp\dataset_summary.csv

,dataset_name,final_regret,final_BAC,final_F1,final_accuracy,original_regret,original_BAC,original_F1,original_accuracy,closure_rate,...,cp_reject_final_error_rate,cp_rejected_pn_count,cp_rejected_pn_ratio,cp_rejected_original_error_rate,cp_rejected_final_error_rate,cp_rejected_final_regret,progressive_update_enabled,average_evidence_count,average_weight_entropy,progressive_closed_count
0,adult_bttwd,0.145089,0.835384,0.72645,0.855563,0.142824,0.817095,0.721184,0.865145,1.0,...,0.0,0,0.0,0.0,0.0,0.0,True,1,0.052975,2994

读取： outputs\governance\no_cp\adult_bttwd\fold_summary.csv

,dataset_name,fold_id,final_regret,final_BAC,final_F1,final_accuracy,original_regret,original_BAC,original_F1,original_accuracy,...,cp_reject_final_error_rate,cp_rejected_pn_count,cp_rejected_pn_ratio,cp_rejected_original_error_rate,cp_rejected_final_error_rate,cp_rejected_final_regret,progressive_update_enabled,average_evidence_count,average_weight_entropy,progressive_closed_count
0,adult_bttwd,1,0.149125,0.829571,0.720141,0.853217,0.146131,0.812092,0.717651,0.865653,...,0.0,0,0.0,0.0,0.0,0.0,True,0.198372,0.037035,671
1,adult_bttwd,2,0.141546,0.840608,0.731947,0.857494,0.141086,0.816867,0.720025,0.864097,...,0.0,0,0.0,0.0,0.0,0.0,True,0.178133,0.036169,502
2,adult_bttwd,3,0.143159,0.836743,0.730149,0.858569,0.141930,0.812855,0.718478,0.865940,...,0.0,0,0.0,0.0,0.0,0.0,True,0.252150,0.062009,572
3,adult_bttwd,4,0.146614,0.834059,0.723638,0.853501,0.143619,0.820569,0.723005,0.864097,...,0.0,0,0.0,0.0,0.0,0.0,True,0.238790,0.063291,699
4,adult_bttwd,5,0.145002,0.835941,0.726377,0.855037,0.141354,0.823089,0.726761,0.865940,...,0.0,0,0.0,0.0,0.0,0.0,True,0.220516,0.066370,550

样本级记录： outputs\governance\no_cp\adult_bttwd\sample_records.csv

===== no_progressive 结果 =====
读取： outputs\governance\no_progressive\dataset_summary.csv

,dataset_name,final_regret,final_BAC,final_F1,final_accuracy,original_regret,original_BAC,original_F1,original_accuracy,closure_rate,...,cp_reject_final_error_rate,cp_rejected_pn_count,cp_rejected_pn_ratio,cp_rejected_original_error_rate,cp_rejected_final_error_rate,cp_rejected_final_regret,progressive_update_enabled,average_evidence_count,average_weight_entropy,progressive_closed_count
0,adult_bttwd,0.144721,0.835661,0.727157,0.856116,0.142824,0.817095,0.721184,0.865145,1.0,...,0.533782,2264,0.0766,0.541818,0.533782,0.403032,False,2,0.092908,0

读取： outputs\governance\no_progressive\adult_bttwd\fold_summary.csv

,dataset_name,fold_id,final_regret,final_BAC,final_F1,final_accuracy,original_regret,original_BAC,original_F1,original_accuracy,...,cp_reject_final_error_rate,cp_rejected_pn_count,cp_rejected_pn_ratio,cp_rejected_original_error_rate,cp_rejected_final_error_rate,cp_rejected_final_regret,progressive_update_enabled,average_evidence_count,average_weight_entropy,progressive_closed_count
0,adult_bttwd,1,0.148434,0.830527,0.721264,0.853677,0.146131,0.812092,0.717651,0.865653,...,0.537757,437,0.074803,0.544622,0.537757,0.406751,False,0.369722,0.071205,0
1,adult_bttwd,2,0.141086,0.840313,0.733140,0.859029,0.141086,0.816867,0.720025,0.864097,...,0.544643,448,0.074542,0.566964,0.544643,0.418527,False,0.343059,0.068944,0
2,adult_bttwd,3,0.142813,0.837163,0.730735,0.858876,0.141930,0.812855,0.718478,0.865940,...,0.496420,419,0.070539,0.501193,0.496420,0.372315,False,0.434122,0.102079,0
3,adult_bttwd,4,0.146384,0.834261,0.724058,0.853808,0.143619,0.820569,0.723005,0.864097,...,0.527721,487,0.083778,0.531828,0.527721,0.395791,False,0.447328,0.110608,0
4,adult_bttwd,5,0.144886,0.836042,0.726587,0.855190,0.141354,0.823089,0.726761,0.865940,...,0.562368,473,0.079336,0.564482,0.562368,0.421776,False,0.433200,0.111703,0

样本级记录： outputs\governance\no_progressive\adult_bttwd\sample_records.csv